### ISSUE TITLE
hardcoded text for nōn-free licence

### ISSUE THREAD

**Issue by mirabilos** [corrados/jamulus#100]
The current server (at least I *hope* it’s in the server, not in the client) hard-codes a text that requires all contributions to be licenced under a nōn-free, very restrictive, licence (CC-BY-NC-SA 4.0), which is inaccepable (e.g. the bylaws of a charity I work with require Free licences to be used).

I wish to package Jamulus for Debian and therefore make it available to a more general audience. Please provide a way, urgently, for a server administrator to set their own terms of use.

**Comment by trebmuh** [comment]
Duplicate #81 .

**Comment by corrados** [comment]
Since it is a duplicate, I will close this issue now.

**Comment by mirabilos** [comment]
corrados dixit:

>Since it is a duplicate, I will close this issue now.

In the other issue, the problem at hand isn’t really
addressed, and discussion has dissolved into something
completely unrelated and irrelevant both.

Perhaps it’d make sense to close _that_ and keep a
focussed discussion here?

**Comment by corrados** [comment]
Ok, done.

**Comment by mirabilos** [comment]
corrados dixit:

>Ok, done.

Thanks.

OK, so on topic: is the message sent from the server to the client
for the latter to accept before joining already?

If so I’d propose a simple command line option (perhaps -L file),
whose OPTARG is read as UTF-8 encoded text file and then used
instead of the hardcoded text.

This plus some documentation¹ would fully satisfy my needs.

I could probably cobble this together if it has chances to be
accepted. I’m not too versed in C++/Qt but an experienced C
programmer.


① I’ll write a manpage for Jamulus(1) as part of the Debian packaging
  anyway so would put it there plus the Markdown documentation.

**Comment by mirabilos** [comment]
I just started actually running/testing Jamulus and saw that the text is only shown optionally. This works for me as a first start (offering another text file as terms the client has to click through would be nice, but only as a feature request; disabling the checkbox in the server GUI by default would also be useful).

**Comment by corrados** [comment]
I don't know why but I did not read your last comments (got no email or the email got lost).

> If so I’d propose a simple command line option (perhaps -L file)

As you already found out, this is exactly what was already implemented in Jamulus :-).

For futher discussion, please also see https://github.com/corrados/jamulus/pull/128 where we continue the discussion started here.

**Comment by mirabilos** [comment]
corrados dixit:

>> If so I’d propose a simple command line option (perhaps -L file)
>
>As you already found out, this is exactly what was already implemented in Jamulus :-).

No, not quite: the ability to send a custom text is not extant.

But with the dialogue being optional, it’s not as pressing
(even though, perhaps, server operators would like to, for
the exact reason you wrote over in #128, use own click-through
terms of use).

**Comment by corrados** [comment]
This is what https://github.com/corrados/jamulus/issues/81 is all about.
I do not want to transmit the legal text through the network when a user connects a server. So I implement it hard-coded in the client. The server operator has then to decide which pre-defined licence he wants to use (right now we only have one licence implemented).

**Comment by corrados** [comment]
Or, of course, the server operator simply uses no licence at all. That will always be possible.

**Comment by mirabilos** [comment]
corrados dixit:

>I do not want to transmit the legal text through the network when a
>user connects a server.

Why?

This may be the needed thing.

**Comment by corrados** [comment]
What about introducing a preprocessor macro where you can mask out the "-L" option and the GUI control completely. Then you can compile it without that stuff in your distribution. In the official Jamulus version on Sourceforge and Github this function is still available.

**Comment by mirabilos** [comment]
corrados dixit:

>What about introducing a preprocessor macro where you can mask out the
>"-L" option and the GUI control completely. Then you can compile it
>without that stuff in your distribution. In the official Jamulus

Nah, the feature can be there, I just prefer to not have it enabled
by default. I can locally patch that of course but we generally
prefer patches to be upstreamed, if possible that is — hence, me
asking. If declined I’ll carry it locally.

**Comment by corrados** [comment]
Let me make a short summary (since we discuss the licence implementation in different Issues):

> I wish to package Jamulus for Debian and therefore make it available to a more general audience. Please provide a way, urgently, for a server administrator to set their own terms of use. [...]
> I just started actually running/testing Jamulus and saw that the text is only shown optionally. This works for me as a first start 

Ok, since the licence is optional, this is no show stopper for a Debian integration and you do not need urgent changes.

Since in https://github.com/corrados/jamulus/issues/81 we are discussing improvements of the licence dialog, we may continue the discussion from this Issue there and close this issue.

@mirabilos what do you think? On Issue for this topic should be enough in my opinion.

**Comment by mirabilos** [comment]
corrados dixit:

>Ok, since the licence is optional, this is no show stopper for a Debian
>integration and you do not need urgent changes.

Indeed.

>Since in https://github.com/corrados/jamulus/issues/81 we are
>discussing improvements of the licence dialog, we may continue the
>discussion from this Issue there and close this issue.
>
>@mirabilos what do you think? On Issue for this topic should be enough
>@in my opinion.

Fully agreed, thanks!

**Comment by corrados** [comment]
Ok, thanks -> closed.
