### ISSUE TITLE
Audio level changes if Buffer Delay is changed

### ISSUE THREAD

**Issue by corrados** [corrados/jamulus#106]
If you change the Buffer Delay in Settings from, e.g., 128 to 256, the audio level what you hear in the headphone increases in volume (about 3 dB). See the following discussion in the forum: https://sourceforge.net/p/llcon/discussion/software/thread/01618b0c5c/#2b97

**Comment by softins** [comment]
I think it is changing the level sent to the server. I did some tests with someone else the other day, and when he changed his buffer setting, it changed the level I heard from him.

**Comment by rudolfc** [comment]
Hi,

I think so too, I remember when testing with a friend I concluded the same thing..

**Comment by corrados** [comment]
Some progress: It must be something in the server. I just checked to output the sound card signal directly back to the sound card: There is no issue. Then I tried a direct connect to the same client: There is no issue.
Now I check what could go wrong in the server...

**Comment by softins** [comment]
Did that test include the opus encoding and decoding?

**Comment by corrados** [comment]
Yes, it did.

**Comment by corrados** [comment]
You can do the test yourself. Start the Jamulus server on the same PC and connect to it. Then in the server GUI you see the port number displayed for the Jamulus client. Then in the Jamulus client connect to 127.0.0.1:[client port number]. Then the client does a self-connect, where the OPUS encoding and decoding is included. I cannot hear a volume difference in that scenario.

**Comment by rudolfc** [comment]
I have to disagree. In my situation, connected with 127.0.0.1, or via my external IP adress: the volume differences are as I described..

**Comment by corrados** [comment]
Ok, I found it. Is it fixed now: 5ace7b635c795b610d12e3c71a4e83c6c973bf71

**Comment by rudolfc** [comment]
Super!
