### ISSUE TITLE
Information duplication

### ISSUE THREAD

**Issue by gilgongo** [corrados/jamulus#107]
Maintaining the same information in more than one place can lead to bugs in the docs (and requires more maintenance work). 

We are duplicating the following:

[Server Manual .md]( https://github.com/corrados/jamulus/blob/master/src/res/homepage/servermanual.md)  vs [Running a Server](https://github.com/corrados/jamulus/wiki/Running-a-Server)

Suggest we remove servermanual.md and replace it with a link to the wiki page from README.md

[Compilation instructions INSTALL.md](https://github.com/corrados/jamulus/blob/master/INSTALL.md)  vs [Compiling on the wiki](https://github.com/corrados/jamulus/wiki/Compiling)

If the INSTALL.md file is a sources convention, then we can keep it and replace its contents with the link to the wiki. Otherwise remove it and link to the wiki from README.md (and remove the current link from the [Linux installation page on the wiki](https://github.com/corrados/jamulus/wiki/Installation-for-Linux), which will make navigating the docs easier for Linux users in any case).

[Required Hardware Setup in README.md](https://github.com/corrados/jamulus/blob/master/README.md)    vs [Hardware Setup on wiki](https://github.com/corrados/jamulus/wiki/Hardware-Setup)

Suggest replace this with link to the wiki.

**Comment by corrados** [comment]
> Suggest we remove servermanual.md and replace it with a link to the wiki page from README.md

Agreed.

> If the INSTALL.md file is a sources convention, then we can keep it and replace its contents with the link to the wiki.

Yes, an INSTALL file should be present. A link to the Wiki should do the job, yes.

> Required Hardware Setup in README.md vs Hardware Setup on wiki

Well, this section is just a kind of abstract. Something like this should be on the main page. Since this is very few information, I have no problem if we have information duplication of just these few sentences. Do you agree?

**Comment by gilgongo** [comment]
>I have no problem if we have information duplication of just these few sentences

Yes, a bit of duplication is OK if the information is going to be pretty stable over time. 

I'll make those changes then and do the relevant PRs.

**Comment by gilgongo** [comment]
Cool. All done.

**Comment by mirabilos** [comment]
There’s something to be said in favour of having the information in the git repository:

Distributions can install it, so people can read the information (corresponding to the version they installed) locally.

But I guess I missed the two hours this was open…

**Comment by gilgongo** [comment]
Well, the information is there, it's just liked to from there :-) But the number of people compiling from source is going to be tiny though, and any advantage that gives them is outweighed by minimising bugs in the docs, no? Unless I misunderstand you.
