### ISSUE TITLE
Change the way that faders responds to mouse clicks from absolute to relative

### ISSUE THREAD

**Issue by dcocharro** [corrados/jamulus#111]
Hello to all contributors, 
Thanks for the amazing application you have put out there.

At the moment, the way Jamulus Faders work is in **absolute mode**, that is, the fader will automatically jump directly to the clicked location.
I find this mode hard to make fine adjustments, because when I click on the the fader I loose the current position.

It would be great to have **relative mode** instead, the fader keeps its relative position when the user clicks - and Moving the mouse sets higher or lower values in relation to that relative position.

Also in addition, would be great to have MIDI support to control faders, solos and mutes with a  MIDI controller. I think I will open a new issue for this feature request and add some mockups for clarification.

Thanks

**Comment by gilgongo** [comment]
Hi @dcocharro I'm not sure I understand. On Windows at least (not tested on other platforms) the behaviour seems to be as you describe for relative mode.


![fders](https://user-images.githubusercontent.com/4561747/79694128-5bfffe80-8266-11ea-8160-bd6937681859.gif)

**Comment by dcocharro** [comment]
I didn't know that about Windows, that's exactly the behaviour I was trying to describe, in Mac OSX it's not working apparently.

![jamulus](https://user-images.githubusercontent.com/405771/79695182-55c15080-826d-11ea-871c-9131130ceb21.gif)

**Comment by corrados** [comment]
Interesting, I just tried it under Linux and we have the same behavior as in Windows (i.e. the desired behavior). So this seems to be a bug in Qt for Mac. Maybe there is a workaround for this possible.

**Comment by corrados** [comment]
BTW:

> MIDI support to control faders

This is already supported.

**Comment by dcocharro** [comment]
I discovered that the trackpad scrolling gesture allows to do smooth adjustments to faders. So I'll assume that the mouse wheel would also do the same behaviour.

**Comment by corrados** [comment]
@dcocharro have you check the mouse wheel behavior? Does this works for you?
If yes, do you think this issue should stay open or shall we close it then?

**Comment by corrados** [comment]
Any update?

**Comment by corrados** [comment]
I just checked in the code: I explicitely set the set size of the faders to 1: https://github.com/corrados/jamulus/blob/master/src/audiomixerboard.cpp#L62
If it does not work correctly on Mac but it does on Windows and Linux, it is a Qt issue. I hope this will be solved in future Qt versions.
Since it is not an issue in the Jamulus code but in the Qt code, I will close this Issue.
If you do not agree with that, please re-open the Iusse.
