### ISSUE TITLE
Build issue on Ubuntu: qInfo() undefined in serverList.cpp

### ISSUE THREAD

**Issue by bspratt** [corrados/jamulus#112]
Worked fine until yesterday - perhaps QT4 is no longer sufficient? If so, build instructions should be updated.

**Comment by bspratt** [comment]
On Ubuntu, at least, that would be package qt5-default - or at least that's what got my build working again.

**Comment by corrados** [comment]
Interesting, not long ago I wrote a message in the Discussion forum: https://sourceforge.net/p/llcon/discussion/533517/thread/6d3f3feb2d/

For the pull request mentioned in that forum thread we implemented a solution which is compatible to Qt4.

**Comment by corrados** [comment]
I will fix the qInfo() issue so that it will hopefully compile under Qt4 again.

**Comment by pljones** [comment]
My fault :(.  Yes, I forgot that bit, sorry.  It'll all be ConsoleWriterFactory based in the end.

**Comment by bspratt** [comment]
It was easy enough to change to QT5 once I located the right package, so whatever works for you is fine.

**Comment by corrados** [comment]
Yes, you can use Qt5. But we do not want to break Qt4 compatibility just because of qInfo(). I will fix that anyway.

**Comment by corrados** [comment]
Ok, it should now compile again. Can you please try it out?

**Comment by bspratt** [comment]
just a moment...

**Comment by bspratt** [comment]
Ausgezeichnet. Es geht mit 4 und/oder 5. Vielen Dank.
