### ISSUE TITLE
Misconfigured ASIO4ALL config can't be corrected

### ISSUE THREAD

**Issue by Hk1020** [corrados/jamulus#117]
If there is no working ASIO4ALL configuration available Jamulus will start with a popup telling this fact but with the only option to close Jamulus. There is no way to change the ASIO4ALL configuration. The only way out is to uninstall/reinstall ASIO4ALL hoping the defaults will work. Jamulus should not quit if ASIO is misconfigured. 

See also [https://sourceforge.net/p/llcon/discussion/533517/thread/777663cf94/#da0c](https://sourceforge.net/p/llcon/discussion/533517/thread/777663cf94/#da0c)

**Comment by pljones** [comment]
No, you can get into ASIO4ALL configuration without an application running.  That's much the better way to do it, in fact.

**Comment by corrados** [comment]
I did some implementations to solve this Issue, see commit: 00b11ee06a515d6fd3889aaa2e916fabdddc7ae4

If it is possible, please try it out as soon as it is available in the next Jamulus version. I will close this issue now. If you (or any other) is not happy with the implementation or it does not work for you, please re-open the issue.

**Comment by Hk1020** [comment]
Wow, I just saw this on git. I'd build from git but can only do so on a Raspberry Pi -  and there the problem doesn't exist. Anyway, just wanted to note that the extra settings app doesn't work so I really appreciate this change. And this project is great.
