### ISSUE TITLE
20.04 doc includes

### ISSUE THREAD

**Issue by drfrog666** [corrados/jamulus#118]
for ubuntu 20.04 i had to install these two pkgs besides build-essential and libjack-jackd2-dev:
 qt5-qmake
 qtdeclarative5-dev

libqt4-dev does not exist on 20.04

should put that in the docs for those using it

Thanks for a wonderful app!

**Comment by vocobox** [comment]
Mentionned your post in the wiki : https://github.com/corrados/jamulus/wiki/Installation-for-Linux

**Comment by corrados** [comment]
Ok, thanks. Then I will close this Issue now.
