### ISSUE TITLE
When Jack is stopped and Jamulus client is open, Jamulus crashes

### ISSUE THREAD

**Issue by newlaurent62** [corrados/jamulus#122]
When I stop Jack using qjackctl or jack_control (jackdbus) and Jamulus client is open (connected or not), Jamulus crashes.

Jamulus : 3.5.1
System: Ubuntu Studio 19.10

**Comment by mirabilos** [comment]
If you mean “… and Jamulus is open” (not “opened”) this is the same as #127 (in which case I’m sorry for the duplicate).

Starting Jamulus with stopped jackd (“and Jamulus is opened”) works for me, however.

**Comment by newlaurent62** [comment]
Yes i mean "is open". It's indeed a duplicate.

**Comment by corrados** [comment]
Ok, so this Issue is older than the other. So let's keep this one and close the other one.

**Comment by corrados** [comment]
This is what is currently implemented in Jamulus: https://github.com/corrados/jamulus/blob/master/linux/sound.cpp#L333
If the Jack server is shut down, Jamulus should show an error mesage and quit. It seems that showing the error message does not work and causes the crash.
But anyway, if I would fix the crash, you most probably would not be happy anyway. I guess what you want is to support that if the jack server is shut down and then restarted, the Jamulus software can then be operated again normally. But this would be a larger change in the code.

**Comment by mirabilos** [comment]
Volker Fischer dixit:

>But anyway, if I would fix the crash, you most probably would not be

Hrm, but a crash (or even malfunction) should still be fixed.
Showing a message and exitting is *much* preferrable.

**Comment by newlaurent62** [comment]
Well indeed, there are two level of answer:
- to quit with a nice error message explaining why the application exits. This is preferrable to the Apport dialog which popups when ubuntu detects a crash.
- to support the kill or restart of jack server which would be nicer in user perspective but will take much more efforts i presume.

**Comment by corrados** [comment]
I just applied a fix to the crash to the Git repo. Could you please test if that fix works for you?

**Comment by newlaurent62** [comment]
Ok thanks. That works.

**Comment by corrados** [comment]
Thank you for testing. I tested it on Windows.

So I will close this Issue now because the coredump is solved. If you want to have this feature: "_if the jack server is shut down and then restarted, the Jamulus software can then be operated again normally_" then you should create a separate Issue for that.
