### ISSUE TITLE
FR: Server logging improvement

### ISSUE THREAD

**Issue by pljones** [corrados/jamulus#123]
From #91
> On the very first registration attempt we could always output the result on the command line if "no GUI server" is run.
> @pljones can you please take care of it? It should be possible with just a few lines of code. But make sure it only outputs at the very first registration attempt and not the successive registrations every 15 minutes.

Yep.

**Comment by corrados** [comment]
Well, I changed my mind. I want all outputs now (as it is implemented right now). So I see no need for improvement. Do you?

**Comment by pljones** [comment]
I'm happy :)
