### ISSUE TITLE
Enabling History on server doesn't reproduce any files

### ISSUE THREAD

**Issue by Snayler** [corrados/jamulus#125]
Hello,

Maybe I'm doing it wrong, but I've been playing around with server options and I can't figure out what the --history (-y) option and --histdays (-D) are doing as the server doesn't reproduce any file on the selected folder.

I'm running to following command to start my server:
"C:\Program Files (x86)\Jamulus\jamulus.exe" --server --fastupdate --log "D:\Users\<redacted>\Documents\Jamulus Recordings\jamulus.log" --histdays 7 --history "D:\Users\<redacted>\Documents\Jamulus Recordings\history.log" --recording "D:\Users\<redacted>\Documents\Jamulus Recordings"

The log file works correctly, it creates the jamulus.log specified in the option on the correct folder, but no history.log file appears on that same folder.

**Comment by Snayler** [comment]
Ok, nevermind. Just found out that History expects .svg as the filename extension. Maybe this should be addressed in the -h and wiki page to avoid any confusion.

**Comment by corrados** [comment]
@gilgongo can you please take care about the documentation needed?

I will close this Issue now.

**Comment by gilgongo** [comment]
BTW when I use `-y` on a headless server, I get this in the log:

~~~
Apr 22 18:16:29 oddjob jamulus[22958]: Qt5 requires a windowing system to paint a JPEG image; image will use SVG
Apr 22 18:16:29 oddjob jamulus[22958]: AHistoryGraph::Start ( /srv/s3ql/recordings/Jams/history.svg )
~~~

What does that mean exactly? Does it default to JPEG with the GUI?
