### ISSUE TITLE
Jamulus segfaults when jackd is restarted

### ISSUE THREAD

**Issue by mirabilos** [corrados/jamulus#127]
Most of the time, when Jamulus is running while qjackctl stops/starts jackd, it segfaults.

If this isn’t a known issue or more detail is needed, I can provide individual backtraces, but I think it’s probably a larger issue.

**Comment by trebmuh** [comment]
duplicate #127

**Comment by corrados** [comment]
As discussed in the other issue, it's a duplicate. I'll close this one.
