### ISSUE TITLE
Detect if no audio Device is selected before trying to connect a server

### ISSUE THREAD

**Issue by corrados** [corrados/jamulus#129]
See https://sourceforge.net/p/llcon/discussion/software/thread/ed7698b0cb/#13a9

> It can happen that no Device is selected even though the dropdown is populated (e.g. if the audio interface you used in your previous Jamulus session is not curently connected).
> 
> If you then try to connect to a server, the main Jamulus window shows "TRYING TO CONNECT" message which is rather misleading.
> 
> The fix is of course to select input and output devices, but a more useful message would be helpful in this situation ("Please select audio devices for input and output before trying to connect").

**Comment by pgScorpio** [comment]
Another problem is that this also happens when there **is** a device selected but there are some undetected problems in it's ASIO setup !

In example when using FlexASIO, setting the number of input channels to 2 and your input device only provides 1 channel !

**Comment by corrados** [comment]
I have now implemented a check for correct audio device functionality. If the audio device does not work correctly, a warning message dialog is shown now:
![grafik](https://user-images.githubusercontent.com/46655886/100497220-230ffc80-315a-11eb-843a-d5ee2bbcf7dd.png)

**Comment by ann0see** [comment]
I think the message should start like this: "**Please open Settings** and check the[...]"
to clarify what to do for unexpected users.

**Comment by corrados** [comment]
Good idea. I just changed it:
![grafik](https://user-images.githubusercontent.com/46655886/101237503-9de89280-36d9-11eb-9c4a-cabdc85d2dc4.png)

**Comment by ann0see** [comment]
Great!
