### ISSUE TITLE
Server doesn't create RPP file when closed

### ISSUE THREAD

**Issue by Snayler** [corrados/jamulus#130]
I've noticed that the server doesn't create the Reaper Project file when we close it. It would be nice to have it create the RPP file when closed so that we can restart the server and keep the project.

EDIT: Can anyone tell me if the generated wav filenames have information that can help me put the channels together on a Reaper project?

**Comment by pljones** [comment]
The RPP is only created if a jam ends cleanly.  I've a script that can cobble a project file together.
[recover-recording.zip](https://github.com/corrados/jamulus/files/4514386/recover-recording.zip)

Unfortunately, closing the server doesn't end the jam - or anything else - all that cleanly.  If using the GUI, I _think_ I spotted somewhere that might be fixable, but for command line, I was stumped (and I use command line...).

**Comment by Snayler** [comment]
I'm currently using the GUI, so it would be a nice addition to me. Wouldn't it be possible to trap a CTRL+C signal on command line?

**Comment by pljones** [comment]
Ah!  Yes, I'd forgotten the script would need to handle `--fast-update` - thanks!!  Hm.  I'm wondering if it's always been off, too...  `POSITION` would also need fixing.

Shame the quotes around $(basename) didn't help on Windows.

**Comment by Snayler** [comment]
> 
> 
> Shame the quotes around $(basename) didn't help on Windows...

I just did a quick and dirty test on an online terminal emulator, it seems to work if you enclose the $(pwd) in quotes:

`projectName=$(basename "$(pwd)")`

**Comment by pljones** [comment]
Back to the main topic, though.  SIGINT / SIGTERM should cause Jamulus server to gracefully exit, disconnecting each client and thus ending any recording in process beforehand.

Something like the method described [here](https://doc.qt.io/qt-5/unix-signals.html) is likely to be needed.

**Comment by sthenos** [comment]
Sorry to hijack this thread, but it is relevant to me just to understand the recording process.   So the only way to get a clean recording is to: 1. bring the server up with recording option on.  2.  Ask clients to connect to the server and do their performance.  3. Tell all clients to disconnect from server.    If I stop and start the server turning on and off the recording option while clients remain connected, this would not work?

**Comment by Snayler** [comment]
@sthenos if you stop the server while the recording is undergoing (meaning there's still clients connected), the server will keep the recordings for all channels up to the point of when you stopped it.  It will just not create the RPP file necessary for Reaper to correctly place the sound files at the correct times and in the correct channels.

**Comment by pljones** [comment]
I've done a first pass through the code based on a few bits and pieces and I've got a second reduction up pass to do, followed by a final clean up pass, then I can start testing it.  It should work on Windows and Linux (and, given MacOS is *nix-like enough, there too).

Unfortunately, I've been a bit burnt out from "real work" this past week or so.

**Comment by pljones** [comment]
The mostly cleaned up version now seems to be working on Linux.  I expect the GUI shutdown on Windows to work, too (as that's a QT signal to slot handler).  I've got to test that and the command line handling on Windows, though.  Might get it done today.

https://github.com/pljones/jamulus/tree/feature/130-signal-handling

The code is "based on" (i.e. I ripped apart and put back together) an example that covered both Windows and Unix signals and more "nicely" than the examples the Google is currently returning -- but of course, now I can't find it again.

**Comment by pljones** [comment]
Except that the Windows version seems to run in the background, might have been nice for that not to happen:
![image](https://user-images.githubusercontent.com/1549463/81427670-0460fe80-9153-11ea-9c8d-510971f522ce.png)
It's rather messy from the command line...

**Comment by pljones** [comment]
Hm.  With the GUI open (on Windows, not tried Linux), the server application sends the "unregister" to the central server -- but doesn't create the RPP.  Without the GUI open (on Linux; on Windows Task Manager kill is rather final), the server application claims to shutdown cleanly - but doesn't send the "unregister" to the central server...
```
 *** Under the GNU General Public License (GPL)
Requested to register entry for 192.168.1.5:55852 (192.168.1.5:55852): Windows test server
Requested to unregister entry for 192.168.1.5:55852
Requested to register entry for 192.168.1.19:55855 (192.168.1.19:55855): Slave4
```
----
```
 *** Under the GNU General Public License (GPL)
Server Registration Status update: Registration requested
Server Registration Status update: Registered
^COnShutdown caught
About to quit
```
Let's see if that can all be sorted out...

**Comment by pljones** [comment]
OK, so I had to refactor the jamrecorder to implement threading correctly (apparently the examples in most of the Qt documentation are wrong, unsurprisingly).  That's got thread shutdown handled cleanly.  With that in place, everything (apart from command line on Windows - there _is_ no command line version for Windows, just a "no GUI" version) seems to work.

I'll install this build locally and see if it seems stable.  @Snayler, if you want to pull it and try, please do and let me know how it goes.

**Comment by newlaurent62** [comment]
So we have two actions:
1) save current jamulus state (config file and jam recorder)
2} exit the application 

So each signal type we should do:
SIGUSR1/USR2: save action
SIGINT: save action and exit
SIGTERM: save action and exit
SIGKILL: exit

Is that right?

**Comment by pljones** [comment]
This feature is about closing the server application.  SIGINT and SIGTERM are now handled and tell the application to close.  Closing the server window also tells the application to close (it already did).

The main change is what happens when the application closes - it cleans up tidily, telling the Central Server it's going and terminating recording.

#170 will cover other features regarding intermediate cutting of recordings.

**Comment by Snayler** [comment]
I'm quite new to using Qt Creator and I'm having some trouble. I can build Jamulus and Run it from Qt Creator, but I'm not sure how to create an installer on Windows.

**Comment by Snayler** [comment]
Works great on GUI under Windows. It does not work when the server is launched as --nogui, but I guess that was expected.

**Comment by pljones** [comment]
Yeah, for some reason I couldn't understand, the Windows "--nogui" detaches from the command window.  I think that must be Qt on Windows, as the "not --nogui" also detaches.  Neither do on Linux.

**Comment by pljones** [comment]
I've raised a pull request: https://github.com/corrados/jamulus/pull/195

**Comment by corrados** [comment]
I have merged #195. Is this issue fixed with that merge? If yes, please close this Issue.

**Comment by pljones** [comment]
Yep, I've a few other improvements that I'll raise separately.

**Comment by Snayler** [comment]
Yes, I'm happy with the solution. Thank you @pljones  and @corrados.
