### ISSUE TITLE
Additions to instrument list

### ISSUE THREAD

**Issue by dszgit** [corrados/jamulus#131]
It would be great to get all the standard orchestral instruments added to the Instrument list.  It looks to me that they're all there except these:
  * viola
  * oboe
  * bassoon
  * percussion (not the same as Drum Set!)
  * tympani (though will there ever be call for this in Jamulus?)
  * harp

Also see [this thread in the forum](https://sourceforge.net/p/llcon/discussion/software/thread/c6b3e51db9/#4671) where Bodo requested some other more esoteric instruments, and suggested a procedure for adding them.  I also don't know if it makes sense to add variants of the standard instruments, like bass clarinet, contrabassoon, English horn.

As the list grows (which seems good to me), it would also be nice to have some sensible sorting to make it easier to find specific instruments.

**Comment by gilgongo** [comment]
@corrados Would there be a problem with allowing free text input (eg an "Other..." option) for the instrument list? They would not be able to specify an icon of course unless we just had a generic one.

**Comment by bomm** [comment]
I suggested to add instruments more or less common in folk music.

* Drum (for any special type of drum not yet listed)
* Percussion (for any type or set of percussion instruments not yet specifically listed)
* Bodhran (special type of drum, very common in Irish folk music)
* Bouzouki (related to mandolin or lute, very common in Greek and Irish folk music, there are differences between Greek and Irish versions)
* Nyckelharpa (keyed string instrument played with a bow, very common in Swedish folk music, sometimes used in other folk music)
* Hurdy-gurdy (keyed string instrument played by turning a wheel, often used in folk music)
* Jew's harp (used in folk music)
* Tamburello

From a folk musicians point of view, these are not esoteric at all.

As the instruments have an assigned type it might be possible to sort/group or filter by this type if the list gets longer. I also suggest to alliw alphabetical sorting (in addition to filtering or grouping by type).

Additional thought:
Would it be possible to extend the protocol to transmit an additional instrument name?
This could be used with an instrument selection "none" or "other" if there is no suitable instrument in the list or to add a more specific name or type to an existing instrument, e.g. "pedal harp", "lever harp" or "Celtic harp", "Bohemian harp" or Greek bouzouki vs. Irish bouzouki.
Older versions of the software should ignore this information.

Bodo

**Comment by bomm** [comment]
For the icons of the instruments I will either provide links to images with a suitable license or create images myself.

**Comment by Snayler** [comment]
Maybe creating a table of instruments with different categories would be best than having a dropdown menu, to enable a bigger instrument list with easy to find instruments.

Getting images without infringing copyright would be easy through a google image search and filtering the results by usage right.

> 
> 
> 
> Would it be possible to extend the protocol to transmit an additional instrument name?

I think it's important to keep the transmission of data to a minimum as to not affect the audio transmission as much as possible.

**Comment by corrados** [comment]
> it would also be nice to have some sensible sorting to make it easier to find specific instruments.
> Maybe creating a table of instruments with different categories would be best than having a dropdown menu, to enable a bigger instrument list with easy to find instruments.

Yes, this is no big deal to support that in the GUI. Since the number of instruments was low, there was no need in the past.

> Would there be a problem with allowing free text input (eg an "Other..." option) for the instrument list?

I am not a fan of such a solution. Let's keep what is currently implemented and just enlarge the list.

> Getting images without infringing copyright would be easy through a google image search and filtering the results by usage right.

I do not think that it is that easy. Copyright issues can easly destroy an open source project...

> For the icons of the instruments I will either provide links to images with a suitable license or create images myself.

Getting the pictures is the hardest part. If you have a good picture which free licence, you simply have to select an appropriate name for the instrument and select a catagory:
OTHER_INSTRUMENT,     
WIND_INSTRUMENT,      
STRING_INSTRUMENT,    
PLUCKING_INSTRUMENT,  
PERCUSSION_INSTRUMENT,
KEYBOARD_INSTRUMENT,  
MULTIPLE_INSTRUMENT

**Comment by trebmuh** [comment]
> I do not think that it is that easy. Copyright issues can easly destroy an open source project...

A bunch of picture searching allows to filter by licenses. Including flickr, google images, [wikimedia](https://commons.wikimedia.org/wiki/Accueil) and probably others.

**Comment by corrados** [comment]
> The image is my own work. I provide the image files under the license CC0.

Thank you.

**Comment by jp8** [comment]
The list currently has a "guitar + vocal" but no "keyboard + vocal".
Could it be added ?

**Comment by corrados** [comment]
If you provide my with an icon, yes.

**Comment by dszgit** [comment]
> I suggested to add instruments more or less common in folk music. 
> From a folk musicians point of view, these are not esoteric at all.
Sorry!  I guess I just meant I didn't know what they were :)   I should get out more...

**Comment by jp8** [comment]
![keysvocal](https://user-images.githubusercontent.com/6978815/80127363-1dcb4d80-858c-11ea-9a5c-239bc4324359.png)

**Comment by corrados** [comment]
What is the licence of that icon?

**Comment by jp8** [comment]
Sorry all I did is merge the two existing images (I rotated the keyboard).  All rights are with the original guy who did the two icons

**Comment by corrados** [comment]
Ok, great. Then I will add it to Jamulus now. Thanks.

**Comment by jp8** [comment]
Thank you corrados.

**Comment by corrados** [comment]
Regarding other new instruments (like the ones mentioned in the initial post): Please create icons for me and I will include them in the Jamulus software then.

**Comment by dszgit** [comment]
Here is a bassoon.  I made it (in inkscape), since I thought the free ones I could find online didn't really look distinctively bassoon-like.  I hereby release it into the public domain, via [CC0](https://creativecommons.org/share-your-work/public-domain/cc0/).

I'm posting a zip file containing both the original svg in case that's helpful, as well as a png I exported at about the as the other instrument icons.  Let me know if this is what's needed, or if I should do something different.

I'm also working on a oboe, and then maybe percussion and tympani.

For viola, I'm not sure how to distinguish it from a violin, so maybe just use the same icon.

[bassoon.zip](https://github.com/corrados/jamulus/files/4565198/bassoon.zip)

**Comment by corrados** [comment]
It's added. Thank you.

**Comment by dszgit** [comment]
Here is an oboe.  Same deal:  made in Inkscape, released to public domain as [CC0](https://creativecommons.org/share-your-work/public-domain/cc0/).
[oboe.zip](https://github.com/corrados/jamulus/files/4567190/oboe.zip)

**Comment by corrados** [comment]
Oboe just added, thanks.

**Comment by dszgit** [comment]
And a harp...  Also inkscape, public domain [CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)
[harp.zip](https://github.com/corrados/jamulus/files/4567225/harp.zip)

**Comment by dszgit** [comment]
For viola, I suggest using the violin icon, but rotated just to be different.  Like this.
![viola](https://user-images.githubusercontent.com/11364388/80857784-8ec0d400-8c22-11ea-8cb5-5285cc6b60b2.png)

**Comment by corrados** [comment]
What about a different color of the instrument for the viola to distinguish the viola from the violin? What do you think?

**Comment by dszgit** [comment]
> What about a different color of the instrument for the viola to distinguish the viola from the violin?

I don't know...  Real violas are the same color as violins. But they do hold them at an
odd angle :)  (Because, you know, they're big--I've had a principle viola jab me with his scroll, sitting inside first stand cellos!!)

**Comment by dszgit** [comment]
> But they do hold them at an odd angle :)

By that token, maybe I should have rotated the other way, with scroll more to the left.

**Comment by dszgit** [comment]
Like this.
![viola](https://user-images.githubusercontent.com/11364388/80865380-56081580-8c89-11ea-9656-a2c313e06984.png)

**Comment by dszgit** [comment]
It will look different in the list, at least.
It's also true that many violists also play violin, so maybe not so bad to confuse them at first glance.
But I guess it could be a different color too.

**Comment by corrados** [comment]
I have now added the viola. I have use the mirror-symmetric version and I adjusted the color a bit:
https://github.com/corrados/jamulus/blob/master/src/res/instruments/viola.png
We may change this png later on but as a first start I think it is acceptable.

**Comment by corrados** [comment]
> tympani (though will there ever be call for this in Jamulus?)

I agree with your comment. I guess nobody will using this with Jamulus. So I think it does not make sense to add this.

**Comment by bspeer** [comment]
I have created this icon for the Congas instrument and freely contribute it The image is my own work. I provide the image file under the license CC0.
[congas_icon.zip](https://github.com/corrados/jamulus/files/4595202/congas_icon.zip)

**Comment by corrados** [comment]
I have just added your congas icon. Thank you.

**Comment by bspeer** [comment]
Thanks you, Volker! Will submit a Bongo soon.

**Comment by bspeer** [comment]
I have created this icon for the Bongo
[bongo.zip](https://github.com/corrados/jamulus/files/4606302/bongo.zip)
 instrument and freely contribute it The image is my own work. I provide the image file under the license CC0.

**Comment by corrados** [comment]
It's added, thanks.

**Comment by bspeer** [comment]
Just an idea, but how about a popup window table similar to the ones used to display the smiley face icons in rows and columns to present the instrument choices?

**Comment by bspeer** [comment]
Oops! Just realized Snayler already suggested the table idea...

**Comment by Alberstein8** [comment]
Hi,
As a choir singer, we use Jamulus for our rehearsals. I'd like to add vocals icons for each tipical choir voices: sopranos, altos, tenors, basses. Would it be possible? Also it would be great if we could sort the channels by instrument, so we can have same voices together by groups.
Thanks for your efforts in making this software so awesome!

Alberto

**Comment by corrados** [comment]
> Would it be possible?

Yes, if you provide me with the instrument icons.

> Also it would be great if we could sort the channels by instrument, so we can have same voices together by groups.

There is already a feature request for it: https://github.com/corrados/jamulus/issues/178

**Comment by Alberstein8** [comment]
Hi,

Please find below icons for choir voices, sopranos, altos, tenors and basses made by myself, if you consider to add them to the instruments list as suggested.

[instrchoirvoices.zip](https://github.com/corrados/jamulus/files/4639343/instrchoirvoices.zip)

Thanks,
Alberto

**Comment by corrados** [comment]
Thanks Alberto, they look funny :-). What is the licence for these pictures? Is it under the license CC0?

**Comment by Alberstein8** [comment]
Hi,

I took them from pngwing.com. I think they allow use of the images if it's
not for commercial.

Alberto

**Comment by corrados** [comment]
On the homepage of pngwing.com I can only read "Transparent background png images for designers". I cannot find a licence file for any of the pictures. It is also unclear who has created them. There is a "contact us" but this only opens a new email. I do not see a true "About" page or something similiar. To me this looks very suspicious. I would not want to include any picture from that page in Jamulus. Unfortunately, this is too critical.
Can you please look at https://openclipart.org if you find a similar picture?

**Comment by Alberstein8** [comment]
Hi,

No problem, I understand, I'll look for new ones. What is the max size of
the icons? And I'm thinking about using pictures from my own, is it ok?

Alberto

**Comment by corrados** [comment]
The height should not be larger than 27 pixel and the width not more than 35.
If you use your own pictures, that should be fine.
To have a proof of licence, please do it like above, e.g., "_I provide the image file under the license CC0._"

**Comment by Alberstein8** [comment]
Ok, hope this works. My own pictures below. 
I provide the images files under the license CC0.

[instrvocalchoir.zip](https://github.com/corrados/jamulus/files/4640010/instrvocalchoir.zip)

So excited I can be a tiny part of this software!

Alberto

**Comment by corrados** [comment]
I just added your icons. Thank you for your contribution.

**Comment by corrados** [comment]
I think it does not make sense to keep this Issue open. If anyone wants to contribute a new instrument picture, he/she should create a new Issue for that. I'll close this one now.
