### ISSUE TITLE
Server List Not Populating

### ISSUE THREAD

**Issue by senorblasto** [corrados/jamulus#132]
Jamulus was working fine for me until the recent update.
Now I do not get a list of servers.
When I press connect it instead connects me immediately to a server instead of showing me a list of options. 
Others are having this problem.

I am using Windows, and the problem occurs on multiple computers.
I believe most of the people in the following email are using MacOS
I received the following email 

> I have a couple students investigating Jamulus for a class and they have a question.  Before they established their accounts they saw a list of servers, but now they have an account, the list is gone.  Not only that, but they are automatically connected to a server, sometimes with poor audio quality (one was connected to Brazil).  Can you reply-to-all if you have suggestions about how to view and choose a specific server?

**Comment by gilgongo** [comment]
We do get reports of this from time to time. The trouble is it seems to be intermittent and I've not been able to reproduce it. 

To date, those people who have reported the issue fixed seem to have tried one or more of the following:

1. [Upgrading ](https://sourceforge.net/projects/llcon/files/)to the latest version of Jamulus (currently 3.5.1). Note that we are releasing new versions quite often, so it's easy to get out of date.

1. Switching the client to use another Central Server, then switching back again (or staying on that Central Server if there are enough servers listed to use).

1. Downgrading to the previous version, running that, then upgrading to the latest.

1. Running the client with `--showallervers` (partial fix)

**Comment by corrados** [comment]
Can you please check if the following setting is set to Default on your PC and the PC of the students:
![grafik](https://user-images.githubusercontent.com/46655886/80102804-98d43a00-8573-11ea-8926-bf9ebc737588.png)

**Comment by vocobox** [comment]
I encountered something similar yesterday evening : the server list remained empty for a "long time" (10 seconds), but finally was populated with servers. The problem just disappeared few minutes later.

**Comment by senorblasto** [comment]
> Can you please check if the following setting is set to Default on your PC and the PC of the students:
>
I tried using the default settings as well as manually entering  jamulus.fischvolk.de:22224 and the older 22124 version.  Both appeared to immediately  bring me into an ongoing jam session, where I could see logged in users as well hear them.
Normally I would have been taken to the server list.
I'll see if there is a log I can attach.
Thank you for your help!

**Comment by corrados** [comment]
> I am using Windows, and the problem occurs on multiple computers.

Hmm, I have three PCs, one with Windows, one with MacOS and one with Linux. I cannot reproduce the issue you reported here on any of my PCs.
Maybe I understood your issue not correctly. You say that you press the Connect button on the Jamulus main windows and no additional dialog opens but you are immediately connected to a server without having clicked with the mouse or have pressed any additional key on the keyboard?

**Comment by senorblasto** [comment]
That is correct, I've tried with the latest version, as well the previous two versions.

Each time I have erased Jamulus and reinstalled.  Then try to connect with default settings as well trying both servers manually.  Always the same thing although I believe connected to a different server each time.

One thing to note is EVERY time I've been instantly connected  that room has many people actively playing.  Perhaps the same thing is happening to them and they assume that's how it works?

**Comment by gilgongo** [comment]
> Both appeared to immediately bring me into an ongoing jam session

@senorblasto I can reproduce this if I put the Central Server address into my _connection setup_ window (the window you get when you click the "Connect" button). But that's not what @corrados was referring to in [his question](https://github.com/corrados/jamulus/issues/132#issuecomment-618390709). His screenshot is from the Settings window (the window you get when you click the "Settings" button.) 

Can you try different settings for the Central Server in the Settings window?

**Comment by pljones** [comment]
@senorblasto, can you post a screen shot?

**Comment by corrados** [comment]
In the Jamulus Discussion forums there are a lot of posts about this topic. Here is the link:
https://sourceforge.net/p/llcon/discussion/533517/thread/7c3f490016/

**Comment by pljones** [comment]
That leaves me speechless.  Are ISP _actually_ allowed to do that legally?  Do they issue contracts that tell people clearly that they only get part of the internet - which, as this shows, is what they're doing (OK, by default - but if they're selling something else in their contracts, that should be the default).

I'd recommend suing.  Really.

**Comment by senorblasto** [comment]
From the sourceforge discussion mentioned above:

> I have discovered the on the virgin media network there is a setting called
"block partial packets" when that is enabled it results in empty server
list and by default that option is set for virgin media customers. Turn
it off and all is good

> outer.

So I used a network activity sniffer and I could see the UDP messages going
out on port 22124 / 22134 but never coming in.
I realized that my internet provider is sharing a same fixed router IP for
several customers and sharing the ports range between
the different customers. My attributed range was not including the 22124 so
every UDP packets coming in were sent to another router.

So, for people in France that are experiencing the same problem, if your
internet provider is Free.fr, you have to ask a full stack V4 Ip address by
going in your Freebox management online interface. It takes 10 minutes to
be operational.

Thank you corrados!  I'll see if I can change the settings my self otherwise I'm calling comcast.
thanks for a making such great software and sorry for wasting your time on an issue that has nothing to do with the software.
