### ISSUE TITLE
When hosting a server on my mac we have sound loss

### ISSUE THREAD

**Issue by hamidogh** [corrados/jamulus#133]
Hello I am a new user so forgive me if the question was already answered, I was trying to host a jamulus server for me and my friends on my mac, everything was fine until the buffer turned red and we had no audio for a few seconds until audio comes back. I have a 100mbps down and 30 mbps uploads so its not a bandwith issue, we are all from the same area we live in the same exact city, I forwarded my port and it was doing the same thing, used a Windows PC and same problem and plus I am not on wifi I am wired so what could be my problem ? Thanks !!

**Comment by pljones** [comment]
You'll need to look into what's happening locally on your PC to find out, I think.  The fact you got the red indicator means you were not able to process fast enough, generally, in my experience.

**Comment by Snayler** [comment]
Take a look into other applications that may be competing with network or CPU usage. On a Windows PC, the Resource Monitor is of great help to diagnose this (Activity Monitor on Mac). Take special attention to what processes are pulling more resources during dropouts.

**Comment by hamidogh** [comment]
Thanks ! I will try that later with my friends

**Comment by hamidogh** [comment]
So after looking at my activity monitor my cpu was nerver over 20% usage, I am using a macbook pro 13inch i5 2015 is my pc too slow to host servers ?

**Comment by Snayler** [comment]
Should be fast enough. Check the network tab

**Comment by corrados** [comment]
Any updates on this topic?

**Comment by hamidogh** [comment]
Still had the same problem, even tried with a windows PC and had the same isssue, even tried to open the ports on mu router and still had the issue

**Comment by corrados** [comment]
There are open questions, see above:

> Check the network tab.

and

> Also, are you connected through wifi or cable?

**Comment by corrados** [comment]
Maybe this issue is somewhat related to this one: https://github.com/corrados/jamulus/issues/182

**Comment by Skeezixes** [comment]
It may be related to #212 which appears to only happen when Server and Client are running on the same machine.

**Comment by corrados** [comment]
This one is very old. I'll close this now. @hamidogh If you still have issues with your Jamulus server, please open a new Issue.
