### ISSUE TITLE
Jamulus client won't start on Windows when .ini file is broken

### ISSUE THREAD

**Issue by elliotclee** [corrados/jamulus#135]
The attached .ini file (which was left by a previous session of Jamulus) prevents the Jamulus client from starting on Windows. I think it might be core dumping.
[jamulus.zip](https://github.com/corrados/jamulus/files/4525288/jamulus.zip)

**Comment by FabriceReynolds** [comment]
I had the same issue when upgrading from version 3.4.4  to ^3.4.5. I have to delete the ini files from my appData folder on Windows

**Comment by corrados** [comment]
I tried it out on my PC but I could not reproduce the crash.
Do you have multiple ASIO drivers installed on your PC? I.e. is the "Device" drop down box filled with more than just one entry?

**Comment by elliotclee** [comment]
Yes I do have more than one ASIO device on the list… Elliot From: corradosSent: Friday, April 24, 2020 9:14 AMTo: corrados/jamulusCc: elliotclee; AuthorSubject: Re: [corrados/jamulus] Jamulus client won't start on Windows when .ini file is broken (#135) I tried it out on my PC but I could not reproduce the crash.Do you have multiple ASIO drivers installed on your PC? I.e. is the "Device" drop down box filled with more than just one entry?—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by corrados** [comment]
Ok, so it might be that Jamulus crashes on one of the ASIO drivers. I have this right now with JackRouter (being worked on, see another Issue). If the list is changed, e.g., by removing or adding a new ASIO driver, Jamulus still has the same number stored for the selected device and then it can take the problematic driver and crashes. Maybe this is the case for you.

**Comment by elliotclee** [comment]
Yea, I posted hints on a possible fix to the JackRouter crash 😊  From: corradosSent: Friday, April 24, 2020 9:18 AMTo: corrados/jamulusCc: elliotclee; AuthorSubject: Re: [corrados/jamulus] Jamulus client won't start on Windows when .ini file is broken (#135) Ok, so it might be that Jamulus crashes on one of the ASIO drivers. I have this right now with JackRouter (being worked on, see another Issue). If the list is changed, e.g., by removing or adding a new ASIO driver, Jamulus still has the same number stored for the selected device and then it can take the problematic driver and crashes. Maybe this is the case for you.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by FabriceReynolds** [comment]
> Ok, so it might be that Jamulus crashes on one of the ASIO drivers. I have this right now with JackRouter (being worked on, see another Issue). If the list is changed, e.g., by removing or adding a new ASIO driver, Jamulus still has the same number stored for the selected device and then it can take the problematic driver and crashes. Maybe this is the case for you.

Ah yes I also have JackRouter so that may be the issue and the difference being that the version ^3.4.5 is 64 bit whereas the previous versions were 32bit. There is an issue with JackRouter in 64bit Jamulus

**Comment by corrados** [comment]
@elliotclee with the newest Jamulus 3.5.2 which includes the fix for JackRouter 64 bit, do you still see the crash with the ini file?
If the crash was caused by the JackRouter, we may close this issue. What do you think?

**Comment by elliotclee** [comment]
Yea, seems to be fixed as well by that other fix!
