### ISSUE TITLE
Jack : when sound card is mono capture Jamulus complains it cannot make connections

### ISSUE THREAD

**Issue by newlaurent62** [corrados/jamulus#137]
When using a mono capture device / stereo playback, Jamulus complains that it cannot make connections but when i start it with -j, i can make manual connections in qjackctl.

What we could expect is to connect mono input to both Left and Right if Stereo is activated, or left if mono is activated in Jamulus settings. Otherwise print a message "connections could not be done" and start Jamulus anyway.

**Comment by corrados** [comment]
That is interesting. I thought the case that the input is mono only should be take care of here: https://github.com/corrados/jamulus/blob/master/linux/sound.cpp#L131

Since you are most probably running Jamulus on Linux, are you able to compile Jamulus? I would like to do some tests.

**Comment by newlaurent62** [comment]
Yes shure. 

The code you point me out work as expected. If it's not a stereo an exception is raised. 

If the left or right connect fails you could print a warning message and go ahead without connecting the missing ports ?

With jack we can still connect Jamulus to other applications (not physical ports) even if the hardware is playback only or even if it is capture only.

**Comment by corrados** [comment]
Yes, you are right. Jamulus should never exit with an error if the connection does not work. BTW, you suggest to "connect mono input to both Left and Right" but this is not needed if the following is implemented in Jamulus: https://github.com/corrados/jamulus/issues/97#issuecomment-620044220
Then you would only connect the single mono in port but in Jamulus you can then distribute this input to left and right channel.

**Comment by corrados** [comment]
Can you please just remove the following "throws":
https://github.com/corrados/jamulus/blob/master/linux/sound.cpp#L128
https://github.com/corrados/jamulus/blob/master/linux/sound.cpp#L137
https://github.com/corrados/jamulus/blob/master/linux/sound.cpp#L152
https://github.com/corrados/jamulus/blob/master/linux/sound.cpp#L161
Then recompile and test if it now works better for you?

**Comment by newlaurent62** [comment]
That works.

**Comment by corrados** [comment]
Thank you for testing. I'll apply this fix to the code as soon as I am back on Git master (I am currently developing on a feature branch).

**Comment by newlaurent62** [comment]
I don't know what's your mind on warning the user that a jack connection could not be established ?

**Comment by corrados** [comment]
Do you think a warning is needed? Usually we have a stereo input. This works fine. If you have a mono input, this also works fine now (you have just tested it). So I do not see a need for a warning message.

**Comment by newlaurent62** [comment]
At least if no connections are made to physical ports (no input or no output), a message could be print to warn the user. May be something wrong or expected but it's not usual and should be pointed out.

**Comment by corrados** [comment]
Recently I made some changes to the jack audio interface. Can you please check if it still works as expected for you?

**Comment by newlaurent62** [comment]
This works fine.

Some remarks : With my mono input device, there's only 3 input ports in Jamulus and 4 output ports. The jamulus:input_1 is activated in the input channel mixer left and jamulus:input_2 is activated in the input channel mixer right (but nothing is connected to the jamulus:input_2 (my capture device is mono). Could it be jamulus:input_1 activated in the right channel mixer ?). 

The mixer works. Good job ! You are going to remove Audio Channels in Settings ? Or will it be a short hand configuration for the channel mixer ? (which i think will not be easy to understand for beginners). Will you add a volume gauge for input and output mixer ?

I connected an audio player to input_2 and input_3 and after setting the input channel mixer it works as expected.

**Comment by corrados** [comment]
> there's only 3 input ports in Jamulus and 4 output ports

This is something I am looking at soon. It seems Jamulus counts the midi channels as audio channels which is not correct.

> Could it be jamulus:input_1 activated in the right channel mixer ?

You have to do this manually. But you have to do it only once. Jamulus stores the level of each input.

>  You are going to remove Audio Channels in Settings ?

No, the button (which is new) shall stay there. Do you have any issues with that new button?

> which i think will not be easy to understand for beginners

That is a good question. Previously there were combo boxes where you could select an input and output channel (thas was only on Windows and MacOS). Now you have a button instead. For beginners, the default settings will work fine (i.e. the first channel on left, second channel on right). If anybody wants to change the default behavior, then he has to enter the new dialog.

**Comment by corrados** [comment]
> This works fine.

Since everything works as expected, I will close this Issue now.

**Comment by newlaurent62** [comment]
Some ideas:

Well since you store the level of each input, may be you should manage preset for use with differents instruments / settings / sound cards and allow to select a preset from command line.

rather than a fix number of input and ouput channel (even if depending on sound card), you could add an input with the number of input channel and output channel to create with the Jamulus jack client ? And allow to fix it at command line.
