### ISSUE TITLE
Expiring empty servers?

### ISSUE THREAD

**Issue by gilgongo** [corrados/jamulus#140]
If my client list is reliable, it's not uncommon to see well over half of servers listed at any one time with zero musicians in them. Apart from this being discouraging (people don't want to join a jam if they think they'll be on their own), it's also an issue if we are still hitting the 200 server limit.

Might we consider an expiry time on empty servers?

**Comment by vocobox** [comment]
I am surprised to often see lot of empty servers as well, and lot of people in a single server. I wonder if there are quality metrics beside latency that should be measured to indicate that these empty servers are actually note safe for jaming because of other problems (e.g. limitation in number of musicians)?

**Comment by gilgongo** [comment]
>  indicate that these empty servers are actually note safe for jaming because of other problems

Regardless if they are safe or not, if nobody's in them, I'm not inclined to join :-)

**Comment by corrados** [comment]
If the Central Server is empty, e.g., at night when people are sleeping, shall this one also be removed ;-).

**Comment by corrados** [comment]
One has to make a start. If you log into a server in the evenings when a lot of people are online, it will not take long that others join.
But usually the Central Server and servers with a specific name (e.g. Musician Lounge) or servers which are promoted in, e.g., Facebook are usually more crowded than others.
Of course it makes a difference if the server is reliable (low ping, good upload rate) or not.

**Comment by gilgongo** [comment]
> If you log into a server in the evenings when a lot of people are online, it will not take long that others join.

Well that's not my experience, but I'm willing to accept I'm in the minority. I know that I'd rather join a server of 1 or more participants than wait alone in one with zero in the hope that somebody joins (and my own server logs show this seems to be the case).

> Of course it makes a difference if the server is reliable

One person's low ping is another's slow one though, so I'm not sure if that's always true, is it?

> If the Central Server is empty, e.g., at night when people are sleeping, shall this one also be removed

Heh. I'd not considered that :-) But I would hope that a server running in Central Server mode  (`-e localhost `?) would not expire.

**Comment by corrados** [comment]
Well, it is hard to judge who is allowed to have a server in the list and who is not. I do not want to discriminate server operators. E.g. you have a music school which relys on the fact that their server is listed in the server list so that students can connect to it. But most of the time there is no teaching going on. If you remove such a server shortly before a teaching session is to be started, there will be a lot of frustration. And this is just one example. There are certainly plenty more examples of this kind...

**Comment by pljones** [comment]
The thing is, how does the Central Server know to stop or start advertising a server?  The Central Server doesn't go out and count the clients on each server currently - that's left to the interested party: the client.

So you'd have to ask each server to tell the Central Server when it sends it's regular "ping", "Hey, and I've got non-zero clients right now" (or zero...).  If it keeps saying zero, it'll be listed for losing its spot in the list (but not lose it).

OK, so along comes a server that's not in the Central Server's list.  The Central Server, of course, doesn't know if it's previously been listed, so considers it "new", regardless.  It checks to see if there's space.  If _not_, the oldest empty server gets dropped off.  Next time that dropped server goes "Ping, empty", the Central Server says "Sorry, full".

Now that server sends its next "Ping, empty".  Of course, it's now not in the Central Server's list.  So the above gets applied to what this server, as if it had never been seen before...

It gets a bit of a juggling act and seems like it's just going to be bouncing one or two entries around forever...

**Comment by gilgongo** [comment]
@pljones Oh OK. I was assuming servers would simply "disconnect" from the Central Server after a period of time being empty (10mins, say). If the server operator wanted to re-connect it, they'd hit a "reconnect" button in the GUI, or perhaps connect a client directly to if it was a headless server on a remote machine.

> I do not want to discriminate server operators.

OK if there's a clear use case not to expire, then that's a good point. There is the "80/20" rule of course (AKA don't annoy the majority for the sake of the minority), but maybe that's not strong enough here. 

Good to have explored it though, so closing.
