### ISSUE TITLE
auto detection of "bad network sounds"

### ISSUE THREAD

**Issue by mawess** [corrados/jamulus#143]
I understand this could be hard nut to crack but it would be VERY welcome if Jamulus could detect and suppress freakish sounds that is the result of bad network communication.

**Comment by corrados** [comment]
Have you tried the new release 3.5.2 yet? I made a big improvement in that area, see:
https://github.com/corrados/jamulus/blob/master/ChangeLog#L30

**Comment by corrados** [comment]
Any update on this? Did the 3.5.2 help?

**Comment by mawess** [comment]
sorry. havent had time to check this yet.
/mats

**Comment by corrados** [comment]
Did you have time to check it?

**Comment by mawess** [comment]
it may be better . Ihave run it and i have heard noise but its true that the noise is nicer now. /m

**Comment by corrados** [comment]
Ok, great. So we can close this issue now?

**Comment by mawess** [comment]
yeah. do that. i can issue a new one if ot reoccurs.
/m
