### ISSUE TITLE
Sample Rate choice OSX / Jack Audio Toolkit Integration

### ISSUE THREAD

**Issue by remixmabix** [corrados/jamulus#15]
Hello,

First let me say that I haven't got any problems to compile the project and I have to say that it is clear like water. (I love QT)

Well actually it is not an issue but a request
All my projects are saved in 44100Hz and default value of Jamulus is 48000, it could be better if we could choose the sample rate.

Thanks for the great job !

**Comment by corrados** [comment]
It would be possible to support 44.1 kHz sample rate in Jamulus but I would have to include a resampler for that. This causes the resulting buffer size at 48 kHz not to be a multiple of 128 so we need an additional conversion buffer which introduces a bit of a delay. So using 48 kHz is the ideal case for Jamulus and that is the reason the Jamulus software forces the users to use that sample rate. I think most (if not all) recent audio cards should support 48 kHz sample rate.

**Comment by mangelajo** [comment]
If it's for recording purposes you can always resample 48kHz to 44KHz

**Comment by vandenoever** [comment]
The simplicity of everyone being on 48kHz is nice. If you want 44100Hz, you can post-process your recordings.

**Comment by mangelajo** [comment]
Do we have any documentation on how recording works?

**Comment by pljones** [comment]
You understand that recording is server side.  The only current documentation is the built-in help (Jamulus --help).  When enabled, a recording starts when the server "starts" (i.e. on first connection) and ends when the server "stops" (i.e. on last disconnect for that session).  You get one (pre-fader) RIFF WAVE file per connection, plus a Reaper RPP file describing how to put them all together on the timeline.

**Comment by remixmabix** [comment]
Ok I'm fine with this answer
