### ISSUE TITLE
Provide configuration settings for connecting multichannel interfaces in LINUX

### ISSUE THREAD

**Issue by matthison** [corrados/jamulus#151]
Taken from the Discussion forum:

https://sourceforge.net/p/llcon/discussion/software/thread/6c68868e88

Just like to add a note here, that I got my SoundCraft UI24R Digital mixer via USB on my LINUX machine (and WIN 10) up and running with Jamulus :-) . So currently not much people seem to be aware that this great Mixer is running out of the box with LINUX (UBUNTU 18.04). So you could add this interface as verified with LINUX/WIN, unfortunately I have no MAC (someother can verify?).

The feature list of the mixer is rich, and you need to configure your inputs/outputs to your needs. This one has 32x32 Audio interfaces! I needed to connect the capture inputs and playback outputs to other than port 0/1.
Port settings 0/1 is hardcoded in sound.cpp of LINUX sources. I modified this with the ports I need and it works great, i.e. when starting jamulus client it connects with correct ports of the running jackd daemon.

So please make this depend on jamulus commendline switches or xml configuraation file or whatever fits the SW architecture best.

![Bildschirmfoto von 2020-04-27 18-33-13](https://user-images.githubusercontent.com/64200197/80403083-466e8280-88bf-11ea-84e8-a121a92c5eaf.png)

**Comment by pljones** [comment]
You know QJackCtl has a "patchbay" where you can save configuration settings for multi-channel interfaces?
![image](https://user-images.githubusercontent.com/1549463/80416891-c3ecbf80-88cc-11ea-8fb2-3261bad2e969.png)

Really useful for saving different configurations depending on how you're using a multi-channel set up.

**Comment by matthison** [comment]
Yes I know this! And in deed this would be a perfect match for the functionality that is requested, if it would be able to load such a template, if it is defined, directly INSTEAD OF the default port conection to port 0/1 when the jamulus client will be started. So I do not know, if the jack API provides means for loading such a configuration that can be programmed in sounds.cpp instead. At least I think some tweaking in sounds.cpp needs to be done so that port 0/1 gets loaded as default only if no template for jack has not been defined.

It would also be cool on top of this, if the 'old' settings of jack (before connecting jamulus) gets reestablished when the jamulus client disconnects (or a different template gets loaded when jamulus disconnects)

At least what should not happen is, that you need to 'disconnect' port 0/1 and load the template MANUALLY after the jamulus client connects (e.g. using qjackctl). On the WIN system, there seem to be a functionality in place that ensures that the selected settings gets reestablisched when you start the jamulus client.

This should also work on Raspian.

**Comment by matthison** [comment]
Maybe I did wrong commenting the issue and closed the issue by mistake. I would still think using 'patchbay' in a change within sounds.cpp would be a good solution. That was my comment so  reopened it again.

**Comment by pljones** [comment]
It sounds like you're asking for JACK functionality, really?  Wouldn't what you're asking for apply whatever JACK clients were involved?

**Comment by matthison** [comment]
No, I'm not saying I use jack under windows, I just say under windows when I start the jamulus client my ASIO setup is loaded already with correct port settings in the drop down list. This feature is missing as in LINUX jack is hardcoded to port 0/1. After the client connects to the running jackd I would have to open qjackctl to disconnect these default settings and apply my port settings, so I always need to run these manual steps. There should be the possibility to connect to the needed ports directly. 

I mark down the hardcoded values of sound.cpp here, these should be supplied with user defined ones OR using a patchbay template, if jack allows to setup connection by a predefined template, I dont know?
..
if ( **jack_connect** ( pJackClient, **ports[0]**, jack_port_name ( input_port_left ) ) )
...
if ( **jack_connect** ( pJackClient, **ports[1]**, jack_port_name ( input_port_right ) ) )
...
if ( **jack_connect** ( pJackClient, jack_port_name ( output_port_left ), **ports[0] )** )
....
if ( **jack_connect** ( pJackClient, jack_port_name ( output_port_right ), **ports[1] )** )

**Comment by corrados** [comment]
We will have a sound card mixer in Jamulus, soon. Then we simply connect all jack inputs/outputs and you will get the same behavior as under Windows.

**Comment by pljones** [comment]
> After the client connects to the running jackd I would have to open qjackctl to disconnect these default settings and apply my port settings

Ah right yes.

You're suggesting, I guess, that by "default" Jamulus would not connect - just expose itself to Jack.  Then you'd be able to patch the client in the Jack patch bay.  Jamulus would detect the patch change and remember it, so when you next started, those are the connections it would make.

That would avoid trying to connect to ports in Jack that were already in use by other applications, too.

**Comment by matthison** [comment]
I think having a sound card mixer in jamulus for LINUX where you can select jack ins/outs will address the issue that I'm facing with. -- my idea was just, if there would be something like 
if ( jack_connect ( pJackClient, **"patchbay_name"** ), unfortunately I found nothing like that in the API. And yes, you would be able to detect used connections and subscribe ti changes. I think this would be something for the soundcard mixer to take care off when a selection has been made by the user.

**Comment by corrados** [comment]
Before I am done with my implementation, you could try to start Jamulus with "-j".
Which is: "disable auto Jack connections (client only)". If you use this command line argument, Jamulus does not make any connection so you do not need to remove the connections.

**Comment by matthison** [comment]
yes, you're  right, I missed this switch, it's working of course. 
So whats your implementation now, complete the soundcard mixer with all flexibilities and  jack connection definitions or start with a simple one like e.g. extended commandline switch like e.g. .... **-j [9,10:21,22]**.... which could connect jamulus inputs to 9,10 and outputs to 21,22 and replaces the default.

**Comment by corrados** [comment]
I just finished a very first version of the new local mixer board (it's on master right now). Now the jack audio interface can be changed so that it queries the number of possible physical input/output channels and creates itself the same number of input/output channels. These channels are all connected to the physical input/output cards automatically on the start of Jamulus. Then you can select your mix in the Jamulus mixer.
This is how it looks like with my 4 input sound card:
![grafik](https://user-images.githubusercontent.com/46655886/80520085-37ec9d80-8989-11ea-8d85-05a0761ced91.png)
In your case you would get 32 faders which you can individually raise or lower and the states of all faders will be stored in the ini file.

**Comment by pljones** [comment]
> it queries the number of possible physical input/output channels

That's a bit of a restriction, really.  JACK lets someone take one audio application and route it to another, bypassing hardware.

I might be running a DAW that I've got a sequencer running in, a standalone software synth and a VST host.  I can plug all of those into JACK and route them.  I might want to route everything through the DAW and then out to Jamulus, with Jamulus returns back to the DAW before hitting the hardware outs.

**Comment by corrados** [comment]
Ok, agreed that it sometimes makes sense to not have the same number of ports in Jamulus as the physical ports. Anyway, I have implemented it now so that you can play with it and see if that is ok for you. Here is the commit: 42cb2698534953388e1f1ab37b2e3b3dc0104b0b
@matthison, can you please compile the latest Git code and tell me if it works for your sound interface?

**Comment by corrados** [comment]
Here is what it looks now for my audio interface with 4 inputs and 2 outputs:
![grafik](https://user-images.githubusercontent.com/46655886/80534241-39c15b80-899f-11ea-9bc3-ce795cb677af.png)

**Comment by corrados** [comment]
@pljones, maybe if you have a special setup, it anyway makes sense to call Jamulus with the -j option because you want to do your connections by yourself and you do not want to have the auto connections of Jamulus anyway, right?

**Comment by matthison** [comment]
I think for those having a mixer for  I/O interface with lets say 4 I/O a mixer (or bit more) inside jamulus is ok and useful to have. In my case and even others using a high count digital bandmixer/interface with 32x32 ports and let jamulus to connect to all is too much. 

One aspect not listed here right npow could be performance, jamulus in this case needs to process 64 I/Os in realtime! :-( So again, it would be great to have means for selecting the ports to be connected between jamulus client and jack server. 

So what think about that? In Jamulus you currently have a dropdownlist for 'IN left/right' and 'out left/right'. In each of them you could select one. If it would be possible to select more than one in a multiselection dropdown widget, and only the selected ones wozuld get connected to Jack and get get a slot in the mixer panel only. This would look smart to me. 

I would limit the mixer slots lets say 4 or soas in your example, this does not overload your screen and eyes and is most convenient for most people. using jamulus alone sitting in front of there computer and just want to mix there guitar/mic*? inside their computer interface and then joining other people. 

What do you think, is this possible or alternately using command line switches to select the (limited) mixer slots?

**Comment by corrados** [comment]
Have you compiled and run the latest code already?

**Comment by matthison** [comment]
Yes, as expected, but I think we need selective selection of channels, as it could become confusing(see attachment). 
Due to this, I really appreciate to add commandline options to select those channels you're interested in. Its easy to use and to understand

**-j** - do not connect jamulus automatically
**-j1,4:5..12,20** connect inputs 1 and 4, connect outputs  5 to 12 and 20 and only add mixer slots for those
 **-j (NOT set)** - connect all and add mixer slots for all
![Bildschirmfoto von 2020-04-29 07-49-45](https://user-images.githubusercontent.com/64200197/80564888-61d8ab00-89ef-11ea-8615-37cc0b906f08.png)
![Bildschirmfoto von 2020-04-29 07-50-10](https://user-images.githubusercontent.com/64200197/80564893-669d5f00-89ef-11ea-9a59-f45c3f551750.png)

**Comment by corrados** [comment]
That looks great, thank you for testing :-).
Now you have to rise the input 9 and input 10 and lower all other faders. This will be stored in Jamulus.

> it could become confusing(see attachment)

For me it is not confusing. You get exactly what you will get on Windows and MacOS if you use the same sound interface. Jamulus will show all inputs and outputs in the Sound Card Mixer dialog.

> -j1,4:5..12,20 connect inputs 1 and 4, connect outputs 5 to 12 and 20 and only add mixer slots for those

If you want to do special setups like this, you should start Jamulus with the"-j" option and make the connections as pljones wrote: "_QJackCtl has a "patchbay" where you can save configuration settings_". I just implemented that jamulus gives you always exactly 2 inputs and 2 outputs if you use the "-j" option.

**Comment by pljones** [comment]
> Jamulus will show all inputs and outputs
Of course, on Windows at least, you get to pick the ASIO driver and that might - like ReaRoute and ASIO4ALL - allow more complexity themselves.

With this new set up, if I picked ReaRoute with 32 I/O connectors (16 stereo channels), would Jamulus default to connecting to _all_ of them?  That would definitely be a problem.  `-j` would then be needed not only for JACK but for ASIO, too.

**Comment by pljones** [comment]
> I just implemented that jamulus gives you always exactly 2 inputs and 2 outputs if you use the "-j" option.

The one thing that might be nice is to change to `-j <in> <out>` (maybe defaulting to 2 each).

**Comment by corrados** [comment]
> With this new set up, if on Windows I picked ReaRoute ASIO driver with 32 I/O connectors

The ASIO interface always picks up all inputs and outputs. This I have not changed. The only thing I have changed that now you can mix all channels and not only pick a channel. So you have more possibilities now.

> The one thing that might be nice is to change to -j <in> <out> (maybe defaulting to 2 each if a bare -j is given).

For what reason do you want this? If you connect the jack ports manually, you can connect whatever input port to any Jamulus port anyway. You can even connect multiple input ports to one Jamulus port. Since Jamulus is just Stereo, two ports are always enough. But maybe I misunderstood your intentions.

**Comment by pljones** [comment]
> The ASIO interface always picks up all inputs and outputs. This I have not changed.

No, it supplied two dropdown boxes currently, to allow choice of inputs / outputs:
![image](https://user-images.githubusercontent.com/1549463/80620390-da665880-8a3d-11ea-808b-c32d9f5dcf66.png)

The difference with the Linux version (up to 3.5.2) is you don't get any such choice.  If I start up with 32 I/O ports:
```
peter@fs-peter:~$ jackd -d dummy -C 32 -P 32 -p 64
```
I get no choice:
![image](https://user-images.githubusercontent.com/1549463/80620725-45179400-8a3e-11ea-9ed4-438d20b8b63f.png)

(I can't get qJackCtl working with the dummy driver over remote X for some reason, so I can't show it being connected.)

So there's a big difference -- Windows, Jamulus already lets you select; Linux it doesn't.

----

> Since Jamulus is just Stereo

Sorry, yes...  Ignore that bit 🤦

**Comment by corrados** [comment]
Yes, I know. Previously it was a combo box, no its faders. If the fader is all the way down, it behaves as it would not be selected in the combo box. I.e. if you just put one fader to the top and the others all the way down, you get exactly the same behaviour as with a combo box.

**Comment by matthison** [comment]
.So I think you're very near to what the soundcard mixer shall be used according to this thread, as I see it working now with some quick hacks in sounds.cpp (see below, its quick hack, sorry)
- for some multichannel interfaces provide a mixer that you can mix your guitar/Mic because your computer I/O has no mixer
- provide a in/out map from jamulus so it connects to a running instance and for high I/O count select only some of them

What I just add to the code is to limit the number of ports to what you want to have and add an index list for input and outputs that you use for the connection. **So the only task starting with the code you already HAVE is to get this information into sounds.cpp**, you could use commandline switches, or I saw an *.ini file, whatever best fits for SW architecture. At least it does what it shall (see attachment)

sounds.cpp (pseudo code)
.....
/*
 need to add code here to extract following information, number of chan and mapping
*/
iNumInChan = 5;
iNumOutChan = 3;
int inPortList[iNumInChan] = {1,5,7,20,8};
int outPortList[iNumInChan] = {12,3,5};
....
 //now create input/output ports of this application
...
        //connect the ports, note: you cannot do this before
        //the client is activated, because we cannot allow
        //connections to be made to clients that are not
        // unning
.....
        // try to connect physical input ports
        if ( inPorts != NULL )
        {
            for ( int i = 0; i < iNumInChan; i++ )
            {
                jack_connect ( pJackClient, inPorts[**inPortList**[i]], jack_port_name ( input_port[i] ) );
            }
        }
       // try to connect physical output ports
        if ( outPorts != NULL )
        {
            for ( int i = 0; i < iNumOutChan; i++ )
            {
                jack_connect ( pJackClient, jack_port_name ( output_port[i] ), outPorts[o**utPortList**[i]] );
            }
        }
 




![Bildschirmfoto von 2020-04-29 20-27-51](https://user-images.githubusercontent.com/64200197/80635317-0395e180-8a5c-11ea-80e9-fd754d636c12.png)
![Bildschirmfoto von 2020-04-29 20-27-46](https://user-images.githubusercontent.com/64200197/80635328-05f83b80-8a5c-11ea-88a7-30571cfd39e6.png)

**Comment by matthison** [comment]
Having thought about lots of the preconfigured patching, I think we might need to keep in mind whats intuitive for the layout of the mixer,
 In almost all analogue mixer you have an input fader and a panning to the L/R channel in our case to the jamulus server inputs, you usually do not have a bank of faders for left and right. 
In the output path you have a fader for the outputs, if its the MAIN fader or SUBGROUP or MONITOR and just selecting which internal input to use. So having 2 banks of output faders is too much, you'll never use. Instead you'll select if you want to have one fader for the level and switches for MONO signal or just one of the L/R signal in our case the jamulus server outputs. Selecting L/R buttons together is just MONO.

I have tweaked the layout with graphics tool to show what I mean,Note: if your server ist a Mono signal, then you just grey-out the panner on the input mixer and the switches on the output mixer.

![input mix](https://user-images.githubusercontent.com/64200197/80675730-86975600-8ab5-11ea-978a-789b79bce23f.jpg)

![output  mix](https://user-images.githubusercontent.com/64200197/80675739-8b5c0a00-8ab5-11ea-8a66-37c5d8f2c6d7.jpg)

**Comment by pljones** [comment]
> Yes, I know. Previously it was a combo box, no its faders. If the fader is all the way down, it behaves as it would not be selected in the combo box. I.e. if you just put one fader to the top and the others all the way down, you get exactly the same behaviour as with a combo box.

With the entry not selected in the drop down, other software could use the I/O ports.  Are you saying that if the fader is at the bottom, Jamulus closes that I/O port, allowing other software to use it?  That's not intuitive behaviour at all, really.  I don't mentally connect "drop the volume" with "disconnect the cable".

**Comment by corrados** [comment]
Ok, since I reverted my Sound Card Mixer, you still have your initial problem.
I am not a fan of your proposal of, e.g., "-j1,4:5..12,20". As I wrote you could use QJackCtr for that. 

But I have another solution for you. How do you start Jamulus? Do you double click on an icon to start it or do you use a startup script. If you use a startup script, you can do what I do if I use Jamulus together with some guitar software:
https://github.com/corrados/jamulus/wiki/Tips,-Tricks-&-More#jamulus-client-linux-start-script
This script does the connections for you. It is very convenient to use.
In that script, as you can see, I also change the audio levels of my alsamixer. So I simply double click on a shortcut on my Linux desktop which calls then the script and all software will be started automatically and all mixer settings and jack connections are done automatically. How do you like this?

**Comment by matthison** [comment]
Thx! I seem to miss this information and I expect that it would do the job for me :-) Didn't check and adapt right now due to time.. Yes I agree, command line options are very 'compact' and your solution having is more visible what really happens. Guess others might want this feature and a soundcard mixer, so I would appreciate if you continue work on this, I support wherever I can.

Let me do comment on this

- For setting up connections like you did in your script, you have to distinguish between those that jamulus 'need' to have and those which are specific to your system (LINUX, Windows). All Jamulus connections and in/out port connections should be initiated by jamulus itself acc. to its configuration, so the approachh would be reusable between different platforms
-  i dont know currently, where jamulus saves settings between sessions (?), for a soundcardmixer, you may want and need to restore setting.
- For the soundcard mixer I provided a mockup screenshot in this thread before. It was inspired by the functionality every analog console has (and mixer template by some soundcard drivers) So it should be intuitive and is very limited to the functionality that really is needed inside jamulus I guess. I would like to know, what you think about this?
- I added a configuration file example for soundcard mixer acc. to my example before (windows INI format) that can act as template for saving and restoring setup of a card mixer. So there is really not so much to configure, at least for musicians, there should be a way to enter this via a user interface in a soundcard mixer enabled jamulus release.
[jamulus.txt](https://github.com/corrados/jamulus/files/4567744/jamulus.txt)

**Comment by matthison** [comment]
I close this issue, as answers made here, especially the reference of using a script for setup, helps solve my initial request of configuration. However, number of discussions have been made, that go in the direction of, having a soundcard mixer is more flexible to handle this. 
I summarized this in https://github.com/corrados/jamulus/issues/177
