### ISSUE TITLE
Manual : hardware precisions

### ISSUE THREAD

**Issue by pcar75** [corrados/jamulus#152]
Add hardware setup information for novices in Jamukus  Home > Using Jamulus >  Hardware
(https://github.com/corrados/jamulus/wiki/Hardware-Setup)

"For users contributing 2 or more sources (e.g. voice + synth + guitar), it is important to note that the Jamulus client app can only input 2 channels (L/R).  So the hardware being used must contribute a mixed-down signal (e.g. stereo output) to Jamulus input.  
	- Audio interfaces generally output a mixed signal on their analog output, but separate signals (1 per source) on their digital output (USB/Firewire/Thunderbolt)
	- Mixers generally only output mixed-down signals on their analog output.
	- Mixers with USB/Firewire/Thunderbolt generally output mixed-down signal on their analog output AND separate signals only (no mixed-down signal) on their digital output.
	- A few Mixers with USB/Firewire/Thunderbolt will either send only a mixed down signal to the digital output (small/budget mixers) or also ADD a stereo mix-down signal to the separate signals on the digital output."

Unless I am seriously mistaken (and would welcome being corrected), 
thanks from the novices !

**Comment by corrados** [comment]
I am currently working on a sound card mixer feature in Jamulus, see:
https://github.com/corrados/jamulus/issues/97#issuecomment-620044220
I think this will solve the issue with "voice + synth + guitar" and multi channel sound cards. Do you agree?

**Comment by pcar75** [comment]
Bonjour,

From your comment, I agree but would’nt this cause more processing at the Jamulus client , therefore more delay ?

Merci
@+


De : corrados<mailto:notifications@github.com>
Envoyé le :27 avril 2020 15:06
À : corrados/jamulus<mailto:jamulus@noreply.github.com>
Cc : pcar75<mailto:pcarrier_junk@outlook.com>; Author<mailto:author@noreply.github.com>
Objet :Re: [corrados/jamulus] Manual : hardware precisions (#152)


I am currently working on a sound card mixer feature in Jamulus, see:
#97 (comment)<https://github.com/corrados/jamulus/issues/97#issuecomment-620044220>
I think this will solve the issue with "voice + synth + guitar" and multi channel sound cards. Do you agree?

**Comment by gilgongo** [comment]
Thanks @pcar75 - I'll add that information to the hardware page, and put a note in about the forthcoming mixer feature for the first point.

**Comment by corrados** [comment]
Please wait for the mixer to be mentioned. I will revert the changes for now. Too many issues with it (see other Issues comments).

**Comment by corrados** [comment]
@gilgongo Have you add the information about the initial post already? If yes, I think we can close this Issue then.

**Comment by gilgongo** [comment]
Yes, added so you can close.

**Comment by corrados** [comment]
Ok, thanks.

**Comment by pcar75** [comment]
Merci :-)
