### ISSUE TITLE
Clients problem with A+P IPv4

### ISSUE THREAD

**Issue by bugith** [corrados/jamulus#153]
[Post @sourceforge]((https://sourceforge.net/p/llcon/discussion/533517/thread/62f7a65264/#4b07/edf5/259c))
As long as the server does not send multicast, maybe he could go on listening on 22124 as usual, but when it comes to sending back the mix to the clients, could we imagine they negotiate their own listening port ?

**Comment by corrados** [comment]
I do not understand this request. The client connects the server, e.g., on the default port 22124. The packets from the server to the client go to the port number on which the client has bound the socket. This could be any port (you can specify this with the -p command line option in the client).

> but when it comes to sending back the mix to the clients, could we imagine they negotiate their own listening port ?

What do you mean by "mix"?

**Comment by bugith** [comment]
Mix: all clients sound mixed together by the server and sent to each client
Its was about your post reply:
https://sourceforge.net/p/llcon/discussion/533517/thread/62f7a65264/#4b07/edf5/259c
to this one:
https://sourceforge.net/p/llcon/discussion/533517/thread/62f7a65264/#4b07/edf5

Rereading the thread, I think there may have a misunderstanding: I'm not sure any more where A+P is a problem: for the client trying to join a public server? For the server operator not having its own 22124 port... or the central server itself. He told about a client problem and refered the tip related to servers in the wiki saying this tip helped him to workaround its client issue when HE (client) got a full port range. Puzzled.

**Comment by corrados** [comment]
Ok, if this Issue is about the problem with the empty server list, then there is another Issue specifically for this problem: https://github.com/corrados/jamulus/issues/156

Maybe we concentrate on that other Issue and close this one. What do you think?

**Comment by bugith** [comment]
Not an issue for me so...
