### ISSUE TITLE
Core dump with Linux client 3.5.3git

### ISSUE THREAD

**Issue by elliotclee** [corrados/jamulus#154]
To reproduce: run Jamulus client, connect to any server, input meters might show random noise coming in. Click "Disconnect" and then close the client window. Client will either core dump when Disconnect is clicked, or when client exits.

git commit bef58357ef1f8c1138af32a7850d35405f79cfa7 doesn't have the bug. git commit 3427f507adf70feddd448ceec34bb0fddd1b4017 is the first one after that where I could get it to compile and reproduce the bug with.

Let me know if you have any problems reproducing.

**Comment by corrados** [comment]
Is the crash only happening on closing the client window or does it also occur by simply pressing the disconnect button (you write that in your text but I want to double-check that I have correctly understood it). So you connect to a server, then you press the disconnect button and it crashes immediately, right?

**Comment by elliotclee** [comment]
Can't reproduce it now with recompiling the latest tree, sorry to waste your time. If it happens again I'll try to get a stack trace etc. It was initially happening when I pressed Disconnect. Then I rebuilt with -g in CFLAGS and it started happening at exit, with a message saying a double free was happening.
