### ISSUE TITLE
The new channel mixer approach is not very ergonomic when you have a lot of inputs and outputs

### ISSUE THREAD

**Issue by rhrhunter** [corrados/jamulus#158]
This is what it looks like when you have lots of inputs & outputs (UAD audio interfaces):

![image](https://user-images.githubusercontent.com/4723899/80652674-69776e80-8a46-11ea-9910-3f319f47ff7d.png)

I feel that being able to select the input and output L/R channels via the drop down method in version r3_5_2 was a much more intuitive way to configure the mixer. It allows users with more complicated rigs to control the summing from any existing SW mixers that they may already have for their audio interfaces.

Perhaps the use of the channel mixer can be made optional so that users that don't already have SW Mixers in place can benefit, and those that just need to assign L/R channels can continue to do so the old way.

Thanks for building this awesome SW!

**Comment by corrados** [comment]
Understood. I put the master to a previous commit now and leave the sound card mixer implementation on a separate branch. A lot of work has to be done on that branch until this feature is ready for a release...

**Comment by corrados** [comment]
Since I put the code on a branch again and I will do a lot of changes on the branch, I will close this Issue since the code on the master contains the old drop downs again.
