### ISSUE TITLE
Jack client name

### ISSUE THREAD

**Issue by newlaurent62** [corrados/jamulus#159]
In case, we want to use more than one Jamulus client, provide a command line option to set the Jamulus jack client name (as well as Jamulus window name). If two or more musicians are connected to Jamulus server from a single host. 

I know that its possible to start more than one instance of Jamulus but then we have to sort out the Jamulus window name and jack client name.

**Comment by gilgongo** [comment]
_Note to self: If this gets implemented, we need to update the docs which currently say not to run more than one client on the same machine._

**Comment by newlaurent62** [comment]
I did a patch on the dev branch:
it add an command line argument : --clientname (no short one)
Example: Jamulus --clientname "Jamulus Paula"
- it sets the clientdlg window title to "Jamulus Paula"
- it sets the jack client name to "Jamulus Paula"
[clientname.patch.zip](https://github.com/corrados/jamulus/files/4559385/clientname.patch.zip)

**Comment by newlaurent62** [comment]
I compiled and tested only the linux version though i modified windows, mac, android and linux files : sound.cpp sound.h.

**Comment by corrados** [comment]
Can you please clone the repo and create a pull request?

**Comment by newlaurent62** [comment]
https://github.com/corrados/jamulus/pull/162

**Comment by corrados** [comment]
Its merged.

>  this gets implemented, we need to update the docs which currently say not to run more than one client on the same machine.

In principle it is possible but still not officially supported.
