### ISSUE TITLE
Listen only mode

### ISSUE THREAD

**Issue by fergbrain** [corrados/jamulus#160]
My understanding is that even when someone has selected "Listen" as their instrument their connection still impacts the real-time quality of the session. Is there a way to have a true listen-only mode that just receives the UDP packets but does not transmit any -- and thus does not impact performance if they are far away?

**Comment by corrados** [comment]
That is not what Jamulus is meant to be. The correct way of doing this is to setup one single Jamulus client which connects to that server and streams its audio to a audio distribution network.

**Comment by fergbrain** [comment]
The intent would be for soliciting feedback from tutors/mentors/listeners who may not be as geographically close. This would be especially helpful because social distancing doesn't always allow in-person sessions.

Understand this may not have been the original intent, but from my understanding of the architecture it seems like this is feasible (understand it would still require time/effort).

**Comment by corrados** [comment]
It is actually not desired. To get the lowest possible latency for the musicians, the server load should be as low as possible. As I mentioned, Jamulus is not meant to be an audio distribution service. There are other services out for that purpose. E.g. you could even use Youtube for that purpose.

**Comment by fergbrain** [comment]
Yes, for one-on-one there are many other better solutions. I'm talking specifically about instances where there are two or more performers (e.g. choir, quartets, small bands, etc) who are seeking input/feedback from a tutor/mentor/director/etc

The server load should be *not* be higher since it just has to send UDP packets to the listener and does not need to receive UDP, mix, or account for jitter.

**Comment by elliotclee** [comment]
@fergbrain The closest to a listen-only mode is to use the "Mute Myself" button. For true one-way audio streaming, there are lots of other protocols that work just fine, and it doesn't seem necessary to add the extra complexity to Jamulus when you can just hook it in yourself...

**Comment by fergbrain** [comment]
It's not just streaming. The listen-only user should be able to mix streams as well...which is not something that any streaming service or protocol provides as far as I'm aware of.

**Comment by corrados** [comment]
You mean all users which just listen to the session should make their own mix? I do not think that is wanted.

Please check out this: https://www.facebook.com/events/221058272530337
They make a session where a lot of musicians are connected via Jamulus and they stream the session to Facebook so that a larger audience can hear the music. One of them is the "mixer" who adjusts the faders so that the overall sound ont he Facebook stream is nice.

This is the correct way of doing a "Listen only mode".

**Comment by corrados** [comment]
Let's get back to the original post of this Issue: "_Is there a way to have a true listen-only mode that just receives the UDP packets but does not transmit any -- and thus does not impact performance if they are far away?_". You then wrote: "_The intent would be for soliciting feedback from tutors/mentors/listeners who may not be as geographically close_".

I think we have to differentiate between tutor and listener. A tutor needs a return audio channel to give feedback on the performance. So for the tutor the normal Jamulus operation is just fine.

It has shown that good Jamulus servers can handle 30 clients easily. So if you have, e.g., a quartet playing and two tutors listening, you still have 24 slots for listeners without impacting the performance. If you want to support more listeners, than you must use other tools like YouTube or Facebook streaming.

So I think we need no modification in the Jamulus software so support your use case. Do you agree? If yes, I think we can close this Issue.

**Comment by WolfganP** [comment]
Listener only mode may be a good use case for those using one instance to feed a live video streaming, without adding another input and mix to the server.

**Comment by fergbrain** [comment]
> It has shown that good Jamulus servers can handle 30 clients easily. So if you have, e.g., a quartet playing and two tutors listening, you still have 24 slots for listeners without impacting the performance.

My original concern was not around concurrent connections but high latency (because of poor internet connection, distance, etc).

My understanding is that if there is even one user with high latency it impacts the experience of all users because Jamulus is trying to synchronize everyone?

**Comment by corrados** [comment]
> My understanding is that if there is even one user with high latency it impacts the experience of all users because Jamulus is trying to synchronize everyone?

No, that is not the case. The listener could have a 1 second delay and that would not impact the ongoing jam session at all. This is because Jamulus is client/server based. No synchronization needed.

**Comment by fergbrain** [comment]
If that's the case then I'm okay with closing this ticket.

**Comment by corrados** [comment]
Ok, thanks.
