### ISSUE TITLE
Client spams server system when server is not running

### ISSUE THREAD

**Issue by elliotclee** [corrados/jamulus#161]
To reproduce, EITHER:

    Run a Jamulus server.
    Have a client connect to that server.
    Exit the server.

OR:
    Have a client try to connect to the server system without Jamulus server running.

tcpdump on the server will show that the client keeps on sending packets rapidly to port 22124 until the client is closed. I have waited a minute or two and it does not seem like CON_TIME_OUT_SEC_MAX in channel.h actually does anything - there is no timeout.

I have some guy in Michigan who has left his client running for days and it keeps trying to connect to my server even when it's in private mode. I have firewalled his IP off, but it would be nice to have the client be a little more gracious about how connection attempts are handled.

The two suggestions I would make for the client are:
1. Implement or fix timeout on connection attempts.
2. Pay attention to ICMP port unreachable and other ICMP messages that might indicate that the server is not reachable or no longer reachable.

**Comment by corrados** [comment]
Exactly for this case, there is an undocumented feature in the server. Simply start your server with "--disconnectall". Then all clients are disconnected.

**Comment by corrados** [comment]
Have you tried it out? Did the --disconnectall worked for you?

**Comment by elliotclee** [comment]
Yes it did, thanks. I think the protocol suggestions still stand - at very
least there should be a timeout in the client when trying to (re) connect.

Elliot

**Comment by dszgit** [comment]
> Exactly for this case, there is an undocumented feature in the server. Simply start your server with "--disconnectall". Then all clients are disconnected

Maybe this should be another thing for the server to do on graceful exit, with SIGQUiT or SIGTERM, along with #130 and #168.

**Comment by corrados** [comment]
Actually not. Sometimes it is required to, e.g., restart the Central Server virtual PC and if musicians are connect to this server, they simply have some seconds no audio but then they can continue there session. If the server would send a disconnect meassage to all clients, they all would have to rejoin the server.

**Comment by dszgit** [comment]
> Actually not. Sometimes it is required to, e.g., restart the Central Server virtual PC. If musicians are connect to this server, they simply have some seconds no audio but then they can continue there session. If the server would send a disconnect meassage to all clients, they all would have to rejoin the server.

OK, I guess that's a design choice.  So it's your call.

**Comment by corrados** [comment]
If I would introduce a command line argument like "--disconnectonquit", would this be a good solution for you? I.e. if you use that command line argument, all clients are disconnected on shutdown of the server.

**Comment by elliotclee** [comment]
Thanks for asking... My opinion is that clients should be designed to eventually timeout if they can't connect, even if that timeout is relatively long to allow for server reboots etc. However, -d will solve the immediate problem when it happens again, so thanks for doing that.
