### ISSUE TITLE
Compiling for Windows+NSIS Installer

### ISSUE THREAD

**Issue by mmomasters** [corrados/jamulus#163]
I'm trying to compile using deploy_windows.bat but I'm getting errors. I use Visual Studio Community 2019 + QTR Creator 5.9.9, any help would be greatly appreciated! What version do you compile with please?

**Comment by corrados** [comment]
Do you just want to compile or do you want to create an installer?

**Comment by mmomasters** [comment]
Hi I managed to compile it with QT 5.2.18 for Windows and make installer as well.

**Comment by mmomasters** [comment]
But I get a registration failed when specifying my own central server...

**Comment by corrados** [comment]
Great. Then I will close this issue.
