### ISSUE TITLE
Headless server not having right information

### ISSUE THREAD

**Issue by brandflake11** [corrados/jamulus#167]
Hello,
I am currently trying to run a headless server on Ubuntu 18.04 LTS and using a compiled version of the latest Jamulus release. I am trying to run this remote server with the following command:

`$ ~/Downloads/Jamulus3.4.4/Jamulus -s -n -R ~/recording -e jamulus.fischvolk.de:22224 -o ICAT;blacksburg;225;`

When I run the command, the server shows up on the central list and I can connect to it, but it only shows up with its name as the ip address and as in USA for location. Is there something wrong with my syntax for the -o option?

Thank you very much for your help on this matter!

**Comment by Snayler** [comment]
I believe you need to put the server information in quotes, like
`$ ~/Downloads/Jamulus3.4.4/Jamulus -s -n -R ~/recording -e jamulus.fischvolk.de:22224 -o "ICAT;blacksburg;225"`

**Comment by brandflake11** [comment]
Thank you so much, it worked! Who knew that all you needed was quotes?
