### ISSUE TITLE
let specify the bit depth of recordings

### ISSUE THREAD

**Issue by newlaurent62** [corrados/jamulus#171]
I see that the bit depth of the wav is 16 bits.

I would prefer sometime 24 bits or 32 bits. But as it takes more disk space, an option could be added (for example: --recording-bitdepth 16|24|32.

**Comment by corrados** [comment]
You will not get any benefit from storing data as 24 or 32 bit. Internally, Jamulus uses 16 bit anyway.

**Comment by newlaurent62** [comment]
Well i don't know if this is worth, but for those using a good network connection, 24 or 32 bits depth could be of sound benefit ?

**Comment by corrados** [comment]
No, the sound quality is defined by the OPUS codec. 16 bit are more than enough bits for the dynamic the compression supports. So there will be no benefit.

**Comment by newlaurent62** [comment]
ok

**Comment by corrados** [comment]
Since a higher bit depth does not gain better audio quality, I would like to close this Issue. Do you agree?

**Comment by newlaurent62** [comment]
Yes I agree.
