### ISSUE TITLE
Server operation: Warning if Central Server is chosen which is not compatible to location

### ISSUE THREAD

**Issue by corrados** [corrados/jamulus#172]
Maybe it is a good idea to show a warning if the Central server selected but the users location is different (e.g. US) -> Show a warning in the GUI and on the command line (for headless Jamulus servers).

**Comment by gilgongo** [comment]
Something like, "You are attempting to register this server in a different continent to you own. Your server may be shown with long ping times by most clients" ?

**Comment by pljones** [comment]
Guess this can be closed.

**Comment by corrados** [comment]
Ah, yes, I agree. Done.
