### ISSUE TITLE
private server

### ISSUE THREAD

**Issue by pjoc56** [corrados/jamulus#173]
Hi looking to set up private server on iMac.  I am unsure should I be putting IP and port forwarding info in the 'Central Server Address' under the 'Manual' option?  And then do I untick the 'Make My Server Public' option.  If I leave this option ticked it says registration failed.  If I untick it it says unregistered.  So not sure what is actually happening with these actions.  Also, I am unsure about what IP address I should be using, do I use the BT Hub router IP address or the iMac IP address followed by colon and the port forwarding number 22124?  

When I open up the client app I am not sure if I am supposed to put the same information in the 'Central Server Address' as in the server app, i.e. 'Manual' and then the IP followed by port forwarding?  

Finally, so far no external clients have been able to connect with me.  So I thought maybe something to do with firewall, as their apps say things like 'trying to connect'.  They I discovered I have 3 firewalls, (1) on BT Hub (2) on McAfee virus protect and (3) in Apple preferences.  Not really sure which of these or if all of these are the problem.   Tried turning them off one at a time and it did not change anything.  

I can connect locally using 127.0.0.1 which tags on :22134 rather than 22124.  

Hopefully I will be able to get this sorted.  Many thanks for help....

**Comment by Snayler** [comment]
Forget Central Server Address, it is only used for public servers. You can leave those empty.

On the **server side**, you need to leave the _Make My Server Public_ option disabled. Then you need to log into your router and enable port forwading with UDP protocol using port 22124 (or any other port of your choosing as long as it isn't used for anything else) into your iMac IP Address. This is so your router knows where the data coming into the port you defined should go into (your iMac).

On the **client side**, you should click the connect button (or _View_ > _Connection Setup..._) and input the server IP address into the _Server Name/Address_ field along with the port you defined on the server, in the format of `<IP Address>:<Port>`.

Now, what IP Address you'll be using to connect depends on where you are. If you're on the same network as the server (both server and client connected to the same router), you should use your iMac IP Address (you can use 127.0.0.1 if client and server are running on the same machine). If you're trying to access the server from outside your network, you should use your router IP Address (aka Public IP Address).

The ports listed on the server table are related to the client port being used to relay the information back to the client, those have nothing to do with the server port and you don't need to port forward those.

As far a firewalls go, you either need to correctly configure them or disable them (which is a security risk). But before disabling any firewall, I would start by correctly setting up the port forwarding on the router.

**Comment by gilgongo** [comment]
Hi @pjoc56 I don't know if you've already seen the [documentation on setting up a server](https://github.com/corrados/jamulus/wiki/Running-a-Server), but if you have it would great to get some feedback from you on what might be confusing as we're always looking to improve it.

**Comment by pjoc56** [comment]
Hi many thanks just to recap

OK so start server untick ‘Make my server public’



I have set up port forwarding with UDP in my BT Hub router for my iMac IP address. 

For me the client app and server app are on the same network, i.e. computer and internal home network.  I can connect the cliental  either using 127.0.0.1 or using the Mac IP + port forwarding.  So use 127.0.0.1.  So locally, things are working OK.

Just to clarify, for external access for other people, when my Jamulus server is up and running, should I ask them to put my router IP plus port forwarding info or just router IP?  

On the client app when I put in my router IP, either with or without port forwarding, I only get ’Trying to connect’. But then again I am not sure this is a valid thing to do anyway.  So I presume this is not a way to check if it is working externally?    

Many thanks  I am sure I will get it going.  

Regards

Pierce

**Comment by corrados** [comment]
> Just to clarify, for external access for other people, when my Jamulus server is up and running, should I ask them to put my router IP plus port forwarding info or just router IP?

If you use the standard port than the IP is fine. Otherwise use [IP of router]:[custom port number] to connect to the server from the outside.

> On the client app when I put in my router IP, either with or without port forwarding, I only get ’Trying to connect’. 

I guess this depends on the router. On my local network it works. But as you suggest, it is better to let one try it out which actually connects from the outside.

If you solved all your issues, please close this Issue.

**Comment by pjoc56** [comment]
Hi

So got some people to try and connect and always get the same message: trying to connect.  So as previously mentioned there are 3 firewall apps on my PC, BT Hub, McAfee virus, and Apple.  If I turn of McAfee it seemed to let me use the router IP which it had not before.   I have not tested this yet with external people but this seems to suggest that McAfee firewall is problem.  Just checking with you if this has been found to be the case.  I cannot see any settings in McAfee to allow firewall to be on but exclude block to Jamulus.  I do not know enough about firewalls to know if my BT hub and Apple firewalls are sufficient to protect computer and therefore McAfee firewall is redundant.  

Will try again but just thought I would check with you if this has been a noted problem in the past.

Again appreciate time with this matter.

Pierce

**Comment by Snayler** [comment]
Yes, having two active firewalls in the same computer is prone to give you problems. One firewall is enough.

**Comment by gilgongo** [comment]
@pjoc56 Turn off any and all firewalls. In doing its job of connecting you to the Internet, your BT hub will be blocking unsolicited requests or data packets from the Internet anyway. Additional firewalls are largely a waste of time, and to troubleshoot this issue you should turn them off.

Connect to your own server using the address `127.0. 0.1`.

Give your friends the [public address you see here](https://www.google.com/search?q=whatsmyip).

If they cannot connect, [read this for a possible solution](https://github.com/corrados/jamulus/wiki/Server-Troubleshooting#nobody-can-connect-to-my-server---but-im-port-forwarding-and-can-connect-locally).

**Comment by pjoc56** [comment]
After trial and error found that McAfee firewall is the problem.  Turned this off connection working fine now.  

Thanks for all the encouragement and support.  Nice when someone responds and takes an interest in the problems we have.
