### ISSUE TITLE
Possibility to change channel/user position ordering

### ISSUE THREAD

**Issue by sthenos** [corrados/jamulus#178]
For a number of different events now happening (Choirs, world jams, public gigs on jamulus), the ordering of channels for users is quite important.   At the moment, I understand the ordering of channels/users is based on the time when a user arrives in a new room, with the server completely resetting its "memory" of user positions when the last person leaves the server.   

I'm wondering how much effort would it be so that channels/users are sorted based on the alphanumeric name of the user.   With a --channelsortalpha argument or something similar passed to the server which enables this feature?  

This way we can ask our friends/choir members to add a numeric value in front of their name to control the order they appear in the mixerboard,

**Comment by corrados** [comment]
> I'm wondering how much effort would it be so that channels/users are sorted based on the alphanumeric name of the user.

It is not trivial. The server assigns an ID to the connected client and all properties (like name, instrument, gain, etc.) are bound to that ID. Of course you could introduce an ID translation in the client which maps the sorted IDs to the IDs to the server but this will require a significant amount of new code. So I would estimate that if you do it correctly, it will require at least two working days to support this.

**Comment by sthenos** [comment]
ok fair enough, thanks for clarifying on the amount of time required.    It's certainly not an urgent thing, but more of a nice to have.   Maybe park this one for a while?

**Comment by corrados** [comment]
I think I found a fairly simple solution to make it possible to re-order the faders. I am currently looking at it.

**Comment by corrados** [comment]
Ok, it is implemented now. We have a new menu item (sorry for German language):
![grafik](https://user-images.githubusercontent.com/46655886/84050849-92c4dc00-a9ae-11ea-92b3-e6d23fdb6b97.png)

Before sorting:
![grafik](https://user-images.githubusercontent.com/46655886/84050744-70cb5980-a9ae-11ea-980e-a9b4c2a64891.png)
After sorting:
![grafik](https://user-images.githubusercontent.com/46655886/84050777-7b85ee80-a9ae-11ea-8657-ccc6d12242c2.png)

Please note that you can use the keyboard shortcut Ctrl+n which simplifies the usage.

**Comment by sthenos** [comment]
Ok thanks Volker.  Works well so far, will do some more testing with larger groups.

One point, thing the english menuitem name should say "Sort channel users by name".   Also it's unclear if it's a checkbox and maintiains the state for all channels or if new people join you need to hit the menu item again to resort people?

**Comment by corrados** [comment]
> should say "Sort channel users by name"

Thanks, I will change this.

> Also it's unclear if it's a checkbox and maintains the state for all channels or if new people join you need to hit the menu item again to resort people?

It's no checkbox. You have to do it again if new people join. But since you have the keyboard shortcut, you can quickly apply it again.

**Comment by WolfganP** [comment]
@corrados great feature. Is there any way that you can post windows nighties / betas to quickly test these changes before it go into a release?

**Comment by corrados** [comment]
No plan to do so. Maybe someone else volunteers to compile and provide Windows binaries.

**Comment by WolfganP** [comment]
> No plan to do so. Maybe someone else volunteers to compile and provide Windows binaries.

Thanks @corrados  
Not wanting to get anything regularly or official beta program, just when you (or someone else) builds the Windows client, drops the .exe here or in any cloud drive for quick testing of the folks wanting the new features.

**Comment by corrados** [comment]
Ok, let's see if this works for you:
[Jamulus.zip](https://github.com/corrados/jamulus/files/4753196/Jamulus.zip)

**Comment by WolfganP** [comment]
> Ok, let's see if this works for you:

It does, thanks a lot @corrados ! I'll test the new features and report back if any issues found.

**Comment by corrados** [comment]
@sthenos "_Ok thanks Volker. Works well so far, will do some more testing with larger groups._" Have you tried out to new functionality yesterday on the World Jam? Did it work for you as expected?
