### ISSUE TITLE
Sound quality issues after someone disconnects from server

### ISSUE THREAD

**Issue by Skeezixes** [corrados/jamulus#182]
Two clients were (successfully) connected to the server running on my Mac laptop, myself and one other; the sound quality was generally acceptable. We had been playing for about an hour. After some time, an unknown person ("Steve") connected. After a time, "Steve" disconnected, and although the other client did not experience this, my sound quality was suddenly atrocious! Crackles, "feedback-like screeches", distortions. I could hear to play, but barely.

**Comment by corrados** [comment]
I have not observed such an issue with the Jamulus server running on Linux. Maybe this is an issue which only shows up on Mac. I suspect the timer on Mac had a problem: https://github.com/corrados/jamulus/blob/master/src/server.cpp#L200

Did you observe this issue just once or does it occur regularly?

**Comment by Skeezixes** [comment]
I think I observed it only once, but I have observed something similar that
I don't understand yet. I can't specify when it happens and when it
doesn't, in other words. I thought it was related to messing with the Mute
buttons and the Settings screen being open for a relatively long period of
time, but not really. Maybe it's related to this timer you speak of. What
does the timer do?

**Comment by corrados** [comment]
> What does the timer do?

This is basically the heart beat of the server. This calls the processing routing at a precise timing. If that has a high jitter, you will get a lot of strange things going on.

**Comment by Skeezixes** [comment]
I will continue trying to figure out what's going on when the sound quality
unexpectedly goes to wreck.

**Comment by sthenos** [comment]
i've had similar issues like this where the sound for everyone suddenly goes very jittery and it happens on the servers that are running on low hardware spec.   I have a google cloud platform server with 4 x cpu's and 2gig ram and it rarely happens.  I would say it happens more when there are lots of channels connected.  I'm not sure if this is the same thing and I can't say if it's a problem in the server code or a problem with the hardware itself.

**Comment by corrados** [comment]
Is the "google cloud platform server" a Linux system? If yes, then it seems that this issue is not only present on a Mac OS.

**Comment by corrados** [comment]
Any updates on this issue?

**Comment by dubnemo** [comment]
We have seen this even on beefy Ubuntu servers.  Is the connection/disconnection request synchronous or asynchronous? If its not async to queue the request, and have a callback to the client with the connection handle (request only).

**Comment by corrados** [comment]
The actual disconnect request is a simple asynchronous UPD packet. That should be harmless.

**Comment by corrados** [comment]
One more question regarding this issue: If the issue happens, do you have to re-start the Jamulus server or does it cures itself after a while? I.e. if all clients have left the server and re-connect to the server, is the sound then fine again?

**Comment by dubnemo** [comment]
Restart had not been required, perhaps since threads are freed up.
It seems to happen on connection as well, especially after 4th or 5th user.  hence why I asked about async.  
We are testing again tonight.  will report any issues.

**Comment by Skeezixes** [comment]
I think it was, but the problem hasn’t happened since.

**Comment by corrados** [comment]
This Issue is quite old. In the meantime we had a lot of new Jamulus releases with a load of fixes and new features. Does anybody who contributed to this discussion still have such problems with the most recent version of the Jamulus software?

**Comment by dubnemo** [comment]
We have the latest that can be tested tonight.  I will ask if the server is a guest on VMware or AWS, vs. bare metal.

**Comment by dubnemo** [comment]
We connected to a 3.6 server, and while the five jammers did not notice a sound quality degradation on connect, they '**heard**' me come on midstream to their jam, which a jammer welcomed me.  Is that a feature?  

We did not notice degradation on jammer disconnect.

**Comment by corrados** [comment]
> they 'heard' me come on midstream to their jam,

What do you mean by this? What is a "midstream" in this context?

**Comment by dubnemo** [comment]
Midstream ::= 'while they were already jamming'
This ::= 'an audible noise'

Restating, I joined a session with active users on.  These users where already playing their instruments, and the audible noise was noticed by the users, and one of the users almost immediately said 'Hi Scott' while other users continued to jam. After everyone stopped,  I explicitly asked how the user noticed me to prompt him to say Hi Scott, and he stated he heard a sound, looked at the computer monitor, and then acknowledged my presence.

Hope that helps.

**Comment by corrados** [comment]
Thanks for the clarification.

> he stated he heard a sound, looked at the computer monitor, and then acknowledged my presence. [...] Is that a feature?

No, not that I am aware of.

**Comment by corrados** [comment]
The original title of this Issue is "Sound quality issues after someone disconnects from server". The question is, does this issue occurs for anyone for the latest Jamulus client/server version? If not, I would like to close this Issue then.

**Comment by Skeezixes** [comment]
I have not been able to test this recently.

**Comment by corrados** [comment]
No more feedback since 20 days now. dubnemo reported that he did not see the issue again. Skeezixes reported that he did not see the issue since then. No further comments from sthenos or any other Jamulus user.

So, I'll close this Issue now since the original request is very old and the problem was not seen recently. If the problem occurs again, just re-open this Issue or create a new one.
