### ISSUE TITLE
Update of the About Dialog

### ISSUE THREAD

**Issue by corrados** [corrados/jamulus#189]
I am in the process of re-designing the About dialog in Jamulus. I want to include the names of the contributors and translators. For the names I have taken the information given at Github. If you do not want your name to be shown or if your name is not listed but you want to be listed, please write a message in this Issue.

![grafik](https://user-images.githubusercontent.com/46655886/81474946-2321cc80-9209-11ea-8bea-77aa45121fcf.png)
![grafik](https://user-images.githubusercontent.com/46655886/81474964-45b3e580-9209-11ea-9380-b2966b5c777a.png)

**Comment by trebmuh** [comment]
Looks very nice. Thanks you very much.

**Comment by ignotus666** [comment]
I'm going to break my cover... :)  Daryl Hanlon.

Cheers for adding us to the list.

**Comment by Snayler** [comment]
Miguel de Matos

**Comment by corrados** [comment]
Ok, I'll update this.

**Comment by gilgongo** [comment]
Thanks for the name check! May as well use my full name of Jonathan Baker-Bates.

**Comment by corrados** [comment]
Sure, I've just updated the code.

**Comment by corrados** [comment]
Since I have just released the new Jamulus version 3.5.3 with the new About dialog, I will close this Issue now.
