### ISSUE TITLE
[RFE] Input mixing console, multiple inputs.

### ISSUE THREAD

**Issue by mangelajo** [corrados/jamulus#19]
I wanted to check what do you think about adding an input mixer, where we could source
multiple input sources (even from multiple sources/cards), into a single signal.

The use case would be: being able to source multiple inputs (like a virtual drummer or background base music), along with a center-panned microphone and your instrument.

I know we have the alternative to run multiple Jamulus instances, and probably we have software options for doing that outside jamulus, but I guess it'd be different on every OS.

I'm not sure I'd have enough steam to code a feature like this. But I wanted to know how you feel about something like that for just in case I found the time.

**Comment by corrados** [comment]
Using different soundcards will lead to synchronization problems. Different sound cards use different oszillators which are not synchronized.
I guess you are talking about Windows. Under Linux you can use this nicely with Jack Audio.

**Comment by mangelajo** [comment]
Windows & OSX at least, yes. 

I'm aware of the possible synchronization issues and the added latency because of that. May be any effort would be better spent trying to document how to use Jack on those OSs instead. 

I tried to setup jack on Windows, but no luck yet. I wonder if it supports ASIO interface for inputs/outputs.

@corrados is there any guide about how to do that in linux you know off the top of your head?

**Comment by corrados** [comment]
There is a nice feature implemented in Jamulus to use the native Jack interface even on Windows, see: https://github.com/corrados/jamulus/blob/master/Jamulus.pro#L49

**Comment by corrados** [comment]
Jack on Windows should support sound cards which have an ASIO driver. I tried it out myself but this is quite a while ago.

**Comment by corrados** [comment]
What guide for Linux do you need? I use QJackCtl and this is very straightforward to use.

**Comment by mangelajo** [comment]
> What guide for Linux do you need? I use QJackCtl and this is very straightforward to use.
Yeah, in linux it works perfectly, I need to investiga the mixing of sources, etc, but that's fine... :)

In windows I didn't get it to work, but I will investigate.

May be we could get JACK also enabled by default on the windows builds?

**Comment by mangelajo** [comment]
Ah, I see you either compile ASIO or JACK, I wonder if we could make both work simultaneusly, I'll investigate the code.

**Comment by ZoomRmc** [comment]
IMO implementing this feature will lead to duplicated efforts. Preparing the source audio signal is much better handled by existing DAWs and hosts.

For Windows, in situations when using virtual ASIO drivers such as ReaRoute is not possible, what could be very helpful is a VST sink which could send the signal from any host to Jamulus.

**Comment by corrados** [comment]
I agree. We should not support this in Jamulus but it should be done with external tools. I close this issue now.

**Comment by ann0see** [comment]
> May be we could get JACK also enabled by default on the windows builds?

Although this is an old issue: We're supporting JACK on Windows since a few versions now. Please have a look at the GitHub release page to download the JACK version.
