### ISSUE TITLE
Default server port changed?

### ISSUE THREAD

**Issue by dszgit** [corrados/jamulus#194]
It looks like in the current development versions, the default server port has changed, from 22124 to 22134.  First, I opened UDP port 22124 in my firewall as instructed by the manual, but not 22123, so packets aren't getting through to my private server.  Second, the client is still assuming the port is 22124, so unless I specify the port number (for a private server), it won't connect.  Of course, I can fix both problems by specifying ports and/or updating my firewall.  But without at least some changes to documentation, this seems like a bug.   Or is this an intended change, and I am just missing something?

I note that in 3.5.2 (git tag r3_5_2) the default server port is 22124.  I see the new behavior starting at least in commit 84d5391 from May 7.

**Comment by Efroymson** [comment]
I noticed something similar, my server opened up a different port than I had pinholed my router for. I opened up a wider range of ports, but my band mates could still not connect, so we had to use a public server

**Comment by dszgit** [comment]
It looks like this started in commit 84d5391 (thank you git-bisect!):

Date:   Thu May 7 20:22:14 2020 +0200

    fix for client port number (avoid socket bind problems if client on the same PC is started before the server)

**Comment by dszgit** [comment]
> I noticed something similar, my server opened up a different port than I had pinholed my router for. I opened up a wider range of ports, but my band mates could still not connect, so we had to use a public server

You can just tell the server to start with the usual port number.  In Linux it's the -p option; I confess I don't know how to do this for Windows or Mac versions.

**Comment by corrados** [comment]
Thanks for reporting. I'll fix it right away.

**Comment by corrados** [comment]
Ok, it should be fixed by now.

**Comment by dszgit** [comment]
Thanks, looks good now!
