### ISSUE TITLE
Feature Request: ability to route multi channel audio out from Server to DAW

### ISSUE THREAD

**Issue by Efroymson** [corrados/jamulus#196]
I'd like to be able to record my jam sessions.  Currently I am running the server on one machine, and client on another.  My band mates log into the server from their machines.  I also run a client on my server machine, and direct it's output to Blackhole (I'm on a Mac and that seems the best virtual port now) so I can record it into Logic.

The problem is that I can only get the whole mix in, I can't get the individual tracks.  Obviously the server must be sending individual tracks to the client, since I can mix and mute them individually from the client.  However, I don't see any way of getting to those individual tracks except via the client, which mixes them down into two tracks, which is fine for monitoring, but not what I would prefer for recording the session to allow further processing.

**Comment by pljones** [comment]
The server can record tracks.

Clients only receive the mix.  That's not going to change.

**Comment by Efroymson** [comment]
I think this is related to #151  and #177, but I am not sure if they are only addressing a desire to allow Jamulus to mix multiple local  audio streams.  I want to be able to record all the streams, local and remote, into one multitrack audio file, i.e. the current output of the Jamulus server.

**Comment by Efroymson** [comment]
@pljones Perhaps I do not understand.  I am asking for the server to be able to record tracks.  I am on a Mac (I can boot into Windows or Linux if that works better, though I am used to Logic) and I do not see how to get the audio from the server to anything other than the client.

**Comment by Snayler** [comment]
The server is already able to record multitracks by using the --recording option and specifying a path for the recordings when launching.

**Comment by Efroymson** [comment]
Looking again, I see this is very similar to #174, which I didn't see when I checked before submitting this (maybe because it was closed) but I don't really need the ability to live process the audio stream, simply recording it would be fine for me. In fact if the server could simply dump out a file for later processing that would be ok, and perhaps easier to implement.  Oh, never mind, I think I see now how this is supposed to work.   Perhaps this should be left open but renamed to "Better documentation on -R Server option, ability to access it from GUI".

**Comment by Efroymson** [comment]
I notice that I am not able to connect to a private server with this option enabled?  Is that correct?  It seems to require the Creative Commons license to be accepted, which is reasonable, but maybe is interfering with private servers?

**Comment by gilgongo** [comment]
> Is that correct??

No, the` --licence` and `--recording` options are independent.

**Comment by corrados** [comment]
>  I don't really need the ability to live process the audio stream, simply recording it would be fine for me

Ok, so you can use the --recording function then. If you are happy with that, is it ok to close this Issue?

**Comment by Efroymson** [comment]
I have been able to record, using --recording, so yes, this issue can be closed.  I have some other issues with it, including the documentation.  I might be able to help write up some notes on how to use it, as I get more comfortable, if that would be useful.  The documentation as it stands is rather sparse.
