### ISSUE TITLE
Looking for documentation for a config file / inifile

### ISSUE THREAD

**Issue by dubnemo** [corrados/jamulus#198]
When I get --help, list of commands show the potential of an inifile, however I am not able to find a wiki page or example file.
./Jamulus -s -inifile myinifile.ini
I can help create the documentation if it does not exist.  I would need a few directions where to look at source code.

**Comment by dubnemo** [comment]
I see main sets strIniFileName, in a CSettings class.

**Comment by pljones** [comment]
The ini file is read/written by the app from GUI mode.  `settings.cpp` is where all the dirty work is done.  It's complicated how the command line and settings interact.  I'm planning to address this under #120 but that'll take a while...

**Comment by dubnemo** [comment]
@pljones issue #120 seems to be server related.  I want the ability to manage client settings, although the same would hold true.  Except there does NOT seem to be the default Jamulus.ini file present on my filesystem.  Was that removed? 

// default names of the ini-file for client and server
#define **DEFAULT_INI_FILE_NAME**            "Jamulus.ini"
#define DEFAULT_INI_FILE_NAME_SERVER     "Jamulusserver.ini"

There a many approaches for settings files, and the one that I have recently used involves the override approach.  That approach implies there would be standard variables set in the code first, then a configuration/ settings file (strIniFileName ) is read to override **only those parameters** / variables present in the file.   Considering I cannot locate Jamulus.ini on my Raspbian client v3.5.3, how is it done now?  

            // load settings from init-file
            CSettings Settings ( &Client, **strIniFileName** );
            Settings.Load();

**Comment by pljones** [comment]
#120 only deals with the server.

The code you quote above only deals with the client.

**Comment by pljones** [comment]
If it's of any use, when I was poking around in this area the other day, I came up with these:
```
    struct SClient
    {
        QString vstrIPAddress[MAX_NUM_SERVER_ADDR_ITEMS];
        QString vecStoredFaderTags[MAX_NUM_STORED_FADER_SETTINGS];
        int vecStoredFaderLevels[MAX_NUM_STORED_FADER_SETTINGS];
        int vecStoredFaderIsSolo[MAX_NUM_STORED_FADER_SETTINGS];
        bool vecStoredFaderIsMute[MAX_NUM_STORED_FADER_SETTINGS];
        int iNewClientFaderLevel;
        bool bConnectDlgShowAllMusicians;
        CChannelInfo ChannelInfo;
        int audioInFader;
        int reverbLevel;
        bool reverbOnLeftChan;
        int sndCrdDev;
        int sndCrdLeftInputChannel;
        int sndCrdRightInputChannel;
        int sndCrdLeftOutputChannel;
        int sndCrdRightOutputChannel;
        int sndCrdPrefFrameSizeFactor;
        bool doAutoSockBufSize;
        int sockBufNumFrames;
        int serverSockBufNumFrames;
        bool enableOPUS64;
        EGUIDesign guiDesign;
        bool displayChannelLevels;
        EAudChanConf audioChannels;
        EAudioQuality audioQuality;
        QString serverListCentralServerAddress;
        ECSAddType centralServerAddressType;
        QByteArray vecWindowPosMain;
        QByteArray vecWindowPosSettings;
        QByteArray vecWindowPosChat;
        QByteArray vecWindowPosProfile;
        QByteArray vecWindowPosConnect;
        bool bWindowWasShownSettings;
        bool bWindowWasShownChat;
        bool bWindowWasShownProfile;
        bool bWindowWasShownConnect;
        int port; //TODO
        //connect TODO and GUI
        //nojackconnect TODO and GUI
        //ctrlmidich TODO and GUI
        //clientname TODO and GUI
    };
```
```
    struct SServer
    {
        ECSAddType centralServerAddressType;
        QString serverListCentralServerAddress;
        bool serverListEnabled;
        QString serverName;
        QString serverCity;
        QLocale::Country serverCountry;
        bool autoRunMinimized;
        ELicenceType licenceType;
        int port; //TODO
        bool fastupdate; //TODO and GUI
        int histdays; //TODO
        //TODO logging
        bool licence; //TODO
        //TODO htmlservername and GUI
        //TODO htmlstatus
        //TODO recording
        //TODO numchannels
        //TODO welcomemessage
        //TODO history graph
        bool startminimized; //TODO and GUI
    };
```
I didn't get as far as finalizing them.  Anything marked "TODO" isn't actually in Settings currently.  The data types are also the "finalized" types, rather than the type stored in the ini file.

**Comment by corrados** [comment]
> When I get --help, list of commands show the potential of an inifile, however I am not able to find a wiki page or example file.

The idea is that Jamulus sets all the settings so you don't have to set it your self. So you start Jamulus with, e.g, ./Jamulus --inifile mytest.ini. If the file does not exist, Jamulus will create one for you. So you start Jamulus, set all your settings and then the settings are automtically stored correctly in the ini file for you.

> That approach implies there would be standard variables set in the code first, then a configuration/ settings file (strIniFileName ) is read to override only those parameters / variables present in the file.

That is what Jamulus actually already does. You can let Jamulus store the complete ini file for you (as written above) and then you can delete all the entries which you do not want to be overwritten.

> Considering I cannot locate Jamulus.ini on my Raspbian client v3.5.3, how is it done now?

It should be located in your home .config directory by default (Qt decides where it is stored). But with using the --inifile command line paramter, you can specify where it shall be located.

Do you need any additional information? If not, I would like to close this Issue.

**Comment by dubnemo** [comment]
@corrados @pljones  sorry for the delay, I have been swamped with a project.  Thank you for the detail.  All is good. Closing.

**Comment by kjcole** [comment]
I use the GUI to set the server options, including HTML and CSS. When I next start the server, the HTML and CSS are gone. So, yes, I think documenting / providing examples of user-editable settings files would be useful. Plus that, just knowing what's what e.g. directory type mapping, is always helpful.

Or maybe a "Save as" menu option? When I make the change, and connect to the server, I don't see an update in the timestamp for `~/.config/Jamulus/Jamulusserver.ini` which seems the most likely candidate file.

**Comment by pljones** [comment]
No, what you're asking for _isn't_ documenting the file -- it's adding another value into the settings.  At the moment, the way you set the server welcome message from the command line is the `--welcomemessage`.  There isn't a settings file entry.

**Comment by kjcole** [comment]
> No, what you're asking for _isn't_ documenting the file -- it's adding another value into the settings. At the moment, the way you set the server welcome message from the command line is the `--welcomemessage`. There isn't a settings file entry.

Thanks.

Is there another issue / thread for why using the GUI strips out the HTML? (When I started the server from the GUI, I got a form that I dutifully filled in, and was hoping it would save everything. It **mostly** does -- though where, I'm not sure. It only fails with the HTML / CSS, stripping it to plain-text on a restart.)

**Comment by pljones** [comment]
> Is there another issue / thread for why using the GUI strips out the HTML?

Oh, sorry, I see - it's not stripping it _all_, just the formatting?  Mmm, I think it was raised once.  But it wants a bug - feel free to raise a new one if you can't see one in the open bug reports.
