### ISSUE TITLE
[RFE] Sending the level of each channel from the server to the clients

### ISSUE THREAD

**Issue by mangelajo** [corrados/jamulus#20]
This would allow to draw a meter together with each slider (or a led),
providing visual input on which channel is playing and/or making noise..

**Comment by corrados** [comment]
plljones is working on this, see: https://sourceforge.net/p/llcon/feature-requests/33

**Comment by mangelajo** [comment]
oh wow @pljones ++ awesome guys!! :)

**Comment by mangelajo** [comment]
I see the design, and it makes sense, 2 bits per channel + a LED per channel to not clutter the UI.

**Comment by pljones** [comment]
OK, initial client side UI is available on my fork on branch `feature/channel-meters`:
https://github.com/pljones/jamulus/tree/feature/channel-meters

Comments on code and UI welcome.  (I tried it with the fancy skin and it looks as I'd expect.)  As far as I can tell, it's using no additional width.  _Maybe_ the height of the LED bar could be reduced (to give it some clearance)?

**Comment by corrados** [comment]
Just one quick comment: Thank you that you respect my way of coding and code style in your own coding. That will make the integration much easier for me.
From a quick look at the code it looks fine with me.

**Comment by corrados** [comment]
It's done: https://github.com/corrados/jamulus/pull/42
