### ISSUE TITLE
Compression for recorded audio

### ISSUE THREAD

**Issue by seanogdelaney** [corrados/jamulus#206]
Congraulations Jamulus authors: Outstanding FOSS with real public benefit. That's not easy.

The storage volume (and IO bandwidth) associated with recording could be reduced by a factor of 10 by using suitable compression. This is especially important for large ensembles. Lossless storage is overkill in the context of Jamulus. 

The OPUS library is already linked, so that's an easy option. OGG or MP3 would have wider support in DAWs. AC3 or MOGG would facilitate a single (synchronised) multi-track output file, and MOGG is supported by free DAWs such as Audacity and Studio One Prime. 

I think libsox would support all of the above (user could choose?), and is cross-platform FOSS.

**Comment by WolfganP** [comment]
Interesting feature... MOGG seams to be supported as a multitrack container by multiple DAWs already (including Reaper)

I did a quick search and opus does have a multistream API up to 255 streams https://www.opus-codec.org/docs/opus_api-1.1.2/group__opus__multistream.html , but the system load on compressing multiple streams simultaneously is unknown

The sweet point may be using a lossless codec on a multitrack container (MOGG container with FLAC encoder?)

**Comment by corrados** [comment]
Is harddrive space really a problem with modern hard drives considering audio signals? I thought the memory requirement even for uncoded audio data is negligible nowerdays...

**Comment by seanogdelaney** [comment]
The requirement is roughly 1.3GB per participant per hour, I believe. For users running their server on a raspberry pi, or on the AWS EC2 free tier (8GB default), this is perhaps not negligible. Jamulus has done a great job in making users lives easier. This feature might help IMHO.

Reaper is a commendable tool and project, but it's not free. Jamulus is free, so it seems odd to promote Reaper over free alternatives. A workaround would be to pad each new wav file with silence before proceeding to write it. Then at least they can be easily imported to other DAWs.

**Comment by pljones** [comment]
How you compress the recorded audio is up to you.

I've a couple of scripts - one watches for the end of a session, the other then checks the audio for silence, deletes those files, compresses the rest and updates the RPP file, before zipping everything and uploading to another server.  (I keep a copy locally ... for no real reason.)

The zip contains the current versions.  They're highly dependent on my local set up, so you'll need to edit them.  That's why I've not posted them anywhere...
[watch-and-publish.zip](https://github.com/corrados/jamulus/files/4616795/watch-and-publish.zip)

**Comment by seanogdelaney** [comment]
Thanks pljones and all.

I fully understand that this feature may not be a priority. There are ways to deal with the output if the user is motivated. I also have a custom script monitoring the output directory, and using the reaper metadata to timeshift and compress the tracks, and archive them to 1 file for download to my DAW. 

I guess this is not 'convenient' for everyone. For me, it's fine!
