### ISSUE TITLE
Question about Max Users

### ISSUE THREAD

**Issue by brandflake11** [corrados/jamulus#208]
Hello all,
I just have a quick question: Is there a limit of maximum users for a Jamulus Server? 

I know you can specify the amount of max users on the server. Does Jamulus have any internal limits in its code on the amount of people that can connect to it?

Thanks your help!

**Comment by corrados** [comment]
The maximum number of users is set here:
https://github.com/corrados/jamulus/blob/master/src/global.h#L180
It is set to 50 right now.

**Comment by corrados** [comment]
BTW: If you are happy with the answer, please close this issue, thanks.

**Comment by brandflake11** [comment]
Thanks for the response. If I was to change this number to something different, say 300, and make the program, would there be other things I would need to change?

**Comment by corrados** [comment]
If you use Qt5 than no.

**Comment by brandflake11** [comment]
Thank you very much, if I run into problems with anything, I will make sure to open an issue here. I cannot thank you enough.
