### ISSUE TITLE
Cannot move faders on Mac

### ISSUE THREAD

**Issue by corrados** [corrados/jamulus#209]
From https://sourceforge.net/p/llcon/discussion/533517/thread/2e9e75221c

Alison reports that on her Mac she cannot move the mixer sliders anymore since version 3.5.2. It seems to be related to the new feature: "use audio level meter bars for normal skin".
Disabling the lever meters solves the issue.
I cannot reproduce this issue on my Mac. Is there anybody else who can reproduce the issue?

**Comment by Skeezixes** [comment]
I will try to pursue this. I think I remember something strange happening with the mixer sliders once but I haven't seen it for awhile. Does it depend on how many are connected?

**Comment by corrados** [comment]
Good question. I cannot reproduce the issue on my (old) Mac. If you are able to reproduce it, please write about it here. I suspect this is an issue with Qt itself. Maybe I have to update my Qt development environment (it asked me in the past but I did not perform the update yet, maybe I should do that now ;-) But this may not be related to the bug at all... ).

**Comment by corrados** [comment]
Maybe this is related to this closed Issue: https://github.com/corrados/jamulus/issues/292

**Comment by corrados** [comment]
The issue is solved, see: https://sourceforge.net/p/llcon/discussion/533517/thread/2e9e75221c/#51a9/15cc/5748/4d53
-> closed
