### ISSUE TITLE
Windows should not support "-n" headless

### ISSUE THREAD

**Issue by pljones** [corrados/jamulus#210]
On Windows, "-n" makes as little sense as "-z" does on other platforms.  The two are "alternatives", really.

The problem with "-n" on Windows is that you are left without a way to stop the server cleanly - you need to use Task Manager, which is the equivalent of a SIGKILL on Unix, it seems.

Using "-z" allows the server operator to run the server "out of the way", but still shut it down "nicely" from the tooltray icon.

(Ideally, I'd have said to get rid of -z and have -n on Windows do what -z currently does.  But I'd rather not go changing existing switches people are used to using.)

**Comment by corrados** [comment]
> makes as little sense as "-z" does on other platforms

It should also work on Linux: https://doc.qt.io/qt-5/qtwidgets-desktop-systray-example.html
But I have not tested it myself actually.

> The problem with "-n" on Windows is that you are left without a way to stop the server cleanly

Yes, but it is similar behaviour as on Linux. The -n option makes sure that no actual Qt GUI is used. Maybe someone needs that on Windows, too. I would not remove that functionality. It does not hurt.

> Ideally, I'd have said to get rid of -z and have -n on Windows do what -z currently does

No, we need the -z option for the Windows auto start of the server. And as mentioned above, I would keep the -n for Windows, too.

**Comment by pljones** [comment]
> It does not hurt.
Yes, it does.  It means the only way to kill the server is through Task Manager, and that's equivalent to SIGKILL on Linux.  You don't want to do it if you don't have to.  You want to be able to shut the server down "with care".  Using "-n" prevents any possibility of doing that.

**Comment by corrados** [comment]
> You don't want to do it if you don't have to.

Maybe someone wants to run the Jamulus server without having the LED icon in the task bar. The Jamulus server is still full functional, even if it is started with -n on Windows.

**Comment by pljones** [comment]
It's running, yes, but it's not as controllable as the Linux version.  You can't send signals to it to tell it what to do, like exit cleanly or start a new Jam.  So "fully functional"?  I'd disagree.

**Comment by corrados** [comment]
Ok, so it should read: "The Jamulus server is still functional". Still, I am of the opinion to keep this flag even for Windows. Should be close this issue?

**Comment by pljones** [comment]
I suppose on a virtual server that boots just to run Jamulus, being headless makes sense, even on Windows.  (I think at least shutting down Windows _will_ terminate the application normally.  I think...)
