### ISSUE TITLE
New Version for Linux available?

### ISSUE THREAD

**Issue by stony245** [corrados/jamulus#214]
Is there a new version fo Linux available, which includes packet size of 64? Current Version is 3.4.4
When compiling from git I get the following error:

```
g++ -c -m64 -pipe -std=c++11 -O2 -D_REENTRANT -Wall -W -DAPP_VERSION=\"3.5.3git\" -DOPUS_BUILD -DUSE_ALLOCA -DCUSTOM_MODES -D_REENTRANT -DHAVE_LRINTF -DHAVE_STDINT_H -DWITH_SOUND -DQT_NO_DEBUG -DQT_XML_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED -I../../share/qt4/mkspecs/linux-g++-64 -I. -I../../include/qt4/QtCore -I../../include/qt4/QtNetwork -I../../include/qt4/QtGui -I../../include/qt4/QtXml -I../../include/qt4 -Isrc -Ilibs/opus/include -Ilibs/opus/celt -Ilibs/opus/silk -Ilibs/opus/silk/float -Ilibs/opus/silk/fixed -I. -I. -o signalhandler.o src/signalhandler.cpp
src/signalhandler.cpp: In static member function 'static CSignalHandler* CSignalHandler::getSingletonP()':
src/signalhandler.cpp:74:58: error: cannot convert 'CSignalHandlerSingleton* (*)()' to 'CSignalHandler*' in return
 CSignalHandler* CSignalHandler::getSingletonP() { return singleton; }
                                                          ^~~~~~~~~
src/signalhandler.cpp: In member function 'bool CSignalHandler::emitSignal(int)':
src/signalhandler.cpp:78:111: error: no matching function for call to 'QMetaObject::invokeMethod(CSignalHandlerSingleton* (&)(), const char [15], Qt::ConnectionType, QArgument<int>)'
     return QMetaObject::invokeMethod( singleton, "ShutdownSignal", Qt::QueuedConnection, Q_ARG( int, sigNum ) );
                                                                                                               ^
In file included from ../../include/qt4/QtCore/qobject.h:47,
                 from ../../include/qt4/QtCore/QObject:1,
                 from src/signalhandler.h:64,

```

**Comment by Snayler** [comment]
Follow the wiki to get the latest git version:
https://github.com/corrados/jamulus/wiki/Installation-for-Linux

**Comment by Snayler** [comment]
You can check the releases on git, try version 3.5.2
https://github.com/corrados/jamulus/releases

**Comment by stony245** [comment]
I tried it. Linux Server with 3.5.2 is OK. Ran it with the same config file as 3.4.4.
However Client had no audio plus latency of more than 100msec instead on 32msec on 3.4.4 
Went back to 3.4.4 on client side.

**Comment by corrados** [comment]
@pljones Can you please take look at it? On my Linux it compiles. Maybe this is a Qt4 related issue? What do you think?

**Comment by pljones** [comment]
Yes it seems the signals solution needs Qt5.  Unfortunately it's not something I'd be able to resolve in Qt4.

See https://github.com/corrados/jamulus/issues/168#issuecomment-627988221 and onwards.

**Comment by corrados** [comment]
Ok, thanks for checking. So I think now we reached a point where it is time to quit Qt4 compatibility...

**Comment by stony245** [comment]
After some testing (had some wrong network settings, sorry) 3.5.2 now works well under Linux with same latency as 3.4.4
Tested with 
- Client Linux Mint 19.1 Mate with realtime kernel
- Client Ubuntu Studio 18.04 with realtime kernel
- Server also runs on 3.5.2 with 64 samples (-F) under Debian Buster 10.4 with Proxmox kernel  5.3.18-2-pve

**Comment by corrados** [comment]
> 3.5.2 now works well under Linux with same latency as 3.4.4

Ok, thanks for the feedback. I will close this issue now.
