### ISSUE TITLE
How to play sound into Jamulus on my Jamulus server?

### ISSUE THREAD

**Issue by stony245** [corrados/jamulus#215]
I am trying to play some backing tracks or metronome sound into Jamulus for my band. We discovered that when playing a backing tracks or metronome sound at my premise, the others do hear this sound delayed, whereas I am hearing this just in time.

So the idea is to insert this sound at the server side, so that all users receive this sound at the same time.
I see 2 approaches here:
1.) Have the possibility to stream a file directly and headless to Jamulus server on the server. Currently I see no tool here (am I right?)

2.) Install a virtual Linux machine with GUI on the same server and run Jamulus client here and manage to play sound from the default device via jack to Jamulus. That way we can play Youtube or any sound file and stream it into the Jamulus session in almost realtime (0.1msec ping to our Jamulus server).

Step 2 I will describe so far and where I am stuck:
a) I have setup a Jamulus server in a Proxmox virtual environment at a hosting provider. Jamulus Server runs on a local IP 10.10.10.11 in a virtual machine in an LXC container. This works well, and we are playing with it since some weeks.

b) I have setup a KVM machine (Linux Mint) with Mate GUI on the same host with IP 10.10.10.13. I was able to install qjackctl and Jamulus here. Jamulus can connect to the Jamulus server under a), and other clients do see the Jamulus on this KVM machine. However we have no sound.

And here comes the tricky part:
- The server has no sound card
- the KVM container has no sound card
So we have to generate some kind of virtual sound card within KVM.

I followed https://alsa.opensrc.org/Jack_and_Loopback_device_as_Alsa-to-Jack_bridge
did a 
`modprobe snd-aloop`

`aplay -l`
Shows me the sound card after fixing some access right in /dev/snd
`setfacl -m user:user:rw /dev/snd/*`

Now I can already assign the loopback device to qjack and can start running Jamulus.
Then I created ".asoundrc" and "loop2jack" according to the above link.
However I do not get any furtehr as I get error messages like
`ERROR cloop:capture_1 not a valid port`

So my question is:
Has anybody already done this or a similar approach and can share this information/solution with me?

**Comment by pljones** [comment]
Sound gets into the server from an attached client.

There will _always_ unavoidably be differing amounts of latency between clients.  That's just how the universe works (speed of light and all that, plus then what your local networking is like and your local hardware, etc, etc,).

If you want synchronisation between clients, then you're not going to find it using a streaming protocol like Jamulus, you'll need a buffered protocol like NINJAM that delays all clients until they align against a set timeline.

**Comment by stony245** [comment]
> Sound gets into the server from an attached client.

That was my idea. Therefore I wanted to put this metronome-client directly on my Jamulus server in order to have a latency of almost 0 msec between Jamulus server and metronome-client.

In an ideal case, if e.g. all 4 attached clients of my band have an overall latency of 30 msec, then the metronome signal arrives at all 4 clients exactly after 30 msec, so we expect all to be in sync.

In case I input the metronome at one external client, as we do it now in the regular way
- the client, who inserts the metronome signal e.g. via a mixer hears the sound directly
- all other clients with 30 msec delay
- (maybe it's even best for the drummer to insert the metronome signal)

BTW: Metronome is just a placeholder for anything which is leading or accompanying us, like e.g. backing tracks.

**Comment by pljones** [comment]
OK, so this issue isn't about Jamulus, it's about how to get audio working on the platform you're running the Jamulus client on, right?

**Comment by stony245** [comment]
Yes that's right. maybe any other place where I can ask this question?

**Comment by stony245** [comment]
For the records: I got it working. I have setup a Linux KVM machine Mint 19 with Jamulus and a virtual sound card (no sound card inside machine available). That way I can play any sound into Jamulus directly on my Server with very low latency to all other participiants.
Applications to be used are e.g.
    • gtick Metronome
    • Youtube videos via any web browser
    • any mp3 or video with a program like Audacity, VLC, Clementine
    • Drumcomputer Hydrogen
    • etc. pp

How did I do it in general:
    • modprobe snd-aloop
    • check mit aplay -l
    • snd-aloop into modules (modprobe, see files at the end)
    • create $HOME/.asoundrc 
    • chown user:user .asoundrc
    • setfacl -m user:user:rw /dev/snd/*
    • usermod -a -G audio user
    • apt-get install linux-headers-lowlatency linux-image-lowlatency linux-tools-lowlatency and activated in Grub (important, otherwise sound is very bad)
    • /etc/modprobe.d/alsa-base.conf : All entires deactivated
    • apt-get install pulseaudio-module-jack
    • Set qjackctl fo after start
`pacmd load-module module-jack-source channels=2; pacmd load-module module-jack-sink channels=2;
`    • Set qjackctl fo after stop
`killall jackd`

How to run it
    • start QjackCtl 
    • start Jamulus starten and connect
    • QjackCtl make connections between PulkseAudio Sink and Jamulus

And very important $HOME/.asoundrc 
```
pcm.amix {
  type dmix
  ipc_key 219345
  slave {
    pcm "hw:Loopback,0,0"
    rate 48000
  }
}

pcm.asnoop {
  type dsnoop
  ipc_key 219346
  slave {
    pcm "hw:Loopback,0,1"
    rate 48000
  }
}

pcm.aduplex {
  type asym
  playback.pcm "amix"
  capture.pcm "asnoop"
}

pcm.ploop {
  type plug
  slave {
    pcm "hw:Loopback,1,1"
    rate 48000
  }
}

pcm.cloop {
  type dsnoop
  ipc_key 219348
  slave {
    pcm "hw:Loopback,1,0"
    rate 48000
  }
}


pcm.!default {
  type plug
  slave {
    pcm "aduplex"
  }
}`
```

More files
/etc/modules-load.d# cat snd-aloop.conf
```
snd-aloop
```

/etc/modprobe.d# cat snd-aloop.conf
```
alias snd-card-0 snd-aloop
options snd-aloop pcm_substreams=2 # This limits the devices to 2, default is 8
```

**Comment by stony245** [comment]
It works, so I will close it now.
