### ISSUE TITLE
GTK theme not honored on master

### ISSUE THREAD

**Issue by fleutot** [corrados/jamulus#218]
Not using Fancy skin:

- Building r3_5_2 from source uses my GTK theme.
- Building master does not (it's using a light theme with blue accents instead).

Is this expected? Is the plan to let it be that way, or to give back theming responsibility to the user?

**Comment by corrados** [comment]
What operating system your are using?

**Comment by fleutot** [comment]
Ubuntu 18.04, WM is xmonad.

**Comment by corrados** [comment]
> Is this expected?

Looking at the ChangeLog, nothing would explain a change in the normal skin of Jamulus.
Have you changed your Qt version?
If you build from master and then build on the same machine on r3_5_2 you get different themes?

**Comment by fleutot** [comment]
Oh, sorry, my bad. My r3_5_2 was apparently an older build than I though. I guess I borked my QT, and I think I know when (trying to build another project). Sorry for disturbing!

**Comment by corrados** [comment]
No problem. So I close this issue now.
