### ISSUE TITLE
GUI Interface for Recording

### ISSUE THREAD

**Issue by pljones** [corrados/jamulus#228]
Currently the Server GUI has no support for recording.

As a first step, I'd like to add
- whether recording is enabled / happening
- ability to start a new recording (similar to SIGUSR1 support under #170)

I've got a little bit of code started for this, so it'll probably be the next thing I pick up.
https://github.com/pljones/jamulus/tree/feature/228-gui-triggered-recording-cuts

**Comment by corrados** [comment]
I wonder if you can apply Labels to a Github Issue when you create it? Or is it only allowed for me to apply labels?

**Comment by Snayler** [comment]
@corrados only the owner of the project can apply labels, as far as I can tell from the issues I created.

**Comment by WolfganP** [comment]
https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/permission-levels-for-a-user-account-repository collaborators can work with labels and other projects´admin tasks.
https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/inviting-collaborators-to-a-personal-repository shows how to invite certain users to collaborate
The other option is to convert the account to an organization which allows for better control of roles and permissions, but it has it´s own drawback https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/converting-a-user-into-an-organization

**Comment by corrados** [comment]
I was just asking because of curiosity. There is no need for getting help with applying the labels. Adding the labels is kind of project organization for me.

**Comment by trebmuh** [comment]
@corrados : there can be some sort off automatic labeling. LMMS github is doing that as far as I remember.

**Comment by corrados** [comment]
No, actually I prefer to set the label myself. There are not too many new Issues created and it seems the first wave of Corona is through and things go back to normal slowly:
![grafik](https://user-images.githubusercontent.com/46655886/82122616-02bbba00-9795-11ea-9eb7-a3fdbda4ddb7.png)

**Comment by trebmuh** [comment]
That was just a "FYI", it's up to you.

**Comment by corrados** [comment]
Yes, I know. Thanks.
But now we should continue in the discussion about the actual topic of the Issue and not only off-topic things :-).

**Comment by pljones** [comment]
I'm sure many governments would like a Corona graph like yours :).

**Comment by corrados** [comment]
Well, this is what we have in Germany regarding Corona:
![grafik](https://user-images.githubusercontent.com/46655886/82123970-90e76e80-979c-11ea-9f73-05242e4b1733.png)
Looks somewhat similar :-).

**Comment by pljones** [comment]
To get back on topic :)
![image](https://user-images.githubusercontent.com/1549463/82730231-28e1dc80-9cf6-11ea-8dea-f1b2db8056a2.png)

One reason I split this from the SIGINT/SIGTERM and SIGUSR1 console work was because I want to actually implement something like the above in the end.

----

Initially, this will just be the new "STATUS" label and "New recording" button.

The "STATUS" field will only be _visible_ if the Jam Recorder is enabled.  It will then basically say whether a server session is in progress or not, as the Jam Recorder is running then.  Although I might display the session directory name in a read-only text box...  Still to be decided / investigated.

The "New recording" button will only be _enabled_ if the Jam Recorder is enabled and a server session is in progress.

----

SIGUSR2 will then be added to allow the console to disable/enable recording "in flight".  Disabling whilst a session was in progress would "tidily" end the recording and prevent further recordings.  Enabling whilst a session was in progress should "tidily" start a new recording and allow future recordings.

After that, I'll add the "Enable jam recorder" checkbox to the GUI, which will initially just do the same thing.

In both cases, the server will still need to have been started enabling recording correctly.

----

Finally, once that's done, probably the hardest bit will be allowing the user to configure the recordings directory from the GUI.  The "Recordings folder" button will open a Qt QFileDialog to allow a directory to be selected.  The text field next to the button will display the configured path (read-only).

I'll also change the Jam Recorder so that the directory can be passed in without it throwing exceptions if it doesn't like it but to return a "that didn't work" response which can be displayed to the user.

This will mean you can start the server _without_ enabling the jam recorder, then set it up from the GUI.

----

Another reason I stopped before is the way the command line options and INI file options interact.  To me, it's surprising that if I say "use this INI file but set the server name to THIS", I don't get obeyed - the server name in the INI file is used regardless.  I'll raise a new issue on that, though.

**Comment by corrados** [comment]
Please note that recently I made some small changes to the server GUI (e.g. moved the server type combo box).

With your proposal it starts that we have too many GUI controls in one dialog. Maybe we should think about a separate settings dialog for the server, similar to what we have for the client. E.g. the jam recorder directory/file could be set in that new dialog but the New recording button should stay on the main dialog.

**Comment by pljones** [comment]
Yep - I also had used the wrong version of _my_ code (from when I was messing around) for the screen shot above.  I won't actually be doing the GUI changes until after you've released the next version, anyway.

There is, as I imply at the bottom of my post, scope for improvement of the server GUI.  The basics, I think, should as they've always been: the list of clients and "Do I want my server on a server list and, if so, what details do I want to publish about it?"  Everything beyond that could probably be moved "out of the way".

**Comment by pljones** [comment]
The current version on my branch:
- shows "Not enabled" if the command line option was not present
- shows "Not recording" if the recording is enabled but no session is in progress
- shows "Recording" and enables the "New recording" button (otherwise disabled) if recording is enabled and a session is in progress

**Comment by pljones** [comment]
![image](https://user-images.githubusercontent.com/1549463/82824025-7ac66600-9ea0-11ea-98ae-28a9f79d62fd.png)
This is what it looks like now I've added the current session.  When you're recording, you can select the session directory name to copy it to the clipboard.  Each click of "New recording" gets a new directory name.  At the moment it's disabling the text box at the end of the session, leaving the final directory name visible.

I think I'll raise a pull request at this point, as it's the first chunk of what I was planning.

**Comment by pljones** [comment]
See also #294 (will be mapped).

**Comment by pljones** [comment]
![image](https://user-images.githubusercontent.com/1549463/83348558-bf7d5180-a325-11ea-88f9-1c971db991d9.png)
This is PR #312 
- SIGUSR2 and a checkbox to switch recording off and on, if it was initially set up correctly.

In addition, "behind the scenes", the application no longer "crashes" if you get setting up recording wrong, it just doesn't record.  It does issue a message, such as
```
"/home/peter/git/Jamulus-wip/foo" exists but is not a directory
```
which attempts to explain what you did wrong, and it won't let you record (the recording controls aren't present).

**Comment by pljones** [comment]
Final part now done in PR #321.

**Comment by pljones** [comment]
Thinking about it overnight, would it look better (more sane) with the overall recording directory line (which determines whether recording gets initialised) above the "per recording" line (whether recording is happening)?

**Comment by pljones** [comment]
#391 is a precursor to making it possible to set up the jam recorder from the server UI without having passed `-R` on the command line.  It moves out code from the server as far as possible - although in this version there's a lot of passing stuff through as the server dialogue only knows about the server and only the server knows about the new jam controller.

Further rewiring may follow.

**Comment by gilgongo** [comment]
Just reading up on this to see what updates to the docs might be needed. I'll wait until you have your final cut of the UI, but meanwhile a minor comment is that Jamulus's "house style" for labels is to use Initial Capitals. This is of course rather unusual, but I think it's quite nice in a way as I assume it's from Volker's Germanic Tradition of Capitalisation of Words :-)

**Comment by pljones** [comment]
#405 is now there with the UI.

**Comment by pljones** [comment]
#405 is now merged to master, so will be in the next release.  Closing.

**Comment by gilgongo** [comment]
Not sure if this should a separate ticket, but would it be better to use a "backspace" icon for the button that clears the recording path in the UI? I wonder if "(X)" might get misinterpreted as "delete the recording(s)" by mistake (it's also used as an emoji to mean "revolting" by children in Korea and Taiwan). 

![button](https://user-images.githubusercontent.com/4561747/86510919-1de99400-bdec-11ea-8bc5-103be7e1ea45.png)



I think Volker used a unicode character for the "muted" icon in the UI, so using using [Unicode character U+232B](https://www.fileformat.info/info/unicode/char/232b/index.htm) might work?

Come to think of it, and given the risk of misinterpretation - is the button strictly necessary? If the user wants to change the directory, they can do so with the "Recordings Directory" button maybe. Bit of an edge case perhaps.

_Nice work though by the way - I'm sure a lot of people don't even know Jamulus can record. That should change now :-)_

**Comment by pljones** [comment]
It's an explicit action - "clear directory and disable recording".  You can't select "no" directory, so it needs a separate action.  I'd suggest submitting a patch with the GUI change separately -- I've no particular view on what it should look like but it needs to express that meaning.
