### ISSUE TITLE
Slight increase in delay with 3.5.2

### ISSUE THREAD

**Issue by Snayler** [corrados/jamulus#233]
I'm noticing a slight increase in delay with the new version when the client and server are running on the same machine.

I was able to get 13ms overall delay with 64 frame buffer and small network buffers enabled on the client, and --fastupdate option on the server. Now with the same settings I'm having 23ms, which is 10ms more than before. Was something changed that might be producing this issue?

**Comment by corrados** [comment]
@pljones I remember in some other thread you mentioned that the server requires more CPU than expected (was it 40% on a fast PC?). You suspected your code to be the cause. Have you further investigated this issue? Maybe this is causing the issue reported here.

**Comment by Snayler** [comment]
Disregard this report. After some troubleshooting, I found that older versions are now behaving the same way. I've re-installed Windows from scratch, so the problem should be just from my end. Closing this now.

**Comment by pljones** [comment]
Yeah, so far, I've not repeated the 40%...  It's looking sane and exactly the same numbers as older versions here.

**Comment by corrados** [comment]
Ok, thanks for the info. Good to know that it seems not to be in issue in Jamulus.
