### ISSUE TITLE
Windows build fails on master

### ISSUE THREAD

**Issue by pljones** [corrados/jamulus#248]
Commit 8788936 seems to break the build.

I've stepped back (not every commit, skipping translates) but before that, the build works, after, it fails.

**Comment by corrados** [comment]
Strange... I usually compile it before I commit. I'll take a look.

**Comment by corrados** [comment]
It compiles fine for me. Can you please post the compiler error you get?

**Comment by pljones** [comment]
Closing -- looks like QtCreator doesn't clean up properly when you tell it to "Rebuild All".

Fixed by deleting `%TEMP%\build-Jamulus*`.

(`make distclean; qmake; make` on Linux was working fine.)
