### ISSUE TITLE
Italian Translation

### ISSUE THREAD

**Issue by dzpex** [corrados/jamulus#249]
Hi and thanks for your job. Jamulus is very beautifull software for us that love to play along with friends!

If is possible i can make the translation from english to italian.

Is the fist time that i use github for coding. How is the rigth way to do that?

**Comment by corrados** [comment]
I could prepare the translation files for you, if you like.
You fork the jamulus git code, make your changes and open a pull request so that I can merge your code changes.

**Comment by dzpex** [comment]
ok i wait for the file and start the translation

**Comment by corrados** [comment]
I just added the file for you: https://github.com/corrados/jamulus/blob/master/src/res/translation/translation_it_IT.ts
I recommend to use the Qt Linugist tool for editing the file: https://doc.qt.io/qt-5/linguist-translators.html

**Comment by corrados** [comment]
The Italian translation is merged now: https://github.com/corrados/jamulus/pull/273
-> closed

**Comment by dzpex** [comment]
I Corrados Thaks a lot.
Can you add my full name?
Firt Name Giuseppe
Last Name Sapienza 
nik dzpex

Thakyou

**Comment by corrados** [comment]
Sure, I just updated the code.
