### ISSUE TITLE
Indicate that other client has muted me

### ISSUE THREAD

**Issue by corrados** [corrados/jamulus#257]
Each client can have its own audio mix. So you can be muted by other clients and do not get the information about that. So I will introduce an indicator above each fader which shows if the other client has muted myself.

**Comment by corrados** [comment]
It is implemented on master -> closed.

**Comment by corrados** [comment]
This is how it looks like now:
![grafik](https://user-images.githubusercontent.com/46655886/82599907-566f3e80-9bad-11ea-87f7-74477ef7b5e1.png)

**Comment by streaps** [comment]
Useful feature, but UI-wise it's weird and unclear what it means. You draw a red circle spanning two channels, which resembles my impression that I don't know if it belongs to the right or left channel.

I don't have a good idea how to improve it (yet). My first intuition is to put it below the participants name.
Above the name: my local controls
Below the name: remote status / indicators

**Comment by corrados** [comment]
Yes, I had the same impression as you that it is hard to identify the fader to which the icon belongs to. I have already changed that in the code that it is more centered. Now it is clear to which fader it belongs to.

**Comment by trebmuh** [comment]
> My first intuition is to put it below the participants name.

I thought exactly the same.

**Comment by corrados** [comment]
> > My first intuition is to put it below the participants name.

> I thought exactly the same.

The problem is that it takes extra vertical space.

I will start with this implementation for the next release:
![grafik](https://user-images.githubusercontent.com/46655886/82635618-da064b00-9c00-11ea-990b-ac18afd9bc3b.png)
As you can see, the indicator has moved towards the middle.

If everybody is unhappy, this can easily be changed in upcoming releases then.

**Comment by streaps** [comment]
This is better, but I'm still unhappy with the placement.

I don't buy the extra space reason. Haven't Google, Apple and Facebook taught us that wasting a lot of space is good design? 😂

More seriously: I don't think these few pixels are really a problem and can be saved somewhere else. The Pan knob is huge. It could be smaller or the word Pan could be put on the knob or completely removed (there is no descriptive word for the volume fader). The rectangle with the name, image, flag and bold border seems to waste some space. There is also extra horizontal space, if the participant's name is longer than a few characters. The elements are also not aligned in any way pleasing to the eye.

My proposal:
- put the icon below the name.
- remove the light grey border and use a vertical line like between "Eingang" and "Pan / Mitte"
- make the border around the name thinner with sharp instead rounded corners.
- put the word "pan" on the knob

I think there are a lot of smaller UI improvements that could be done, but that could be discussed in another issue.

**Comment by corrados** [comment]
I think we should discuss these things in this Issue instead: https://github.com/corrados/jamulus/issues/73

**Comment by corrados** [comment]
This is how it looks like if two bands are on the Central Server and all of them set to solo to hear only their band mates:
![grafik](https://user-images.githubusercontent.com/46655886/82941792-44b7dd80-9f97-11ea-9fff-ea00e4f9285c.png)
I used to do that with my band, too. But nowadays we don't do that since we do not want to disturb the other musicians. We now play on a private server.
But for this situation the new indicators are very useful.

**Comment by trebmuh** [comment]
@corrados are those rotative knob supposed to be displayed on a GIT version? (built from 8bf87a3 here)
I only got this:
![jamulus](https://user-images.githubusercontent.com/8705846/82944542-b3973580-9f9b-11ea-9732-ccba14bd2ed1.png)

**Comment by corrados** [comment]
The server version must be >= 3.5.4 (try out the Central Server) and you have to use Stereo (right now it seems you have Mono according to your screen shot).

**Comment by trebmuh** [comment]
OK thanks for the explanation.
