### ISSUE TITLE
When Jamulus Server window is minimized, overall delay rapidly grows to large value

### ISSUE THREAD

**Issue by Skeezixes** [corrados/jamulus#264]
With my server running on MacOS 10.15.4, client running on the same machine, the overall delay is ~25 ms.

When the Jamulus Server window is minimized, the overall delay rapidly (over about 30 seconds) increases from ~25ms to ~80ms,  occasionally hitting > 500ms. 

When the window is maximized again, the overall delay returns to ~25ms.

**Comment by Skeezixes** [comment]
Never mind. I could not verify this just now.

**Comment by Skeezixes** [comment]
With my server running on MacOS 10.15.4, client running on the same machine, the overall delay is ~25 ms, sometimes as low as 19 ms. However, I think have observed two occasions where the overall delay rapidly increases:

1. When the Jamulus Server window is minimized (worst case). It increases from ~25 ms to ~80 ms,  occasionally hitting > 500ms. If the window is restored and Jamulus has focus, the overall delay drifts back to ~25 ms. 

2. I THINK it also happens when the Jamulus Server (or other Jamulus windows?) does not have focus. In this case the increase doesn't seem to be as great or as rapid, but still occurs. The overall delay may be ~ 50 ms. If Jamulus is again given focus, the overall delay goes back to ~25 ms. 

I'm sure of the conditions of the first case, less sure of the second.

**Comment by corrados** [comment]
I guess you hit the same problem as described here: https://github.com/corrados/jamulus/issues/23
That issue is currently worked on.

**Comment by Snayler** [comment]
I was about to open another issue, but maybe it's better to leave it here, since it looks related

I've recently noticed there is a lag spike (with sound interruption) once I minimize the server screen on Windows. This might have something to do with the way Windows operates, so maybe not a Jamulus issue.

The ping time returns to normal after a few milliseconds, it's just when the window is minimizing that the spike occurs.

**Comment by corrados** [comment]
> The ping time returns to normal after a few milliseconds, it's just when the window is minimizing that the spike occurs.

Maybe it has to do with the window animations when minimized. Can you switch off the Windows window animations and try again?

**Comment by corrados** [comment]
@Skeezixes Are you able to compile the code? In the Git master we have a fix for https://github.com/corrados/jamulus/issues/23 which maybe also fixes the issue you reported.

**Comment by Snayler** [comment]
> Maybe it has to do with the window animations when minimized. Can you switch off the Windows window animations and try again?

It still does it, even with animations disabled.

**Comment by Skeezixes** [comment]
No sorry, I am not.

**Comment by corrados** [comment]
@Skeezixes Jamulus version 3.5.6 is released now. Could you please try if that new version fixes your issue and report back here?

**Comment by corrados** [comment]
@AronVietti I guess that this problem is also solved with your code (see https://github.com/corrados/jamulus/issues/23)? Do you agree?

**Comment by AronVietti** [comment]
@corrados I was just able to reproduce it with an older version, but not the latests. So I believe it also fixed this issue, which was very similiar.

**Comment by corrados** [comment]
Thank you for the testing. -> closed
