### ISSUE TITLE
A server in the same NAT region as the client is not visible in the server list

### ISSUE THREAD

**Issue by gilgongo** [corrados/jamulus#27]
_This issue has been migrated from Sourceforge. Created: 2013-08-24_

If the Jamulus server and client are in the same local network using local IP addresses assigned by a usual router (using NAT), the server does not show up in the server list.

> Gronaz - 2014-03-18  
> Some usual routers may not allow connections from within an IP in the private lan to another IP in the lan via the router's wan IP.
> 
> Although, I first didn't notice this "server-not-visible" behaviour for me. Once the server upgraded to 3.3.4, I had a need to run the server with the GUI and then I couldn't see the server in my same-lan client's list.
> As I kept the 3.3.3 binary I could test it: same thing, not visible when ran with GUI.
> Whatever, for both 3.3.3 and 3.3.4, whith the setting in the client "Central server address" unchecked and the field below filled with a reference to the server's lan IP (/etc/hosts entry for me) the client can connect to the server, even when the list is empty.
> When the reference is to the server's wan ip, I simply can't connect, which seems to be related to the first sentence in this post.
> 
> So this bug is only half-a-bug: when server is ran with GUI.
> The situation when the wan ip is used, it doesn't seem to be a bug in Jamulus.

**Comment by corrados** [comment]
@pljones: Hi Peter, if you have time, could you please take a look at this issue? A lot of people have problems with that bug and we have a lot of messages in the Discussion forum about it.
For running client/server on the same PC, I have written special code to support it: https://github.com/corrados/jamulus/blob/master/src/serverlist.cpp#L419
But if we are on the local network but not on the same PC, the server which registers to the server has to tell the Central Server his IP address under which he can be reached in the local network and this IP address has to be substituted in the Server List IP address protocol message for the client in the same network requesting the network list. Is this something you could do?

**Comment by pljones** [comment]
@corrados: Hi, yes - I'll take a look.

The clients as the central server for the server list directly...  Yes, that's a problem.  So the local server needs to pass a _string_ that should be used in place of the hostname and port number (internal network management can be complicated, so I think that would be simpler).  Then the client uses that string where the address would go.

**Comment by corrados** [comment]
You really think a string is needed? I thought that we simply find out the local IP address of the server PC like 192.168.x.x and send this to the Central Server. The local port number is already sent to the Central Server. Do you think it is not possible to query that local IP address from the OS?

Line 414 makes sure that the empty message is not sent to the Central Server (the Central Server is always the very first entry in the list). We need the empty message to be transmit to open the firewall and setup the NAT for the clients IP address so that the client is able to send UDP packets to that server.

**Comment by corrados** [comment]
Multiple instances are no problem since the local port is already known at the Central Server.

**Comment by pljones** [comment]
IP would work in simple domestic cases, which probably covers 100% of actual usage :).

However, you could have a configuration where "outwards" facing servers (i.e. connected to the internet) are in one subnet (192.168.1.x or 10.0.1.x), "internal" servers are on another (192.168.2.x, 10.0.2.x) and "private" (end user) machines are on a third (192.168.3.x, 10.0.3.x).  "private" users would not be allowed directly to the "outwards" facing servers, only to the "internal" servers (where they exposed services).

In that set up, you'll have bridging and routing rules much like going out through a WAN router.  Using a hostname allows internal configuration to say "on the private network 'jambox.lan' means 192.168.2.x", and in the routing there, there would be a forwarding rule for the port to the jamulus host on 192.168.3.x.  If the server there just returned its own IP to the client, it wouldn't work.

As I say, I'm probably over-complicating it...

**Comment by pljones** [comment]
> Line 414 makes sure that the empty message is not sent to the Central Server (the Central Server is always the very first entry in the list).

Ah, I thought that was probably it.  Thanks for the confirmation.

**Comment by corrados** [comment]
Lets keep it simple. We just have to cover most usecases which we do with a simple IP address.

**Comment by pljones** [comment]
OK, so as a client, "if my external IP address == <some server in the list>'s external IP address", substitute <some server in the list>'s internal IP address, as it supplied along with its internal port.

**Comment by corrados** [comment]
This solution sound feasable: https://stackoverflow.com/questions/12927273/how-to-get-local-ip-address-of-a-computer-using-qt

**Comment by corrados** [comment]
No, that should not be done at the client. It should be done in the server. The correct place would be the CentralServerQueryServerList().

**Comment by corrados** [comment]
I fear we have to change the register server protocol so that it includes not only the local port but also the local IP address.

**Comment by corrados** [comment]
I guess right now if a client is in the same local network, this client runs in the condition: "if ( vecServerInfo[iIdx].HostAddr.InetAddr == InetAddr.InetAddr )". But then the substitution of "localhost" is not correct. The substitution in that case must be the local IP address.
I guess we can distinguish the actual PC where the server is running on or another PC in the same local network by looking at the port. So if the IP address is the same (see above if condition) but the port is different, we should know that this is a PC in the same local network.

**Comment by corrados** [comment]
Either we introduce a new message, or we could "abuse" the "topic" string to insert the local IP address. Since the "topic" was never used so far. Maybe we can simply rename the protocol. Then we would be compatibel to old versions (since the topic is simply empty, easy to check). See https://github.com/corrados/jamulus/blob/master/src/protocol.cpp#L213.

**Comment by pljones** [comment]
Maybe change topic into a len/value subfield inside where topic was, for further abuse in future..?

**Comment by pljones** [comment]
QUdpSocket::localAddress _may_ work to supply the Central Server with the server's local UDP socket address.  Whether it's filled in or null for UDP wasn't clear from the QT docs (sparing, as ever, with detailed examples).

**Comment by pljones** [comment]
> I guess right now if a client is in the same local network, this client runs in the condition: "if ( vecServerInfo[iIdx].HostAddr.InetAddr == InetAddr.InetAddr )".

This should be okay - the match on external IP is correct.

> But then the substitution of "localhost" is not correct. The substitution in that case must be the local IP address.

This can be the identifier used by the client to refer to the value in the topic.

> I guess we can distinguish the actual PC where the server is running on or another PC in the same local network by looking at the port. So if the IP address is the same (see above if condition) but the port is different, we should know that this is a PC in the same local network.

Hm.  I expose one port externally but run on a different port internally (so the default port gets forwarded to a different internal port).  This is sort of why I though "give up, make it a string"...

**Comment by corrados** [comment]
The Central Server server list should store the port number of the UDP packets arrived from the other server. If that port does not match the current received port in CentralServerQueryServerList(), we know that it is not the server PC. This is the only information we need actually.

**Comment by corrados** [comment]
> Maybe change topic into a len/value subfield inside where topic was, for further abuse in future..?

No, if we decide to use it for the IP number, we should not change that in the future.

**Comment by corrados** [comment]
> Hm. I wanted to expose one port externally but run on a different port internally (so the default port gets forwarded to a different internal port). 

I do not understand the issue here. If the PC in the local network knows the local port number of the server and the local IP address, it can connect. We have to tell both numbers (IP and port) when the server list is queried.

**Comment by pljones** [comment]
`2 bytes number n` - the old clients will evaluate the list based on this, so for backwards compatibility, that part must remain.

`n bytes UTF-8 string topic` - if the value here is simply unused, it can be used for the CHostAddr field.

**Comment by pljones** [comment]
> 
> 
> > Hm. I wanted to expose one port externally but run on a different port internally (so the default port gets forwarded to a different internal port).
> 
> I do not understand the issue here. If the PC in the local network knows the local port number of the server and the local IP address, it can connect. We have to tell both numbers (IP and port) when the server list is queried.

If I tell the central server "my port number is 22123" and my port forwarding rules forward that on port 50123, then a local client needs 50123 but a remote client needs 22123.

Currently a local client doesn't see 22123 at all - they see nothing - so they have to know the port.

If we start telling the client the local address, the local port should also be supplied and it can differ.

**Comment by pljones** [comment]
Old clients will also do this:
https://github.com/corrados/jamulus/blob/master/src/protocol.cpp#L2217

Probably not an issue...

**Comment by corrados** [comment]
> 
> 
>         Hm. I wanted to expose one port externally but run on a different port internally (so the default port gets forwarded to a different internal port).
> 
>     I do not understand the issue here. If the PC in the local network knows the local port number of the server and the local IP address, it can connect. We have to tell both numbers (IP and port) when the server list is queried.
> 
> If I tell the central server "my port number is 22123" and my port forwarding rules forward that on port 50123, then a local client needs 50123 but a remote client needs 22123.
> 
> Currently a local client doesn't see 22123 at all - they see nothing - so they have to know the port.
> 
> If we start telling the client the local address, the local port should also be supplied and it can differ.

Sorry, I still do not understand the issue. At least in my local network, if I start a server with port 22123 on a PC with IP=192.168.178.22 in my local network, then I can connect to this server from any other PC in my local network by typing in 192.168.178.22:22123 in the Server List dialog of Jamulus and it connects just fine. Internally, i.e. in the local network, there should be no port translation. Just the port may be translated if you are outside the local (NAT) network.

**Comment by corrados** [comment]
> 2 bytes number n - the old clients will evaluate the list based on this, so for backwards compatibility, that part must remain.
> 
> n bytes UTF-8 string topic - if the value here is simply unused, it can be used for the CHostAddr field.

We should use these two fields as they are intended. I.e. the first element shows the length of the string and in the "topic" string field we write, e.g., "192.168.178.22". There should be toString and fromString functions in the Qt IP address class.

**Comment by pljones** [comment]
Could make it shorter using hex ("C0A8AC16" is eight characters, rather than 14).

**Comment by corrados** [comment]
Sounds good, go ahead. Have you already done some coding? Any success on finding the local IP address?

**Comment by pljones** [comment]
Getting the local IP address of the socket connecting to an internet server works.  It's good enough for that "100% of all known use cases".

I _had_ the protocol messages exchanging... suddenly they're not.  I'll look into that later on.  But this could be done very soon.

One thing is, I'll have to allow two *servers* on the same IP with different local ports (i.e. I'm running my own local test "central server" and registering another slave server on the same IP), which means a slight change to "have I seen this server before" in the server list processing to take port into account.

**Comment by pljones** [comment]
OK, here's where we are:

Start up the "central server"
```
peter@fs-peter:~/git/Jamulus-wip$ ./Jamulus -s -n -p 55050 -u 2 --centralserver localhost
- server mode chosen
- no GUI mode chosen
- selected port number: 55050
- maximum number of channels: 2
- central server: localhost
CServerListManager lives!
iNPortNum  55050
sNCentServAddr  "localhost"
strServerInfo  ""
iNumChannels  2
bNCentServPingServerInList  false
local IPv4 address for Internet connectivity is QHostAddress("192.168.1.19")
add 0:  "{CServerInfo: [ HostAddr: 0.0.0.0:0, LHostAddr: 192.168.1.19:55050, {CServerCoreInfo: [ iLocalPortNumber: 55050, strName: , eCountry: 224, strCity: , iMaxNumClients: 2, bPermanentOnline: 1 ]} ]}"
 *** Jamulus, Version 3.4.6git
 *** Internet Jam Session Software
 *** Under the GNU General Public License (GPL)
```
Start up the test server, with the test central server
```
peter@fs-peter:~/git/Jamulus-wip$ ./Jamulus -s -n -p 55150 -u 2 --centralserver 192.168.1.19:55050
- server mode chosen
- no GUI mode chosen
- selected port number: 55150
- maximum number of channels: 2
- central server: 192.168.1.19:55050
CServerListManager lives!
iNPortNum  55150
sNCentServAddr  "192.168.1.19:55050"
strServerInfo  ""
iNumChannels  2
bNCentServPingServerInList  false
local IPv4 address for Internet connectivity is QHostAddress("192.168.1.19")
add 0:  "{CServerInfo: [ HostAddr: 0.0.0.0:0, LHostAddr: 192.168.1.19:55150, {CServerCoreInfo: [ iLocalPortNumber: 55150, strName: , eCountry: 224, strCity: , iMaxNumClients: 2, bPermanentOnline: 0 ]} ]}"
CServerListManager::SlaveServerRegisterServer
CProtocol::CreateCLRegisterServerMes : InetAddr  "192.168.1.19:55050" , LInetAddr  "192.168.1.19:55150" ,  "{CServerCoreInfo: [ iLocalPortNumber: 55150, strName: , eCountry: 224, strCity: , iMaxNumClients: 2, bPermanentOnline: 0 ]}"
 *** Jamulus, Version 3.4.6git
 *** Internet Jam Session Software
 *** Under the GNU General Public License (GPL)
```
Test central server protocol layer evaluates the registration:
```
CProtocol::EvaluateCLRegisterServerMes
CProtocol::EvaluateCLRegisterServerMes : InetAddr  "192.168.1.19:55150" , LInetAddr  "192.168.1.19:0" ,  "{CServerCoreInfo: [ iLocalPortNumber: 55150, strName: , eCountry: 224, strCity: , iMaxNumClients: 2, bPermanentOnline: 0 ]}"
```
That's logged just after
```
    emit CLRegisterServerReceived ( InetAddr, LInetAddr, RecServerInfo );
```
Eventually that gets to `CServerListManager::CentralServerRegisterServer` where `if ( ServerList[iIdx].HostAddr == InetAddr )` means my test server should get added to the list as it's not the zeroth element.  OK, I was wrong above :).

**Comment by pljones** [comment]
Bit more debugging trace...
```
CProtocol::EvaluateCLRegisterServerMes
CServerListManager::CentralServerRegisterServer bIsCentralServer true bEnabled true
Server InetAddr "192.168.1.19:55150" being added to list
CProtocol::EvaluateCLRegisterServerMes : InetAddr  "192.168.1.19:55150" , LInetAddr  "192.168.1.19:0" ,  "{CServerCoreInfo: [ iLocalPortNumber: 55150, strName: , eCountry: 224, strCity: , iMaxNumClients: 2, bPermanentOnline: 0 ]}"
```
So that works for adding the details (I'll fix the check earlier on to also check `iLocalPortNumber`).

**Comment by pljones** [comment]
OK, I'll just clean up what I have now and raise a pull request.  I'm running a "Central" server and a "Slave" server on my usual server box, with a client on that same box (three instances sharing the IP address, different ports, different roles) and another client on another box.

The central server is acting okay, claims to be central server, registers slave servers and distributes the list of servers to querying clients, both on the same IP and others (within the LAN).

I'll do some quick backwards compatibility checks, too...  This shouldn't break either existing servers or existing clients.

**Comment by pljones** [comment]
PR raised.  It could do with some WAN testing (local testing seems fine but nothing would use the external address anyway).

**Comment by corrados** [comment]
Ok, thank you. I'll review your code soon.

**Comment by gilgongo** [comment]
Just tested this with the 3.4.7git build and I can now see my server in the list, but only if I use `--showallservers ` What's the reason I can't see it otherwise? 

(Also, why are only some of the servers shown with ping times, and some are bold text?)

**Comment by corrados** [comment]
The code is in the Git-repo on master now: https://github.com/corrados/jamulus/pull/48
Thank you pljones once again for your contribution.
