### ISSUE TITLE
Windows support without ASIO

### ISSUE THREAD

**Issue by kersam84** [corrados/jamulus#271]
I was wondering if there are any plans to support the native Windows APIs (WASAPI) for capturing and playback, without going through ASIO.
I think that would lower the entry barrier, since it would not require the installation of additional software. In addition, it would also avoid some problems caused by the ASIO4All driver, when the users hardware is not supported.

**Comment by corrados** [comment]
We have an Issue about portaudio: https://github.com/corrados/jamulus/issues/116
If that is implemented, WASAPI should be supported, too.

**Comment by corrados** [comment]
To avoid having multiple Issue about the same topic, I will close this one. Please use this Issue: https://github.com/corrados/jamulus/issues/116 for the discussion on that topic.
