### ISSUE TITLE
Minimized Settings window cannot be made to reappear

### ISSUE THREAD

**Issue by Skeezixes** [corrados/jamulus#272]
Click on Settings checkbox and the Settings window appears. Click on the yellow/orange button on the Settings window to minimize that window. The Settings window disappears. It has now disappeared forever.

The Settings checkbox is still checked, but if you click on the Jamulus icon in the Dock (that shows running apps), you cannot make it reappear. You see only the Jamulus windows that are already open. Unchecking the Settings checkbox and then checking it again has no effect either. The only way you will see that Settings window again is if you quit Jamulus and restart it.

**Comment by corrados** [comment]
Are you on a Mac?

**Comment by Skeezixes** [comment]
Yes. Sorry I didn't mention that before.

**Comment by corrados** [comment]
> if you click on the Jamulus icon in the Dock (that shows running apps), you cannot make it reappear

I had such an issue with other applications on the Mac. Can you please left-mouse-click on the icon in the Dock and select something like "show all windows"? That did the trick for me when I had this problem with other Mac applications.

**Comment by Skeezixes** [comment]
Oh, Bingo! I guess I’ve learned something.  I never knew you could do that.
So—not a bug. A feature.

**Comment by corrados** [comment]
Ok, great that it works for you. I'll close this Issue now.
