### ISSUE TITLE
Manual.md needs to be updated

### ISSUE THREAD

**Issue by corrados** [corrados/jamulus#274]
The Jamulus client manual at https://github.com/corrados/jamulus/blob/master/src/res/homepage/manual.md needs updates:

- There were several language fixes in the What's This help texts which are included in the software which should also be applied to this manual (see, e.g., https://github.com/corrados/jamulus/commit/e2e0bb4cf561e52bfeeb4a1ce1ce647fa7869745, https://github.com/corrados/jamulus/commit/06d804b96a19fefcf0fad45ab9f75c4fcde3dc6e, https://github.com/corrados/jamulus/commit/0a9e188c964d1583decfda26791524bcdc690fa0, https://github.com/corrados/jamulus/commit/720b2de644fe9b94201073faa747869bf7af3a8a, https://github.com/corrados/jamulus/commit/4ec464614722cb65624e6472adfdb1f1c1641e29, https://github.com/corrados/jamulus/commit/e2d46b5e48531622718f505cb94a3a07637d836c and https://github.com/corrados/jamulus/commit/642f2f06efe073805012d38b273bb6351d5a66c2).
- There were several new features added (e.g. the new panning) which have to be considered.
- It would be nice to have consistent screen shots.

Any volunteers?

**Comment by gilgongo** [comment]
I'm assuming the new features that need explanation as of 3.5.4 are:

1. Panning
1. Indicator that another client has muted me
1. Genre-based central server

Is that right? If so, I'll see if I can add those, add the language fixes, and update all the screenshots.

**Comment by corrados** [comment]
Yes, these are basically the new features which should be added.
Thanks.

**Comment by gilgongo** [comment]
Couple of questions about the genre-based central servers:

1. How does the "custom" genre work?

2. Can you check that the note [I've put here](https://github.com/corrados/jamulus/wiki/Command-Line-Options#notes) for `-e` is correct?  

BTW I assume that if a server is configured without `-e` it is a private server. But what does "default" mean in this case for `-e`? Can I set it without a value?

**Comment by WolfganP** [comment]
Talking about documentation, I think one of the concepts I struggled more was the audio paths clients/server flow and the controls interaction (ie Mute, Solo on faders section and myself)

I was thinking in augmenting https://github.com/corrados/jamulus/wiki/Getting-Started with a diagram like https://github.com/corrados/jamulus/issues/148#issuecomment-629679659 (by @matzix) but is probably better to keep that page simple as it is and expand to a more technical/advanced one to explain with more details?

What do you guys think?

**Comment by gilgongo** [comment]
I did in fact play about with a conceptual diagram as part of the never-ending quest to clarify the meaning of "mute" and "mute myself". 

![mute](https://user-images.githubusercontent.com/4561747/82755967-0a034900-9dcf-11ea-916d-78b9ab6c3bda.gif)

 But I didn't think it would really help. It's so easy to confuse people even more with diagrams I think.

**Comment by corrados** [comment]
> How does the "custom" genre work?

You specify a custom URL or IP address in the Settings dialog of the Central Server you want to use. So if you e.g. want to use a server list which is hosted at jamulus.example.com you set the Custom Central Server Address edit box to "jamulus.example.com" and in the Connect Dialog on the top left drop down list you select Custom.

> Can you check that the note I've put here for -e is correct?

Looks ok to me.

**Comment by gilgongo** [comment]
Oh OK . So that's how the client selects a different central server. I expect some people might wonder what it means in the context of genres though, so I hope we can explain it clearly enough. Something like this?

_"Your can set up your own list of servers (that is, a 'custom central server'). You need to tell other server operators to register their servers with your custom server, and then tell those server operators to tell their users to set their clients to your central server so that those clients can see their servers listed by your custom server."_ 

:-)

Another question: What's the difference between "Default" and "All Genres"?

And talking of which, I assume that if a server is configured without `-e` it is a private server. But what does "default" mean in this case? Can I set `-e` without a value to have it use the default?

**Comment by corrados** [comment]
> Something like this?

Your text is correct but really sounds a bit funny :-). Maybe a picture helps...

> What's the difference between "Default" and "All Genres"?

That's caused by compatibility issues. Since we are now using genre based servers, a "north america" server seems not to fit in. Since the server operators which have registered to the two old servers did not have a genre in mind, I decided to use a name which includes all genres.

> And talking of which, I assume that if a server is configured without -e it is a private server. But what does "default" mean in this case? Can I set -e without a value to have it use the default?

If you have a private server, you do not need any Default central server since you do not register anyway. So you are completely independent of any server list but the clients must connect to your server by using an IP address or DynDNS URL.

**Comment by Matzix** [comment]
>  a diagram like [#148 (comment)](https://github.com/corrados/jamulus/issues/148#issuecomment-629679659) (by @Matzix)

What are best practices to draw a diagram, such that it can be used in documentation and also be edited by others (graphic tools, file formats, ...)?

**Comment by WolfganP** [comment]
> 
> 
> > a diagram like [#148 (comment)](https://github.com/corrados/jamulus/issues/148#issuecomment-629679659) (by @Matzix)
> 
> What are best practices to draw a diagram, such that it can be used in documentation and also be edited by others (graphic tools, file formats, ...)?

No idea if there's any preferred diagram collaborative tool, but I prefer it be some (accessible, free, easy to use, ...) tool like LibreOffice Draw or some online solution like Draw.io

**Comment by gilgongo** [comment]
@Matzix I used some free diagramming thing. It was a bit fiddly though, so not sure if it's that good really. [See this comment](https://github.com/corrados/jamulus/issues/64#issuecomment-613875648).

**Comment by gilgongo** [comment]
> but really sounds a bit funny

Hehe - yes, I wasn't taking it very seriously, sorry :-)

The concept of the custom server is going to be hard to document without people getting confused I think. It will be easier if we can give some example use cases for it. The only one I know of is for something like a virtual music festival, so you can collect a bunch of participating servers and then advertise for clients to connect to that central server for the duration of that event. Are there others?

**Comment by WolfganP** [comment]
Thx @gilgongo I didn't find https://github.com/corrados/jamulus/issues/64 before, that will be a better place to collaborate on visual diagrams

**Comment by ignotus666** [comment]
I've applied the corrections to the manual.md file, but as I said in the pull request, I'm not entirely confident about my technical knowledge to update it with the new features.

**Comment by gilgongo** [comment]
I'm having a look at updating manual.md to update it with the new features and screenshots. There are a number of tweaks that are needed I think.

**Comment by corrados** [comment]
OK, great. But please wait before you start until I have merged the pull request.

**Comment by corrados** [comment]
> The only one I know of is for something like a virtual music festival, so you can collect a bunch of participating servers and then advertise for clients to connect to that central server for the duration of that event. Are there others?

You are talking about, e.g., the word jam event on Facebook, right? What I have seen was a list of servers specifically for choir sessions. I make sense not to put them in the official list to prevent other clients to enter a rehearsal.

**Comment by corrados** [comment]
BTW: I have just merged the pull request.

**Comment by gilgongo** [comment]
Sorry for delay on this - just trying to work out how to use git. I tried Git Desktop (on Win and Mac) and for some reason when I clone the repo it gives me an old version (eg manual.md has the server setup instructions in it). So I've abandoned that.

To put me out of my misery, what do I need to do on the command line?

```
git clone

git checkout -b issue274

[do some edits]

git commit -a -m 'Some comment here'
```

And then I can do the pull request in the web interface? Not sure.

**Comment by ignotus666** [comment]
Are you forking corrados/jamulus? You need to do that first, which will create your own Jamulus repository in your git account, and then you clone that to your computer with `git clone https://github.com/gilgongo/jamulus.git`. Make your edits, upload them to the Jamulus fork in your repository, and then from there you make the pull request.

**Comment by gilgongo** [comment]
@ignotus666 OK cloning creates a fork, I see. So I need to delete the gilgongo/jamulus repo, then `git clone https://github.com/gilgongo/jamulus.git`, make the changes, and then what? `git commit`?

**Comment by ignotus666** [comment]
No; delete gilgongo/jamulus, come back to corrados/jamulus and fork it - this will create an updated fork of jamulus (gilgongo/jamulus). If you delete it and try to clone it with `git clone https://github.com/gilgongo/jamulus.git` it won't work because there'll be nothing to clone.

the `git clone` command will create a copy of the jamulus files on your PC. You can edit them there, and when ready, I'm not sure about the command, but what I do is just go to my repository (in your case gilgongo/jamulus), go to the directory where the edited files are, and click on "upload files". Just select your edited files and they'll be uploaded to your fork. Then, you click on "make a new pull request" (or something to that effect). Give your pull request a name and optionally a description and that's it.

**Comment by gilgongo** [comment]
Sorry, I meant `git clone https://github.com/corrados/jamulus.git` after I'd deleted `gilgongo/jamulus` 

OK I didn't see the "upload files" button. I can use that for the screenshots then so I don't have to use git. 

Thanks - I'll give that a go.

**Comment by gilgongo** [comment]
OK I've done that PR now.

**Comment by corrados** [comment]
Great, thank you. I just merged your changes.

**Comment by ignotus666** [comment]
I suppose these changes now need to be reflected in the software itself and the translations. I can volunteer to do that and have a go at properly revising the text while I'm at it, but it might take some time because I'm pretty busy with work right now.

Ok, so I just found out how to update the .ts files without editing them one by one, using lupdate... I've been making things much harder for myself than they needed to be. Feeling pretty stupid.

**Comment by gilgongo** [comment]
I made quite a large number of minor changes in manual.md, so if the diffs are confusing, the main things are:

Replaced the first section of the old description of the Connection Window description of genre based servers.

Added "Mute Myself button" section.

In "Server audio mixer" section, added pan control description and updated Mute and Solo button descriptions.

Replaced old "Central Server" section with new "Custom central server address" description.

BTW there are some typos I'd like to fix, and I'd like to go around again on the screenshots at some point so I may do another PR in the next few days maybe.

**Comment by ignotus666** [comment]
Ok, I'll wait for that to happen and will then reflect your changes in the source files where appropriate and carry out a more in-depth revision of the rest of the texts.

**Comment by corrados** [comment]
I fear all the "+ APP_NAME +" in the translation code will make problems now. Maybe these should be reduced. But this will cause a lot of effort for all the translations...

**Comment by ignotus666** [comment]
What about getting rid of them altogether and just replacing them with "Jamulus"?

**Comment by corrados** [comment]
My preferred solution would be to exchange this by something more general. E.g., instead of "_by using the Jamulus software, ..._" one could write "_by using this app, ..._".

**Comment by ignotus666** [comment]
Or "_by using Jamulus ..._".

**Comment by corrados** [comment]
No, this is not what I want. I do not want to have the name "Jamulus" in the help files. That is the reason I have chosen "this app" in my example.

**Comment by ignotus666** [comment]
Ok, I understand.
I've started working on a revision of the texts (very early stages still). When it's done it would be good for Volker and maybe others to have a look at it to suggest possible changes/corrections. Should I just do a PR or what would be the best way?

OTOH, I see obsolete segments can be removed with lupdate, but I think it might be better to leave them until after the translations are done, as translators can reuse large chunks of the obsolete translations.

**Comment by corrados** [comment]
Yes, you should leave the vanished translation texts.

I guess the translators will have a lot of work when you are done. I hope they are willing to spend that time.

> Should I just do a PR or what would be the best way?

Yes, just do a PR.

**Comment by corrados** [comment]
Since my initial request of this Issue is already been worked on, I will close this Issue now.
Of course, if we add new features to Jamulus, the manual has to be adapted again. But this is not the scope of this issue.
