### ISSUE TITLE
3.5.4 Custom Central Server does not seem to work

### ISSUE THREAD

**Issue by brynalf** [corrados/jamulus#280]
Just updated to 3.5.4. Custom Central Server does not seem to work.

**Comment by corrados** [comment]
It works for me. Can you please give some more information what exactly does not work? Which OS?

**Comment by brynalf** [comment]
Win10.
1) I enter a Central Server Address in the client settings
2) I press connect
3) I only see the servers at the Default Central Server

**Comment by corrados** [comment]
On the top left of the Connection Dialog (that dialog which opens when you press the Connect button on the main window) you find a dropdown list. In that list you must choose "Custom". Then you should see your list.

**Comment by brynalf** [comment]
Will install 3.5.4 again and come back.

**Comment by brynalf** [comment]
Yes. It works also for me. 
The problem was on my side.
My virus protection blocked my servers.
Have sorted that.
Thanks for the fast response and sorry for the inconvenience.
This software is a lifesaver for real.
