### ISSUE TITLE
Weird PAN knob on 3.5.4

### ISSUE THREAD

**Issue by Snayler** [corrados/jamulus#281]
The PAN knob on 3.5.4 looks weird under Windows.
![image](https://user-images.githubusercontent.com/11491485/82755508-d96de000-9dcb-11ea-912d-ecdeed917a8d.png)

**Comment by corrados** [comment]
This is the standard Qt design for the QDial control, see: https://doc.qt.io/archives/qt-4.8/qdial.html#details

**Comment by Snayler** [comment]
Oh, you're right. I was just seeing the 2 black lines, which would be weird. Now I see there's also a white line, giving the 3D effect. Closing

**Comment by corrados** [comment]
That could be done but I think it will be better to fix the Windows installer so that you get the new design (as I use in my screen shots). There is already a pull request for this: https://github.com/corrados/jamulus/pull/184
I will work on this for the next Jamulus release.

**Comment by Snayler** [comment]
That knob looks great! Thanks.

**Comment by Matzix** [comment]
Is it possible to change the mouse action, such that the knop position can be adjusted via horizontal movements only?

**Comment by Snayler** [comment]
@Matzix I find it useful to use the mousewheel (or the touchpad equivalent gesture) for fine tuning.

**Comment by corrados** [comment]
@Snayler I just released a new Jamulus version 3.5.6. Now you should see the new Pan knob design.
