### ISSUE TITLE
Jamulus as VST/AU plugin

### ISSUE THREAD

**Issue by mk030166** [corrados/jamulus#285]
Will it be possible in the near future to have Jamulus as a VST / AU plugin?

**Comment by corrados** [comment]
This is a duplicate, see https://github.com/corrados/jamulus/issues/82

**Comment by corrados** [comment]
Since this is a duplicate, I would like to close this issue. Is this ok for you?

**Comment by mk030166** [comment]
Yes, it is ok for me. Thank you and sorry for my duplicate.
I hope someone could resolve the situation.
Bye
Marco

Il mar 26 mag 2020, 11:10 Volker Fischer <notifications@github.com> ha
scritto:
