### ISSUE TITLE
QT-Cocoa issue w server on MacOs

### ISSUE THREAD

**Issue by ABeerten** [corrados/jamulus#289]
Serverstart on MacOs 1.15.4 & Jamulus 3.5.4 gives ''This application failed to start because it could not find or load the Qt platform plugin "cocoa" in "".'

**Comment by corrados** [comment]
I have seen that there is already a discussion going on on Facebook. Here is the link: https://www.facebook.com/groups/619274602254947/permalink/665159894333084/

**Comment by ABeerten** [comment]
My issue w cocoa was solved with the 3.5.5-release. All works fine now. Thx Jamulus
