### ISSUE TITLE
Fade-in/fade-out audio on start/stop/reconfiguration

### ISSUE THREAD

**Issue by gilgongo** [corrados/jamulus#29]
_This issue has been migrated from Sourceforge. Created: 2014-03-11_

Implement a fade-in/-out in the sound base class if the audio interface is started/stopped. This avoids clicks in the audio.

**Comment by corrados** [comment]
There is a fade-in supported in the server now on a new client connection.
Using a fad-in/fade-out on start/stop seems not to be necessary since I did not observe audio issues with that. So I will close this issue now.
