### ISSUE TITLE
Sorting of servers in serverlist

### ISSUE THREAD

**Issue by sthenos** [corrados/jamulus#293]
Currently the sorting is defaulted to lowest ping.  This is fine in most cases, but it would be nice if you could sort by something static that doesn't result in the servers moving around when you're trying to click them.   For instance, I would like to be able to sort by alphabetical title or perhaps by location or by number of musicians in a room.    Simple way, I would think is to allow the headings of the serverlist treeview to be sortable, with it defaulting to sort by ping time ascending.

**Comment by corrados** [comment]
If you use --showallservers, you can click on the headers to sort. For the normal mode, turn off "show all musicians" and the filter function should be sufficient. Do you agree?

**Comment by sthenos** [comment]
Very few people use the --showallservers or even know how to use it.  Turning off the "show all musicians" I don't believe solves the initial use case which is the fact that the servers bounce around the list when you open up the serverlist, also the filter is not remembered, I would hope that your sorting preference would be remembered so that everytime you open the serverlist, if I have it sorted by title or location it would remember that setting so I don't need to keep typing something in filter every single time.   Actually same goes for the filter that it remembers the previous filter you had typed.

**Comment by fleutot** [comment]
I too would appreciate what @sthenos describes. I happened to jump in the recording studio of the World Jam Night by mistake because of this (order changed in the middle of my double click).

**Comment by corrados** [comment]
> doesn't result in the servers moving around when you're trying to click them

> I happened to jump in the recording studio of the World Jam Night by mistake because of this (order changed in the middle of my double click).

As I was yesterday on the World Jam I also heard people complaining about this issue. We also had another Issue about this: https://github.com/corrados/jamulus/issues/78

I see the need for a solution here. The proposal by sthenos: "_sort by something static that doesn't result in the servers moving around_" would be one solution. But the users would have to know that they have to click on the table header to get the results stable. Maybe there is another solution to that problem. I have to do some brainstorming...

BTW: What I usually do is that I avoid using the "double click" on the server list table. What I do is to simply select a server and then I press the Connect button on the lower right of the dialog to actually connect to the server. If in between there is an update of the server list, the selection of the server does not change and you are still connecting to the desired server. But as written above with the "click on the header to sort": The user has to know how to operate the list...

**Comment by corrados** [comment]
I think I found a simply solution to the issue. There is a "QWidget::underMouse()" function which returns true if the mouse pointer is over the list. So I would simply stop the update of the list if the mouse cursor is currently over the list trying to double-click a server.

**Comment by corrados** [comment]
I actually really like this solution. Here is a video of the new functionality:
![0Lm3uniCKm](https://user-images.githubusercontent.com/46655886/87880765-9b202600-c9f4-11ea-8e5b-8e2699a60ad1.gif)
You can see that the ping times are updated if the mouse is over the table but the items to not move (i.e. the sorting is disabled). As soon as you move the mouse out of the table area, on the next ping update the sorting is applied and the items change their order. That way you will be able to savely double click on the server you want to connect.

How do you like the new implementation?

**Comment by Snayler** [comment]
Seems perfect to me, I like it.

**Comment by sthenos** [comment]
Looks fantastic Volker!

**Comment by corrados** [comment]
Thanks for your feedback. If you are all happy with the new implementation, then I close this issue now.
