### ISSUE TITLE
Create server recording indicator

### ISSUE THREAD

**Issue by Snayler** [corrados/jamulus#295]
As discussed on #276, it would be useful to have an indicator on the client to let the user know when a server is recording.

**Comment by pljones** [comment]
Picking this up now.

**Comment by pljones** [comment]
Raised #324 - see comments there.

**Comment by Snayler** [comment]
This wasn't implemented yet, was it?

**Comment by corrados** [comment]
No, it wasn't.

**Comment by pljones** [comment]
Yep, sorry I've been busy at work and simply exhausted (I'm a programmer and my brain can't cope...).  I was hoping to get some more done over this weekend, just not had a chance yet.  But this is what I'll be doing next.

**Comment by pljones** [comment]
Yep, getting to this now - #363 done above, #366 with @corrados and I've the next one lined up with the client side changes, so we could be good to go.

**Comment by pljones** [comment]
#366 done and #368 ready now.  All done once that's in.

**Comment by corrados** [comment]
merged -> closed

**Comment by pljones** [comment]
Looks like I'm not clearing the client idea of reccorder state.  I switched from my 3.5.7git server with recording active to a 3.4.5git server - predates recording and can't notify anyway! - and was told recording was active..!

**Comment by corrados** [comment]
I already fixed that in the Git repo. Just make a pull and everything should work as expected :-)
