### ISSUE TITLE
User interface improvements

### ISSUE THREAD

**Issue by JezDruce** [corrados/jamulus#296]
Hi,

When entering a 'room' it would be preferable to have the levels set on a toggle at 50% rather than full up. I mix for the world jam and have to pull everything down hear others.

Also, the ability to group the users to make listening easier. With multiple musicians, I have to pull their levels down one by one if that makes sense?

'My Dev request is this:
To add a personal fold back channel to Jamulus. This would be a button that appears under each player above solo and mute, that allows the user to include that player in their fold back channel. Once they have set the individual slider for each player included in the foldback, they can adjust the foldback group as a whole.
This will be easier than adjusting each player individually.
You will still have the general feed and monitor channel for live performances, but you will also be able to balance your own preferences against it.
For example, vocalists may want to have the keys and/or other vocals dominant over the band for easier pitching and harmonies.
The bass and drums have each other louder to lock in better for the groove. Etc., etc.'

**Comment by Snayler** [comment]
> When entering a 'room' it would be preferable to have the levels set on a toggle at 50% rather than full up. I mix for the world jam and have to pull everything down hear others.

That's already implemented, you just have to go to settings and set the "New Client Level" to the fader value you want.

**Comment by corrados** [comment]
> When entering a 'room' it would be preferable to have the levels set on a toggle at 50% rather than full up.

I just supported this in the newest version of Jamulus 3.5.5: https://github.com/corrados/jamulus/blob/master/ChangeLog#L27
So you set the New Client Level to 50 % and this is applied to unknown musicians which are currently on that server. Of course, if you met them previously, the fader position of that session is stored for them so they are no "new clients" and will not get the New Clients Level applied.

**Comment by corrados** [comment]
> Also, the ability to group the users to make listening easier. With multiple musicians, I have to pull their levels down one by one if that makes sense?

We already have an Issue about this feature request: https://github.com/corrados/jamulus/issues/202

**Comment by JezDruce** [comment]
Hi Volker. Simon set up a group on Facebook as you know and it's been a massive point of contact and social interaction during isolation. It's his birthday on 10th June. Any chance you could join us for a message?On 28 May 2020 20:07, Volker Fischer <notifications@github.com> wrote:

Also, the ability to group the users to make listening easier. With multiple musicians, I have to pull their levels down one by one if that makes sense?

We already have an Issue about this feature request: #202

**Comment by corrados** [comment]
> Any chance you could join us for a message?

Sure, what kind of message do you have in mind?

**Comment by JezDruce** [comment]
Hi Volker,Maybe something like: 'so pleased to see Jamulus has been brought to so many people and kept them playing music and connected. Happy birthday'?You might be aware he runs an online jam for many people in a Saturday and of course created the page on Facebook that helped people resolve connection issues etc. You'd be very welcome to join us!On a personal note, I live alone and most contact is done online. Jamulus has kept music alive and helped maintain some sense of normality and purpose. Thank you!Kindest regards, JezOn 30 May 2020 14:18, Volker Fischer <notifications@github.com> wrote:

Any chance you could join us for a message?

Sure, what kind of message do you have in mind?

**Comment by corrados** [comment]
@JezDruce your request: "_This would be a button that appears under each player above solo and mute, that allows the user to include that player in their fold back channel. Once they have set the individual slider for each player included in the foldback, they can adjust the foldback group as a whole._" is now implemented, see: https://github.com/corrados/jamulus/issues/202#issuecomment-647035442
I'll close this Issue now. If you think that there is still something todo, then just reopen the Issue.
