### ISSUE TITLE
 Jamulus crash when history file is given

### ISSUE THREAD

**Issue by gilgongo** [corrados/jamulus#30]
_This issue has been migrated from Sourceforge. Created 28-03-2020_

The version 3.4.4 seems to crash when history file is provided:

```
Jamulus -n -s -p 22124 -l /jam/jamulus.log -y /jam/history.jpg
- no GUI mode chosen
- server mode chosen
- selected port number: 22124
- logging file name: /jam/jamulus.log
- history file name: /jam/history.jpg
- welcome message: Wellcome to Jamulus docker server.
Qt5 requires a windowing system to paint a JPEG image; image will use SVG
AHistoryGraph::Start ( /jam/history.jpg )
```

This behaviour is reproduced on Docker image: probably it missing some dependencies.

> Volker 29-03-2020: pljones has changed the history graph recently so that it can use SVG, see https://github.com/corrados/jamulus/pull/6. I hope he can give you support on this.

> Volker 29-03-2020: SVG uses QXmlStreamWriter. Does this need a special library? Do you know this?
Do you have an error call stack available to see where it crashes?

**Comment by pljones** [comment]
Basically,
> Qt5 requires a windowing system to paint a JPEG image
so, if you use `-n`, it's assumed that you don't _want_ to use a windowing system, so you do not have the option to use a JPEG image.  The filename you give has SVG data written to it.

If you want to view it, use a `.svg` as the suffix - so either change your start up command or move the file afterwards.

**Comment by corrados** [comment]
This is obviously a configuration issue and can be solved by using correct command line options. I will close this Issue now.
