### ISSUE TITLE
Intercom to individual user

### ISSUE THREAD

**Issue by robsco** [corrados/jamulus#300]
If I join a channel, it would be handy to "shout" to a friend in the room, but privately, so not to disturb the group.

Could this be possible?

"Hey Bill, I'll be over in room XYZ when you're done in here."

Think of it as virtually walking up to someone and telling them something, rather than send a text message which they may not read for a while.

**Comment by Snayler** [comment]
Wouldn't that disturb the user you're talking to? When I need to talk with a friend in the middle of a session, I just message him through other means, like whatsapp.

**Comment by robsco** [comment]
That would be the idea, but a "do-not-disturb" could be implemented too, if you really never wanted anyone to talk to you while you're playing.

Whatsapp and other means may work sometimes, but I've had many occasions where I can't get hold of a friend because they're not checking their phone, but did want interrupting.

This would negate the need to keep checking your whatsapp, or the chat window, etc. especially useful if you're not in front of the pc, or don't keep checking your phone.

**Comment by corrados** [comment]
The implementation of the feature would be quite compilcated. Right now at the server a separate mix for each client is calculated. In case of an intercom, you would have to mute your signal for all other clients and only ship that audio data to the desired client. That would mean to add protocol messages for enabling/disabling the intercom and some modifications in the server signal processing. At the same time some intercom button would have to be put on each channel in the client. That would mean you have another button (which may confuse some users). Then you have a lot of special cases. E.g. if intercom is activated and the other user disconnects.

The question is how many people would actually use that. Normally you would write these things in the chat dialog that you, e.g., want to leave the server and go to another server. That would not disturb the audio session.

I think it is too much work to do and too little benefit.

**Comment by robsco** [comment]
OK, no worries if it's too difficult.

**Comment by corrados** [comment]
I don't think this will ever be implemented in Jamulus so I will close this Issue now.
