### ISSUE TITLE
Question about the "jamulus" user

### ISSUE THREAD

**Issue by trebmuh** [corrados/jamulus#308]
I'm searching information about the "jamulus" user that I can see is created on the [debian packaging instructions](https://github.com/corrados/jamulus/blob/master/distributions/debian/postinst).

I've read [this bit of the wiki documentation](https://github.com/corrados/jamulus/wiki/Server---Linux#compile-sources-create-a-user) and it looks that it's is only useful when running a jamulus server. Am I right here?

**Comment by gilgongo** [comment]
It's recommended to run the server as a non-privileged user (hence the fact the script creates a system user by convention for that).  

While you can run the client as the jamulus user that's created by the package, you would I think run in to problems with that on the desktop.

**Comment by corrados** [comment]
@ trebmuh Is your question answered with the respond from gilgongo?

**Comment by trebmuh** [comment]
Thanks for your messages @gilgongo and @corrados .

So, IIUC, this _jamulus_ user is **only** used when running a server, ie: not used when running a client, is that correct? If so, this thread can be closed.

**Comment by gilgongo** [comment]
Ah, I think see what you mean now. When you build the package, and then run Jamulus (as either server or client) by invoking it on the command line with `./Jamulus` or `./Jamulus -s` then it will run as you (the currently logged in user).

If you run the server headless or need to start it root (for example, when using a systemd unit file to access realtime kernel stuff) then the jamulus system user is there so you can run it as that user if you want. But it's not compulsory.
