### ISSUE TITLE
Jamulus 3.4.4 not starting on Windows 10

### ISSUE THREAD

**Issue by fritzbauer** [corrados/jamulus#31]
I tried to install Jamulus (v3.4.4) for the first time yesterday. However, it did not even open.
I tried deactivating all other sound devices and startup programs, however I was not able to open the application.
Please see the details from the event viewers crashlog:
[Jamulus_crashlog.txt](https://github.com/corrados/jamulus/files/4402065/Jamulus_crashlog.txt)

I tried to download the previous version for windows (v3.4.2) since I realized the most recent version was just 5 days old. And indeed I was able to open the application on v3.4.2

Please let me know, if you need me to provide further details or if there is any debug mode of the application.

**Comment by fritzbauer** [comment]
ok another attempt to install v3.4.4 worked successfully. Sorry for the noise

**Comment by corrados** [comment]
Maybe the Visual Studio redistributable was not installed correctly on the attempt to install the newest version. Maybe with the older it succeeded and therefore then the newer also worked. I re-opend the issue to keep in mind that there may be something odd with the installer.

**Comment by fritzbauer** [comment]
I tried it on a second device. A Windows 10 notebook. Jamulus was working on the first attempt to install v3.4.4.
Thank you!

**Comment by corrados** [comment]
Great to hear. Thank you for the feedback. So I will close this issue now again.
