### ISSUE TITLE
Store recorder settings

### ISSUE THREAD

**Issue by pljones** [corrados/jamulus#313]
Just to avoid cluttering #228 with any more bits...

The last "Enable recording" state and the recording directory - now they exist / are on the UI - should be stored in the server settings.

Depends on me finishing #228, of course :).

**Comment by pljones** [comment]
Aha, now I guess I need to pick this up.
@pljones Maybe this makes it appear in my issue highlights?

**Comment by corrados** [comment]
As I am in a progress of revising the settings implementation, we may get a lot of merge problems if you start right now. Maybe it is wise to wait for some days until my implementation has settled a bit.

**Comment by pljones** [comment]
Ah yes, good point.  There are a few settings-related Issues still open, I'll see if there are any unrelated ones I was thinking of.  (Even the auto-update touches settings as it has settings to store.)

**Comment by pljones** [comment]
OK, I might pick this up next if things have stabilised.

**Comment by corrados** [comment]
Yes, go ahead. I'm done for now with my changes in the settings.

**Comment by pljones** [comment]
Just to tag #513 as the branch for this (in case anyone else is watching).
