### ISSUE TITLE
Avoid showing IP address if no name in the musician profile is given

### ISSUE THREAD

**Issue by corrados** [corrados/jamulus#316]
The server should not send a valid IP address in the musicians list to the clients for privacy reasons. The client should show, e.g., an empty name if no name is given instead of showing the IP address. In order to preserve the old protocols, the server should use an invalid IP address.

See also this Issue: https://github.com/corrados/jamulus/issues/314

**Comment by gilgongo** [comment]
Perhaps show "No Name" by default? Blank might make the musicians list in the connection window look strange.

**Comment by corrados** [comment]
I actually don't see an issue with that. It gives you minimum width for the fader, see:
https://github.com/corrados/jamulus/issues/257#issuecomment-634229124
The fifth fader has an empty name.

**Comment by gilgongo** [comment]
Sorry, I meant in the [Connection Window](https://github.com/corrados/jamulus/blob/master/src/res/homepage/connect.png). Might make it look like somebody had two flags or something? (Talking of flags, I notice on that screenshot that there is someone without a flag...)

**Comment by corrados** [comment]
done

**Comment by atsampson** [comment]
The fix seems to work. :-) It looks a bit odd in the Connection Setup window, especially if someone hasn't set a country or instrument either (then you get a completely blank line) - perhaps show "(no name)" there?

**Comment by corrados** [comment]
> perhaps show "(no name)" there?

This is already implemented: https://github.com/corrados/jamulus/blob/master/src/settings.cpp#L129

**Comment by atsampson** [comment]
I was thinking on the receiving end - there are a lot of older clients and servers out there. I guess the other advantage of doing it on receive is that you can translate "No Name" into the receiving (rather than sending) client's language.

**Comment by corrados** [comment]
Yes, that it true. But I am against this solution. Most of the users which do not have set a name are new users which either do not want to change the name or do not know where to do it (they do not find the musician profile dialog). But if these users will show up more often on the Jamulus servers, they will certainly set a name then. So the empty names are just for new users. So if I release the new version where you have No Name per default on a new Jamulus installation, you will see it often in the list.
