### ISSUE TITLE
Increase number of audio inputs

### ISSUE THREAD

**Issue by robsco** [corrados/jamulus#320]
Can we increase the number of audio channels within a single instance of Jamulus, and have this reflected as additional faders in the GUI.

This is basically possible now by running multiple instances of Jamulus, to send different instruments/mics separately.

I've seen a few people do this, but obviously it's a pain switching servers.

**Comment by Snayler** [comment]
I currently use 2 audio interfaces with only one Jamulus instance. You can check the guide in the [Wiki](https://github.com/corrados/jamulus/wiki/Tips,-Tricks-&-More#running-jamulus-with-multiple-audio-interfaces). I haven't updated the MacOS part, but with the latest versions it's also possible by using aggregate devices.

**Comment by robsco** [comment]
Just another use-case, I send all my inputs through my DAW and output that into Jamulus, but would like to be able to mute my own mic coming back from the server, so you don't get the disorientating delay when chatting, but not mute my instrument.

**Comment by Snayler** [comment]
You can check the Wiki article I posted in my previous comment. I use Voicemeeter to drive my microphone into Jack, which in turn sends it's signal to Jamulus. From voicemeeter I have full control over my Microphone, I can mute it, lower or raise the volume, change equalization, etc...

**Comment by robsco** [comment]
I'm on Linux too.

Would that not mute it **going** to the Jamulus server?

I still want my mic to be sent to the server, so everyone else can hear me, but I don't want to hear it coming back.

But I still want my instrument to go to the server, and I **do** want to hear that coming back.

Hence wanting 2 separate faders on the GUI, so I can mute/turn down my own mic return signal, but not my instrument.

**Comment by Snayler** [comment]
I think doing it like that would double the amount of data sent to the server, as you'd be sending two separate streams. This could have some implications, since the server channels are limited, you'd be occupying two of them.

**Comment by robsco** [comment]
It would yes, but no different to running 2 separate instances of Jamulus (which I see people do) - it's just that way is cumbersome changing servers, leaving half of yourself on one server by accident.

**Comment by Snayler** [comment]
I've tried the 2 separate instance method, but with the possibility to have everything on one instance and all the work involved in switching servers and figuring out which window is what stream, it's just not worth it.

In my experience it's possible to fine tune the microphone to have no perceivable delay on a close by server, and if hearing my own voice bothers me, I just mute my stream while speaking. I'm not sure about other OS's, but on windows, after clicking the mute button the first time, I just need to hit space to toggle it, so it's no bother to me switching between the two modes (mute for speaking, unmute to play).

Anyway, we'd better wait for corrados input on this.

**Comment by corrados** [comment]
I think this is a duplicate of this: https://github.com/corrados/jamulus/issues/96
We should close this Issue and continue the Diskussion in the original issue.

**Comment by robsco** [comment]
Closing, glad I'm not the only one wanting this.  :)
