### ISSUE TITLE
3.5.5. Jamulus on Ubuntu, poorer performance

### ISSUE THREAD

**Issue by corrados** [corrados/jamulus#325]
Issue reported in this thread:
https://sourceforge.net/p/llcon/discussion/server/thread/1f8f7b5d1b

**Comment by corrados** [comment]
@pljones This sounds critical to me. Could you please try to reproduce the issue?

**Comment by corrados** [comment]
3.5.3 seems to work (see post in thread). You also noticed higher CPU load once. I assume this is related.

**Comment by corrados** [comment]
3.5.4 introduced the signal handling. Maybe is this related?

**Comment by pljones** [comment]
> Luuk - 5 hours ago
> Problem seems to have vanished by itself, tried 3.5.5. client and 3.5.4. client on a 3.5.5. server, hardly any buffer red lights.

Wait and see...

**Comment by corrados** [comment]
Initially he wrote that he compared versions directly so I assume that it is was not a temporary network problem. I am still not convinced that we have no issue since another user also reported about problems...

**Comment by corrados** [comment]
I just did tests on my virtual server where the Central Server runs on. I have tested a binary with 3.5.3 and 3.5.5 and could not find an issue with both of them. Both run just fine.

**Comment by corrados** [comment]
I cannot reproduce the issue and others in the Sourceforge forum also report that they cannot reproduce the issue -> closed.
