### ISSUE TITLE
Clarification on muted icon

### ISSUE THREAD

**Issue by gilgongo** [corrados/jamulus#328]
When updating the documentation, I believe I misunderstood #257 and said the wrong thing about the mute icon. 

So just to check: the icon means that **somebody else** has muted **you** (so they can't hear you), not that **they** have muted **themselves** (so that you can't hear them) - is that right?

In manual.md I said that if you clicked on "Mute Myself", then other clients would see the mute icon over your fader, but that's not right. Only you know that you have muted yourself.

**Comment by corrados** [comment]
Yes, thats right.

**Comment by gilgongo** [comment]
Ah - a follow-up question:

If I solo somebody, will all the non-soloed musicians also see the icon (to indicate that I can't hear them)?

**Comment by corrados** [comment]
Yes, they will.

**Comment by Snayler** [comment]
Same for putting a fader in the minimum, the icon will appear.

**Comment by pljones** [comment]
Hm.  Are there any privacy issues regarding someone else's mix information being displayed like this?

**Comment by gilgongo** [comment]
@pljones That's an interesting point. I think the advantage of knowing that somebody can't hear you outweighs the disadvantage of perceived rudeness or lack of privacy. The existence of the chat channel means the affected person has some control over the situation, so as long as we're clear in the docs (not that anyone actually reads them...) then I think it's probably OK. One to bear in mind if we ever consider things like contact details in profiles though!

@Snayler I'll add that in.

**Comment by corrados** [comment]
The original request of this Issue was the clarification of the mute icon. I think this is clarified so I will close this Issue. Feel free to continue your discussion here anyway.

**Comment by gilgongo** [comment]
I just need that muted icon - is it not in the sources?

**Comment by corrados** [comment]
It's a unicode symbol: https://www.compart.com/de/unicode/U+1F507
It may look different on different OSs. E.g. on Mac it looks more like this:
https://www.fileformat.info/info/emoji/mute/index.htm

**Comment by softins** [comment]
> It's a unicode symbol: https://www.compart.com/de/unicode/U+1F507
> It may look different on different OSs.

It doesn't display at all on Windows 7. It just shows an empty square with an orange border. I think W7 Unicode maybe stops at FFFF.

**Comment by corrados** [comment]
> It doesn't display at all on Windows 7

Too bad but I can live with that. Windows 7 is no longer supported and if just the icon is not displayed, that should not be a big issue for users which still stick to that unsupported OS.
