### ISSUE TITLE
[FR] Provide Windows x64 builds

### ISSUE THREAD

**Issue by ZoomRmc** [corrados/jamulus#34]
ATM Jamulus doesn't see ReaRoute (virtual asio driver) provided by x64 builds of Reaper. It's needed to set up Reaper as a host for existing VST[i] plugins and instruments and prepare the signal to be fed to Jamulus.

x86 ReaRoute works ok, but it requires bridging existing x64 plugins inside Reaper, or installing separate x86 copies of said plugins/instruments, which is suboptimal.

**Comment by corrados** [comment]
The next Jamulus Windows release will contain a hybrid 32 bit/64 bit installer. See: https://github.com/corrados/jamulus/commit/324287beda73af17f4f9faff8e324c3618b27ab0

**Comment by corrados** [comment]
The release is done. Starting fom Jamulus version 3.4.5, the Jamulus installer will install a 64 bit version of Jamulus if a 64 bit operating system is detected and will install a 32 bit version of Jamulus if a 32 bit operating system is detected.

**Comment by ZoomRmc** [comment]
That was fast! Thank you!
