### ISSUE TITLE
Personal mix should always mute your own audio

### ISSUE THREAD

**Issue by mikedickey** [corrados/jamulus#340]
As per the[ Getting Started documentation](https://github.com/corrados/jamulus/wiki/Getting-Started#having-trouble-cant-keep-in-time), it's bad practice to monitor your own audio stream. This even makes something as simple as carrying out a conversation with someone challenging. Performing music with this is extremely difficult.

Despite this guidance, Jamulus' default behavior is that you own audio is always played back to you at full volume. I believe the default behavior when you join a server should be that your own audio is always muted in your personal mix. There also appears to be no way to configure this via settings or using the --inifile.

**Comment by mikedickey** [comment]
This currently makes Jamulus unusable for headless use cases like on Raspberry Pi. See my [blog article](https://25ms.org/2020/06/07/testing-jamulus-latency-on-raspberry-pi/) about this for more details.

**Comment by mikedickey** [comment]
Also related to #187

**Comment by corrados** [comment]
> Performing music with this is extremely difficult.

You overall delay must be short enough to be able to play. It is very critical to hear your own signal coming back from the server and synchronize on that, otherwise if you play with others you will not play in sync and your tempo will slow down.

**Comment by corrados** [comment]
> Despite this guidance, Jamulus' default behavior is that you own audio is always played back to you at full volume.

As I said, you should hear your own signal coming back from the server (Jamulus Rule #1 ;-) ). Ok, if you want to violate that rule, than simply move your own fader all the way down. Jamulus will store this fader position and when you disconnect and connect to a different server, the fader position will be restored and it will be all the way down as you have moved it previously.

**Comment by WolfganP** [comment]
> As per the[ Getting Started documentation](https://github.com/corrados/jamulus/wiki/Getting-Started#having-trouble-cant-keep-in-time), it's bad practice to monitor your own audio stream. This even makes something as simple as carrying out a conversation with someone challenging. Performing music with this is extremely difficult.
 
The guidance suggests to not monitor you locally outside of the server loop, because that way you get out of sync of others players (which is what Mute Myself does).
Check this diagram https://github.com/corrados/jamulus/issues/148#issuecomment-629679659 for how it works.

**Comment by corrados** [comment]
Regarding your blog: There are facebook groups which may be of interest for you:
https://www.facebook.com/groups/1618969401583627/
https://www.facebook.com/groups/507047599870191/

**Comment by corrados** [comment]
@mikedickey Are you happy with our feedback? Or do you need more information about this topic?

**Comment by mikedickey** [comment]
Suppose I misread the documentation. I didn't realize that the audio was coming back to me from the server versus monitor because I have a very low roundtrip (<10ms).

When running Jamulus headless (from command line without a GUI), is there any way to mute your signal coming back from the server? I understand that the GUI app allows you to do this but how can one do it via command line?

**Comment by corrados** [comment]
There are two possibilities: Either use MIDI or change the ini-file manually.
With the ini-file: Check your name (in my case: <name_base64>dGVzdA==</name_base64>) then find this in the storedfadertag (in my case: <storedfadertag0_base64>dGVzdA==</storedfadertag0_base64>). Then you now the stored ID. Then search for the level entry (in my case <storedfaderlevel0>100</storedfaderlevel0>). Set this value to 0 (i.e. change the 100 to 0).

But as said above, I cannot recommend to mute your own signal coming back from the server.

**Comment by corrados** [comment]
There is a much easier solution. Start Jamulus on your Windows/Mac PC and start with --inifile myfile.ini. Then set your profile information, connect to any server and move your own fader down. Then quit the Jamulus software. The settings are now stored in the myfile.ini. Copy that file to your Raspberry Pi and start the Jamulus on the Raspberry Pi with --inifile myfile.ini. That's it.

**Comment by corrados** [comment]
@mikedickey I would like to close this issue now. Is that OK for you or are there still open issues?

**Comment by corrados** [comment]
No response after 8 days. I'll close this Issue now. If there is anything still open, please re-open this Issue or create a new one.

**Comment by CAguayo** [comment]
Wouldn't it be better to simply add a command-line flag to enable this start-up state on headless servers?

**Comment by mikedickey** [comment]
@corrados Sorry for long delay but I have another use case now where this is absolutely required. I tried both of your suggestions, and neither seems to work using 3.5.12 on a headless linux build. Perhaps it has something to do with the sliders not being there since there is no gui? I tried both with a headless build (via qmake config) and via --nogui with same results.

**Comment by corrados** [comment]
You are right, there are restrictions in the headless build which I did not consider in my recommendations. In headless client mode the inifile is read but not all values apply since the class which manages the faders/mute/solo/etc. is not used in headless mode.

But the MIDI control should work. You write that you have tried both suggestions so you have tried the MIDI and it did not work? We had an issue that MIDI control did not work for headless but this is already fixed, see https://github.com/corrados/jamulus/issues/483. Have you tried the latest version of Jamulus?

**Comment by mikedickey** [comment]
I didn't try the MIDI support. I stumbled across that and think it sounds awesome, but honestly I have almost zero experience/knowledge with MIDI. Is there an easy way to use that to tell Jamulus to "mute my audio in my personal mix" at startup? Perhaps there is a MIDI cli for Linux that I use to run a command that performs this action?

Note that I'm using an automation systemd agent to control headless Jamulus instances. Although I think this particular item has use cases outside of automation, it's particularly useful for that. Specifically, what I am working on now is creating a "Jamulus Bridge" to other systems that integrate with Jack. Being unable to exclude the audio that my "bridge client" sends to the server in the mix that the server sends back to the client is creating a feedback loop.

**Comment by mikedickey** [comment]
For the sake of mentioning it, my current "bridge design" is kind of a hack. I have to run a Jamulus client process just to make Jack connections available that I can patch in with other applications. If there was a way to run the Jamulus server so that it created Jack input and output connections for the mix, it would make this a lot easier and eliminate the need to run a separate client process.

**Comment by WolfganP** [comment]
> 
> 
> For the sake of mentioning it, my current "bridge design" is kind of a hack. I have to run a Jamulus client process just to make Jack connections available that I can patch in with other applications. If there was a way to run the Jamulus server so that it created Jack input and output connections for the mix, it would make this a lot easier and eliminate the need to run a separate client process.

Already in discussion here https://github.com/corrados/jamulus/issues/146

**Comment by corrados** [comment]
Does it have to be a headless client? If you would use the normal client with GUI, it would be so much easier to mute your own signal.

> Is there an easy way to use that to tell Jamulus to "mute my audio in my personal mix" at startup?

No, it is not easy since you have to know the fader ID of your own channel. But setting up MIDI with jack should be not so difficult.

**Comment by corrados** [comment]
I have setup an experimental branch https://github.com/corrados/jamulus/tree/feature_mutemyself_headless on Github where I have "misused" the "-M, --mutestream" command line argument. If you have compiled Jamulus with `qmake "CONFIG+=headless"` and using the -M command line argument, your own signal should now be muted in your own mix. But make sure that the Jamulus server which you are using has an up-to-date version installed.

**Comment by mikedickey** [comment]
@corrados I just tested feature_mutemyself_headless and it is EXACTLY what I needed! Thank you!

**Comment by corrados** [comment]
Thanks for testing. I've now changed the implementation again so that I can merge it to the master branch and make it an official feature. I have now introduced a new command line argument since re-using -M is not a good solution. The new command line argument is --mutemyown and works only in combination with the -n flag. Could you please update your code from the latest code in the feature_mutemyself_headless branch and give me a quick feedback if the new code works for you?

**Comment by mikedickey** [comment]
Just confirming that --mutemyown works as expected. Thanks again!
