### ISSUE TITLE
Core dump with -R if directory exists

### ISSUE THREAD

**Issue by gilgongo** [corrados/jamulus#35]
Jamulus 3.4.4 on Ubuntu 18.04.4 LTS amd64 with libqt4-dev 4:4.8.7+dfsg-7ubuntu1 

**Steps to re-create**:

1. Stop Jamulus server and create dir with jamulus write permissions:

```
mkdir /home/gilgongo/JamRecordings
chown jamulus:jamulus /home/gilgongo/JamRecordings
```

2. Start server with UID jamulus GID jamulus with `-R /home/gilgongo/JamRecordings`

3. Jamulus core dumps and shuts down with error:

```
Mar 31 22:31:44 covid19 jamulus[12427]: - recording directory name: /home/gilgongo/JamRecordings/
Mar 31 22:31:44 covid19 jamulus[12427]: terminate called after throwing an instance of 'std::runtime_error'
Mar 31 22:31:44 covid19 jamulus[12427]:   what():  /home/gilgongo/JamRecordings does not exist but could not be created
Mar 31 22:31:45 covid19 systemd[1]: jamulus.service: Main process exited, code=dumped, status=6/ABRT
Mar 31 22:31:45 covid19 systemd[1]: jamulus.service: Failed with result 'core-dump'.
```

**Expected behaviour**: either keep server running but ignore -R and show warning (if Jamulus is expecting to create `JamRecordings` dir itself), or just allow Jamulus to write to the directory.

Note that letting the server create the directory works (and works across subsequent server reboots) but obviously required jamulus xrw on the parent dir, which may not be a good idea.

**Comment by pljones** [comment]
Does the user Jamulus is running as have permission that location?

**Comment by gilgongo** [comment]
The JamRecordings directory was owned by Jamulus, so I assume the error  "does **not** exist but could not be created" would seem incorrect, no?

But in any case it works if (for example) I give it a path of /tmp/somedir, but do not create somedir before starting the server.

So I guess the expected behaviour here (assuming Jamulus wants to create the directory itself) would be for the message to say something like "_/home/gilgongo/JamRecordings already exists, ignoring -R_" and continue working without a core dump. 

Ideally though, if the directory already exits and the permissions are OK (eg owned by Jamulus?), then Jamulus should just use it.

**Comment by pljones** [comment]
The path needs to be accessible.

If `/home` or `/home/gilgongo` is not accessible (does not have read and execute access), then the content, no matter whether they exist or not, is not accessible.

**Comment by gilgongo** [comment]
The path was accessible. Both /home and /home/gilgongo are 0755 (as per the Ubuntu defaults), so both drwxr-xr-x.

**Comment by pljones** [comment]
That means the path is not writeable by user Jamulus, so initially couldn't have created the the required path.  That means the first error is correct.

**Comment by gilgongo** [comment]
Apologies - I was unclear in the ticket. I'll edit he ticket to add the steps to re-produce.

**Comment by pljones** [comment]
Hi,

It would have been easier to comment afresh - now there are a lot of unanswered questions in the thread.

Those questions are not answered by your edit to the original post, either.  Explicitly: you are not stating the effective user performing each command.  That's vitally important if there are permission issues.

The reason for the core dump is made clear:  /home/gilgongo/JamRecordings does not exist but could not be created.

**Comment by gilgongo** [comment]
Sorry - I'll stick to the comments then in that case.

>  you are not stating the effective user performing each command.

- mkdir /home/gilgongo/JamRecordings is performed as UID gilgongo GID gilgongo
- chown jamulus:jamulus /home/gilgongo/JamRecordings  is performed as UID gilgongo GID gilgongo
- Start server with UID jamulus GID jamulus

> What you need to explain is why the existence of that directory could not be determined by the effective user trying to make that determination

If I knew why, I wouldn't have raised this issue :-)  But it sounds as if I've not understood something. 

What I observe is that I created a directory that the server's UID can read, write and execute to, in a path which the server's UID can execute, but that the server core dumps. The behaviour I expected would be that it would write to that directory without crashing.

**Comment by pljones** [comment]
OK, I tried it step by step here and I've attached the logs.

Can you try reproducing this exactly as I've done it?  (Changing only the path to Jamulus.)

[JamulusRecordingLog.txt](https://github.com/corrados/jamulus/files/4464425/JamulusRecordingLog.txt)

Then post the log here.

**Comment by gilgongo** [comment]
@pljones useradd  on Ubuntu doesn't create a home dir, so I get:

```
No directory, logging in with HOME=/
$  ls -ld / /home /home/myJammingServer
ls: cannot access '/home/myJammingServer': No such file or directory
```
Is that significant?

**Comment by pljones** [comment]
Oh, sorry - add `-m`.  I must have logged the wrong line (I typed it wrong once :) ).

**Comment by gilgongo** [comment]
OK done that:

[gilgongo-log.txt](https://github.com/corrados/jamulus/files/4464932/gilgongo-log.txt)

**Comment by pljones** [comment]
OK, so the server starts up and creates the recording directory when it's not there and it also starts up and uses an existing recording directory.  That means there's no problem with the server.

If it's failing, it's a permissions problem.

The `ls -ld` down the path to where the recording directory would be created is important.

Can you re-do that for your "real" server, please.
(The "r" and "x" bits need to be on at each level for the user the server runs as in order for it to traverse the path.)

**Comment by gilgongo** [comment]
This is what I get for that, which of course means that Jamulus would not be able to create `JamRecordings ` inside my home dir. That's why I created it beforehand for Jamulus to write to before I started the server with -R.

The current behaviour of -R would means that if I want to have recording in my home dir but avoid a core dump, I need to create a directory which would then allow Jamulus to create another directory inside that, which seems odd to me. I don't think I've encountered an application that has an option which creates a directory if it doesn't already exist.

```
gilgongo@oddjob:~$ ls -ld / /home /home/gilgongo /home/gilgongo/JamRecordings
drwxr-xr-x 24 root     root     4096 Apr  7 06:32 /
drwxr-xr-x  3 root     root     4096 Mar 17  2019 /home
drwxr-xr-x  9 gilgongo gilgongo 4096 Apr 11 15:49 /home/gilgongo
drwxrwxr-x  2 jamulus  jamulus  4096 Mar 31 22:26 /home/gilgongo/JamRecordings
```

**Comment by pljones** [comment]
Hm, looks okay.

I'll try reproducing it again now I can see exactly what you've got there.

**Comment by gilgongo** [comment]
> what command do you use to start Jamulus as the "jamulus" user?

I'm using a systemd unit so `service jamulus start` The unit file is as per the [docs here](https://github.com/corrados/jamulus/wiki/Server---Linux).

**Comment by pljones** [comment]
OK, don't run it like that for now.  Run the actual command directly.

**Comment by pljones** [comment]
Ah!  Reproduced it.  No idea why it happens yet.  I tried it in a subdirectory of my home directory and it seemed fine.  Tried again in my home directory and it failed.  Which is very odd.

**Comment by pljones** [comment]
```
peter@fs-peter:~$ ls -ld / /home /home/peter /home/peter/r
drwxr-xr-x 25 root    root    4096 Apr  8 06:35 /
drwxr-xr-x  4 root    root    4096 Apr 11 18:09 /home
drwxr-xr-x 75 peter   peter   4096 Apr 11 18:12 /home/peter
drwxrwxr-x  2 Jamulus Jamulus 4096 Apr 11 18:12 /home/peter/r
peter@fs-peter:~$ sudo -u Jamulus /opt/Jamulus/bin/Jamulus -s -n -R $(pwd)/r
- server mode chosen
- no GUI mode chosen
- recording directory name: /home/peter/r
 *** Jamulus, Version 3.4.7git
 *** Internet Jam Session Software
 *** Under the GNU General Public License (GPL)
^C
```
Still no luck reproducing it (if I get the wrong user on the "r" directory, I get a different error - i.e. the directory exists but cannot be written to, which is correct).

**Comment by gilgongo** [comment]
> Are you sure your unit is running as the right user?

It's as per the [wiki](https://github.com/corrados/jamulus/wiki/Server---Linux), so `User=jamulus` Perhaps `Group=jamulus` is needed too?

**Comment by pljones** [comment]
Sounds reasonable.  I don't run my Jamulus server using the unit file in the wiki.

**Comment by corrados** [comment]
Any updates on this issue?

**Comment by gilgongo** [comment]
I don't think @pljones managed to reproduce it, and we've not had any reports of it happening on the forums as far as I know (in fact people are strangely silent about `-R` in general), so closing.
