### ISSUE TITLE
SIGUSR2 handling is (sometimes?) not working

### ISSUE THREAD

**Issue by pljones** [corrados/jamulus#351]
I've hesitated in raising this because it's taken me some time to convince myself it actually happens...

SIGUSR2 should toggle "Enable jam recording" on and off.

When you start the server with recording initialised, any client connection will, by default, get recorded as part of the current session.

SIGUSR2 should terminate that session and prevent further sessions.

----

* start the server with the GUI: `./Jamulus -s -p 55850 -R /tmp/recorder`
* connect a client to the server, note that the current session directory is displayed on the server GUI
* disconnect the client, note that the server console displays the paths of the recording project files
* get the process ID: `ps -ef | grep 55850 | grep Jamulus` (depending on your `ps`, it's the second column; MacOS may need different options and, of course, no chance on Windows).
* send SIGUSR2 to the process: `kill -SIGUSR2 <pid>` (turns off recorder)

With the GUI open, the "Enable jam recording" check box toggles and (possibly _because of that_) the system appears to work as expected.  Leave the application running and try:
* connect a client to the server, note that the current session directory is displayed on the server GUI
* disconnect the client, note that the server console displays the paths of the recording project files

No current session should have been displayed on the GUI and the server does not list the project files.  Now, one more test:
* send SIGUSR2 to the process: `kill -SIGUSR2 <pid>` (turns on recorder)
* connect a client to the server, note that the current session directory is displayed on the server GUI
* send SIGUSR2 to the process: `kill -SIGUSR2 <pid>` (turns off recorder)

At this point, the client is still connected but the server has emitted the current project and the field becomes disabled.  So, finally:
* disconnect the client, note that the server console displays the paths of the recording project files

No project files are created as no session was in progress.  All is well.

----

Without the GUI the tests are not **ALWAYS** successful.
* start the server without the GUI: `./Jamulus -s -n -p 55850 -R /tmp/recorder`
* connect a client to the server
* disconnect the client, note that the server console displays the paths of the recording project files
* get the process ID: `ps -ef | grep 55850 | grep Jamulus` (depending on your `ps`, it's the second column; MacOS may need different options and, of course, no chance on Windows).
* send SIGUSR2 to the process: `kill -SIGUSR2 <pid>` (_should_ turn off recorder)
* connect a client to the server, note that the current session directory is displayed on the server GUI
* disconnect the client, note that the server console displays the paths of the recording project files

At this point, as we expected the recorder to have been disabled, no recording project files should have been displayed on the console.

I tried it earlier and managed to reproduce the reported defect.  I tried it just now... and it worked fine.

**Comment by pljones** [comment]
To help diagnose this, I've added some logging.  It might be worth including this in the next release, in case the issue remains.  The log shows, for example:
```
- server mode chosen
- no GUI mode chosen
- selected port number: 55850
- recording directory name: /tmp/recorder
Recording state enabled
 *** Jamulus, Version 3.5.7git
 *** Internet Jam Session Software
 *** Released under the GNU General Public License (GPL)
OnHandledSignal 12
Recording state disabled
...
OnHandledSignal 12
Recording state enabled
OnHandledSignal 12
Recording state disabled
OnHandledSignal 12
Recording state enabled
OnHandledSignal 12
Recording state disabled
2020-06-11 20:30:45, 192.168.1.5, connected
OnHandledSignal 12
Recording state enabled
OnHandledSignal 12
Recording state disabled
Session RPP: "/tmp/recorder/Jam-20200611-193052653/Jam-20200611-193052653.rpp"
Session LOF: "/tmp/recorder/Jam-20200611-193052653/Jam-20200611-193052653.lof"
2020-06-11 20:31:24,, server stopped -------------------------------------
2020-06-11 20:32:23, 192.168.1.5, connected
OnHandledSignal 10
OnHandledSignal 12
Recording state enabled
OnHandledSignal 10
Session RPP: "/tmp/recorder/Jam-20200611-193312939/Jam-20200611-193312939.rpp"
Session LOF: "/tmp/recorder/Jam-20200611-193312939/Jam-20200611-193312939.lof"
OnHandledSignal 10
Session RPP: "/tmp/recorder/Jam-20200611-193328729/Jam-20200611-193328729.rpp"
Session LOF: "/tmp/recorder/Jam-20200611-193328729/Jam-20200611-193328729.lof"
OnHandledSignal 12
Recording state disabled
Session RPP: "/tmp/recorder/Jam-20200611-193419044/Jam-20200611-193419044.rpp"
Session LOF: "/tmp/recorder/Jam-20200611-193419044/Jam-20200611-193419044.lof"
OnHandledSignal 10
```
as a result of
```
$ ./Jamulus -s -n -p 55850 -R /tmp/recorder
```
and
```
$ ps -ef | grep 55850 | grep Jamulus
$ kill -SIGUSR2 <the pid>
# above several times, logged as `OnHandledSignal 12` with the appropriate resulting state.
$ kill -SIGUSR1 <the pid>
# above several times, logged as `OnHandledSignal 10` and, if recording was enabled, the project files.
```
Just to be sure what was happening, I also did
```
$ rm -r /tmp/recorder/Jam-20200611-193052653
```
after the first recording and before the second, and then did `ls /tmp/recorder` several times _during_ the recordings to see that the new directories were being created.

Everything appear to work fine.  Again.

Hm.

**Comment by corrados** [comment]
What is the status if this Issue? Is this still relevant?

**Comment by pljones** [comment]
I've actually used the GUI controls a few times since the refactoring and had no problems.  I'm seeing `OnHandledSignal X` in the log when I'd expect to on server shutdowns (but the first - and in that instance only - signal generally worked).

So no further instance of failure.  I'm going to close it.  If anyone spots a problem, a new issue can always be raised and the logging is at least there now.
