### ISSUE TITLE
Configuration file for server

### ISSUE THREAD

**Issue by valecs** [corrados/jamulus#354]
I am very interested in being able to specify the jamulus server's total configuration in a separate file and then pass that file as a command line argument. Is this the intention of the --inifile command line argument? I cannot find documentation describing how to write the inifile and poking around settings.cpp seems to indicate not all command line arguments are supported. I would be glad to help by writing code to support this feature.

Among other things, we could imagine distributing a standard systemd service for jamulus, which would ease packaging and configuration for Linux machines.

I imagine having a file stored at /etc/jamulus/config and then usign a systemd service like:

```
[Unit]
Description="Jamulus server"
After=network-online.target

[Service]
Type=simple
Restart=always
RestartSec=1
Nice=-5
NoNewPrivileges=true
ProtectSystem=strict
ConfigurationDirectory=jamulus
ExecStart = /usr/bin/jamulus --config ${$CONFIGURATION_DIRECTORY}/config

[Install]
WantedBy=multi-user.target
```

Questions:
* What are the desired properties of such a configuration file?
* Is anyone else thinking about this?
* Are there any concerns/pitfalls to watch out for?

My forum reference: https://sourceforge.net/p/llcon/discussion/server/thread/39fbb114d2

**Comment by corrados** [comment]
> I cannot find documentation describing how to write the inifile

The intention is that only the Jamulus software writes this file. But it is a standard xml file so it is possible to write it by some script, too. I am actually use this in my Raspberry Pi script, see: https://github.com/corrados/jamulus/blob/master/distributions/raspijamulus.sh#L114

> jamulus server's total configuration in a separate file

Not all command line settings are stored in the ini file right now. And there are command line arguments which do not make sense to put them in the ini file, like the "-s" command.

Here is a similar Issue: https://github.com/corrados/jamulus/issues/198

As you can see, pljones already started some implementation: https://github.com/corrados/jamulus/issues/198#issuecomment-628563218

**Comment by gilgongo** [comment]
Other than incorporating some of the command line options into the config, what other changes are  implied by this ticket? 

You say "amongst other things" but could you expand on that? By specifying a config in the unit file you can avoid re-initialising systemd if you change the server config, but having to navigate (and preserve the validation of) an XML file isn't as easy as passing command line arguments in a shell script really.

Just trying to understand the scope of what you're implying.

**Comment by gilgongo** [comment]
Is this worth keeping open? I don't really understand what problem it's solving.

**Comment by corrados** [comment]
I agree with you. Your post was 20 days ago and we did not receive any feedback. So I'll close this now.

**Comment by kjcole** [comment]
> > I cannot find documentation describing how to write the inifile
> 
> The intention is that only the Jamulus software writes this file. But it is a standard xml file so it is possible to write it by some script, too. I am actually use this in my Raspberry Pi script, see: https://github.com/corrados/jamulus/blob/master/distributions/raspijamulus.sh#L114

```
404 - page not found
The master branch of jamulus does not contain the path distributions/raspijamulus.sh.
```
