### ISSUE TITLE
Quitting client when server window minimized not handled cleanly

### ISSUE THREAD

**Issue by Skeezixes** [corrados/jamulus#355]
Running MacOS  10.15.5, Jamulus version 3.5.6, server and client on the same machine, and client  connected to the server.
Minimize the server window.
Quit the _client_ by clicking the red close button on the client window or COMMAND-Q. 

Results:
The client window closes. 
AND one of these things happens:
1. The **server** window closes too! (CTRL-click on server icon -> no "show all windows" available, so the server appears to be dead) but apparently the server is still around since top --> Two Jamulus processes still running. If you try to launch JamulusServer by clicking on the icon, you get a "Network Error: Cannot bind socket (maybe the software is already running?)", OR

2. The server window can be restored; it has not been closed. The server is still running. The client (now dead) is still in the connections list. 

IF in the case of #1 above, you then kill the Jamulus server process and restart the Jamulus server by clicking on the icon, the Jamulus Server window opens, and
the client is in the connections list (but it hasn't been connected to this instance of the Server).

IF in the case of #2, you restart the client and connect to the server again, everything is apparently fine (no duplicate connection or anything else strange).

**Comment by corrados** [comment]
@AronVietti Another Mac issue. Would you have time to look at this Issue?

**Comment by AronVietti** [comment]
@corrados Yeah, assign this to me I'll take a look today.

**Comment by AronVietti** [comment]
@Skeezixes @corrados I can not repro 1 but can repro 2 pretty regularly. Looking to fix 2 today.

**Comment by AronVietti** [comment]
@corrados Have a fix up for this https://github.com/corrados/jamulus/pull/383

There may have been other bug reports related to this. Minimizing the Server window caused hide() to get called, which stops the UI from updating, but there was no call to show() to start it back up. So it looked like nothing in the UI was working, when really it was just that the UI wasn't refreshing.

**Comment by corrados** [comment]
Great, thank you. I have merged your code. Let's wait what feedback we get after your fix goes into an official release version.

**Comment by corrados** [comment]
@Skeezixes Can you please test it again with the latest release version 3.5.8?

**Comment by Skeezixes** [comment]
Sorry for the delay. Finally got around to testing this. It looks great. I tried all the possibilities I could think of and couldn't make it misbehave. :-) Nice.

**Comment by corrados** [comment]
Thanks for checking. I close this Issue now.
