### ISSUE TITLE
Jamulus Server window too wide

### ISSUE THREAD

**Issue by Skeezixes** [corrados/jamulus#357]
The Jamulus Server window is excessively wide, made so by this line:
[ ] Make My Server Public (Register My Server in the Server List) [ Genre dropdown ]  / Registered

How about making two lines of this, like this:
[ ] Make My Server Public (Register My Server in the Server List)
     Genre: [    genre dropdown   ]    Registered

Then the window won't block other Jamulus windows I have open or take up more space than it needs to.

**Comment by gilgongo** [comment]
Coincidentally, I realised we didn't have a screenshot of it on the wiki page section yesterday so I put one in and thought the same :-)

https://github.com/corrados/jamulus/wiki/Server--Windows-&-Mac

**Comment by corrados** [comment]
Ok, quick fix. I'll do it later today.

**Comment by corrados** [comment]
Done:
![grafik](https://user-images.githubusercontent.com/46655886/84562970-76cb8c80-ad58-11ea-99e6-0878c0cb74e9.png)

**Comment by Skeezixes** [comment]
Good! Did you also adjust the preferred size of the window, so every time I open it I don't have to resize it smaller? :-)

**Comment by corrados** [comment]
The window position and size of the server window is now stored in the settings.

**Comment by Skeezixes** [comment]
Most excellent!
