### ISSUE TITLE
Active links in welcome message 

### ISSUE THREAD

**Issue by corrados** [corrados/jamulus#360]
I like to post a link to music and/or the video service in my server welcome message - but links don't work. So users then have to copy/paste the URL into a browser. Could links be made active? Thanks.

Copied from https://sourceforge.net/p/llcon/discussion/developerforum/thread/c4ae1cf17b

**Comment by corrados** [comment]
I have raised a question in the following issue: #314 (comment) regarding this feature request.

**Comment by corrados** [comment]
See: https://github.com/corrados/jamulus/issues/314#issuecomment-644191787

**Comment by corrados** [comment]
Regarding security issues, please read also https://github.com/corrados/jamulus/pull/380#issuecomment-647042975

**Comment by ann0see** [comment]
I‘d at least add an option somewhere to disable active links. Furthermore I‘d add a message which asks the user if he „really wants to visit https://www.example.com“

**Comment by corrados** [comment]
This is solved by the following Issue: https://github.com/corrados/jamulus/issues/591 -> closed.
