### ISSUE TITLE
Github "latest release" doesn't work?

### ISSUE THREAD

**Issue by gilgongo** [corrados/jamulus#362]
It seems that most repos have a link that shows the latest release (as used by https://gitreleases.dev), but Jamulus doesn't. Is that difficult to change? Might be useful to have for things like update scripts.

https://api.github.com/repos/corrados/jamulus/releases/latest

**Comment by corrados** [comment]
This should work now. The problem is that I have to remember to click the "publish" button on Github everythime I create a new release...

**Comment by gilgongo** [comment]
Yes, I guess there's no easy way of letting github know that something is a draught release or not.

I'll close this for now then.
