### ISSUE TITLE
Server window cannot be resized if "Make My Server Public" is unchecked

### ISSUE THREAD

**Issue by Skeezixes** [corrados/jamulus#364]
If "Make My Server Public" is unchecked, the Server window cannot be resized. This seems sort of silly, so I am inspired to want to fix it.
I know, not of major importance, just tidying up.

**Comment by corrados** [comment]
I cannot reproduce the issue under Windows. What OS are you using?

**Comment by Skeezixes** [comment]
10.15.5

**Comment by corrados** [comment]
I cannot reproduce this issue on my macOS 10.11.

**Comment by Skeezixes** [comment]
If, when the window first opens,  [  ] Make my server public is unchecked, then the window cannot be resized. If you check it then, the window becomes resizable. 

If, when the window first opens, [x ] Make my server public is checked and you uncheck it, the window is resizable.

**Comment by corrados** [comment]
That's what I have tried. And I could not reproduce your issue. It may be related to your macOS version. I cannot upgrade my Mac so someone else who has a newer Mac must try to reproduce this issue and fix it.

**Comment by gilgongo** [comment]
I can't reproduce on MacOS 10.15.4

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/4561747/84880606-a34b1580-b084-11ea-8a0d-00fc5aee7954.gif)

**Comment by Skeezixes** [comment]
I'm sure that under 10.15.5, it does (or doesn't) do this, but the issue is certainly not worth a lot of bother. Let's close it.

**Comment by corrados** [comment]
Ok, done.
