### ISSUE TITLE
Functionality of Server Name/Address on Connection Setup window

### ISSUE THREAD

**Issue by Skeezixes** [corrados/jamulus#365]
If the server I want to connect to is in the Server Name/Address dropdown (bottom of the Connection Setup window) but that server is not selected in the Server list (Server Name/Ping Time etc) and I click "Connect", I do not connect to it. The server must be selected in the Server list for the connection to be made.

1. What is the desired functionality of the Server Name/Address dropdown?
2. Is it needed?

MacOS 10.15.5, client and server running on the same machine.

**Comment by corrados** [comment]
> The server must be selected in the Server list for the connection to be made.

This is how it is intended. Either you select a server in the server list or you type in a custom IP address in the Server Name/Address dropdown.

**Comment by Skeezixes** [comment]
But I should think that if my server is in the drop down list it is
“selected” and if I click Connect then I should connect to it. But I don’t.
Would it work to have the dropdown control selection in the list, which
could be overruled by clicking on another server in the list? That would
fix the confusion, right?

**Comment by corrados** [comment]
Now I am confused...

**Comment by Skeezixes** [comment]
OK. I'll see if I can explain it better. When I open my Connection Setup window, the dropdown list has two entries, my server which happens to be called ChamberMusic, and "Legs" which is the name of my laptop on which both client and server reside. ChamberMusic is the item in the dropdown list that's visible. It's also in the server list, but it's not selected in the server list. 

Because ChamberMusic is the visible item in the dropdown list, that says to me that it's "selected" and so I click "Connect" thinking that I'm connecting to ChamberMusic. This doesn't work, of course. I have to click on it in the server list to select it, and then click Connect. This feels like I've just had to select it twice.

**Comment by corrados** [comment]
It seems you once have typed in these names and they got stored. When you highlight a row in the table, the name is displayed in the Servername/Address combo box but not stored. Can you try to delete the Jamulus ini file or start Jamulus with an empty ini file with --inifile? Then you will see that the combo box is empty.

**Comment by corrados** [comment]
Any updates on this matter?

**Comment by Skeezixes** [comment]
The inconsistency between what's selected in the dropdown and what's
selected or not selected in the server list frankly makes no more sense to
me now than it did before, although, of course, I have learned how to use
it. If I can't convince anyone else that what we have isn't great, then
what? We leave it.

**Comment by corrados** [comment]
The first step is to understand the implemented functionality. Second step is to start discussing the functionality.

You are the first one who reports issues with the Server Name implementation. Anybody else has issues with it?

**Comment by chrisrimple** [comment]
Restating the issue, which I've also seen...

Prior server connections are retained in the dropdown list.  One of those (likely my last server connection) is displayed in the edit field that is associated with the dropdown.  If I click Connect, nothing happens - the shown server name in the edit field is not used.  But if I click on the dropdown and select from it, then click Connect, I'm connected.

So it seems that the edit field should not be filled with "last connected server" on Jamulus client startup.

**Comment by corrados** [comment]
> If I click Connect, nothing happens - the shown server name in the edit field is not used. But if I click on the dropdown and select from it, then click Connect, I'm connected.

Does this happen for your for entries like a pure IP address? Because if I type in 127.0.0.1 (to connect to my local server) and close Jamulus, then restarting Jamulus and simply press Connect after the Connection Setup dialog (server list dialog) opened, it works fine for me.

**Comment by chrisrimple** [comment]
Did a little testing and maybe I misunderstand the purpose of the Server Name/Address edit field.  I'm on a Mac and my results:

- [Bug?] Only manually entered values are being retained in the dropdown list.  Servers that I select from the listbox and connect are never added to the dropdown.  So it's not very effective as a "history list" or a "reconnect to last server" list.
- [Bug] Manually entering a string that matches a server name from the listbox and clicking Connect does nothing.  I typed in "Buzzards" and "YACBJS", both servers in All Genres that are close to me, and clicking Connect dismissed the Connection Setup dialog rather than connecting.  Note that choosing a value already in the dropdown, to which I'd previously successfully connected, DOES connect - worldjam.vip was already in my dropdown list and choosing it will connect, as will a number of previously-connected IP addresses.
- [Bug] Manually entered server names have all spaces removed when retained in the dropdown list and edit field.  "NW WA" became "NWWA" and "Herd Immunity" became "HerdImmunity" after clicking Connect, seeing nothing happen, and bringing up the Connection Setup dialog again.

**Comment by corrados** [comment]
Ok, I see, copying the server name from the list in the combo box just causes confusion. I was implementing this to avoid confusion but that was a bad choice. So I'll change this in the code now.

The idea is that if you want to connect to a server in the list, you do not use the combo box at all. You simply select a server and click on Connect or double click the server in the list.

The combo box is just for the purpose to enter an IP address of the server or a known valid URL of the server. If you type in the server name of the server list, that will obviously not work.

**Comment by corrados** [comment]
Now I changed two things to make the situation clearer:
- When you change your selection in the server list, the server name is no longer copied in the Server Name/Address line edit.
- The title "Server Name/Address" is changed to "Server Address".

I hope with these changes the functionality of the "Server Address" line edit is clearer. What do you think?

**Comment by corrados** [comment]
I think I'll include my changes to the next Jamulus release. Than you all have a chance to test it. I'll close this Issue now. If after your testing there is still an issue with that GUI control, just re-open this Issue or create a new one.
