### ISSUE TITLE
Licence agreement function for server

### ISSUE THREAD

**Issue by gilgongo** [corrados/jamulus#367]
As per the discussion on this (https://github.com/corrados/jamulus/issues/314#issuecomment-643954741) and in order to avoid legal complications relating to GDPR and/or music copyrights, I propose we move to something like this (details like submit buttons, help text etc. pending):

Essentially, the ability for server operators to display an agreement of their choice (or not if they wish) to anyone who attempts to join their server (public or private).

![image](https://user-images.githubusercontent.com/4561747/84663267-d2427980-af14-11ea-8d3f-497c65ccc533.png)

I suppose we could "seed" the field with a statement of fact relating to GDPR like:

_"I agree that my profile will be displayed publicly for the purposes of differentiating me from other musicians on the server, and that my IP address will be displayed to server operators as part of Jamulus's necessary operation."_

**Comment by pljones** [comment]
To handle things like the Welcome message and the Licence message, it's getting to the point where adding tabs or something (you could build them even if Qt doesn't have them natively) becomes worthwhile.

Something like: "Who's on", "Make public", "Welcome & Licence", "Recorder".  (I guess Windows' Hide on start up stays on "Who's on"...)

Anyway, back on topic: in addition to having the text input box, a "Use file" option would be good.

**Comment by gilgongo** [comment]
Yes, I'd forgotten about the welcome message. It's sort of conceptually similar to the licence UI too, so we'd need to be clear about what it was (although I know Volker isn't a fan of welcome messages).

I'll have a think about arranging the UI bit I think...

**Comment by corrados** [comment]
These things are hard to implement. Problems: Compatibility to old versions (client/server), size of the licence message (could be blocked because of UDP packet fragmentation).

We now send a protocol message to request the licence dialog. What does a new client do with that message? Ignore it since the licence text was removed from the code?

Maybe the easiest solution would be to remove the licence check completely from the Jamulus software.

**Comment by gilgongo** [comment]
> Maybe the easiest solution would be to remove the licence check completely 

That's not as bad as it sounds, since they could if they wanted include a link to a licence or conditions of use in the Welcome Message. It would just be a passive rather than active agreement.

**Comment by gilgongo** [comment]
@pljones Tabs might group things something like this?

![image](https://user-images.githubusercontent.com/4561747/84750548-50edf400-afb3-11ea-91a3-7ac6ec62a5db.png)

**Comment by pljones** [comment]
Indeed.  I have a local branch named `coding-gone-mad` that started on this as part of my Jam Recorder changes...  Of course, it's nothing to do with the Jam Recorder changes directly...

**Comment by corrados** [comment]
@gilgongo I like your proposal for the tabbing of the server GUI. I have just implemented it accordingly:
![grafik](https://user-images.githubusercontent.com/46655886/87050378-7959be80-c1fe-11ea-8ea7-eb610f878abb.png)
![grafik](https://user-images.githubusercontent.com/46655886/87050405-824a9000-c1fe-11ea-88c8-0a55b68da887.png)
How do you like it?
Note that this does not address the things discussed here but is (as a first start) only the existing Jamulus server re-ordered in tabs.

**Comment by gilgongo** [comment]
Nice! So it should be quite scalable in the future when/if we have other Options, or if we ever wanted to have a third tab for thing not related to Setup or Options (like User Management, for example).

**Comment by corrados** [comment]
Yes, this way we do not need a separate settings dialog as we have in the client. BTW, now we can set the Welcome message in the GUI:
![grafik](https://user-images.githubusercontent.com/46655886/87075839-3d842080-c221-11ea-87c1-1007340a323d.png)

**Comment by corrados** [comment]
We now refer to the server welcome message in the licence accept dialog, see https://github.com/corrados/jamulus/issues/587#issuecomment-699513191. Therefore this Issue can be closed now.
