### ISSUE TITLE
Add a pt_BR translation

### ISSUE THREAD

**Issue by melcon** [corrados/jamulus#372]
How would one do about it? I would be happy to help with it.

**Comment by corrados** [comment]
Yes, sure. But in the current Jamulus implementation we just differ languages and no countries. So if you do the pt translation, it is for all countries.
Should I prepare the translation files for you or do you want to do it yourself?

**Comment by Snayler** [comment]
> Yes, sure. But in the current Jamulus implementation we just differ languages and no countries. So if you do the pt translation, it is for all countries.

So in this case what would happen to the pt_PT translation?

**Comment by melcon** [comment]
> So in this case what would happen to the pt_PT translation?
> 
> EDIT: Maybe #297 makes sense to allow people to choose the preferred language. Although pt_PT and pt_BR are essentially the same language, there are some differences in the way the language is spoken. I'm sure the same is true for Spanish and Dutch.

Yeap, I saw that there's a pt_PT already.  pt_BR and pt_PT are pretty much the same but as pointed by @Snayler , there are some small differences. I agree it would make more sense once #297 is implemented.

Anyways, I could start doing the pt_BR till there. I'm not sure what I need to prepare the translation files. Can you please point me in the right direction?

**Comment by corrados** [comment]
I have added a pt_BR translation file for you:
https://github.com/corrados/jamulus/blob/master/src/res/translation/translation_pt_BR.ts
I have initialized it with the content of pt_PT. Is that ok for you? If not, I can revert this change and let you start with an empty one if you prefer this.

**Comment by melcon** [comment]
That's ok. I'll start on that. Thanks

**Comment by corrados** [comment]
I just changed the code so that countrys are also considered: https://github.com/corrados/jamulus/commit/dbb0148a7045d9b9378a12cda13daa1fcd382a27
So it should work fine now when you add your BR translation.
@Snayler Can you please check if the new Git code works for you?

**Comment by melcon** [comment]
Nice. Should I use the File->Release menu on QT Liguist to generate a `translation_pt_BR.qm` before creating a PR or just the .ts file is enough?

**Comment by corrados** [comment]
The .ts file should be enough.

**Comment by melcon** [comment]
> The .ts file should be enough.

I'll keep that in mind for the next ones.
