### ISSUE TITLE
Jamulus 3.5.6 on PowerPC

### ISSUE THREAD

**Issue by Snayler** [corrados/jamulus#374]
Is it still possible to run Jamulus 3.5.6 on a PowerPC Mac? I know someone with a older Mac running on the PowerPC Architecture and he's using an older version of Jamulus, I would like to know if it would be possible to compile the newest version and how one would go about it. If someone already has the binaries, it would be greatly appreciated.

**Comment by corrados** [comment]
I think the problem is the Qt version. I have upgraded the Qt version on my MacMini so I cannot create such a binary.

I am curious: What is the latest Jamulus version which runs on that older PowerPC Mac?

**Comment by Snayler** [comment]
Sounds like I was induced in error, as the person says he's running 10.6.8, so it's not a PowerPC Mac. Given that the latest version of MacOS that runs on PowerPC is 10.5, I must assume he's on an intel Mac. The newest version of Jamulus he managed to run was 3.3.5. I'm waiting for an opportunity to gather more information on his setup, but since it's not related to PowerPC, I'm closing this.
