### ISSUE TITLE
Allow jamulus server to support multiple cores

### ISSUE THREAD

**Issue by sthenos** [corrados/jamulus#375]
We are finding that about the maximum number of clients on the most power single cpu server is about 35 people on a Google 3Ghz cpu burstable to 5Ghz, even if the server has multiple cores.   Whilst the overall cpu utilisation of the server on an 8xvCPU system never goes above 20%, the jamulus process uses 100% of cpu and then eventually degrades audio for everyone on the server and the overall delay jumps >500ms.   

It would be great if jamulus server could support up to 100 people on a single server and make use of the multiple cores available to it.  

![googlecpuchart](https://user-images.githubusercontent.com/11177553/85132304-6885e080-b230-11ea-8b7a-60e5590c93a6.png)

This chart shows our large 8 core 16GB GCP VM and the red circles indicate when the server began to degrade audio for people on the room.  When people people the room, the server recovered.

**Comment by sthenos** [comment]
![GoogleInstancedetails](https://user-images.githubusercontent.com/11177553/85132472-c5819680-b230-11ea-97c6-995f0ccb904c.png)

Sorry the RAM is 8GB not 16GB

**Comment by corrados** [comment]
I just added some experimental code for OMP in the Git repo: https://github.com/corrados/jamulus/commit/3ac8a2de8dcc7766d8e8ce250e21de426d236b72
I you want to give it a try, use:
qmake "CONFIG+=multithreading"

**Comment by WolfganP** [comment]
Quickly looking at the code, that `for` includes the call for the opus encoder. I wonder if there's any optimization for multithreading in the codec code that may help as well...

**Comment by WolfganP** [comment]
Kind of answering to myself... https://github.com/xiph/opus/issues/163

**Comment by sthenos** [comment]
Excellent thank you!  I'll do this one of my big servers and see what happens during tomorrow's jam

**Comment by corrados** [comment]
Yes, you can do not. But be careful, the code might be instable and do not work as expected. I did some tests on my laptop and it seems the CPU load is much too high. But at least it is spread over all CPU cores :-). If you do you test, you should only apply it to uncritical servers, i.e. not servers which stream to Facebook.

**Comment by corrados** [comment]
I think the topic in this Issue is already covered by the existing one: https://github.com/corrados/jamulus/issues/339. Maybe we should close this Issue and continue the discussion in the existing one. What do you think?

**Comment by sthenos** [comment]
ok thanks - fine with me

**Comment by corrados** [comment]
I did some more tests. Unfortunately, the OMP implementation does not work as expected. Using the current Git code, the Jamulus server runs on much too high CPU if OMP is enabled. I did some tests and even if I just use the following code inside the OnTimer() function:
```
#ifdef USE_OMP
# pragma omp parallel for
#endif
for ( int z = 0; z < 1; z++ )
{
    static int test = 0;
    test++;
}
```
the CPU usage is very high which does not make sense. Somehow the OMP in general has a problem when used inside the OnTimer() function of the Jamulus server.
Anybody has an idea what could go wrong here?

**Comment by WolfganP** [comment]
I didn´t follow the full code so I don´t know how often OnTimer()-for loop is called or if it's just once per session, but may be the case that the cpu usage you observe is the overhead of threads creation/destruction?

**Comment by corrados** [comment]
> overhead of threads creation/destruction

Thanks for that hint. Yes, I agree with you, I assume that this is the case. The OnTimer() function is the core processing loop in the server and will be called every 2.7 ms.

**Comment by WolfganP** [comment]
Just for easier reference, performance tests discussed at https://github.com/corrados/jamulus/issues/455
