### ISSUE TITLE
Cost of running -F on a server?

### ISSUE THREAD

**Issue by gilgongo** [corrados/jamulus#376]
This came up in a forum post and I thought it might worth clarifying in the docs. If a server operator turns on fast update, are there any disadvantages of doing so? I'm assuming increased bandwidth use or CPU?

**Comment by corrados** [comment]
If you run the server without -F and a client with 128 samples block size connects, the time to encode/decoder the OPUS packets are 2.7 ms. If you use the -F option, the server only has half the time to do that, i.e. 1.3 ms. That may lead to crackling sound if the CPU is not fast enough.

**Comment by gilgongo** [comment]
OK so server operators might need to be careful they have enough CPU (eg if there are perhaps high numbers of 128 block size clients connected).

**Comment by corrados** [comment]
Also, the network load will be higher if a client using 64 samples buffer size and "Enable Small Network Buffers" enabled is connecting to the server.
