### ISSUE TITLE
Save and restore mixer state (fader / mute / solo...) 

### ISSUE THREAD

**Issue by newlaurent62** [corrados/jamulus#377]
Hello,

To stream web concert with Jamulus and several band, it would be nice to let the user save and restore the mixer state (fader, mute, solo,... ) 

Each musician would have a unique and same channel name or a channel uuid across connections. If a musician is disconnected then when reconnected, the level, mute and solo should be the one of the current preset for that channel or the default.

BR, 
Laurent

**Comment by corrados** [comment]
This is already supported in the Jamulus software.

**Comment by newlaurent62** [comment]
Can we name the presets ? Like first song mixer, second song mixer ...

**Comment by corrados** [comment]
Yes, you can do this. Start Jamulus with Jamulus --inifile "c:\temp\jamulussetup1.ini".
Just do your session, than disconnect and close the Jamulus software. Then all fader settings are stored in the ini-file. If you then want to store another session, simply copy the file jamulussetup1.ini to jmulussetup2.ini and start with --inifile "c:\temp\jamulussetup2.ini". If you then done with the storage, and want to recover the first session, then simply start Jamulus with the first file again.

**Comment by newlaurent62** [comment]
I will try that but it would be easier to have a preset handling in the gui (preset save/load button)

**Comment by gilgongo** [comment]
I've added this to the [Tips & Tricks](https://github.com/corrados/jamulus/wiki/Tips,-Tricks-&-More#saving-client-mix-states-between-sessions)

**Comment by pljones** [comment]
I have a client and server ini file overhaul sitting here on a branch...  It's actually quite a large task to get it right...  (At the moment, the ini file is handled on start up / shut down; it needs to change to be more dynamic to get this to work, which means a _lot_ of changes.)

**Comment by melcon** [comment]
> Yes, you can do this. Start Jamulus with Jamulus --inifile "c:\temp\jamulussetup1.ini".
What's the equivalent for Mac?

**Comment by gilgongo** [comment]
Open a Terminal window, type:

~~~
/Applications/Jamulus.app/Contents/MacOS/Jamulus --inifile /path/to/somewhere/jamulussetup1.ini
~~~

Hit return key.

**Comment by newlaurent62** [comment]
Considering a concert streaming : Each musician is connected to Jamulus and an additionnal Jamulus client (called "Streamer") will handle the output streaming mix of the musician playing and will be send to a social network or icecast2 using OBS.

The store/load of fader/pan mixers is intended to help handling the streaming of a Jamulus concert. This would allow to prepare each song settings before the concert begins and recall them as needed during the concert. An easy and fast action to store/load would be preferable. Closing the Jamulus client should not be needed.

May be, it would be better to let the user dispose of a jack client with a port for each channel from the server or a special client to the server with an output jack port for each channel. This would allow to put some VST/LV2 on channels and making sub groups for a more complex mix in a DAW that otherwise would be impossible.

**Comment by corrados** [comment]
See my comment https://github.com/corrados/jamulus/issues/347#issuecomment-655554694 and the following discussion.

**Comment by corrados** [comment]
This is implemented now. It is available on Git master -> closed
