### ISSUE TITLE
Swedish translation

### ISSUE THREAD

**Issue by genesisproject2020** [corrados/jamulus#378]
I like to help adding Swedish translation. Can I get some help with an empty translation file that I can start with?

**Comment by corrados** [comment]
Sure, I just added the file for you: https://github.com/corrados/jamulus/blob/master/src/res/translation/translation_sv_SE.ts

**Comment by genesisproject2020** [comment]
Thx. I have now done a first complete translation to Swedish and supplied it. There will probably be need for some changes but it’s a good start.

**Comment by corrados** [comment]
Any updates on the Swedish translation?

**Comment by genesisproject2020** [comment]
How do I compile it so I can get the translation in the client?
(Its ready to be used.)

**Comment by corrados** [comment]
The usual way to do it is to make a pull request with your modified .ts file. I will then merge that pull request and update the .qm file. Then you can use the latest Jamulus Git master code and test your translations.

**Comment by genesisproject2020** [comment]
I think I've made my first pull request. :)

**Comment by corrados** [comment]
Something went wrong, I cannot see your pull request. Have you used the correct target branch?

**Comment by corrados** [comment]
I have now created and merge a pull request from your branch since I want to add new strings to translate and did not want to risk merge conflicts. Thanks for your contribution!

**Comment by genesisproject2020** [comment]
Updated the translation.

I do have a question about 519 around line 2541. I have two entries for 519 and do not know how to do the translation in the best way.

**Comment by corrados** [comment]
You should not edit the xml file directly. I recommend to use the Qt Linugist tool (https://doc.qt.io/qt-5/qtlinguist-index.html).

**Comment by genesisproject2020** [comment]
Thx. I created a new file with the latest changes. It should now be okay.

**Comment by melcon** [comment]
Just in case: https://download.qt.io/linguist_releases/

**Comment by genesisproject2020** [comment]
I've today updated the translations so it's in line with the current release.
