### ISSUE TITLE
Add send button to chat window

### ISSUE THREAD

**Issue by Hk1020** [corrados/jamulus#384]
We had quite a few people new to Jamulus recently who thought the chat window isn't working. They tried to enter their text in the large window above the actual one line answer window.

I'd suggest to add some placeholder text to the one line window and also a send button. Although hitting enter is much faster people seem to expect a send button these days.

**Comment by corrados** [comment]
I was also thinking about this some days ago. Then I looked at Skype and Whatsapp but both do not have a send button. Both have a placeholder text like "Type your text in here" or something similar. Maybe this would be better than a send button.

**Comment by corrados** [comment]
Wow, that was simple. Qt already has a property for the edit box for that:
![grafik](https://user-images.githubusercontent.com/46655886/85220063-043a5c80-b3a9-11ea-972d-f530b97cba01.png)
What do you think? Maybe we should start with this and see if users still have issues with the chat window.

**Comment by Hk1020** [comment]
Looks great. Exactly what I had in mind. 

I’d add a send button at the end of the same line. Microsoft Teams has one there. But it makes more sense there as you can send multiline messages in Teams. Same with iMessage. Some people are just not used to send anything with the return key. 

Anyway, do as you like. And thanks a lot for the quick reply and Jamulus in general.

**Comment by corrados** [comment]
It would be no big deal to add a send button. But I just looked at "Teams" screen shot and found, e.g., this one: https://pulse.microsoft.com/uploads/prod/2019/06/SUR18_Team_FirstLineWorker_Screenshot-1536x1024.jpg
It seems there is no real button but a symbol at the lower right corner. Is that what you are referring to?

**Comment by Hk1020** [comment]
Yes it is.

**Comment by corrados** [comment]
I just added a send button:
![grafik](https://user-images.githubusercontent.com/46655886/85224871-a0765a80-b3cd-11ea-8f05-0c35e5bde739.png)

**Comment by Hk1020** [comment]
Thanks, that’s it.
