### ISSUE TITLE
Proposal: retry on loss of registration

### ISSUE THREAD

**Issue by pljones** [corrados/jamulus#392]
I just realised my server has once not got a response to its regular updates:
```
...
Jun 21 20:45:07 fs-peter Jamulus-server[8417]: Server Registration Status update: Registered
Jun 21 21:00:07 fs-peter Jamulus-server[8417]: Server Registration Status update: Registration requested
Jun 21 21:00:07 fs-peter Jamulus-server[8417]: Server Registration Status update: Registered
Jun 21 21:15:07 fs-peter Jamulus-server[8417]: Server Registration Status update: Registration requested
Jun 21 21:30:07 fs-peter Jamulus-server[8417]: Server Registration Status update: Registration requested
Jun 21 21:30:07 fs-peter Jamulus-server[8417]: Server Registration Status update: Registered
...
```
Given that, on first registration, up to five failed attempts are retried, should a server that has been successful in registration revert to retrying if it subsequently fails to get a response?

I've also a situation like:
```
Jun 18 08:22:01 fs-peter Jamulus-server[1120]: Recording state enabled
Jun 18 08:22:01 fs-peter Jamulus-server[1120]:  *** Jamulus, Version 3.5.7git
Jun 18 08:22:01 fs-peter Jamulus-server[1120]:  *** Internet Jam Session Software
Jun 18 08:22:01 fs-peter Jamulus-server[1120]:  *** Released under the GNU General Public License (GPL)
Jun 18 08:22:01 fs-peter Jamulus-server[1120]: Server Registration Status update: Bad address
Jun 18 08:37:01 fs-peter Jamulus-server[1120]: Server Registration Status update: Registration requested
```
That is, the server tries to register but gets told the central server address is bad.  Without any change, 15 minutes later the attempt succeeds.  Would an earlier retry have worked?

**Comment by corrados** [comment]
> I just realised my server has once not got a response to its regular updates:

That is no problem. The registration is configured as:
SERVLIST_TIME_OUT_MINUTES        33 // minutes (should include 3 UDP registration messages)
SERVLIST_REGIST_INTERV_MINUTES   15 // minutes
So if one or even two intermediate registrations fail, the server still stays registered.
If the internet connection is so bad that three attempts fail, then the server should not be listed anyway ;-).

**Comment by pljones** [comment]
Ah right.
