### ISSUE TITLE
Hidden empty servers

### ISSUE THREAD

**Issue by Lucafeelgood** [corrados/jamulus#397]
Hi, is it possible to put a switch to show or hidden servers with no users inside?
Thanks

**Comment by corrados** [comment]
I have found a simple solution for your feature request. I have introduced a special filter character "#". If you set this in the filter edit box, you will see only the occupied servers:
![grafik](https://user-images.githubusercontent.com/46655886/86506312-a3f6e200-bdce-11ea-9cd1-a52163bedd2c.png)
I also changed that the filter is not cleared if you switch to another server list. This way you can set "#" as the filter and switch the Genres and only see the occupied servers of each Genre.

**Comment by Lucafeelgood** [comment]
Nice idea, thank you so much

**Comment by corrados** [comment]
Good that you like it :-). I'll close this issue now.
