### ISSUE TITLE
Problems when running client and server simultaneously

### ISSUE THREAD

**Issue by brianmountford** [corrados/jamulus#40]
Both I and my friend have had the same problem when trying to run the Jamulus client and server simultaneously on a Mac on a home network. The client can connect to the server just fine. We do port forwarding on our home router so that the other person can connect in remotely. At first the remote connection seems to work fine as well. But after a short period of time (less than a minute), the remote client connection goes silent, only occasionally letting through a very short burst of sound. I'm sorry to file a bug with so little solid documentation, but it happened relatively reliably. When I ran only the server and not the client, the remote connection appeared to work fine. So I suspect some kind of interaction between the client and server, but don't really know. We were both running relatively modern versions of Jamulus, installed between a month and a week ago.

**Comment by gilgongo** [comment]
OK so you have:

- Machine A running a Server and ClientA behind NAT router with port forwarding
- Machine B running a ClientB behind NAT router with no port forwarding

Machine B can connect to Server on Machine A, but only for short periods.

Just some initial questions:

1. Did you compile the Jamulus binaries according to the [INSTALL.md](https://github.com/corrados/jamulus/blob/master/INSTALL.md)?

2. I'm assuming the Server is configured as a private server (so un-checked "Register my server...") and that it's running on the default port 22124. Also that ClientA can connect to Server OK. Is that correct?

3. Are you using the Server's LAN address to connect ClientA?

**Comment by brianmountford** [comment]
1. We are running on Macs. I just installed the pre-compiled Mac version, and I assume my friend did likewise.

2. Correct.

3. We are using what I assume is the router's external IP address to connect, and then the router is forwarding the port. The connection appears to work; even when it goes into silent mode, both clients still show each other as connected to the server.

**Comment by gilgongo** [comment]
This forum thread may also be related: 

https://sourceforge.net/p/llcon/discussion/server/thread/0566755f65/

**Comment by gilgongo** [comment]
> I just installed the pre-compiled Mac version

Where did you get this from? There is at least one pre-compiled binary out there that is known not to work properly.

**Comment by gilgongo** [comment]
(Sorry, - ignore question 1, I forgot we were talking about Mac not Linux)

**Comment by brianmountford** [comment]
Ok, we tested again just now. I am running 3.4.5 on the Mac. I started the server (with -s and -a) and client. I connected the client to my externally-visible IP for my router, and my friend connected remotely (to the same IP). After a little while (a couple minutes at most), all sound was lost, save for a 200ms burst every 5 seconds or so. We could not hear each other, nor could we even hear the echo of ourselves. It seems like the server was terminally confused. When we both disconnected and reconnected, it healed itself for a few minutes, then got messed up again. I tried connecting my local client to my locally-assigned IP address, but the same thing happened. Let me know if you need any other information.

**Comment by pljones** [comment]
I'm wondering if the version I'm working on may address this some how...

**Comment by brianmountford** [comment]
W'd be happy to try it out when you are ready. It wasn't too hard to replicate the problem.

**Comment by pljones** [comment]
OK, pull the latest master and try.

(Note don't try server recording - I've a fix there to do for one of Volker's changes.)

**Comment by gilgongo** [comment]
@brianmountford I think you will need to compile it to get the 3.4.7git release which contains this fix.

**Comment by brianmountford** [comment]
I see that 3.4.7 is now the current release. Can I just use that one?

**Comment by gilgongo** [comment]
Yes, you should always try to use the current release if you can.

**Comment by pljones** [comment]
Hi, any update on this?  (Again, grab the latest version - 3.5.1 or later.)

**Comment by brianmountford** [comment]
We had tried with 3.4.7, and had the same problem. I guess I can keep trying with a newer version. So I understand, should I try new versions because changes have been made to attempt to address such issues, or because we just hope that the problem will eventually get fixed as a result of other work being done?

**Comment by pljones** [comment]
Because the latest version is the one just out of development.  Earlier versions are "dead" in that sense.

If the problem isn't reported in the latest version it will, in time, be considered a "dead" issue, too.

So if you're still having the problem, the very first thing to do is to see if it still happens in the latest version - because that's the version nearest what's being worked on now.  If the issue is there, it may well not be dead, so still needs fixing.

That applies to pretty much any program by any small development team.

In this case, I explicitly said 3.5.1 or later, so trying with 3.4.7 hasn't helped.

**Comment by corrados** [comment]
Here is an interesting post about OS priorities: https://sourceforge.net/p/llcon/discussion/server/thread/5d82abac76/#00a7/b575/5983
Maybe this is something we should consider if the server runs on the same PC as the client. Maybe it is wise to give the server a higher priority than the client in that case.

**Comment by brianmountford** [comment]
Thanks. We were actually seeing quite strange behavior when I last tested this -- the ping time would go to ">500 ms", and the sound would cut out entirely. I don't think it would be because my computer was completely bogged down, since I was the only one on the Jamulus session. I have the feeling that something else must be at work. However, since one can only fight so many technical battles at once, we have decided to stick for now with our GCP server. And when we did a livestream last night, I ran two clients by having one on my laptop, where I was singing along with a dozen other Jamulus users, and another client on my desktop, running OBS, Isadora for some video effects, a DAW, and Zoom for the video feed. That setup worked pretty well, so I think we're just going to go with that for the moment. Maybe in the long run, a Jamulus server and multiple clients will start playing nice on the Mac, and I can consider consolidating, but I will leave that to others to figure out in the meantime. :)

**Comment by brianmountford** [comment]
P.S. Kudos to Jamulus generally.

**Comment by corrados** [comment]
Here is some info about issues when running client and server on the same PC: https://www.facebook.com/groups/619274602254947/permalink/665245477657859

**Comment by gilgongo** [comment]
Is this still a problem or does it only happen in very specific circumstances? I'm pretty sure I see people imply they're running clients and servers on the same machine without issues quite regularly on the forums.

**Comment by brianmountford** [comment]
To be honest, I haven't tried. We run our server on an VM on Google Cloud, which has pretty reliable performance for us, and then I connect from two computers, one with my microphone and audio interface, so I can sing, and the other with a DAW and OBS, to stream to YouTube. I don't know whether the problem I had before would now be fixed, but since the problem seemed to happen both on my computer and on my friend's, we decided to go with a solution that worked for us, and have just stuck with it.

**Comment by pljones** [comment]
Anyone object to this being closed?  I've not been able to reproduce it on Windows or Linux.

**Comment by brianmountford** [comment]
I have moved away from running a server on my local machine, so I don't have any data on whether this is still a problem. Ok to close from my point of view.
