### ISSUE TITLE
Incorrect selection of UI language

### ISSUE THREAD

**Issue by Skeezixes** [corrados/jamulus#408]
v. 3.5.7
For the first time, the Jamulus UI is French, for some reason. Why? And how can it be changed to English?

**Comment by corrados** [comment]
Start with the -t command line parameter.

**Comment by Skeezixes** [comment]
How is the default UI language determined? It’s no longer English?

**Comment by corrados** [comment]
Based on your OS system language and location settings. I guess you have set either your language to French or your location to France, right?

**Comment by Skeezixes** [comment]
Nope. I have several languages set in the Keyboard preferences (English,
French, Georgian) but my location is “Cupertino, CA” and neither keyboard
nor location/time zone settings changed between v 3.5.6 when Jamulus was
English and 3.5.7 when it became French.

**Comment by corrados** [comment]
This is bad news... I changed the selection of the language recently to support, e.g., Brazilian Portuguese. But it seems that did not work as expected.

**Comment by corrados** [comment]
I'll fix that in the next Jamulus release.

**Comment by Skeezixes** [comment]
If it helps, my Keyboard preferences are set to: U.S., Greek, Icelandic,
French, Georgian, in that order. U.S. was selected.

L

**Comment by corrados** [comment]
@Skeezixes I have just release a new version of Jamulus 3.5.8. Can you please check if that new version gives you the correct GUI language even if you do not use the -t command line argument?

**Comment by Skeezixes** [comment]
Will do.

**Comment by Skeezixes** [comment]
Much better! Both client and server look good. Thanks for the prompt fix.
