### ISSUE TITLE
Empty server list, which finally refreshes

### ISSUE THREAD

**Issue by Skeezixes** [corrados/jamulus#409]
v. 3.5.7, MacOS, server & client running on the same machine
I just installed this version. When I tried to connect to my server, the server list for the sub-genre my server is listed under was blank. I clicked to the other genre lists, which were populated, and back to mine, which was blank. My server's genre list remained blank for maybe a minute, maybe two, and then refreshed.

**Comment by pljones** [comment]
Each genre is server by a different server so you need to say which genre.

**Comment by Skeezixes** [comment]
Yes. I know. I said which genre when I started my server. It would always
show up at the top of that genre list. With this release, that genre list
was blank, unpopulated, and as I was writing the bug report, suddenly the
list of servers appeared, with mine at the top, as usual. This can't be as
desired.

**Comment by pljones** [comment]
I mean no one can help you unless you say which genre server you were registering with because each genre server is separate and hosted across multiple sites.  You have not stated which genre.

**Comment by Skeezixes** [comment]
Sorry. I misunderstood. It’s the Classical, Folk, Choir server.

**Comment by pljones** [comment]
OK, you may have been updating it at the same time I was updating, or shortly before.  In that case, you're registration would have been lost, along with everyone else's, until they re-register 15 minutes later.

**Comment by corrados** [comment]
As far as I understood, the issue was that the central server was offline causing the mentioned issue, right? If this is the case, please close this Issue.

**Comment by Skeezixes** [comment]
Yes, the problem has not reoccurred.
