### ISSUE TITLE
Create a new, modern app icon for Jamulus

### ISSUE THREAD

**Issue by corrados** [corrados/jamulus#410]
The Jamulus icon and other pictures are very old and were created by myself. I am not a designer and therefore the quality of the icon is not very good.

Therefore, a designer is currently working on creating a new, modern icon for Jamulus.

**Comment by sthenos** [comment]
Do you need any help designing the icon/artwork?   I have some good graphic designers on the World Jam group if you need assistance

**Comment by corrados** [comment]
Thanks for your offer. But the designer I am in contact with has already created the new icon which will be applied to the Git repo soon.

**Comment by corrados** [comment]
Thanks to Martin, here it is, the new Jamulus icon:
![grafik](https://user-images.githubusercontent.com/46655886/86255069-fc539700-bbb6-11ea-9b1b-5fb35ae6ebba.png)
![grafik](https://user-images.githubusercontent.com/46655886/86254993-e514a980-bbb6-11ea-83e6-dfad797d9196.png)

**Comment by corrados** [comment]
To give you a little more background info about the new icon. Martin interpreted the name "Jamulus" as being derived from Jam and Cumulus Cloud. This was not my intention when I defined the name but I very much like this new interpretation. Therefore the icon is a cloud. The flash was not in Martins initial proposal but I thought we should at least take one peace from the old icon so that you have some sort of recognizable.

**Comment by melcon** [comment]
>... Jamulus" as being derived from Jam and Cumulus Cloud
I always thought the same. Now I know I wasn't alone :). Just for the sake of curiosity, where the name came from?

**Comment by corrados** [comment]
I like the Latin word "Oculus". It was initially derived from that word.
