### ISSUE TITLE
Ability to rename the Jamulus window title and save a profile

### ISSUE THREAD

**Issue by sthenos** [corrados/jamulus#412]
Quite a few of us are now running multiple jamulus sessions (so you can have two independent channels one for mic and one for an instrument) or for monitoring and streaming audio from one room to another.

It would be good if we can rename a jamulus window title and save that along with your profile details to different profiles.

**Comment by Snayler** [comment]
There are already options to do this on the Command Line Section of the Wiki. Check --inifile and --clientname

**Comment by sthenos** [comment]
Brilliant thanks!  I'll close
