### ISSUE TITLE
Ability to remove servers from a central server you manage

### ISSUE THREAD

**Issue by sthenos** [corrados/jamulus#413]
I run a central server:  World Jam.   It would be good if I could have the ability to remove servers that publish themselves to it.     At the moment, I have to figure out who owns the server and then message them directly somehow and ask them to switch it off.   If there was a flag, that unregistered all servers that would be good.   I can't even really do it using the firewall either as there is no way to distinguish a user requesting the serverlist versus a server registering itself.

**Comment by gilgongo** [comment]
" there is no way to distinguish a user requesting the serverlist versus a server registering itself."

Not sure I follow. Could you not drop the route on the IP you see in the server list? Not ideal though, obviously.

**Comment by melcon** [comment]
Maybe add a sort of passphrase/key to be matched then allow the servers to be registered/listed on the central server. If no passphrase/key then any server can register itself

**Comment by corrados** [comment]
A passkey does not make any sense. You could simply only tell the guys whos shall register to your list the URL/IP-address of your central server.
Simon has a special case since he publishes his address in the Worldjam group.
Simon, what about two central servers? Create one additional just for the Worldjam event. Only publish that URL in the current song list of that jam. People have to register to access the song list so you control over who sees the URL.

**Comment by pljones** [comment]
What if the number of "open" slots on a central server could be specified (like the number of user connections on a server can)?  Then you could use the start up list on the central server to specify the "registered" known servers and ignore any additional ones.

**Comment by jp8** [comment]
I believe I will have a somewhat similar requirement in the future for music schools.  I will want to control which servers are visible to which clients.  I imagined I would have to do it with firewall rules but if some functionality is to be added to the code for the main central server, it would help me to be able to specify, for each connected server, a list of IP ranges that will see that server in the list.

**Comment by sthenos** [comment]
I would rather not have to manage this with firewalls (I do currently and it's a pain).  Would what be really good is to have a command that I send to the server (central server in this case) which causes the central server to de-register a server from a particular IP/port.    jamulus could listen on a specific admin port for control messages:

`$wget --post-data "action=deregister&ip=10.10.10.10&port=123" "http://localhost:3333"`

**Comment by corrados** [comment]
I was more thinking of a possible blacklist which is a simple file listing server names or IP addresses which should be blocked. If the file exists, the server reads it and applies the rules when a register request is incoming.

**Comment by corrados** [comment]
@sthenos Supporting a "whitelist" would not be a big deal. I think this would be the perfect solution for your World Jam central server since you exactly now which servers you want to allow. So you can make sure only these are registered. The whitelist could contain the IP address filter, an additional port filter or even filter for server names.

If the whitelist would be a solution which works for you, I could start looking at the implementation.

**Comment by sthenos** [comment]
Actually yes a whitelist is perfect.  Just a list of IP/hosts in a file or comma/semicolon seperated list on the command line would be perfect!

**Comment by corrados** [comment]
I have just finished the implementation. The new code is available on Git master. Here is what it looks like:

```
corrados@lubuntufd:~/jamulus$ ./Jamulus -s -n -e 'localhost' -f "192.168.178.33;127.0.0.1;10.114.2.14;27.27.27;test"
- server mode chosen
- no GUI mode chosen
- central server: localhost
- server list filter: 192.168.178.33;127.0.0.1;10.114.2.14;27.27.27;test
Whitelist entry added: 192.168.178.33
Whitelist entry added: 127.0.0.1
Whitelist entry added: 10.114.2.14
Whitelist entry added: 27.27.0.27
Recording state not initialised
 *** Jamulus, Version 3.5.10git
 *** Internet Jam Session Software
 *** Released under the GNU General Public License (GPL)
```
The IP addresses are separated with a ;. In my example I added invalid addresses, too.

@sthenos Can you please test the new implementation if it works for you and if you are happy with it? If yes, then I think we can close this Issue.

**Comment by sthenos** [comment]
Awesome!!

I'm away on holiday but back on tuesday so I can test then.

**Comment by gilgongo** [comment]
Will it blacklist itself if you don't whitelist localhost?

**Comment by corrados** [comment]
No, that was just an example. Of course, the Central Server itself is always present in the list, regardless of any whitelist.

**Comment by ann0see** [comment]
@corrados The -f cli argument isn't documented yet in the wiki but seems to show up if you run Jamulus -h. Should it be added to the wiki or do you wait until this issue is closed?

**Comment by corrados** [comment]
Yes, please add it to the Wiki.

**Comment by ann0see** [comment]
Ok. Done. Probably this is central server only?

**Comment by ann0see** [comment]
Can this issue be closed now?

**Comment by corrados** [comment]
Yes, I think it is ok to close this now.
