### ISSUE TITLE
Even crackles when connected to localhost server.

### ISSUE THREAD

**Issue by 38github** [corrados/jamulus#418]
When connecting to a localhost server (3.5.8, Windows 10 x86_64, airplane mode) I get crackles. I am using a sine tone generator in REAPER and connecting it to Jamulus using ReaRoute ASIO and then bring it back to REAPER. Reaper has one track with the JS plugin called tone generator and a second that has the ReaInsert plugin to bring back the signal to REAPER.

In the video I will add I used ASIO4All in REAPER but also tried Focusrite latest drivers for Scarlett 2i2 which was even worse.

How come it gets buffer problems on a localhost (127.0.0.1) and sounds bad? Sometimes it kind of works and there are almost no artifacts.

Video:
https://streamable.com/96s1mm

**Comment by 38github** [comment]
These artifacts are not heard in REAPER when not sending it to Jamulus and back.

**Comment by pljones** [comment]
Have you tried non-local hosts?  Could you also provide details about buffer sizes in your sound card, Reaper, use of small network buffers in the Jamulus client and fast update in the server.

**Comment by 38github** [comment]
> Have you tried non-local hosts? Could you also provide details about sample rates and buffer sizes in your sound card and Reaper and use of small network buffers in the Jamulus client and fast update in the server.

It happens on remote servers too, public and private. It also crackles without using any middle man (Reaper). I use 48000 Hz since we have to and I believe that the sound card used 128ms latency but it also happens when I use 64 and 256ms. I have used both with and without small networks buffers and the difference is not night and day. I have also tried all this in Fedora 32 with JACK (64, 128 and 256ms latency) and I experience the same thing. Using JACK and normal playback of audio with Reaper or Deadbeef produce no issues at all.

It is strange to me that the crackling/buffer behaviour is present on a localhost server.

**Comment by pljones** [comment]
Ignore for now the localhost idea as you've said it makes no difference.

Do either of the Buffers or Delay LEDs light up on the client UI?

Are you using Auto Jitter Buffer?  If not, what values do you use?

**Comment by 38github** [comment]
> 
> 
> Ignore for now the localhost idea as you've said it makes no difference.
> 
> Do either of the Buffers or Delay LEDs light up on the client UI?
> 
> Are you using Auto Jitter Buffer? If not, what values do you use?

Thank you for replies, pljones. If you watch the video in post #1 you will see the settings of the client and how it behaves. Regards.

**Comment by pljones** [comment]
Is there something running on your computer that might be interfering with your networking?

**Comment by 38github** [comment]
If there is anyting it is Windows' services and Lenovo updates application that I know of.

**Comment by 38github** [comment]
Is it possible that some computers have really bad network controllers? I know that I should not use Wifi but I had to try it out to see how it behaves. I noticed that between two different wifi usb dongles it was a massive difference in ping and gargling and crackling sound. Is a computer with a dedicated graphics card prefered? I wonder bcause I notice when moving something around on the monitor sometimes also throws Jamulus of and produces artifacts.

These things, except potentially graphics, should not interfere with Jamulus/sound card, right?

What kind of computers do you guys have who have like no problems at all?

**Comment by pljones** [comment]
Only ever use hard-wired, real ethernet with no Wifi enabled.  (No ethernet "repeaters" and no Wifi enabled on the DSL router/modem, either, but those shouldn't affect the localhost issue.)  On my audio PC(s), I always disable as many services as I can that I don't need (you can find guides aplenty on configuring Windows for real-time audio).

I can't remember the spec of the first machine I ran Jamulus on but it was fine on my AMD FX-8350 machine with an Echo AudioFire4 soundcard, running Windows 7 to 10.  It's got a dedicated video card but it's pretty low spec (so passively cooled).  My new machine uses the onboard graphics (as I couldn't find a passive card).

**Comment by gilgongo** [comment]
You could try sticking the [Jamulus live USB](https://sourceforge.net/projects/jamulus-os/) version in it and see if that's any better.

Even if you don't end up using it for real, you might be able to isolate some problems perhaps?

**Comment by 38github** [comment]
I would like apologise for taking up your time. After trying out many things without success I went into the BIOS where I have only changed boot device and legacy/UEFI settings. I loaded default settings just see if it would somehow reset any potential bad things and then changed the boot device and UEFI settings so that my computer boots correctly. Now Jamulus works really well. Strange.

**Comment by corrados** [comment]
That's really strange... Shall we close this Issue now?

**Comment by 38github** [comment]
Yes, you can close it. Sorry for taking up your time. A request, setup somewhere where we can donate to this project, please.

Jul 6, 2020, 16:34 by notifications@github.com:
