### ISSUE TITLE
Volume issues using groups feature with 3.5.7

### ISSUE THREAD

**Issue by artaudiocanada** [corrados/jamulus#419]
Hello all..

Last night I noticed a small issue while using the grouping feature. After selecting a group of musicians , if I pull down the highest fader to the bottom and then return it back. I notice the volume for all the effected channels will remain at nil and won't come back until I remove the musicians from the group and then reset their fader position.

FYI Using windows 10 BTW

Thanks for the great work.
Al T

**Comment by corrados** [comment]
Thanks for reporting. The grouping of faders is heavily re-worked right now. See the discussion in https://github.com/corrados/jamulus/issues/202. As you can see in the GIF video, the bug is already fixed.

**Comment by corrados** [comment]
Ok, the new grouping code is done in the Git repo. The problem you described should be solved in the next Jamulus version. I'll close this Issue now.
