### ISSUE TITLE
Manual clip LED reset

### ISSUE THREAD

**Issue by fleutot** [corrados/jamulus#421]
As a musician, I want to quickly check my input does not clip , so that I can correct my input level quickly.

After adjusting my input level, I want the clip LED to reset since its state is tied to my old input level.

Jamulus cannot know that I changed my input level, probably in hardware gear.

Suggested solution: let the user manually reset the clip LED after adjusting their input gain.

**Comment by corrados** [comment]
I just implemented this request similar to what you have implemented in your original code. But I do not combine the level meters so you can reset the left and right channel separately.
