### ISSUE TITLE
Allow sorting Server list by other than Ping Time

### ISSUE THREAD

**Issue by fleutot** [corrados/jamulus#424]
I usually double click on the server to join. I was on the World Jam Night 13, and while attempting to enter a Waiting Room server, the list reordered in the middle of my double click, and I entered the studio. Luckily I understood what was going on quickly enough, but people could have been mad at me.

Suggested solution: let the user sort by name (or really, any column).

**Comment by pljones** [comment]
The `--showallservers` option allows that already.

**Comment by corrados** [comment]
This is a duplicate, see https://github.com/corrados/jamulus/issues/293

**Comment by fleutot** [comment]
Closing as duplicate of #293
