### ISSUE TITLE
3.5.9git new icon appears rather small in Linux UI 

### ISSUE THREAD

**Issue by gilgongo** [corrados/jamulus#427]
Ubuntu 18.04.4 and 20.04

Might be better about 2.5x the size?

![small-icon](https://user-images.githubusercontent.com/4561747/86511236-07910780-bdef-11ea-8671-5c69c7832d1f.png)

(Cute icon BTW! @geheimerEichkater)

Also BTW I've not compiled 3.5.9 on other platforms.

**Comment by geheimerEichkater** [comment]
I replaced all of the existing ones with their exact dimensions. What file are you using?

**Comment by gilgongo** [comment]
I just compiled the current git head sources. 

The icon that appears in the task switcher is fine BTW.

**Comment by corrados** [comment]
The size of the icon has not changed. If you go back to the version before the icon change on your Ubuntu, you will notice that it has the same size as the new one.
We could enlarge it a little bit but not 2.5x. That's too much in my opinion. Maybe start with 1.5x and see how that looks like.
The file which is used for the icon is: https://github.com/corrados/jamulus/blob/master/src/res/fronticon.png

**Comment by geheimerEichkater** [comment]
Done, it's now 45 x 45 px (made it square now), see Pull Request #430

**Comment by corrados** [comment]
I just compiled with the new icon under Windows:
![grafik](https://user-images.githubusercontent.com/46655886/86517595-717ad280-be2a-11ea-9a8a-5e627115749b.png)
I would not enlarge it further.

**Comment by gilgongo** [comment]
I think it must be something to do with the scaling for my screen resolution as it's still quote small for me. I've got a 4K monitor (3840 x 2160). So maybe just me then.

![small-still](https://user-images.githubusercontent.com/4561747/86517649-6cb22080-be22-11ea-91f6-51ad55e67737.png)

**Comment by WolfganP** [comment]
Maybe an effect from the way windows manages apps & scaling display in high DPI mode?

**Comment by gilgongo** [comment]
Yes, I think so (although this is Ubuntu)

**Comment by corrados** [comment]
In my opinion your screen shot looks ok.

**Comment by geheimerEichkater** [comment]
Does Ubuntu maybe also offer a dedicated icon file-format like Windows does with .ico and OS X with .icns which would allow for different icon sizes at once or do you have to stick to the .png?

**Comment by corrados** [comment]
For this icon displayed on the main dialog, all OSs use the same .png file.

**Comment by gilgongo** [comment]
Oh well, nothing that can be done I guess. I still think it could be bigger as there's a lot of space around it doing nothing and it's a nice logo. But I'll close to keep the noise down.
