### ISSUE TITLE
Need remove Usb to amplifier

### ISSUE THREAD

**Issue by lonbluster** [corrados/jamulus#43]
After choosing the Yamaha amplifier ASIO, Jamulus give error message (different sampling or frequency error) and won't start any more.
I need remove the usb from the Yamaha, then Jamulus starts.

Reinstalling won't help.

**Comment by pljones** [comment]
Jamulus requires the sample rate on the selected ASIO device to be set to 48000Hz.

**Comment by lonbluster** [comment]
Solved after Yamaha usb driver upgrade.. Thanks

But for what you say there s a video showing to disable some interfaces in
Windows Sounds
