### ISSUE TITLE
Enable feature for recording audio stream locally or to a cloud service (Google drive, iCloud, Dropbox etc.)

### ISSUE THREAD

**Issue by gvermag22** [corrados/jamulus#431]
Right now, we do an audio bridging with Zoom to enable audio recording of the Jamulus session. The steps are mentioned here https://bit.ly/onlinegroupkirtanforadmins (see bridging section). BUT, it would be a LOT nicer and convenient to record the stream recorded at the client level itself. Maybe it can be saved to a cloud service as well which can be setup ahead of time. Please consider this enhancement and roll it out. This would save a lot of people a lot of trouble and many more albums may come out into the world.

**Comment by WolfganP** [comment]
I don't quite understand what you are trying to achieve, but for recording you may use the server recording feature or at a client level, launch an additional client and record it's output mix.

**Comment by gvermag22** [comment]
how do we use  the server recording feature? How do we record the output
mix on client side?

**Comment by gilgongo** [comment]
@gvermag22 The next release will have a server recording GUI, but for now you can enable recording on the command line using the `-R` option: https://github.com/corrados/jamulus/wiki/Command-Line-Options

**Comment by WolfganP** [comment]
> how do we use the server recording feature? How do we record the output mix on client side?

> There is no built-in way of recording from the client.

Right. Usually the recording (or the streaming of the Jamulus session) is done via virtual sound interfaces. https://github.com/corrados/jamulus/wiki/Tips,-Tricks-&-More describes how to use ReaRoute and Reaper, but it may be adapted to other programs as well.

**Comment by corrados** [comment]
I agree with the comments. So should we close this Issue then?

**Comment by gvermag22** [comment]
Not yet please. I tried recording on the JamulusOS today with -R or --recording switch. It was simple: --recording /home/krishna. On startup of Jamulus server, it said that the directory did not exist and it could not be created. that's impossible as that's the home directory of the same unix user running Jamulus. How can we fix this? I'm using 3.5.8 version on JamulusOS.

**Comment by gvermag22** [comment]
Also, please allow for the recording to be in mp3 format, which is more universal. I understand that's not supported now.

**Comment by corrados** [comment]
> allow for the recording to be in mp3 format

MP3 is a proprietary format. This will not be implemented in Jamulus since this would make a lot of trouble....

As discussed above, I'll close this issue now. @gvermag22 if you disagree and want this Issue to be kept open than simply re-open this Issue or create a new one.
