### ISSUE TITLE
Official zoom audio plugin

### ISSUE THREAD

**Issue by gvermag22** [corrados/jamulus#435]
Please consider providing an official zoom plugin for Jamulus. Today, people are using their own hacks: hardware loopback with audio interfaces or software solution with qjackctl and pulseaudio (as outlined in https://bit.ly/onlinegroupkirtanforadmins ). But these solutions are messy and prone to variation in performance. It would be ideal to have an official audio bridge solution/plugin from Jamulus. This is important because musicians need to share their performances live with other people and Zoom is a defacto standard now.

**Comment by pljones** [comment]
Zoom isn't anywhere near as close to real time as Jamulus, so it _needs_ a substantial work around.

In my view, it's far better to keep such solutions _outside_ Jamulus, which is intended to be as close to real time as it can be.  If someone wants to set up a cross-platform standardised way of doing this as a separate project, I could some see benefit it that.

**Comment by gilgongo** [comment]
From a brief reading of Zoom's documentation, I don't think a Zoom plugin could act as an audio bridge. From what I can tell, it's aimed at stuff like integrating Zoom itself into things, or triggering events such as leaving and joining Zoom meeting, to be used by third party apps. But I'm happy to be corrected.

**Comment by corrados** [comment]
>  don't think a Zoom plugin could act as an audio bridge. From what I can tell, it's aimed at stuff like integrating Zoom itself into things, or triggering events such as leaving and joining a Zoom meeting, to be used by third party apps

This is also my understanding. Should we then close this Issue?

**Comment by gilgongo** [comment]
@gvermag22 may know more than we do about this, perhaps?

**Comment by gvermag22** [comment]
If it's not possible to provide an audio bridge, then you can close the
issue. But do you think it's possible to have some sort of a
share functionality to facebook live or youtube live for a session. It
could be an interesting idea.

**Comment by WolfganP** [comment]
> If it's not possible to provide an audio bridge, then you can close the issue. But do you think it's possible to have some sort of a share functionality to facebook live or youtube live for a session. It could be an interesting idea.

Many people use Jamulus as the audio "virtual studio" for jams, and then feed into OBS for youtube or facebook live streaming.

**Comment by corrados** [comment]
> If it's not possible to provide an audio bridge, then you can close the issue.

Ok, so I'll close this issue now.
