### ISSUE TITLE
Jack : buffer per period parameter and audio latency calculation

### ISSUE THREAD

**Issue by newlaurent62** [corrados/jamulus#437]
Hello,

Changing buffer per period parameters in qjackctl decrease the number of Xruns (at least for USB Sound card) for the same period/frame but this increase the audio latency. Latency that is not report by Jamulus in settings. 

It seems that Jamulus does not care of buffer per period in audio latency calculation.

BR,
Laurent

**Comment by corrados** [comment]
There is a function called GetInOutLatencyMs() in Jamulus which is not implemented for the Jack audio interface (actually it is just implemented for the Windows ASIO interface). In the Jack audio help pages I found the following:
https://jackaudio.org/api/group__LatencyFunctions.html
I have not really understand how I can simply query the input/output latency. A lot of functions are declared as deprecated. If anyone has experience with this, please give a hint in this Issue.

**Comment by bflamig** [comment]
**@corrados:**

I have implemented the GetInOutLatencyMs() for the Jack audio interface. I have tested it with two different audio devices with a Raspberry Pi. I'll make a branch for it soon. (I'm still learning GitHub).

The basic gist is to call jack_port_get_latency_range(), which according to jackaudio.org is the function to call (about the only one of the latency functions that hasn't been deprecated.) After opening the jack ports, call this function twice, once for each direction (in and out.)

On my Raspberry Pi 4, I plugged in a Behringer UMC404HD, and also a Focusrite Scarlett 4i4. I put in some debug print statements, and below are the results using a frames/period value of 64, and periods of 2, 3,  and 4. The latencies reported below are in units of frames.

Behringer, Frames/Period = 64, Periods/Buffer = 2: Input latency = 64, Output latency = 128, Total latency = 192
Behringer, Frames/Period = 64, Periods/Buffer = 3; Input latency = 64, Output latency = 192, Total latency = 256
Behringer, Frames/Period = 64, Periods/Buffer = 4; Input latency = 64, Output latency = 256, Total latency = 320

Scarlett, Frames/Period = 64, Periods/Buffer = 2: Input latency = 64, Output latency = 128, Total latency = 192
Scarlett, Frames/Period = 64, Periods/Buffer = 3; N/A
Scarlett, Frames/Period = 64, Periods/Buffer = 4; Input latency = 64, Output latency = 256, Total latency = 320

**Comment by bflamig** [comment]
**@corrados:**
 
Okay, I created a fork at bflamig/jamulus that has proposed changes to compute latency for Jack interfaces. Just a few lines in two files. I'm unsure how to make a pull request. Github  is still new to me.

**Comment by corrados** [comment]
Great, I saw your pull request, thanks. I'll do a review shortly.

**Comment by corrados** [comment]
Your code is now applied to the Git master. Thanks again for fixing -> closed.
