### ISSUE TITLE
Direct Out - Jamulus on Patchage

### ISSUE THREAD

**Issue by ivanmelillo** [corrados/jamulus#443]
Hello!
I'm a Brazilian musician and productor. My field is Brazilian music (choro, samba, baião, mainly acoustic music).
I'm a user of Linux (AvLinux) in all my productions. I've tested the Jamulus and I would like to ask about a possibility in its structure: would it be possible to separate the musicians in a room in different channels on the Patchage (Jamulus shows only as input or output on the Patchage, and still keep the latence low?
I think about having only one server in charge (the creator of the server), to have a better quality in rehearsals, Boeing able to use pan, eq, reverb, compress... All this passing through a DAW (Ardour, for example) or effects (such as Calf reverb), which can be seen on the Patchage. This is all very similar to a table with Director out, which hás independent outs for each in.
I was wondering if you intend to develop it or if se could consider doing it.
Thank you very much for tour attention,

**Comment by WolfganP** [comment]
If I understood you currently, you want to access every individual track at server level?
If yes, it's being discussed at https://github.com/corrados/jamulus/issues/433

**Comment by corrados** [comment]
We already have an Issue about this topic: https://github.com/corrados/jamulus/issues/146. We should continue the discussion in that original Issue and close this one.

**Comment by corrados** [comment]
Since this is a duplicate, I'll close this Issue now. If you disagree then please re-open this Issue again.
