### ISSUE TITLE
Jamulus does not recognize the system default input/output devices on macbook

### ISSUE THREAD

**Issue by gvermag22** [corrados/jamulus#447]
When we insert new devices into the computer and select the system default input/output devices, they are not reflected in Jamulus. You have to specifically select the other device interfaces from the drop down list. This is confusing for many users who don't know the trick/bug. We struggled with this earlier on and now have grown to explicitly select the devices for input/output. The selections made in system settings don't seem to work for Jamulus with system in/out value of the dropdown list in Jamulus setting.

**Comment by corrados** [comment]
This is a duplicate. We already have an Issue for that: https://github.com/corrados/jamulus/issues/181. Let's continue the discussion in that original Issue and close this one.

**Comment by corrados** [comment]
Since this is a duplicate, I'll close this Issue now. If you disagree then please re-open this Issue again.
