### ISSUE TITLE
Jamulus adds disturbances in audio stream for windows and linux with the same mic as compared to macbook

### ISSUE THREAD

**Issue by gvermag22** [corrados/jamulus#448]
I recorded the audio stream on Jamulus server by connecting to it on 3 separate OSs (mac, windows 10, jamulusOS-Linux), all while using the same input mic https://smile.amazon.com/gp/product/B06XCKGLTP/ref=ppx_yo_dt_b_asin_title_o01_s00?ie=UTF8&psc=1. 

The results were quite different with the same input hardware. with mac server and mac client, there were no disturbances whatsoever. With windows and linux clients, there were disturbances. The linux recording even had a gap in the audio. The disturbances are kind of the same sound you hear in an old B&W movie.

Here are the recordings. 
[Fifine recordings.zip](https://github.com/corrados/jamulus/files/4906101/Fifine.recordings.zip)

My point is that with the same mic, if the software is producing different quality of audio streams, it's obviously a bug. Maybe Jamulus needs a better codec? I'm not an engineer or audio expert, but am speaking from an experience point of view.

**Comment by gilgongo** [comment]
If I understand you correctly, the variable here is in the quality of the computers' handing of the audio input/output. Macs tend to have pretty good audio stacks, but most PCs less so.

**Comment by gvermag22** [comment]
Still. Different results with same hardware is an issue. Anyway to address
it.

**Comment by corrados** [comment]
> My point is that with the same mic, if the software is producing different quality of audio streams, it's obviously a bug.

Audio hardware needs drivers to work. These drivers are different for different OSs. Different performance is expected on different platforms. This is not a Jamulus issue but a drivers issue.

**Comment by gilgongo** [comment]
> Different results with same hardware is an issue.

You may be using the same **mic**, but you're using different hardware and software:

Mic -> Audio interface hardware -> device driver(s) -> Jamulus

**Comment by gvermag22** [comment]
If I demonstrate that on the same machines, using the same mic, zoom does not introduce audio disturbances, will that prove the point? Do you agree? Then the weak link would be Jamulus, because the other variables are the same.

**Comment by gvermag22** [comment]
Here are the recordings with Zoom app on the same machines: mac, windows 10, JamulusOS. Zoom audio processing was turned off on all using https://docs.google.com/document/d/1VSO5mbWtzVD-_-XN_pwPzL4eUUv1E3DSxNqD-3a-3T0/edit. Interestingly, there is a different kind of disturbance in it.. after singing pauses, there is some shhh static sound introduced. I saw it in all three recordings.

[Zoom recordings with fifine.zip](https://github.com/corrados/jamulus/files/4907540/Zoom.recordings.with.fifine.zip)

**Comment by gilgongo** [comment]
I'm unsure whether this means Jamulus has a bug or not.

**Comment by gvermag22** [comment]
I've created https://github.com/corrados/jamulus/issues/487 so you may close this

**Comment by corrados** [comment]
Ok -> closed
