### ISSUE TITLE
Issue with server install instructions

### ISSUE THREAD

**Issue by nearsu** [corrados/jamulus#45]
Good Day

I tried installing the headless server software as recommended at https://github.com/corrados/jamulus/wiki/Running-a-Server
However, I am experiencing the same issue as detailed here
https://sourceforge.net/p/llcon/discussion/server/thread/3e4035ff18/
The problem is quite simple, the line "ExecStart=/usr/local/bin/Jamulus ..." should read "ExecStart=/usr/local/bin/Jamulus/Jamulus ..." 
The instructions tell you to make a jamulus directory for the binary file but the jamulus.service configuration file points to the folder instead of the binary

Have a good day

**Comment by nearsu** [comment]
Sorry, wrong webpage, the instructions I followed are at
https://github.com/corrados/jamulus/wiki/Server---Linux

**Comment by gilgongo** [comment]
I've now removed the reference to making a jamulus directory for the binary file.

**Comment by nearsu** [comment]
Thanks

**Comment by corrados** [comment]
Ok, so I assume that this issue is fixed so I close it now.

**Comment by nearsu** [comment]
Yes, definitely closed, thanks for your efforts
