### ISSUE TITLE
Maximum clients on server not visible in serverlist

### ISSUE THREAD

**Issue by dingodoppelt** [corrados/jamulus#451]
Hi,
I'd love to see how many channels a server offers in the serverlist.
When people want to meet in a bigger group they should be able to see which server is going to fit their needs. At the moment they have to do it by trial and error. I commited some code into my branch to fix this issue. Was it ok to create a pull request? (Sorry for asking, this is my first time ;)
cheers, nils

**Comment by corrados** [comment]
Yes, sure. Good idea.
