### ISSUE TITLE
2 GUI issues 

### ISSUE THREAD

**Issue by bugith** [corrados/jamulus#456]
1) In new Normal & Compact themes, bold text above band faders is partially hidden
![Jamulus](https://user-images.githubusercontent.com/6240207/87241403-109f5b80-c423-11ea-8df9-cb9c44ad595e.png)
2) Long time issue (Ubuntu 16.04), even before 3.4.3, Shift+F1 tooltips show exactly like in the picture above. Tooltips in Audacity show fine white text/black background.

**Comment by corrados** [comment]
That is interesting. Why is this in bold font in your example:
![grafik](https://user-images.githubusercontent.com/46655886/87242639-e18ee700-c42e-11ea-81a5-37e70c39c7ea.png)
It is supposed to be in normal font:
![grafik](https://user-images.githubusercontent.com/46655886/87242652-fcf9f200-c42e-11ea-8bd6-4b5603db6b86.png)
Have you changed something in the code so that it is in bold font?

**Comment by trebmuh** [comment]
It looks a theming issue to me.
A shot in the dark: do you use qt5ct maybe?

**Comment by bugith** [comment]
Still don't know about bold font, but foreground font color for the tooltips WAS definitively a Ubuntu (upgraded from 12.04 to 14.04 to 16.04) theme bug:
Just change the 1st line in these 2 files:
/usr/share/themes/Ambiance/gtk-2.0/gtkrc
/usr/share/themes/Radiance/gtk-2.0/gtkrc
from *...\ntooltip_fg_color:#ffffff\n...*  to *...\ntooltip_fg_color:#000000\n...* did the job.
Sorry for the noise for the tooltips... I investigate for the bold font

**Comment by bugith** [comment]
Not such a big problem.
@corrados , Volker, your layout is not the same too: you have rotating controls when AFAIR always had sliding faders. Also, maybe it is not font bold/regular issue, but instead something related to a margin around elements. No change to Jamulus code. BTW, I DL'd yesterday the source code 3.5.9git to compile myself as per usual instructions.
@trebmuh No qt5ct here
I also guess another theme issue, because I didn't had this bold font in Ubuntu 18.04.
`/usr/share/themes$ grep -r bold *
Ambiance/gtk-3.0/gtk-widgets.css:    font: bold;
Ambiance/gtk-3.0/apps/gnome-applications.css:    font: bold;
Ambiance/gtk-3.0/apps/gnome-applications.css:    font: bold;
oxygen-gtk/gtk-2.0/icons4:gtk-bold actions/format-text-bold.png
Radiance/gtk-3.0/gtk-widgets.css:    font: bold;
Radiance/gtk-3.0/gtk-widgets.css:    font: bold;`
...
`/usr/share/themes$ grep -r margin *`
Too long output to post here... give up, not a big problem.
