### ISSUE TITLE
Network names and address cannot contain spaces

### ISSUE THREAD

**Issue by pljones** [corrados/jamulus#462]
As a usability improvement, any address being parsed should be checked for spaces.

Leading / trailing spaces should be trimmed.  In the UI, the input field should be updated to reflect this.

Embedded spaces should prevent the value being accepted.

Reference:
https://www.facebook.com/groups/507047599870191/permalink/573265499915067/?comment_id=573296806578603&reply_comment_id=573341753240775

**Comment by dingodoppelt** [comment]
#469 Isn't it sufficient to accept every input and just remove any whitespace from it since there are no validity checks for network addresses in general?

**Comment by pljones** [comment]
I think a command line passing a host name with an embedded quoted space should cause the command to be refused with an error.

That there is currently no validation is an argument for not adding validation.

**Comment by corrados** [comment]
I have no issues with that we just remove the spaces and there is no error shown. I have merged the code from dingodoppelt and have modified it slightly. Now the custom server entry can have a space at the beginning (as written in https://www.facebook.com/groups/507047599870191/permalink/573265499915067/?comment_id=573296806578603&reply_comment_id=573341753240775) and it still works fine.
I close this issue now.
