### ISSUE TITLE
Feature request - Fancy Skin, BG colour

### ISSUE THREAD

**Issue by njc235** [corrados/jamulus#470]
I often have to run two client instances on the same machine.  It would be nice to have the ability to change the grey to a custom colour to easily see which is which e.g. pink for her, blue for me.

**Comment by corrados** [comment]
Why not using a different skin for each of them. Use the normal skin for one and the fancy skin for the other instance of Jamulus.
BTW: There is a command line argument specifically for this usecase where you can give each Jamulus instance a name which is shown in the window title.

**Comment by njc235** [comment]
Hi Volker, That’s a fair point can you give me a pointer to using the command line arguments?

**Comment by corrados** [comment]
It's the `--clientname` command line argument, see also https://github.com/corrados/jamulus/wiki/Command-Line-Options

**Comment by corrados** [comment]
I assume that your problem is solved with the tips I gave you. Can we close this issue?

**Comment by njc235** [comment]
Thank you. I now use the —clientname but it would be nice if a genius could make a colour option :). You can close the ticket.
