### ISSUE TITLE
Headless servers: easily toggle recording on/off 

### ISSUE THREAD

**Issue by gilgongo** [corrados/jamulus#474]
Now that the server UI has recording controls and other things, there have been [some](https://sourceforge.net/p/llcon/discussion/533517/thread/37fdfe3795/) [posts](https://sourceforge.net/p/llcon/discussion/server/thread/99ae1e1e0c/?limit=25#612a) on the forum relating to managing headless servers. 

So for the purposes of discussion at least, I thought I'd raise this ticket to propose having the ability for the server GUI to be put into a "remote mode" enabling you to control a headless server.

**Comment by pljones** [comment]
There are currently only three things you can tell Jamulus server headless:
* Stop cleanly (terminate any recording, tell the server list server you're shutting down).
* Start a new recording (if recording enabled and recording in progress)
* Toggle recording enabled (if there's a recording base directory set)

Assuming the server is managed by systemd, then the first case is simple "stop the service unit".

The second and third cases just require a small script written and executed from separate service units.

**Comment by corrados** [comment]
Thanks pljones for clarifying this. Maybe we should add these informations in the Wiki.

> The second and third cases just require a small script

Could you create an example script for this which we could add to the Wiki page?

**Comment by gilgongo** [comment]
Thanks pljones for clarifying this too.

What though do people think of the feasibility of the proposal in the ticket?

**Comment by pljones** [comment]
Looks like it doesn't need a script.  A unit type oneshot with `systemctl kill -s SIGUSR1 Jamulus-server` should do the trick.  I'll write up a couple of unit files and paste them here.

**Comment by pljones** [comment]
OK.  Results first :)
```
root@fs-peter:/etc/systemd/system# systemctl start newRecording-Jamulus-server.service
root@fs-peter:/etc/systemd/system# systemctl start toggleRecording-Jamulus-server.service
root@fs-peter:/etc/systemd/system# systemctl start toggleRecording-Jamulus-server.service
```
```
Jul 24 22:39:14 fs-peter Jamulus-server[1521]: Server Registration Status update: Registration requested
Jul 24 22:39:14 fs-peter Jamulus-server[1521]: Server Registration Status update: Registered
Jul 24 22:40:49 fs-peter Jamulus-server[1521]: OnHandledSignal:  10
Jul 24 22:41:02 fs-peter Jamulus-server[1521]: OnHandledSignal:  12
Jul 24 22:41:02 fs-peter Jamulus-server[1521]: Recording state disabled
Jul 24 22:41:05 fs-peter Jamulus-server[1521]: OnHandledSignal:  12
Jul 24 22:41:05 fs-peter Jamulus-server[1521]: Recording state enabled
```
And the unit files:
```
root@fs-peter:/etc/systemd/system# cat newRecording-Jamulus-server.service
[Unit]
Description=Start a new recording on Jamulus-server
Requisite=Jamulus-server

[Service]
Type=oneshot
ExecStart=/bin/systemctl kill -s SIGUSR1 Jamulus-server
```
```
root@fs-peter:/etc/systemd/system# cat toggleRecording-Jamulus-server.service
[Unit]
Description=Toggle recording state on Jamulus-server
Requisite=Jamulus-server

[Service]
Type=oneshot
ExecStart=/bin/systemctl kill -s SIGUSR2 Jamulus-server
```

Of course, if you want something more deterministic than "toggle", you would need to determine the current state of the recorder.  There's currently nothing providing that, though.  There's a separate issue for more "health check" information, I think, which would cover this.

You could also have a systemd timer unit that triggers the "newRecording" unit say once an hour, with the timer only enabled whilst there are people on the server.  And that would need a further unit to monitor the server state (at which point, it might need a script - I've not looked into how systemd can use inotify).

**Comment by jaymil3** [comment]
it'd be super nice if any client connected to the server could signal to initiate/stop the recording tho, so that there doesn't have to be anyone  actively managing that at the server.  thoughts?

**Comment by corrados** [comment]
That would mean in turn that anybody could trun off pljones's recording on his server which he does not want I assume. This calls for some small "third party" tool which sends the SIGUSR via SSH to the server. Only the one who has access to the SSH shell has the rights to manage the recording.
I do not want to introduce any password protection in the client (if you suggest to force a password for this setting in the client).

**Comment by gilgongo** [comment]
> I do not want to introduce any password protection in the client 

OK so changing the title of this ticket to avoid confusion :-)

**Comment by gilgongo** [comment]
@pljones Sorry, but how do you actually run the unit files once you've done a `daemon-reload`?

**Comment by gilgongo** [comment]
OK done that (and tested it on my server which is also running the same unit file as in the docs): https://github.com/corrados/jamulus/wiki/Server---Linux#controlling-recordings let me know if there's mistake.

BTW I don't know if this line is correct though:

"The Jamulus process name in the ExecStart line needs to be the same as that of the server."

Is it the process name or some systemctl "name"? When I tried making it the same as the Requires name, it failed.

**Comment by pljones** [comment]
It's the systemd unit service name for pedantry :)

**Comment by jaymil3** [comment]
> That would mean in turn that anybody could trun off pljones's recording on his server which he does not want I assume. This calls for some small "third party" tool which sends the SIGUSR via SSH to the server. Only the one who has access to the SSH shell has the rights to manage the recording.
> I do not want to introduce any password protection in the client (if you suggest to force a password for this setting in the client).

Got it, thx

> OK done that (and tested it on my server which is also running the same unit file as in the docs): https://github.com/corrados/jamulus/wiki/Server---Linux#controlling-recordings let me know if there's mistake.
> 
> BTW I don't know if this line is correct though:
> 
> "The Jamulus process name in the ExecStart line needs to be the same as that of the server."
> 
> Is it the process name or some systemctl "name"? When I tried making it the same as the Requires name, it failed.

And this looks great

**Comment by pljones** [comment]
OK, having got the "simple" versions working, I just had to do this.  I've be trying to get "systemd templates" working for _anything_ for ages and ages.  So I thought: "What if I had multiple servers?"  They need the same controls - don't want multiple unit files all over the place, thought...
```
[Unit]
Description=Start a new recording on %i
Requisite=%i

[Service]
Type=oneshot
ExecStart=/bin/systemctl kill -s SIGUSR1 %i
```
`systemctl start newRecording@Jamulus-server` would trigger the `/bin/systemctl kill -s SIGUSR1 Jamulus-server`.

And so, for the toggle, similarly:
```
[Unit]
Description=Toggle recording state on Jamulus-server
Requisite=Jamulus-server

[Service]
Type=oneshot
ExecStart=/bin/systemctl kill -s SIGUSR2 Jamulus-server
```

**Comment by gilgongo** [comment]
> It's the systemd service unit name, for pedantry :)

Where does it take that name from though? The actual unit file name in `/etc/systemd/system`?

(On the use of systemd templates, it's a pity it doesn't do the upstart thing of enabling "commands" in the unit file so you can't do `service start Jamulus-Server toggleRecording` or something. At least I'm pretty sure it doesn't do that.)

**Comment by pljones** [comment]
`Jamulus-Server.service` would be the file name for the systemd service unit named `Jamulus-Server`.

The other thing I'd like to be able to do is:
- when a server becomes active and starts recording, start monitoring
- every hour (or whatever), if it's _still_ active and recording, tell it to start a new recording

I could write a bit of bash quite easily to do that (similar to my existing jam archiver).  I've yet to try with a "pure" systemd solution...

**Comment by pljones** [comment]
@gilgongo - is anything else needed here or can the request be considered complete?
