### ISSUE TITLE
Show if the client is locally muted in the window title

### ISSUE THREAD

**Issue by dingodoppelt** [corrados/jamulus#476]
Sometimes I forget to unmute myself, especially when the client window is not visible or I sometimes just want to know, if I am muted or not without bringing the client window to the front to be able to check.
I've created a quick fix for this and created a pull request for everybody to review.
cheers, nils

**Comment by corrados** [comment]
I do not think putting this information in the server title is a good idea. We already have the recording information put there.

**Comment by dingodoppelt** [comment]
Hi,
it is shown in the window title, not the server title. That way you can see if you are muted even if the client window is not visible and while you are playing your instrument you cannot reach for your mouse to bring the window to the front. You can see it in the taskbar.
![selfmute](https://user-images.githubusercontent.com/62596379/88973775-f20ce180-d2b7-11ea-8cd5-f76f07e58d26.jpg)

**Comment by corrados** [comment]
Thanks for the clarification. We had a discussion about the mute state before, see: https://github.com/corrados/jamulus/issues/187#issuecomment-647026426
WolfganP suggests something blinking which would be more obvious. Maybe color code your own fader to make it more visible that you are muted.

We had a very lengthy discussion about the name "Mute Myself", see #187. In your implementation you simply use the word "MUTED". But this is not exactly what is happening. Since you hear your own signal even if MUTED is displayed. What actually is done is that your stream to the server is stopped when you activate Mute Myself.

I would prefer some color coding but this would mean some more coding. The advantage of your solution is that its implementation is fairly simple. Please give me some more time to think about this feature and do some more brainstorming and looking at the code. I'll get back in this thread sometime soon.

**Comment by storeilly** [comment]
Can I throw in a suggestion? The objective is to alert the musician that
their stream is not live to other users! So why not kill the local audio so
that when a musician plays or sings, they don't hear themselves, they only
hear other musicians. If you need a local loopback test, that should be a
separate feature that does not need a server and not confuse this. Hope
I've explained correctly.

Stephen

**Comment by corrados** [comment]
Thanks for your suggestion. But the intended use case of Mute Myself is that if a session is ongoing and you want to find out, e.g., which chords are played, you want to hear the others and your instrument but you do not want your signal to be sent to the server. See the original request from Simon: https://github.com/corrados/jamulus/issues/75 and also this post: https://github.com/corrados/jamulus/issues/75#issuecomment-614686896

**Comment by dingodoppelt** [comment]
hi,
thanks for your response. I would love to see this issue addressed, since it is still an issue for me not knowing outside of the client window if I am muted or not. (with my implementation I do, that's why I'm using it already ;) That is why I put the Information in the window title so it shows up in the taskbar. I'd love to see it flashing lights in the taskbar (maybe trayicon/floating overlay?) and so on, but I couldn't figure out how to do that on all platforms since Qt doesn't offer this functionality, I think. The most important point for me is that I get the info about my mute status even when I'm looking at sheet music or a zoom feed and the jamulus window itself isn't visible.
Since my implementation is far from elegant and the code isn't consistent with your design I already know what I will be improving, once I know how to call functions from a different namespace :)
thank again volker, and keep up the great work!

**Comment by corrados** [comment]
I have a different proposal:
![grafik](https://user-images.githubusercontent.com/46655886/89727920-4850f180-da29-11ea-9979-2f301e1b7228.png)

> That is why I put the Information in the window title so it shows up in the taskbar.

This you will not get with my implementation. Do you often have the situation that the client window is not shown but you have set yourself to muted? I think this is a special case. Most users will have the Jamulus client window up-front when they jam and when they use the Mute Myself button.

I think the red bar clearly shows the state. And we have the possibility to add some descriptive text (as I do in my example) to make it clearer what Mute Myself does (I am referring to again to https://github.com/corrados/jamulus/issues/187). @gilgongo I think that red info bar with the additional text would solve the confusion, what do you think?

**Comment by gilgongo** [comment]
Yes, seems pretty clear. I'd suggest, "MUTED (You are not sending any audio to the server)"

BTW does this message override the server recording one? It seems to be shown in the same place.

**Comment by corrados** [comment]
No, but we could move the information about the recording also in that label.

**Comment by pljones** [comment]
Well, recording is what the server is doing to you, whereas muted is what you're doing to yourself, so it seems sensible to keep the recording info in the server group box border to me.

**Comment by corrados** [comment]
Agreed.

**Comment by corrados** [comment]
I have just added the code of the new implementation to the Git repo.

@dingodoppelt I did not get any feedback from you, yet. I think with the implemented solution we have improved the situation at least for the Jamulus users which have the main window visible (which, I guess, are the most of them). For your special case, you already have implemented the support for showing the muted state in the Window title so I guess you can live with using your special version of Jamulus.

So I will close this Issue and also your pull request now. If you disagree, please write your opinion in this Issue and/or re-open the pull-request/Issue again if you think that is necessary.

**Comment by Hk1020** [comment]
Oops, I am too late, sorry. I’m not using Jamulus anymore, we went back to physical rehearsals. Anyway, why not say in the red text _You aren’t heard by other participants_ or something like that. Who cares about the technology, say what’s the effect. Otherwise I like your change.

**Comment by corrados** [comment]
Good idea. What about "_The others will not hear me_"?
@gilgongo What's your opinion?

**Comment by gilgongo** [comment]
Yes that's perhaps even better because it's the practical effect of muting yourself rather than the technical function of it.

**Comment by corrados** [comment]
@gilgongo You are the native speaker. Would be "_The others cannot hear me_" better?
Or maybe "_The others cannot hear you_"?
But since we have "Mute Myself", maybe "me" is better than "you".

**Comment by jerogee** [comment]
@corrados, @gilgongo, I really support to describe the effect as @Hk1020 suggested. Both variants are possible and fine imho. I will just go with "Others cannot hear you" in Dutch as this seems more common (in English and Dutch at least).

**Comment by Hk1020** [comment]
One other wording that stuck in my mind: _Other people won’t hear you_.

**Comment by gilgongo** [comment]
"You" vs "Me" in this context is really just stylistic and usually depends on the style used in other messages in the app. "Me" is sometimes said to be possibly unclear if the reader thinks the app (Jamulus) is referring to itself, so for this message perhaps "you" is clearer even though we have "mute myself"?

**Comment by corrados** [comment]
Thanks, so let's use "you".
Last question (to the native speakers): Should we use:
"_Other people won’t hear you_"
or
"Other people don’t hear you"
?

**Comment by storeilly** [comment]
Won't

**Comment by corrados** [comment]
Ok, thanks. I'll change it now.
