### ISSUE TITLE
Main process exited, code=killed, status=11/SEGV

### ISSUE THREAD

**Issue by pljones** [corrados/jamulus#480]
My server is running a build based on
94055a81 2020-07-19 (HEAD -> master, upstream/master, origin/master, origin/HEAD) Merge pull request #469 from dingodoppelt/remove_spaces

Compiled, Jul 20 07:11 BST

It's been running fine since then.  Until...
```
Jul 28 19:27:56 ***** Jamulus-server[3758]: Server Registration Status update: Registration requested
Jul 28 19:27:56 ***** Jamulus-server[3758]: Server Registration Status update: Registered
Jul 28 19:33:59 ***** Jamulus-server[3758]: 2020-07-28 19:33:59, 82.65.90.AAA, connected (4)
Jul 28 19:34:11 ***** Jamulus-server[3758]: 2020-07-28 19:34:11, 90.242.228.--, connected (5)
Jul 28 19:34:24 ***** Jamulus-server[3758]: 2020-07-28 19:34:24, 82.65.90.AAA, connected (4)
Jul 28 19:34:24 ***** Jamulus-server[3758]: 2020-07-28 19:34:24, 82.65.90.AAA, connected (4)
Jul 28 19:34:24 ***** systemd[1]: Jamulus-server.service: Main process exited, code=killed, status=11/SEGV
Jul 28 19:34:24 ***** systemd[1]: Jamulus-server.service: Failed with result 'signal'.
```
Edit - build command:
```
make distclean; qmake "CONFIG+=nosound headless"; make -j; make clean
```
No idea what caused the SEGV, of course, I'm just posting here in case anyone else sees one.

I'm also not sure what other info would help.

**Comment by corrados** [comment]
Have you ever seen this issue before? What was the last stable version you have used?

**Comment by corrados** [comment]
Another question: With what command line options was the server running?

**Comment by pljones** [comment]
No, never seen it before.

I tend to run git versions on jamulus.drealm.info as I often use it for "proving" my own changes have worked.  (The Server List servers only get updated to release versions and often not straight away -- but they're not used for jams.)  I've since updated it again to the latest master git (which contains another change to `server.cpp`).

```
Jamulus-server -s -n -F -p 54850 -u 30 -e jamulus.fischvolk.de:22224 -m /opt/Jamulus/run/status.html -l /opt/Jamulus/log/Jamulus.log -y /opt/Jamulus/log/history.svg -L -R /opt/Jamulus/run/recording -a jamulus.drealm.info -o "jamulus.drealm.info;London;224" -w "<html><body><h3>Jamulus Jam server at drealm.info</h3> <p>Find out more at http://jamulus.drealm.info/</p> <p><strong>Recording enabled:</strong> CC BY-NC-SA 4.0 applies: no cover versions! <br/><small>NOTE: Client 3.4.2 or later required here!</small></p></body></html>"
```

I _vaguely_ remember some mention of `make -j` sometimes causing issues in the built executable - I can't understand how, myself.

**Comment by corrados** [comment]
You are using all server features like the HTML file, svg file, logging and recording. Since I never saw this issue on my Central server (which only uses the logging, nothing else), the issue may be caused by one of these additional features. But this is just guessing.

> make -j sometimes causing issues in the built executable

I don't think this is causing the issue here...

**Comment by corrados** [comment]
In your log file you can see that "82.65.90.AAA" was connecting and disconnecting twice with the same time stamp. So I assume that this connect/disconnect operation which was obviously quickly done has caused the issue.

**Comment by corrados** [comment]
I found that the function OnNewConnection() in the server needs a mutex. I added this in my commit https://github.com/corrados/jamulus/commit/df0ec35d050343d3af03425181ab820d985e4c18 among other things. Maybe this is the fix to the problem you saw.

**Comment by pljones** [comment]
> In your log file you can see that "82.65.90.AAA" was connecting and disconnecting twice with the same time stamp. So I assume that this connect/disconnect operation which was obviously quickly done has caused the issue.

Yep, that was the only suspicious thing I could see.  A missing mutex could be the problem, indeed!  Hasn't happened before so hopefully it won't again now.  :)

One reason I _don't_ auto-restart my server is so that I become aware of crashes -- with an auto-restart had I not been around, I might never have seen it.  At least I can be _fairly_ sure nothing like it's happened before (can't see any other SEGVs in the logs).

**Comment by corrados** [comment]
Ok, since you agree with me that a missing mutex could have caused the crash and I have fixed this now, I may close this issue and if it happens again, just re-open this or create a new one. What do you think?

**Comment by pljones** [comment]
Yes - I think so.  No point leaving it "just in case".

However, to be handled separately, is there anything similar in the server list code that could have the same problem (two servers registering at the same time)?

**Comment by corrados** [comment]
Good question. Actually when I added the mutex for the OnNewConnection() I also added one for the OnProtcolCLMessageReceived() function. All "connection less" protocol messages are routed through this function so it is actually mutexed. So I think we do not have a problem there.
