### ISSUE TITLE
Tabs not sorting list alphabetically or numerically.

### ISSUE THREAD

**Issue by AndyMcProducer** [corrados/jamulus#481]
Hiya all, could the tabs be set to list alphabetically or numerically when they are clicked, so if Server Name clicked it sorted
the list alphabetically, or musicians sorted numerically and so on?
![image](https://user-images.githubusercontent.com/8242017/88827305-b42d9180-d1c1-11ea-93db-e352f0d32573.png)

**Comment by corrados** [comment]
See https://github.com/corrados/jamulus/issues/424 and https://github.com/corrados/jamulus/issues/293

**Comment by corrados** [comment]
Since we have a Filter function, for what specific reason do you need the sorting?

**Comment by AndyMcProducer** [comment]
Sort by musician to quickly see what servers have musicians or find a server by name or check servers to see how they're performing. I have 3 servers running atm and sometimes finding them in the list takes a while when a quick click to sort by name would save a lot of time. Same for the Musicians and Location, it just makes Jamulus the same as all other windows when you click the title and it sorts. 
I thought it had bugged at first and restarted the software to try fix it then realised it was only titles and not the norm when normally laid out like that.

The filter option helps some.

Also I imagine this has been asked before but how come in List there is a Default, then All Genres, is there a reason for that or 
has it just become like that over time?
When I install Jamulus it shows All Genres as the default but then has default to. I was a bit unsure which was the default to set the servers to but I changed it to All Genres, but just want to make sure i have them on the right one.

**Comment by corrados** [comment]
> Sort by musician to quickly see what servers have musicians

This is already supported: "_add special server list filter for filtering occupied servers by using "#" (#397)_" -> just type in # in the filter field and only occupied servers are shown.

> find a server by name

Just type the name in the Filter box, this is much quicker than to search in the sorted list.

> check servers to see how they're performing

What do you mean by that? How would the sorting do this?

> I have 3 servers running atm and sometimes finding them in the list takes a while when a quick click to sort by name would save a lot of time

See above, just type in the name in the Filter box.

> how come in List there is a Default, then All Genres, is there a reason for that or has it just become like that over time?

Yes, it has become like that over time.

**Comment by AndyMcProducer** [comment]
Yes dude that's cool.
