### ISSUE TITLE
Enhancement to Reverb On Off

### ISSUE THREAD

**Issue by AndyMcProducer** [corrados/jamulus#484]
Hi, does the reverb gain any ms? I'd never use it and it would be good to turn it off instead of just min mix volume.
But not a off but that just mutes, to be able to deactivate it so I can grab those 1 or 2 extra ms back.

Thanks, Andy.

**Comment by corrados** [comment]
The reverb is off if you move the fader all the way down. No ms or CPU is consumed.

**Comment by corrados** [comment]
Since nothing to do for this Issue, I'll close it now.
