### ISSUE TITLE
Client "nosound" driver performance

### ISSUE THREAD

**Issue by pljones** [corrados/jamulus#486]
This is a client connected to a server running on the same linux machine.

The client and server were compiled with
```
df0ec35d 2020-07-31 (HEAD -> master, origin/master, origin/HEAD) added more mutex in the server (may fix #480)
```
using
```
$ make distclean; qmake "CONFIG+=nosound"; make -j; make clean
```
The only difference from that commit are my changes to set thread names.

I was hoping to use the client with the nosound driver for comparing performance but it appears there's some flaw:
![image](https://user-images.githubusercontent.com/1549463/89103981-bbe17600-d40d-11ea-9a33-27b07e962d47.png)

I've yet to investigate why the jitter buffers are so high!

With the jack driver or from Windows the jitter is more sane (same commit):
![image](https://user-images.githubusercontent.com/1549463/89104208-6d34db80-d40f-11ea-9363-264da7df6396.png)
![image](https://user-images.githubusercontent.com/1549463/89104213-73c35300-d40f-11ea-94d5-04d5a3d57980.png)

Is anyone aware of what the problem with "nosound" could be?

**Comment by corrados** [comment]
nosound is no valid mode for the client. It was introduced for the server so that you do not need jack for compiling the server.

**Comment by corrados** [comment]
To give you some more info: If you run the client in the "nosound" mode, there is no audio interface blocking so the client processing routing runs much too fast and sends out network packets at a much too high rate. So no meaningful testing possible in that mode. It was just not intended to be used in the client.

**Comment by pljones** [comment]
Ah right.  OK, I'll just use jackd.
