### ISSUE TITLE
audio recording should be combined for all streams

### ISSUE THREAD

**Issue by gvermag22** [corrados/jamulus#488]
The current audio recording feature records different audio wav files for each session. But this is not very useful for taking actual group recordings. The wav file starts when a new session starts, and its very difficult to overlap these files into a combined full experience. Normally, we would expect multiple singers or instrument players to join at different times and then practice together at a particular timestamp, but its next to impossible to create that experience with the current output files. Thus, I request you to create a combined audio output file while using the recording feature. This will make it really useful for actual recordings and also for troubleshooting audio issues with a common timestamp.

**Comment by pljones** [comment]
The recording feature supplies not just the WAV files.  It supplies two additional files both of which allow you to mix the wav files in either Reaper or Audacity or import them into the DAW of your choice and precisely align.

**Comment by gvermag22** [comment]
What would I need to Do to create a mixed experience in audacity then

**Comment by gilgongo** [comment]
Recordings are per track in Audacity `.lof` format and REAPER `.rpp`. Open the respective files to listen to the recording in those applications and you can mix to your heart's content.

**Comment by corrados** [comment]
@gvermag22 Did gilgongos answer helped you? Can we close this Issue then?

**Comment by gvermag22** [comment]
Yes
