### ISSUE TITLE
Allow display of server IP address in client

### ISSUE THREAD

**Issue by Som30ne** [corrados/jamulus#489]
Yesterday I tried to perform some Choire rehearsal using Jamulus.
I encountered the following phenomenon:
Some of the clients were able to see a specific server, let's call it XYZ in the list of servers,
others were not able to see this server.
We were all in the same country, and relatively in a small radius of distance (Approx 30km radius).
But we were using different ISPs.

I believe that if the clients that were not able to see the server have the option to enter it's IP address,
they would have been able to connect to it as well.

So - my request is to be able to view the IP address of the server,
either in the servers list (I know this might make the list cluttered, so this is lower prio.),
or in the settings dialog, next to the ping/latency information.
(I believe this is not very hard to implement)

**Comment by corrados** [comment]
You can see the IP address here: http://jamulus.softins.co.uk

**Comment by Som30ne** [comment]
> You can see the IP address here: http://jamulus.softins.co.uk

That's an interesting solution.
It might be acceptable, if it is guaranteed that all servers are seen there.
The question whether all servers are shown on that page arises from the original situation,
where some clients listed the specific server, and others did not.

**Comment by corrados** [comment]
In that list all servers are always shown.

**Comment by WolfganP** [comment]
@Som30ne did you verify all clients tried to retrieve the same list of servers? (ie all pointing to the same genre list?)

**Comment by gilgongo** [comment]
BTW I've added something on the wiki about this [here](https://github.com/corrados/jamulus/wiki/Client-Troubleshooting#cant-see-the-server-you-want-to-join).

**Comment by corrados** [comment]
@Som30ne Are you fine with the workaround? If yes, then we can close this Issue.

**Comment by Som30ne** [comment]
Thank you all,
and apologies for the delay in reply.

@WolfganP 
Yes, all clients were looking on the same server list
@gilgongo 
Thanks for that, it's very helpful, and still, _sometimes_ it appears that even when typing the IP,
it does not really connect -
The server shows an empty user being connected, and added to the list in the other users' UI,
but the new user gets "Trying to connect" message, and gets "stuck" at that stage.
(All clients were the same version (latest version available, at the time we did tried that)
@corrados 
I believe this can be an acceptable workaround, if it was just a bit more Googleable.
Trying several phrases in google, did not get me to the wanted page.
(The only way I was able to get there was to google "jamulus wiki", manually clicking the Client Troubleshooting link,
and searching the page for the required information)

I know you have no responsibility for/on the google algorithms and page ranking,
but maybe some more keywords definitions on the page 
(I think google's robots search for some defined section with keywords)
and/or linkage to the troubleshooting page will move it up the ranks.

Thanks again, to all of you guys (and girls ?), for the time and patience to respond to this.

**Comment by gilgongo** [comment]
> but maybe some more keywords definitions on the page

The vast majority of the wiki has only been in existence a few months. Before that, there were some blobs of content on the [SF website](http://llcon.sourceforge.net) which we migrated to GH. and I would expect very few sites link to it yet. I'm no SEO expert, but I think it'll take quite a while for Google to see the wiki as important. We do suffer from too much (often outdated) content existing scattered across the web though, but I hope with time that will improve.

**Comment by corrados** [comment]
As we have a workaround I'll cose this Issue now.
