### ISSUE TITLE
Change auto jitter buffer algorithm to get less audio drop outs

### ISSUE THREAD

**Issue by lefty665** [corrados/jamulus#492]
Auto Jitter Buffers tend to settle in a little too low and are slow to self adjust. That causes lots of noise and distortion. We've found letting Auto Jitter Buffers settle in then changing to manual Jitter buffers and bumping them one or two notches works pretty well, but that's at best semi auto. I believe Auto Jitter buffer behavior changed several updates back. 

Thanks for what you are doing with Jamulus. It continues to surprise. The other evening we, on the east coast of the US, had participants from mid Atlantic US, Canada, Florida, Australia, Seattle WA, Italy, Brazil, Argentina and a couple of other places. Amazingly the Aussie was able to take a lead ride. My hat's off to him, dunno how he did it with that delay. He was on the other side of the date line, a calendar day and 12 hours ahead of us. Having pickers from 4 continents on line is amazing! Jamulus is making the world a more sociable place. Hope that brings a smile to y'all, nice work.

**Comment by corrados** [comment]
This is related to the following Issue: https://github.com/corrados/jamulus/issues/417
I actually proposed the same in my comment: https://github.com/corrados/jamulus/issues/417#issuecomment-661955471
No decision made, yet.

**Comment by corrados** [comment]
The auto jitter buffer was changed in the newest release 3.5.10: https://github.com/corrados/jamulus/issues/417#issuecomment-674129803

Please test if that change is sufficient for you to get better results. Please note that you have to connect to a server which also uses the newest Jamulus version 3.5.10 to get the new auto jitter buffer parameter on both, the client and server jitter buffer.

I'll close this Issue now. If you think the auto jitter buffer is still not good, please re-open this Issue or create a new one.
