### ISSUE TITLE
Option to set "Mute Myself" on with startup arguments

### ISSUE THREAD

**Issue by watsonSBCC** [corrados/jamulus#495]
Startup option argument to set "Mute Myself" to on.

Use case: 15 ensemble members already joined and one leader is talking or two ensemble members are working something out - it's very disruptive to have an ensemble member all of a sudden join in with their mic too hot and drowning out whatever else is going on. Or a department chair dropping in to observe and their kid in the background starts yelling.

Implementation: it would be nice to set that as a command line option so that no matter what they were last doing, it starts up in a non-disruptive state, especially if launched with a script or a url.

**Comment by corrados** [comment]
This is now implemented. Spec:` -M, --mutestream      starts the application in muted state`

**Comment by mikedickey** [comment]
@corrados this doesn't seem to work using a headless build on Linux (version 3.5.12 on client and server). From the client logs:

jamulus[2203]: - mute stream activated
jamulus[2203]: No GUI support compiled. Running in headless mode.

But others connected to the server can still hear me.

**Comment by corrados** [comment]
Thanks for your feedback. Can you please create a separate ticket for that bug? Then it is easier to keep track of the fixes.

**Comment by corrados** [comment]
I just looked at the code. If you mute the client on startup, how do you unmute that client afterwards if you do not have a GUI?

**Comment by mikedickey** [comment]
Good question! I stumbled on this while catching up on the change log and trying to figure out #340. At first I thought this was what I was originally asking for, and later realized the difference between muting your outgoing audio versus muting yourself in your person mix (two different things). What I would like most to get working is #340.

I imagine the same question could be asked of #340 too. My use case involves external automation, where Jamulus is being controlled by an outside agent, and it's perfectly acceptable to just (edit ini file, then) restart the process to make any changes.
