### ISSUE TITLE
How many Jamulus servers can be run on a single computer?

### ISSUE THREAD

**Issue by brandflake11** [corrados/jamulus#496]
I am currently using Jamulus to run a server at a university, and the university is interested in running multiple Jamulus servers for ensemble rehearsals. I tried to do this as a quick test by trying to run 5 servers in a bash script, and it only seemed to allow one to run. Is it possible to run multiple Jamulus servers from a single computer? If it is not, would virtual machines be the way to go for this? I have found running a Jamulus server in a vm had worse latency (makes sense), but I am a little concerned with how I would go about doing this without having have as many computers as our university wants servers. 

Does anyone have any suggestions for these things, and is it possible to run multiple servers on a single machine?

Thank you for your time. I understand that this project is very busy, so I appreciate any help that I get.

EDIT: Just discovered you can change the local port the server uses (with option -p), which is great. Is this the best way to run many servers on one computer?

**Comment by corrados** [comment]
You can run as many Jamulus servers as you like but they have to have different port numbers. So you should start Jamulus like this:
```
./Jamulus -s -n -p 22124
./Jamulus -s -n -p 22125
```
etc.

**Comment by brandflake11** [comment]
Thanks @corrados! Would running a central server (the server that the Jamulus servers can be accessed from, I am not sure if this is the right terminology) have any benefits to just running them all on the USA central server?

**Comment by corrados** [comment]
The benefit is that you have your own private server list. So only the clients who know the address of your "Central Server" get access to your server list.

**Comment by brandflake11** [comment]
Thank you @corrados, this helps greatly. I really appreciate your time. If this ends up happening, and you are interested, I can let you know how it goes.

**Comment by pljones** [comment]
@brandflake11 - it works, I do this frequently when testing updates to the client, server or server list processing.

**Comment by brandflake11** [comment]
I have another question related to all of this. Say we run multiple Jamulus servers on one computer, is it possible to have multiple private/non-advertised servers? I know you can connect to servers that aren't advertised with an ip address, but is it also possible to connect with ip address and port, if there were say 3 private servers, and 2 public servers on the same computer, as an example?

**Comment by pljones** [comment]
@corrados, I'm going to ask you how the registration works as I always get confused with the source ports...

**Comment by corrados** [comment]
> is it also possible to connect with ip address and port, if there were say 3 private servers, and 2 public servers on the same computer, as an example?

Yes, this is possible.

>  I'm going to ask you how the registration works as I always get confused with the source ports...

Do you mean registering a server where the central server is on the same PC?

**Comment by brandflake11** [comment]
Thanks @corrados. How would you choose between the 3 private servers? Do you specify when connecting like this?:
123.12.123:11220

**Comment by corrados** [comment]
Yes, that's the way to do it.

**Comment by brandflake11** [comment]
Thanks @corrados!

**Comment by pljones** [comment]
> > I'm going to ask you how the registration works as I always get confused with the source ports...
> 
> Do you mean registering a server where the central server is on the same PC?

No.  This issue was raised recently (again) where someone had a server started with `-p 22124` (or, rather, default) but the port registered at the central server was some other value.

**Comment by corrados** [comment]
Some routers do these strange things...
