### ISSUE TITLE
Replacing internal history graph functionality by external scripts/tools

### ISSUE THREAD

**Issue by corrados** [corrados/jamulus#501]
It is better to have external scripts/tools to parse the normal log file and create a history graph than to use an internal implementation since that way the graph is customizable. Also some more features can be added to the graph easily without having to create a new Jamulus release.
Since recently we even had stability issues with this history graph, see https://github.com/corrados/jamulus/issues/493, now it is a good time, to remove that functionality from Jamulus.

**Comment by corrados** [comment]
I have just created a directory "tools" in the Jamulus repo and I added the two repos from softins to it as submodules. pljones, since you have more scripts, maybe it is better if you put all your scripts and tools in one repo which you own and I also include this as a submodule. What do you think? I actually would prefer that solution.

**Comment by pljones** [comment]
OK - I'll also be adding my recording exporter scripts, as I've been asked for them several times.

**Comment by corrados** [comment]
Ok, thanks. When you have a stable state in these repos, please create a pull request to point the submodule to that corresponding commit in your repos.

**Comment by pljones** [comment]
OK, first cut version is up and running at http://jamulus.drealm.info/jamulus

**Comment by corrados** [comment]
Hmm, it looks exactly like it was before. Is that intended? If yes, good work :-).

**Comment by corrados** [comment]
@gilgongo I think there is some work to do to describe the changes in the Wiki. Do you have time to do it?

These two command line arguments are removed: "-D, --histdays" and "-y, --history". The functionality will now be in pljones repo which is included as a Git submodule in the official Jamulus Git repo. But there is a catch: If you download the tar.gz or zip from the Github Jamulus release: https://github.com/corrados/jamulus/releases/tag/r3_5_9 these submodules are not included. To get the code you have to clone the Git repo and also you have to call `git submodule update --init`.

I also included some other Git repos in the new tools directory: https://github.com/corrados/jamulus/tree/master/tools
These are the two repos which power the page http://jamulus.softins.co.uk. Also, we have a Docker configuration repo for Jamulus. One repo from pljones which replaces the history graph which used to be integrated in the Jamulus software and another repo which deals with the jam recordings (as far as I understood it).

**Comment by pljones** [comment]
> Hmm, it looks exactly like it was before. Is that intended? If yes, good work :-).

:)

The code looks pretty much the same, too - the abstraction layer worked well and I re-implemented the QXmlWriter in javascript to make the port easier.  Most of the pain was in things like C++/Qt `QDate` vs javascript `Date` - although, I even extended javascript Date to make that easier.

**Comment by gilgongo** [comment]
Ok I'll see if I can update the docs to reflect that.
