### ISSUE TITLE
Prevent [enter] from disconnecting you from a server and change it to [esc]

### ISSUE THREAD

**Issue by sthenos** [corrados/jamulus#515]
On windows at least, the "Disconnect" and "Connect" button is linked with the [enter] key on the keyboard.    This is fine for the "connect" button.  But when you are on a server the disconnect button is also triggered when the [enter] key is pressed.   This can be annoying, for instance when you think you are on the chat window and writing a message and press enter, but you actually have the main window in focus.   This causes you to disconnect.   I would prefer that [esc] is the button that causes you to disconnect from a server.

**Comment by corrados** [comment]
It is fixed now.  Just prevent accidental disconnect by pressing enter should be ok. Some people like, e.g., pljones, often use esc and would not like it if they get disconnected on esc.
