### ISSUE TITLE
Password protect server connections with a username and/or password?

### ISSUE THREAD

**Issue by bren1818** [corrados/jamulus#521]
Hi, in the wake of "Zoom bombing" I was wondering if there was any option to add a "password" option which could be required when connecting to a server? I looked through the configuration options but didn't see any way to specify one.

Thank you

**Comment by corrados** [comment]
There is no password protection and I do not want to implement any. If you want to have a server which can only accessed by your band, you should setup a private server which is not listed in the official Jamulus server lists.

**Comment by bren1818** [comment]
Thank you for the response. Cheers
