### ISSUE TITLE
APTX-LL

### ISSUE THREAD

**Issue by AndyMcProducer** [corrados/jamulus#526]
Hiya, APTX-LL is a codec use in bluetooth now to achieve low latency, I've got a transmitter and reciever and it works very well and very good latency. 
I'm mentioning it here becuase Mac and Android and Windows already support it and I think it is worth keeping an eye on
as it becomes mroe intergrated.

Hopefully it gets picked up by some hardware makers as it woudl effectively allow for low latency ausio with out the need for
asio or wdm. Possibly then being able to be pulled direct into Jamulus and the hardware handling the low latency resulting in
that turn around ms being dropped or got rid of.

If it's supported in windows and mac and android there must be a method of pulling audio straight in with out adding latency.
I'm assuming here though.

https://www.aptx.com/aptx-low-latency

Whe I mentioned codec before, I was on about OPUS and maybe testing x264 x265 or x266 which almsot half the bandwidth and increase quality of each generation.
But each need more cpu to encode but that's becoming less an issue now days.
https://en.wikipedia.org/wiki/Video_Coding_Engine

I was giving a link to somit here i think where it was discussed using the gpu's to encode the audio but not sure where it is now.

Something else I read about too.
https://en.wikipedia.org/wiki/AAC-LD

Also there is a ACC-ELD to, but not all are free but is a bunch on here that are.
https://en.wikipedia.org/wiki/Comparison_of_audio_coding_formats

This sites down atm but hopefully is workign when ya try.
http://celt-codec.org/

This link is workign if th eother don't
http://espico.co.uk/m.celt.html
It is already part of opus.

**Comment by jerogee** [comment]
Great pointers, thanks. However, both APTX-LL and AAC-LD require licensing (Qualcomm, Apple), which is not compatible with Jamulus (open source). Also, these low latency codecs are optimized for Bluetooth and prioritize low power / CPU which are not critical to Jamulus. Other than that, Opus is either on par or superior as for latency-quality trade-off with the these codecs, especially at the higher bitrates. Hard to beat.

**Comment by corrados** [comment]
> However, both APTX-LL and AAC-LD require licensing (Qualcomm, Apple), which is not compatible with Jamulus (open source).

Since it is not compatible to open source, it is not relevant to Jamulus -> closed.
