### ISSUE TITLE
Purge or edit "Server Name/Address" list in Jamulus client

### ISSUE THREAD

**Issue by Willikens** [corrados/jamulus#528]
It would be useful to be able to purge or edit the list of server addresses that get stored in the "Server Name/Address" drop down field within the Jamulus Connection Setup window.  This field seems to record everything ever typed in it, including mispellings, servers no longer available, and servers for which the user no further need.  The resultant clutter can cause user confusion if the list of broken or otherwise undesired entries gets long, particularly if most of the entries are numeric IP addresses.  An ability to clear mistyped and no longer needed server entries from the "Server Name/Address" field would be useful.

**Comment by corrados** [comment]
As a workround, you can remove unwanted entries by editing the file: C:\Users\[yourUserName]\AppData\Roaming\Jamulus\Jamulus.ini

There you finde entries like:
`<ipaddress0>jamulus.fischvolk.de</ipaddress0>`

If you, e.g., don't like this entry, simply replace it by
`<ipaddress0></ipaddress0>`

**Comment by Willikens** [comment]
This may help some of my friends who are on Windows systems.
I'm on a Mac (OSX 10.15.6).  There is probably a similar file somewhere, but I can't find it.

**Comment by corrados** [comment]
Same on MacOS. The path is /Users/{yourUserName}/.config/Jamulus/Jamulus.ini

**Comment by Willikens** [comment]
Hidden file. Found the file and successfully edited out sites I wanted
removed.  Thanks.
