### ISSUE TITLE
Issue with Focusrite Scarlett 2i2 audio interface

### ISSUE THREAD

**Issue by corrados** [corrados/jamulus#53]
See the following thread: https://sourceforge.net/p/llcon/discussion/533517/thread/e0f18d2381/

**Comment by philipmountifield** [comment]
I've just hit this same issue with a new focusrite 8i6 using 3.4 6. Is there any additional debug I can do to assist? I'm a software developer.

**Comment by victorypoint** [comment]
Have you tried the beta Focusrite USB driver version 4.64.15.598? http://beta.focusrite.com/

**Comment by philipmountifield** [comment]
Great shout! I have just tried the `4.64.15.598` version from http://beta.focusrite.com/ mentioned above, and can confirm that the buffer size issue going to 136 has been resolved. There as a fix listed as:

>  Fixed an issue that caused some DAWs (namely Studio One, Reason and Sibelius) to expose buffer sizes that we don't support

Now when selecting the buffer in Jamulus to 128, 256 or 512 works correctly. One this thing which does not work is using the "ASIO Setup" button to choose a buffer size other than 128, 256 or 512, in that case, you can set it when disconnected to say 64, but when you connect it will go back to 128. From the comments in the todo list I think you're planning to allow all available options in a future version though already.

**Comment by corrados** [comment]
That is great news! So you can use your Focusrite with the default block sizes now.

> From the comments in the todo list I think you're planning to allow all available options in a future version though already.

In the current Git code, I will change the default block sizes anyway so that you can select 64, 128 and 256. That would give you the possibility to run your Focusrite with 64 samples frame size. That should give you a great low latency. So it is not necessary to allow all available options.

Since this issue is basically solved by the new Focusrite driver update, I will close this issue now.

**Comment by philipmountifield** [comment]
One thing to note: the driver that fixes it is from their beta site, so not installed automatically. Even though the driver on the beta site has been around since November 2019, so that's a bit odd! Hopefully focusrite will push the driver to general release soon so all users can benefit.

**Comment by victorypoint** [comment]
Glad I could help. I can confirm that the beta drivers works fine with my 1st gen Scarlett 6i6 and Jamulus... and Ableton Live, Reaper, Tracktion Waveform. It seems pretty stable.

**Comment by zuppoii** [comment]
I can confirm that I solved this issue on my 18i8 1st gen by installing the beta driver from the site mentioned above. Superhappy with Jamulus and this solution. But I 'm unable to play using it in DAW mode. When I do that the sound gets blurry no matter what I try. With or without using Reaper and the rearoute solution following Philip's guidance on Facebook or following other guides.  It sounds like in and out are connected to each other...  I 'm on the latest version of Jamulus in Windows 10. Wondering how I can find out where the problem lies? When playing in 'no latency' mode I have the impression when playing together that my sound is synchrone and clear for the other players... Cheers!
Paul

**Comment by flach** [comment]
Is there a fix for Mac users? My friend has a Focusrite Scarlett 2i2 and we were puzzled by the fact that his instruments seemed nearly two semitones out of tune, until we realised that the Scarlett operated at 44.1kHz not 48kHz. The way to change this on a Mac is via Audio MIDI Setup but the Scarlett keeps reverting back to 44.1kHz. Any suggestions? Thanks.
