### ISSUE TITLE
Cannot connect to server socket err & request channel

### ISSUE THREAD

**Issue by WolfganP** [corrados/jamulus#530]
In order to not hijack another issue, I solved the audio problems in headless debian systems I observed at https://github.com/corrados/jamulus/issues/80#issuecomment-674526754 , but still cannot connect to my private server in my lan, launched as:

```
$ jamulus --nogui --server --port 22122 --fastupdate \
        --log /tmp/jamulus-srv.log \
        --servername "Priv server" --htmlstatus /tmp/jamulus.dat
```

Tested with both a client on an amd64 system (where the same jamulus is launched as a server and receives connections from a windows client), and an armhf one. Built from master as:

` qmake "CONFIG+=headless noupcasename" Jamulus.pro && make clean`

Both clients launched in diff machines as:
```
$ jamulus --nogui --connect 192.168.1.155 \
        --port 22122 --clientname Raspi1 \
        --inifile /tmp/jamclient.ini --log /tmp/jamulus-clt.log &
```

Client log files are empty. Client stdout is:
```
 - no GUI mode chosen
- connect on startup to address: 192.168.1.155
- selected port number: 22122
- client name: Jamulus Dev1
- logging file name: /tmp/jamulus-clt.log
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jackdmp 1.9.12
Copyright 2001-2005 Paul Davis and others.
Copyright 2004-2016 Grame.
Copyright 2016-2017 Filipe Coelho.
jackdmp comes with ABSOLUTELY NO WARRANTY
This is free software, and you are welcome to redistribute it
under certain conditions; see the file COPYING for details
JACK server starting in non-realtime mode
self-connect-mode is "Don't restrict self connect requests"
Cannot lock down 82280346 byte memory area (Cannot allocate memory)
creating alsa driver ... hw:1|hw:1|256|2|48000|0|0|nomon|swmeter|soft-mode|32bit
configuring for 48000Hz, period = 256 frames (5.3 ms), buffer = 2 periods
ALSA: final selected sample format for capture: 16bit little-endian
ALSA: use 2 periods for capture
ALSA: final selected sample format for playback: 16bit little-endian
ALSA: use 2 periods for playback
Cannot lock down 82280346 byte memory area (Cannot allocate memory)
 *** Jamulus, Version 3.5.10git
 *** Internet Jam Session Software
 *** Released under the GNU General Public License (GPL)
```

Jack connections are performed, and works even with that annoying mem lock issue:
```
$ jack_lsp -c
Cannot lock down 82280346 byte memory area (Cannot allocate memory)
system:capture_1
   Jamulus Dev1:input left
system:capture_2
   Jamulus Dev1:input right
system:playback_1
   Jamulus Dev1:output left
system:playback_2
   Jamulus Dev1:output right
Jamulus Dev1:input left
   system:capture_1
Jamulus Dev1:input right
   system:capture_2
Jamulus Dev1:output left
   system:playback_1
Jamulus Dev1:output right
   system:playback_2
```

Any clues?

**Comment by gilgongo** [comment]
What's the reason you're specifying the port?

**Comment by pljones** [comment]
* The log file is for the server to log client connect/disconnects, so not used by the client.
* `--port` specifies the local port, not the target
* ...so, `--connect 192.168.1.155` -- can you try `--connect 192.168.1.155:22122`, as it'll use the default port otherwise.

**Comment by WolfganP** [comment]
Thx guys, working perfectly now. I knew it should be something so obvious that I was missing out completely, but I couldn't figure out. I'll update the wiki with this comments are they are worthy.

**Comment by gilgongo** [comment]
This reminds me that I suspect there may be some mistakes in the descriptions of some of the options in the Configuration section on the wiki (is -p server only for instance?)

**Comment by WolfganP** [comment]
That's what I understood from the explanation above. 
Other "thing" I discovered, is that `--clientname` doesn't affect the profile name (I was trying to script the launch of multiple clients for load testing and noticed all connected with the same name to the server, not sure if that's the original intent).

**Comment by gilgongo** [comment]
Yes, `--clientname` came out of a feature request to be able to change the window title. The term "client" being different from "profile name", but I can see the possible confusion.
