### ISSUE TITLE
Expected behaviour of the connection list GUI?

### ISSUE THREAD

**Issue by gilgongo** [corrados/jamulus#54]
I have a public server on a cloud host outside my network running v3.4.7git (Linux) and a client v3.4.6 (Win) on my LAN.

**Summary**

1. The default connection list only seems to show a small sub-set of servers. I assume this is because Jamulus only wants to show me servers with acceptable ping times. However, my server has a short ping time for me, but does not show on the list unless I use `--showallservers`.  But I **can** get my server to show in the default list if I first connect directly to it (but only until I quit the client). I would expect it show automatically in the default list if the server list is sorted/truncated by ping time. 

2. I also observe that `--showallservers ` omits some, but not all, ping times and musician numbers from the list. I would expect all ping times and musician numbers to be displayed.

3. Some servers are shown in bold text. Why is that?

**Screenshots to illustrate**

The default connection window I see looks like this:

![connectionlist-normal](https://user-images.githubusercontent.com/4561747/79040527-0e89ee80-7be1-11ea-888e-2bd71e1aa7b7.png)

My server is not listed. However, when I run my client with `--showallservers`, I see this:

![connectionlist](https://user-images.githubusercontent.com/4561747/79040589-688ab400-7be1-11ea-97a7-8df5f0a40e71.png)

My server is listed, but shows no ping time or musicians. 

If I then connect directly to the server, I can connect OK, and the ping time is lower than shown by others on the list:

![connection-ping](https://user-images.githubusercontent.com/4561747/79040478-9a4f4b00-7be0-11ea-979e-be26b7fb59eb.png)

If I then remove the `--showallservers` option and open the connection window again, I see my server at the top of the list (but only until I quit my client):

![connectionlist-listed](https://user-images.githubusercontent.com/4561747/79040561-46913180-7be1-11ea-8315-6f91665671fc.png)

**Comment by corrados** [comment]
@pljones I fear that this is related to: https://github.com/corrados/jamulus/pull/48
See my comment "Ok, so no "LocalHost" required anymore since if we are running on the same PC, the local IP address should also work, right?" on line 420 in the code. Do you agree?

**Comment by pljones** [comment]
I'm not sure - I'm wondering if it's the existing "else" clause on line 441 down - maybe line 448 should "just happen" once the target address has been determined (even if it's localhost because we couldn't determine something better)?

**Comment by corrados** [comment]
@gilgongo Can you please do your test again with using 3.4.6 official version for the server? Does it work with the old version?

**Comment by corrados** [comment]
> Some servers are shown in bold text. Why is that?

These are "permanent" servers which are online longer than 24 hours.

**Comment by corrados** [comment]
One more question: Are you running the client and server on the same PC when you observer the issue with your server not shown in the list the first time you start the Jamulus client?

**Comment by gilgongo** [comment]
> Are you running the client and server on the same PC

No, the server is on a cloud host on another network the client on my LAN.

**Comment by corrados** [comment]
Ok, then we do not have a problem with the LocalHost I mentioned above: https://github.com/corrados/jamulus/issues/54#issuecomment-612396664

Now the important question is the following: https://github.com/corrados/jamulus/issues/54#issuecomment-612403699
I.e., did we introduce the issue in the current Git code or is the problem caused by something else?

**Comment by gilgongo** [comment]
I've just tried again with Version 3.4.6. 

As far as I can tell, the behaviour is the same. The only difference is that I can't reproduce the last observation. _"remove the `--showallservers` option and open the connection window again, I see my server at the top of the list"_. With 3.4.6 I can't get my server to show in that condition.

**Comment by pljones** [comment]
What if you try registering with jamulus.fischvolk.de:22224 ?

**Comment by pljones** [comment]
Oh - I notice (completely unrelated to this :) ) - that the Connection Setup doesn't refresh the connected client profile details after the dialogue first opens.  If a client changes profile, it's shown in the mixer but not the details for the current server in the Connection Seteup.

**Comment by corrados** [comment]
Yes, this is to keep the traffic low. Client properties are only updated if the number of connected clients change on the Server.

**Comment by gilgongo** [comment]
> What if you try registering with jamulus.fischvolk.de:22224 and then having a client use that to look up servers?

That seems to work OK. I can see my server immediately in that case. I still have one "hidden" server ("drealm Test Server") which I can only see with --showallervers and it has no ping or musicians numbers showing.

**Comment by pljones** [comment]
If I understand it correctly, that means:
- the server has registered with the central server
- your client cannot ping the server

Which is interesting.  Both Volker from his site and I locally can see the server, so it's not an issue on the server side or with the central server.

It sounds like you may have something strange blocking UDP packets from certain address ranges.  That's about all I can think of.  It would explain why you're getting the effect.

**Comment by gilgongo** [comment]
> It sounds like you may have something strange blocking UDP packets from certain address ranges

Would that be at the client or server end?

**Comment by pljones** [comment]
`--showallservers` tells your client to show servers in the list it receives, regardless of whether your client can ping them.

So, if a server only shows with `--showallservers` for you, then it means your client cannot ping that server.

As I noted above, the "drealm Test Server" could be seen and connected to - without, as far as I'm aware (@corrados correct me if I'm wrong) `--showallservers` - which indicates there's nothing wrong in the settings either of the central server or of drealm Test server.

**Comment by gilgongo** [comment]
I'm not sure I follow. 

I could (and did) connect to "drealm Test Server" in the same way as I can connect to any other server. Are you saying that it's something at my client end that is blocking traffic from certain network so that I can't ping those servers to have them turn up on my default list?

**Comment by pljones** [comment]
It's working for other people than you.

It's not working for you.

So it does seem to be a problem that's local to you.

Yes, it's your client that requests the list of musicians and the ping time from your client to each server.

(The central server _cannot_ know the ping time from your client to each server and it would be too much load for it to maintain the list of musicians.)

**Comment by gilgongo** [comment]
Sorry, what do you mean by "it" when you say "It's working for other people than you."? 

What determines whether my client can ping a server or not?

**Comment by pljones** [comment]
"It" - the connections list.  @corrados displayed and connected to both my servers, one on the default central server, one on the north america central server, using the connections list.

There's a very long list of things that can prevent network traffic between hosts.

However, given that the protocol is the same whether it's the ping to the server and its response or connecting to the server and playing in a jam, if you can do the latter successfully, you'd expect the former to work.

**Comment by pljones** [comment]
Now, please note, the server list is in a state of recent change...

Prior to that change, a client with the same "external IP" as any other host was treated as "the same host" and had "localhost" returned for the host IP to use.

What that means is if you're _not_ the same machine as a server, "localhost" is useless.  That's why the list of servers won't show your server without --showallservers (as I think the central server is running the "stable" code) - again @corrados to confirm.

The "new" way is for the central server to say "aha, you're the same external IP as this server, so I won't return 'localhost' which might be useless, I'll return the value the server told me to use".

Of course, that only works where the registering server is running that same "new" code.

Where it isn't, the central server has to make something up.  It's either using "localhost" or the external IP --  both being useless for any machine other than the server itself, for which "localhost" would do.

**Comment by corrados** [comment]
The current Central Server runs to newest 3.4.7 code. So after we fixed the issue, I replaced the binary again so that is uses the latest code.

**Comment by gilgongo** [comment]
@pljones 
> given that the protocol is the same whether it's the ping to the server and its response or connecting to the server and playing in a jam, if you can do the latter successfully, you'd expect the former to work.

Yes, this is what I was thinking. Now that you've explained the issue, I think it may confirm something I think I'm seeing on the forums (at least reading between the lines of some posts). I'll create a separate ticket about it.

**Comment by corrados** [comment]
What is the status of the Issue? Is it solved in the meantime or still open?

**Comment by gilgongo** [comment]
I think it sort of turned into another ticket. I'll close it.
