### ISSUE TITLE
Crash when using the JACK backend and quickly reconfiguring

### ISSUE THREAD

**Issue by corrados** [corrados/jamulus#543]
It is reported that Jamulus crashes if a quick reconfiguring is done. See https://github.com/corrados/jamulus/pull/529

**Comment by corrados** [comment]
@hselasky Can you please write how to reproduce the crash? What did you do exactly before it crashed? Do you mean with "quick reconfiguring" a settings change in Jamulus like, e.g., from Mono to Stereo?

**Comment by hselasky** [comment]
@corrados : Please use the attached patch to provoke the error.

Without my patch you will get this print: "Sound was processing while init"
With my patch this print is gone, and everything is fine.
The crash results from accessing the data buffers while they are being reconfigured, but is not so easy to reproduce.

--HPS
[provoke.txt](https://github.com/corrados/jamulus/files/5137662/provoke.txt)

**Comment by corrados** [comment]
Now I think I know what's causing the crash. Any yes, a mutex as you implemented will solve the issue. Thanks for your code. I'll merge it soon.

**Comment by corrados** [comment]
The code is merged now -> closed
