### ISSUE TITLE
suggest have other idicator of other musicans delay on Jam slider screen

### ISSUE THREAD

**Issue by kezzy1966** [corrados/jamulus#548]
What about having a function of having a traffic light colour to indicate other musicians delay on your Jam session. 
Just a red/amber/green under their slider on the main jam session screen.

This is as i sometimes listen in to a session and someone is badly off. I end up taking all sliders down until i find the culprit. A red or amber light might help identify them quickly. Likewise an experienced Jammer could advise a newbie on things to check.

**Comment by corrados** [comment]
I think this is a duplicate, see https://github.com/corrados/jamulus/issues/164.

**Comment by gilgongo** [comment]
> Likewise an experienced Jammer could advise a newbie on things to check.

See my thoughts on this: 549#issuecomment-682375542

**Comment by corrados** [comment]
Since this is a duplicate, I'll close this one. Please continue the discussion in the existing Issue.
