### ISSUE TITLE
Change stop server message when idling

### ISSUE THREAD

**Issue by bflamig** [corrados/jamulus#551]
When I'm scanner the Jamulus server logs, I'm always thrown for a loop when I see the message "server stopped". This makes me think the server has shutdown, when in fact, most of the time it is idling because there are no more clients connected.

I propose the message be changed to "server idling" when there are no clients. My branch bflamig:change_stop_server_msg has proposed code to make this change.

**Comment by corrados** [comment]
Why not simply exchange the string "server stopped" at https://github.com/corrados/jamulus/blob/master/src/serverlogging.cpp#L62 by "server idling"? I could do that quickly on Git master.

**Comment by bflamig** [comment]
Is the call to stop the server always for when no clients are currently connected? I thought maybe it was called when the server was normally shutting down too. If it's the former, then yeah, it's an easy fix for you if you want.

**Comment by corrados** [comment]
Yes, it's just when no clients are currently connected. I'll change this quickly on master and close your pull request afterwards.

**Comment by corrados** [comment]
It's applied -> closed
