### ISSUE TITLE
Jamulus Server Assign IP Address to be Used

### ISSUE THREAD

**Issue by brandflake11** [corrados/jamulus#553]
Hello all,
Is there a way for the Jamulus Server IP to be set at runtime? I am currently running a machine with about 5 Jamulus servers on it, and my machine has two ethernet cards installed. I want to run 3 servers on one card, and 2 other servers on another, with separate IP addresses. How could I do that?

Thanks for any help on this matter.

**Comment by pljones** [comment]
Can you check #141 and see if you think this is a duplicate.  If so, it can probably be closed.

**Comment by gilgongo** [comment]
Could you do this with socat? 

So if you have IP x.x.x.x and y.y.y.y and the Jamulus servers are all running on x.x.x.x but on different ports with `-p`, have socat direct any UDP requests on y.y.y.y:[port] to x.x.x.x:[port] ?

So maybe `socat UDP-LISTEN:y.y.y.y:[port],fork UDP:x.x.x.x:[port]`

That would mean clients would need to specify the port on their connection to y.y.y.y but I guess you're doing that anyway if you have multiple servers.

**Comment by corrados** [comment]
Yes, I agree, it's a duplicate. @brandflake11 please use the Issue https://github.com/corrados/jamulus/issues/141 for further discussion on that matter.
