### ISSUE TITLE
Show Server Name in Titlebar

### ISSUE THREAD

**Issue by jonw2** [corrados/jamulus#559]
Goal:  The name of the current server should be more prominent.   

Currently the server name is shown inside the main window above the VU meters.

**Requesting to change the main window titlebar,
From:	Jamulus (\<N\> users)
To:           	\<ServerName\> - \<N\> connections - Jamulus**
(And if disconnected, it could say, "No server connected".)

Inside the main window, change text display,
From:	Personal Mix at \<ServerName\>
To:          	Personal Mix

Titlebars would then be more like e.g. MS Word, where the document name displays before the app name, separated by dashes.  So people would find it more familiar.  (In other words, the titlebar would name the working context within the app.)
![Titlebar](https://user-images.githubusercontent.com/5332637/91722287-07e81d80-eb68-11ea-9066-60961733e62b.png)

Some of our users get confused between servers with similar names, and would be less confused if the server name was in the titlebar.

The word "connections" might be more accurate than "users" in that often someone leaves a server connected but is not at their computer, so during that time there is no active user.  Also in the future it's possible that Jamulus might allow connections which were playing automated sound with no human musician.

**Comment by pljones** [comment]
It's already the case that one user might have multiple connections (backing track, vocals, instrument).  "Channels" is the term used under the "Edit" menu, so it's probably best to stick to that rather than introduce a separate term.

**Comment by jonw2** [comment]
Good comment, it would also be fine if the titlebar kept the word "users" like this:
<ServerName> - <N> users - Jamulus

**Comment by corrados** [comment]
So it would look like this:
![grafik](https://user-images.githubusercontent.com/46655886/92308102-a5de4c80-ef9b-11ea-9f2c-e7fb3d6fed92.png)

If not connected:
![grafik](https://user-images.githubusercontent.com/46655886/92308119-b7275900-ef9b-11ea-9351-e89b64a996e2.png)

If only one client is connected:
![grafik](https://user-images.githubusercontent.com/46655886/92308131-c8706580-ef9b-11ea-90c2-f64959a8cdaf.png)

**Comment by corrados** [comment]
The code is applied to the Git master -> closed.
