### ISSUE TITLE
Add the description paper to the wiki

### ISSUE THREAD

**Issue by jzy3d** [corrados/jamulus#56]
Congratulation @corrados for your work and thank you for releasing this as an open source software. May I suggest to add your paper to the wiki?

http://llcon.sourceforge.net/PerformingBandRehearsalsontheInternetWithJamulus.pdf

One interesting point is the global architecture description that I could not find on the wiki.

**Comment by corrados** [comment]
I guess you can do it yourself, its a Wiki :-).

**Comment by gilgongo** [comment]
Go for it @jzy3d :-)

Maybe on the home page something like, "_For detailed information about how Jamulus hacks the space-time continuum to produce a near-perfect 5th dimension of collaborative sound, see this paper by Volker Fischer (PDF 92Gb)_" ?

**Comment by vocobox** [comment]
@gilgongo I love that sentence :) (I am the same person than @jzy3d)

**Comment by vocobox** [comment]
Just did it here (https://github.com/corrados/jamulus/wiki), you might close the issue!
Martin
