### ISSUE TITLE
Client Software to auto connect to a single server

### ISSUE THREAD

**Issue by kezzy1966** [corrados/jamulus#561]
Hi Team,

May I ask you to consider adding a function to the client s/ware to set connect to 
1) my default server or 
2) select from the public server list. 

This is to assist non technical users who have had their software setup by a someone else. They would always connect to the same server and might get confused seeing all these other servers pop up. The default maybe a public server or unlisted private server. 

If default server box is selected, there would need to be a space to type in and remember the server address. Would be great if Jamulus OS - on a usb stick - could be a persistent so the settings could be saved on the USB.

Thanks.

**Comment by ann0see** [comment]
I think the -c option already does this. Look at the command line section in the wiki

**Comment by kezzy1966** [comment]
Thanks so much. That looks promising. I'll check it out. 
Here is the wiki I think you are referring to (I just found it):
https://github.com/corrados/jamulus/wiki/Command-Line-Options

**Comment by ann0see** [comment]
Yes. That’s it.

**Comment by corrados** [comment]
Should we close this Issue then?

**Comment by kezzy1966** [comment]
Corrados, may I be given have a couple of days to test that please ?

**Comment by corrados** [comment]
Sure, no problem. Take your time :-).

**Comment by kezzy1966** [comment]
OK. Yes happy to say using the -c option works. 
However, As an ordinary user it would still be nice to have it within the client under a setting. 
...but i'm grateful for anything you guys do.  The system if great.

**Comment by ann0see** [comment]
I think you could edit the desktop icon on Windows and add the -c flag.

**Comment by corrados** [comment]
> As an ordinary user it would still be nice to have it within the client under a setting.

I think the auto connection is a very special need and not for the "ordinary user". So I think a setting in the client GUI would more likely confuse the users then users can profit from it. So I think we keep the existing way to do it to use a command line argument (as ann0see noted, you can simply modify a Windows desktop shortcut to auto connect to a server).

**Comment by corrados** [comment]
I'll close this now.
