### ISSUE TITLE
jamulus.desktop and jamulus-headless.desktop

### ISSUE THREAD

**Issue by trebmuh** [corrados/jamulus#564]
_(from #563)_

It'd be great to generate a desktop file for jamulus-GUI ("jamulus.desktop") and another desktop file for jamulus-headless ("jamulus-headless.desktop").

**Comment by tormodvolden** [comment]
Why a desktop file for something that is meant to run as a system daemon or from a command line in a non-desktop environment? People can still run a server with the "full" jamulus.

Maybe you meant a separate desktop file for running the "full" jamulus as a server with a GUI?

**Comment by trebmuh** [comment]
> Why a desktop file for something that is meant to run as a system daemon or from a command line in a non-desktop environment? 

That's a valid point.

To be honest and precise, my real point here is that I ended up with a desktop file named "jamulus.desktop" with a "jamulus-headless" as 'Exec" line.

Which in my opinion, this very need to be avoided.

Then, I though "oh well, maybe someone needs a desktop file which launch jamulus-desktop, so better to keep it". I didn't think about such a use case.

The real important things is to avoid to have a jamulus.desktop file which is launching a jamulus-headless binary like it was the case before I made #563.

If we're to go (I've no opinion on that) to remove the auto-generation of a jamulus-headless desktop file.

Your call guys.

**Comment by tormodvolden** [comment]
You already fixed this in #563. It could be made more robust by manually copying out the desktop file from the gui build and specifying it explicitly in debian/jamulus.install but as long as we are aware of the potential issue it is maybe good as it is for now.

Still, a "jamulus-server" desktop file could be useful (for the "jamulus" package).

**Comment by tormodvolden** [comment]
Or on a second thought, should the autogenerated desktop file have its name from the cmake TARGET variable? It would prevent the earlier clash.

**Comment by trebmuh** [comment]
> You already fixed this in #563 

Not really, it's only a workaround in a .deb package build context. That is why I opened this issue here for @corrados to have a look at it if he thinks that deserves a fix.

**Comment by tormodvolden** [comment]
Yes, I started to understand that your point was not about just the Debian packaging :) It should rather not create and install the desktop file for the qmake "headless" build variant. I have made a suggested modification of Jamulus.pro so that it skips the desktop and icon installation on "headless": https://github.com/corrados/jamulus/pull/566

**Comment by trebmuh** [comment]
#566 has been merged.
Closing here then.
