### ISSUE TITLE
RYG indicator lights need colour-blind compensation

### ISSUE THREAD

**Issue by gilgongo** [corrados/jamulus#57]
Red–green colour blindness affects up to 8% of males and 0.5% of females of Northern European descent. Colours of traffic lights are confusing to these people as there is insufficient apparent difference between them.

To avoid discriminating against red-green colour blind people, suggest adding textual status to avoid confusion:

![image](https://user-images.githubusercontent.com/4561747/79046096-a0f0b900-7c06-11ea-9ed7-36847c84c9f5.png)

## Another approach

Maybe use blink rates? Not as clear - the user has to know what the blink rates mean - but once they know they can remember forever. Might also help those without colour blindness too.

- No blinking (steady) on Green
- Slow blinking on Yellow
- Fast blinking on Red

**Comment by pljones** [comment]
:) Maybe "Poor"...

**Comment by trebmuh** [comment]
I agree. I'm color blind and those color are hard to see for me.

**Comment by FabriceReynolds** [comment]
I also agree as I'm colour blind too and the green and yellow almost look the same to me

**Comment by corrados** [comment]
This is related to that: https://github.com/corrados/jamulus/issues/71. I''ll try to fix both.

**Comment by Skeezixes** [comment]
I am not discouraging anyone from adding explanatory text, but in addition, the RYG colors themselves can also be altered slightly (make the Red more bluish, the green more yellowish, the yellow more orangish--I think) to be more discriminable by color blind individuals. Online tools exist for this.

**Comment by gilgongo** [comment]
The trouble is that not all colourblind people are "blind" to the same colours. So if you rely on simply altering the chrominance, the best you can hope for is to make it better for some, but not all colourblind people. See the discussion in #71 . There is also the issue of monitor and ambient light variances too, which mean that colours can be rendered differently in ways we can't control.

**Comment by Skeezixes** [comment]
Exactly. I'm not disagreeing. You can make the hues more discriminable to most but not 100% discriminable to all, or even to some. You can make them better, but you can't fix the problem by changing the colors.

**Comment by corrados** [comment]
Is this still relevant? There were a lot of changes done to the GUI in the last month. Maybe we can close this Issue now.

**Comment by gilgongo** [comment]
I guess we can close it. Accessibility hasn't been a very big issue, so I guess if it gets mentioned again we can reference the ideas here.

**Comment by moyesmars** [comment]
For me, it is still not possible to distinguish red/green LEDs. I would very much appreciate if, eg, the current colour would be mentioned in the mouse-over text. E.G.: "The LED indicator is currenty **yellow**. If it turns to red, you will not have much fun..."

**Comment by gilgongo** [comment]
Mouse over text would require you interact with the UI to discover its state though. Would one of the proposed solutions work not for you?

BTW you could ask why have the lights at all. If all is well then you don't need to look at them. If all is not well then one of the lights will simply show what your ears confirm, but only when you are looking at them. The issue is whether you know what to do in the latter event. But without any history available that's a bit difficult 🔢

**Comment by kwindrem** [comment]
I think having these indicators is nice to have as it can give you a warning to future issues or to confirm what your ears have detected without opening the Settings pane. 

I am not color blind but find short flashes of a color change doesn't always register. I find this with one light level indicators that are green for active signal and turn red for clip.

What about expanding each LED to THREE: 3 lights = Good, 2 lights = Fair, 1 light = Poor?

Maybe having just one quality indicator(three LEDS) that incorporates Buffer and Delay indications would be sufficient.

**Comment by gilgongo** [comment]
Yes, I guess it's nice to have some visual "feedback" of the problems you have with your sound. And of course what to do about it is a separate issue.

> What about expanding each LED to THREE: 3 lights = Good, 2 lights = Fair, 1 light = Poor?

Yes that would also solve the issue of using colour alone to convey meaning. Although it would mean a bit more screen space being used. There is also the slight issue of them looking like they might be audio signal indicators perhaps. But one advantage this this approach has over simply labelling the status of the light is that the labels might flicker, so three lights might be clearer in that respect.

**Comment by moyesmars** [comment]
> I think having these indicators is nice to have as it can give you a warning to future issues or to confirm what your ears have detected without opening the Settings pane.

Agreed. Especially, since I can see when it switches to yellow - but when it switches away from yellow, I don't know whether to red or green...

> 
> I am not color blind but find short flashes of a color change doesn't always register. I find this with one light level indicators that are green for active signal and turn red for clip.
> 
> What about expanding each LED to THREE: 3 lights = Good, 2 lights = Fair, 1 light = Poor?

Yes, that sounds like a very good idea to me.

**Comment by corrados** [comment]
What about a simple solution:
![CMVVYnKYnH](https://user-images.githubusercontent.com/46655886/98436834-f3cc1980-20de-11eb-93b2-62f3fdeeaeb6.gif)

**Comment by moyesmars** [comment]
Thanks for reopening the issue. Yes, simple and suffient IMHO.

**Comment by corrados** [comment]
@geheimerEichkater From a designer perspective, can you please comment on the new LED designs I created?

**Comment by Skeezixes** [comment]
I like it!

**Comment by geheimerEichkater** [comment]
Very good topic. I would add two thoughts:
1) Adjust the colors a tiny bit. I would try to have green be the brightest color, yellow a tad darker/more saturated and red to be the darkest of the three, so brightness offers hierarchy.
2) Instead of a vertical and horizontal bar which carry no implicit meaning, it'd suggest to set a black dot (or horizontal bar) into the center of the yellow led and a white cross inside the red led.

<img width="361" alt="normal" src="https://user-images.githubusercontent.com/67019343/98684273-41a68300-2366-11eb-9377-cfe7d63666ad.png">

<img width="361" alt="Deuteranopia" src="https://user-images.githubusercontent.com/67019343/98684313-4d924500-2366-11eb-9b01-6a6d7272a40e.png">

The color values I've applied are: 
CC3333 (red)
FFCC00 (yellow)
66FF00 (freen)

**Comment by corrados** [comment]
Good idea, thanks. I'll try these out. Since for the "Fancy" skin we still have the LED meters which are not distinguishable for color-blind people, I only make these changes for the normal skin (this has bars for the level meters).

**Comment by corrados** [comment]
Here it is:
![ERkoKsSjMs](https://user-images.githubusercontent.com/46655886/98702761-15e1c800-237b-11eb-9624-7d84aee4367f.gif)

**Comment by corrados** [comment]
The new Icons are now applied to the Git master -> closed.

**Comment by moyesmars** [comment]
Thanks!

**Comment by trebmuh** [comment]
That's looking good !
