### ISSUE TITLE
Recording on server using command line

### ISSUE THREAD

**Issue by sthenos** [corrados/jamulus#574]
This may already be possible so feel free to close, but is there a way to specify a server to have a recording directory but to not start up initially with recording enabled?   I.e. i'd like my servers to setup without recording turned up, but then use SIGUSR2 to enable recording once it has started?

**Comment by gilgongo** [comment]
I think this came up on the forums the other day: 

https://sourceforge.net/p/llcon/discussion/server/thread/698e6ee735/#b6f5

Assuming it's the same issue, I suggested an (untested) workaround to simply start the server and immediately issue a SIGUSR2.

Maybe.

**Comment by pljones** [comment]
I don't run Jamulus directly from the service file - I use a script.  So, for me, it it would be relatively easy to add `& (sleep 1; systemctl start toggleRecording)`.  I'm not sure if that'd work cleanly directly from the service file.  (And it assumes you have the toggleRecording service... it's just a `systemctl kill -s SIGUSR2 Jamulus`.)

**Comment by sthenos** [comment]
Yes that's what I'm currently doing, I issue `kill -12` to the process, it's just not very clean.   It would be great if there was a `--enable-recording` flag as well as the `--recording` flag that would enable recording if `--enable-recording` is also passed, otherwise it leaves recording off. and then I can start recording at a later date using `kill -12`

**Comment by pljones** [comment]
It'd likely be a `--disable-recording` or an `--enable-recording (yes|no)` option, defaulting to yes.  Coz it's mine, all mine, I tell you... ;)

**Comment by sthenos** [comment]
lol, yes that logic makes more sense.     and yes I guess my use case is probably less frequent for most! ;)

**Comment by pljones** [comment]
OK, just to write here what I wrote in #536...

Passing `--recording <dir>` will have the server log that recording is enabled... unless...
`--norecord` is passed as well, in which case the it will log that recording is disabled.

Passing neither should not log anything about recording.

I'm probably going to have to investigate why Jamulus Server with GUI isn't saving the recording directory (for me, at least).

**Comment by pljones** [comment]
#596 raised to address this.

**Comment by corrados** [comment]
The code is merged -> closed.

**Comment by pljones** [comment]
I'm sure this would have been picked up but I really need to get into the habit of updating the change log.

#600 is now there to do that.

**Comment by pljones** [comment]
[Wiki](https://github.com/corrados/jamulus/wiki/Command-Line-Options) updated.
