### ISSUE TITLE
Input threshold for -R?

### ISSUE THREAD

**Issue by gilgongo** [corrados/jamulus#58]
It appears that -R starts recording on the first connection and ends after the last connection has ended. 

If a connection is making very little sound, it still uses quite a lot of disk space (a user connected to my server for several hours and used over 1Gb of disk space while only producing a slight hum the whole time).

Would it be useful to only start server recording over a certain volume so that disk space isn't wasted?

**Comment by pljones** [comment]
I post-process the files to clean up.  It saves using extra server CPU during a jam.

**Comment by pljones** [comment]
Attached are my scripts.
[JamRecordingHandlers.zip](https://github.com/corrados/jamulus/files/4465424/JamRecordingHandlers.zip)

**Comment by gilgongo** [comment]
Ah - yes I forgot about inotify. Will try those - thanks!
