### ISSUE TITLE
Transmitting uncompressed audio

### ISSUE THREAD

**Issue by dyfer** [corrados/jamulus#580]
Hello, I was searching the issues/PRs for this but could not have any information whether this has been discussed.

I wanted to ask whether support for uncompressed audio (in addition to current OPUS options) could be considered. Aside from difference in quality, I would think that this would lower the processing latency associated with OPUS encoding/decoding (client encode + server decoder + server encode + client decode). My question is whether there's any interest in having this option and whether there are any obvious roadblocks in implementing it.

**Comment by corrados** [comment]
It has been discussed in this Issue: https://github.com/corrados/jamulus/issues/516.

**Comment by dyfer** [comment]
@corrados thanks! somehow I missed that
