### ISSUE TITLE
Minor calculation error in client.cpp

### ISSUE THREAD

**Issue by bflamig** [corrados/jamulus#584]
Near the bottom of client.cpp are two lines that compute the "delay to fill network packet". The lines are

```
const double dDelayToFillNetworkPacketsMs =
        GetSystemMonoBlSize() * 1000 / SYSTEM_SAMPLE_RATE_HZ;

```
Since GetSystemMonoBlSize() returns an integer, the division being done is all integer, so the result is truncated. For example, when I'm running Jamulus at my client settings, GetSystemMonoBlSize() is 64 samples. So 64 * 1000 / 48000 = 1.33 ms. Yet the source code truncates this to 1 ms. So it's off by 0.33 ms.

Yes, it's minor, but I thought I'd point it out.

**Comment by corrados** [comment]
Should be fixed now on master. Can you please test if the result is now correct?

**Comment by bflamig** [comment]
Yes, it works

**Comment by corrados** [comment]
Thanks for testing. I'll close this Issue now.
