### ISSUE TITLE
-L considered harmful 

### ISSUE THREAD

**Issue by gilgongo** [corrados/jamulus#587]
I have mentioned this before, but seeing as some tickets have been raised recently about legal issues, I thought I'd mention it again :-)

I think (but I am not sure) that the `-L` CC licence option for servers is supposed to imply that participants agree that anything they play will be under that licence.

Whether rights holders (or even Creative Commons) might object to server operators imposing CC licences on the performance of what might be otherwise protected works is not the issue. Nor whether they might want to shut down the Jamulus project as a consequence, and jail us all along with the founders of The Pirate Bay for enabling mass online copyright infringement.  

The issue is that the Jamulus project should not be making legal decisions on behalf of anyone by giving them a specific licence to show.

Allowing arbitrary licences seems to be too difficult https://github.com/corrados/jamulus/issues/367#issuecomment-644195372 and I think if server operators wanted to display a copyright message they could do so with a link in the welcome message. 

So I think the `-L` option should be removed.

**Comment by pljones** [comment]
Perhaps alter what it does.

1. Display the welcome message, if there is one.
2. If there was a welcome message and --license / -L is specified, require the user to confirm consent to complying with whatever they've been told they have to comply with.
3. If and only if they agree, enable processing of their chat and audio messages.

**Comment by corrados** [comment]
Actually a good idea but it would break compatibility. E.g. if some starts his server with: ./Jamulus -s -n -L -w "Welcome to my beautiful server" and upgrades just the Jamulus software but not his start script, at the client a licence dialog would open showing the text: "Welcome to my beautiful server" -> Press OK if you agree to the licence? :-)

So how should we solve the compatibility issue?

**Comment by gilgongo** [comment]
> So how should we solve the compatibility issue?

If we don't solve it, then it would keep [--histdays](https://sourceforge.net/p/llcon/discussion/server/thread/c004de2ea9/#23a4) company :-)

**Comment by corrados** [comment]
I think --histdays is very different. If a script did contain the --histdays command line argument, the Jamulus server will not start anymore. This is not the case here. The server starts fine but does something unexpected.

**Comment by gilgongo** [comment]
Could we show a "deprecation message" instead? So instead of the licence, the window shows a message saying the licence text feature is being removed and server operators are encouraged to use [new method]  (eg link to licence in welcome message, or maybe @pljones solution although I thought that might not possible last time we talked about it. Something to do with UDP payloads?)

**Comment by corrados** [comment]
I am now of the impression that removing the -L completely is the most simple and effective solution.
@gilgongo You were proposing that the server operator simply puts it's licence in the server welcome message. The problem is, that the Jamulus user must not press a button to agree to that licence. Do you think that is a problem?

**Comment by gilgongo** [comment]
>  the Jamulus user must not press a button to agree to that licence. Do you think that is a problem?

Most copyright notices seem to be "passive" in the sense that they don't block your use of things (at least I can't think of a common example that prevents you from proceeding). I guess the _playing_ of live music in public might be different? No idea (and I don't think any lawyers would know either). Just about all music (outside of some folk and classical) that people know is under copyright anyway so committing to not "copy" it would be ... very hard :-)

**Comment by corrados** [comment]
@pljones Since you are a "power user" of the licence dialog since you publish your jam recordings: What is your opinion on removing -L?

**Comment by pljones** [comment]
I want something that prevents a user who has not acknowledged any limitation or expectation placed upon them.

The current -L does this (with a fixed message), which isn't ideal.

Perhaps "-L" with no argument could default to the existing behaviour exactly, preserving backward compatibility and -L with an argument of "welcome" could have my suggested behaviour?  Or perhaps -L with a filename to display that text?  Or both of those additional options?

**Comment by ann0see** [comment]
Do the recent commits to master fix the UDP fragmentation issue? If so, other licenses/free text or HTML could be possible?

A short free text message telling the user to look at {link to license} with is shown to newly connecting users and they have to agree to could be a workaround.

Compatibility will probably have to be broken. 

A solution could be a welcome mesage saying that the client is too old. 

Or the server could send the license text/link and block audio mixing unless the client replies „I agree“ to the server. 

I‘ve already implemented kind of similar code on my fork (edu tools branch) to handle messages, block audio,... from specific clients (https://github.com/ann0see/jamulus/tree/eduTools)

**Comment by pljones** [comment]
> A solution could be a welcome mesage saying that the client is too old.

-L didn't work before 3.4.2 anyway.  I discovered that :).

**Comment by gilgongo** [comment]
> Perhaps "-L" with no argument could default to the existing behaviour exactly,

This doesn't address the problem though, which is that _we are not lawyers_.  How do you know what licence to show on behalf of any server operator?

As I understand it, anyone agreeing to the CC message will need have a handy list of CC licensed works to play ... that others on the server will know. Even if that was practical (which is isn't), we should just keep out of any licence or legal positioning of any kind. That's the point of this ticket.

**Comment by pljones** [comment]
> This doesn't address the problem though, which is that we are not lawyers. How do you know what licence to show on behalf of any server operator?

This is for people who are already using it.  We can safely presume _they_ know what they're doing and state that alternative behaviour is available.

**Comment by pljones** [comment]
@corrados I guess we're back with you then:

- remove `-L` entirely
- break backward compatibility and reimplement `-L` (or call it something else, removing `-L`)
- retain `-L` and extend it (or add something else as well)

I guess the second option probably satisfies most people here and will at least alert server operators that something has changed (reading the Changelog to find out what...).

**Comment by gilgongo** [comment]
> My idea of jamming is you're not using other people's work at all

Yes that too. But as I say, that's not relevant to this ticket, which is not about whether the CC licence is appropriate or not, but about what the Jamulus project should be doing when it comes to licensing in general.

**Comment by ann0see** [comment]
And Jamulus doesn’t have to be used for jamming only. Rehearsals of other pieces is also done especially nowadays.

**Comment by corrados** [comment]
> -L didn't work before 3.4.2 anyway.

Ok, so the situation right now is that if you use the -L flag, no never know if the user had to accept any licence.

> Most copyright notices seem to be "passive" in the sense that they don't block your use of things (at least I can't think of a common example that prevents you from proceeding). I guess the playing of live music in public might be different? No idea (and I don't think any lawyers would know either).

I am no lawyer. And as you proposed, we should remove everything from Jamulus which would indicate that we would be lawyers. I agree with this.

> @corrados I guess we're back with you then

If you ask me, I would prefer the simplest solution -> just remove the -L support. But I guess some people will not be very happy about this. At least with the welcome message some sort of licence text could be shown to the users of the server.

**Comment by pljones** [comment]
> And Jamulus doesn’t have to be used for jamming only. Rehearsals of other pieces is also done especially nowadays due to COVID

That can be done on a private server and no one would have to have to have a server generated licence agreement - they'd have agreed to anything before being allowed in.

**Comment by pljones** [comment]
> Most copyright notices seem to be "passive" in the sense that they don't block your use of things (at least I can't think of a common example that prevents you from proceeding).

When I watch a DVD, the copyright and licence message display for quite a long time and I can't skip them on my DVD player.  That was a pretty common example before people started to expect to be able to get everything they wanted for free on-line.

It's that behaviour I'd like to have "something like -L" replicate.

**Comment by ann0see** [comment]
What about reimplementing (and removing -L)? A new flag would show a window saying:

"Before connecting, please agree on this:

{HTML Message (only short but with the ability to add a link)}

[Agree] [Disagree & Disconnect]

and backwards compatibility handled via chat:

> Or the server could send the license text/link via chat and block audio mixing, receiving, sending, chat,... for the new channel unless the client replies "I agree" to the server. After having received this message, the server starts sending audio.

This would give the server a free choice of linking licenses. If -L is setup the client also shows this message but with the text

"{Link to current license} ... this server is outdated. Please inform the server admin to upgrade!"

**Comment by corrados** [comment]
We are discussion how to change the licence mechanism. But what gilgongo initially stated is more like: "_So I think the -L option should be removed_.". As far as I know he was in contact with a laywer and he recommended to better remove any licence stuff from the software (@gilgongo is this correct?).

**Comment by gilgongo** [comment]
@corrados The person I spoke to isn't actually an IP lawyer, but worked as the licencing manager for the British Library (print, film and sound archives) for a number of years, and was active in promoting the use of open and CC licencing as part of that work. He said that given the very uncertain situation around copyrights on the Internet, he thought it best for the Jamulus project to stay as neutral as possible to avoid unwelcome surprises :-)

**Comment by pljones** [comment]
Which doesn't mean that a server owner shouldn't be provided with a means of displaying _something like_ the existing -L pop up.  It means that the Jamulus software should not say "If you want a licence, it's CC-NC-SA 4.0".

**Comment by WolfganP** [comment]
If no SME/law experts involved, why force a license on the generated content by just guessing what's needed? It may cause more legal issues than keeping the situation of explicit enforcement by server owners & users.

My preference will be just remove the -L stuff, and if any disclaimer is needed, just state it in the wiki and/or the program installer. If the server owner wants to exert any license stuff, then the chat welcome message will be a good channel for warning users.

**Comment by gilgongo** [comment]
> Which doesn't mean that a server owner shouldn't be provided with a means of displaying _something like_ the existing -L pop up. It means that the Jamulus software should not say "If you want a licence, it's CC-NC-SA 4.0".

Exactly.

> The server owner is "expected to" accept the GPL 2 under which the software is supplied

Yes, but just to be clear: the licence under which the Jamulus **source code** is made available is a completely separate matter not being discussed here. I'm sure you didn't mean to conflate the two - just checking :-)

**Comment by pljones** [comment]
> I'm sure you didn't mean to conflate the two - just checking :-)

Just introducing my example that makes it clear that it _is_ entirely separate.

> If no SME/law experts involved, why force a license on the generated content by just guessing what's needed?

This is what we're discussing.  What should replace the existing option?

**Comment by corrados** [comment]
> From a legal perspective, it would be nice if positive acceptance were logged in a way that showed a licence had been accepted. That, at least, would help the server owner demonstrate they'd displayed something to the user and they'd agreed. (Again, a point at which the server owner needs the IP address in full logged.)

Old clients do not show the accept dialog even with -L used in the server. And it is not clear that an "accept" button is required. So I think if you put the licence in the Welcome message, it should be ok. So I still would like to just completely remove the -L.

**Comment by corrados** [comment]
I just implemented that the chat window is always shown und upfront if a server welcome message is received. That way we can make sure that the Jamulus client user will really have the text visible.

**Comment by corrados** [comment]
> So I still would like to just completely remove the -L.

Any opinions on that? I would like to start coding...

**Comment by ann0see** [comment]
I vote for reimplementing:
Block Audio Mixing for client unless he responds "I accept" to the server which has sent the license as a text message.

**Comment by WolfganP** [comment]
I'm for totally removing it. I don't think there's any rights or license to enforce on the content that won't cause more problems that leaving it free to users to resolve on their own. Just look at the constant battle of incidental music in the background in youtube, or the fights about who owns a selfie by a monkey...

On the other end, enforce license/copyright for the authors on the code: 100% agreed.

**Comment by pljones** [comment]
@WolfganP - anyone who wants what you want just doesn't use -L, right?  Some of us do want to let our server users (a) know we're recording and (b) that they're agreeing to certain terms.  So using -L to do that makes perfect sense.  If you don't want that, you don't use -L.

**Comment by gilgongo** [comment]
> Without some confirmatory action, simply displaying text there is valueless.

For the purposes of this ticket, as long as the licence wording is not fixed as it is today, then having a function that "clickwraps" something (blocks entry to the room until you've agreed) would be fine. But then I'm not doing any coding.

**Comment by pljones** [comment]
I think we've got it down to two groups:

1. those who don't see the need to have a click-wrapper license.
2. those two do see the need to have a click-wrapper license.

For the former group, the current solution is: don't use -L.  No one is proposing to change this.

For the latter group, the current solution pre-determines the text that's agreed to and it's generally felt not to be ideal to have it work like this.

Thus this ticket _can_ add value to the existing solution, rather than removing it (i.e. doing what "don't use -L" already does).

Does it need a separate pop up to _hold the text_?  For me, not necessarily.
Does it need a separate pop up to _request confirmation of acceptance_?  For me, not necessarily -- although it's probably easiest for the user to understand.

So what do I need?  Until they accept:
- No audio is sent from the server to the client
- No details of other connections are sent from the server to the client
- Only server-generate chat appears in the chat window
- No indication of their presence is seen by others connected to the server

Yes, that's much of a change from the existing behaviour but, as we're changing what it means, I can't see why not... :)

**Comment by corrados** [comment]
> Block Audio Mixing (server side) for client unless he responds "I accept" to the server [...] So what do I need? Until they accept

Thanks for your feedback. The fundatmental question remains unanswered (and I guess you need an answer for each country Jamulus is used in): Do you need an explicit button to accept a licence or is it enough to just show it in the Welcome Message. I assume most server operators are fine with the fact that they just show a "usage guide" or "some sort of licence" in the Welcome Message.

Ok, but this Issue is not about implementing a new licence mechanism (we may create a separate Issue for that), it is all about a problem that Jamulus should not be a "legal guide" by any means. So the setting must be removed.

@gilgongo What about the following:
- Remove the "Show Creative Commons BY-NC-SA 4.0  Licence Dialog" from the server GUI and the settings ini-file.
- Remove the description of -L from the "--help" command line help text.
- Remove the -L description from the Wiki.
- BUT: Keep the -L functionality in the Jamulus client/server software (as a hidden feature) so that "power users" like pljones can still use the existing functionality (and I think he is happy with what is implemented right now, right?).

What do you think? I think that would solve the intention of this Issue by, let's say, 95% :-).

**Comment by gilgongo** [comment]
@corrados That's a good compromise I think. And "power users" might even be able to re-compile with a different licence if they wanted I suppose? Maybe put a comment in the code that says if they use this undocumented feature, they do so at their own risk. 

Meanwhile, we assume that people are free to put links to licences in the welcome message. It just won't be click-wrap.

**Comment by pljones** [comment]
> "power users" might even be able to re-compile with a different licence if they wanted I suppose?

But why make it that hard?  Why not just have `-L` display a simple "Do you agree to the text in the chat window?"  Then, those who want CC4-NC-SA can display it (i.e. same as today) and use -L if they need confirmation or not if they don't need confirmation.  Or those who want something else can display something else - and use -L if they want agreement, or not if they don't.

**Comment by WolfganP** [comment]
> 
> 
> > "power users" might even be able to re-compile with a different licence if they wanted I suppose?
> 
> But why make it that hard? Why not just have `-L` display a simple "Do you agree to the text in the chat window?" Then, those who want CC4-NC-SA can display it (i.e. same license as today) and use -L if they need confirmation or not if they don't need confirmation. Or those who want something else can display something else - and use -L if they want agreement, or not if they don't.

That's probably a better solution for (almost?) all use cases. Instead of Jamulus being an unified text "legal guide" as commented above, keeping the -L with click "Accept license to proceed", and allow a custom text/rich html file to be displayed as with --welcomemessage may suit all needs.

**Comment by gilgongo** [comment]
As long as the user is free to display any license they choose including none, and Jamulus is not "endorsing" any particular licence, then all is well. If we want to clickwrap it then that's fine too.

But do not endorse or otherwise suggest any particular licence. We are not lawyers :-)

**Comment by corrados** [comment]
Yes, this is good idea, pljones. But I still would remove the -L setting from the GUI and settings. The preferred way of doing it is to simply write a text in the Welcome message. If the server operator sees a need to have a "button press" confirmation, he has to use a command line argument:

So I would then implement the following:

- Change the licence text in CLicenceDlg::CLicenceDlg to "Do you agree to the text in the chat window?".
- Remove the "Show Creative Commons BY-NC-SA 4.0 Licence Dialog" from the server GUI and the settings ini-file.
- (KEEP the description of -L in the "--help" command line help text) _<- nothing to do here_

**Comment by corrados** [comment]
Ok, it's done now (https://github.com/corrados/jamulus/commit/81e978e84a98023ab96b048c6176678a562ab9ce). This is how it looks like after the change:
![grafik](https://user-images.githubusercontent.com/46655886/94344633-f556ec00-0020-11eb-8914-d7b9edebe1a1.png)

**Comment by ann0see** [comment]
Actually I‘d add a clickable link to show the chat window. This would ensure that the license is always readable.

**Comment by corrados** [comment]
> This would ensure that the license is always readable (and the user doesn’t have a way to say he didn’t find it).

This was already considered in that commit: https://github.com/corrados/jamulus/commit/923c7d71b374fae9cf7aed7e84d3b290dd941719 -> if the server welcome message was received, the chat dialog goes upfront.

> Furthermore I‘d remove the Text box and just show a label.

Yes, I agree. I'll change that.

**Comment by corrados** [comment]
Here we go:
![grafik](https://user-images.githubusercontent.com/46655886/94345459-474e4080-0026-11eb-9561-539b9d9808fe.png)

**Comment by ann0see** [comment]
Looks good. How is backward compatibility handled?
(What if a server operarator doesn’t know about the change and wants the current license but doesn’t set a welcome message?)

Nevertheless I‘d suggest to add a button to bring the chat window upfront (again) since in my opinion this is a safer and more user friendly approach (since we don’t know if he maybe accidentally closed it)

**Comment by gilgongo** [comment]
Given that it may not actually be a licence that's displayed (it may just be something that says you must not swear, or anything you play will be streamed live to the Mormons, etc.), it may be better to say:

 "This server requires you accept conditions before you can join. Please read these in the chat window" 

It also avoids the more important issue of how to spell "licence" (it's with a "c" in the UK and Canada, and with an "s" in the US) :-)

**Comment by corrados** [comment]
> "This server requires you accept conditions before you can join. Please read these in the chat window"

Good idea. I've just updated the text.

> (since we don’t know if he maybe accidentally closed it)

The chat window definitely was upfront when the server welcome message arrived. If the user closed it and did not read the text, he cannot accept. But no problem, he can simply press "Decline" then connect again and then read the text instead of just closing the chat window :-).

**Comment by ann0see** [comment]
Debian Buster LXQT (and probably all OS):

Started Jamulus 3.5.11 server with -s -L -n (note: no welcome message)
And new client shows the warning but (of course) no welcome message. How can this issue be solved? 

Also: if I start the server with -s -L -n -w "TEXT" the chat window is not shown upfront since the license message is shown there. But this message must stay upfront unless the user clicks on Agree.

Suggestion: Move the Agree/Deny buttons to the chat window, show "this server requires you [...]" Accept/Deny message (prefered in a seperate box). Make the chat dialog stay upfront unless the agree button is clicked.

Link the Server Welcome Message via a html id (e.g. wcmessage) to make it possible to jump to the message again after a few chat messages were received.

**Comment by corrados** [comment]
> And new client shows the warning but (of course) no welcome message. How can this issue be solved?

That is the responsibility of the server operator. The -L is now for "experienced users" only. They have to know how to use it. The recommended way of doing it is to just use a server welcome message without the "agree/decline" dialog.

@gilgongo I think we now should remove all "-L" references in the Wiki and maybe create a page where we, e.g., give an example server Welcome message for a simple licence. That is what we recommend to use.

> But this message must stay upfront unless the user clicks on Agree.

It is actually right behind the "agree/decline" dialog. The "agree/decline" dialog is modal so it has to be over the chat window. I do not want to overcomplicate the implementation. I have just used what was implemented before. Since you can move the "agree/decline" dialog, you can always read the text in the chat window.

> Link the Server Welcome Message via a html id (e.g. wcmessage) to make it possible to jump to the message again after a few chat messages were received.

The chat window can be cleared completely. If you want to read the licence again, just disconnect from the server and re-connect.

**Comment by gilgongo** [comment]
> maybe create a page where we, e.g., give an example server Welcome message for a simple licence

We could add an entry to "Tip and tricks" that shows how to link to a click-wrapped agreement with a welcome message. eg:

~~~
Jamulus [options] --licence --welcomemessage \
"<h1 style="color:red;font-family:verdana">Welcome to our server</h1> You agree to your audio being licensed under WTFPL and streamed live to Elon Musk's bedroom. <a href="https://www.tesla.com/jamulus">Full details here.</a>"
~~~

**Comment by corrados** [comment]
No, we should not mention -L or --licence anywhere in the Wiki. As I wrote, the recommended way of doing it is to use just a text in the Welcome message and no "accept/decline" dialog.

**Comment by gilgongo** [comment]
I see. `-L` would just be in the `--help` argument only, described as something like, "Show an agreement dialogue before users can connect."

**Comment by corrados** [comment]
Yes, that was the intention. I just updated the --help text with your proposal in the code.

**Comment by gilgongo** [comment]
OK we have the resolution on this now so closing.
