### ISSUE TITLE
Release message consistency?

### ISSUE THREAD

**Issue by mxmilkiib** [corrados/jamulus#589]
I'm putting together an aggregation of release info feeds. The Jamulus messages are slightly different from most others, and I was wondering if a slight modification of format going forward might be possible? https://libreav.org/news

**Comment by corrados** [comment]
Are you referring to this file: https://github.com/corrados/jamulus/blob/master/ChangeLog
Or to the messages in the Sourceforge forums like this: https://sourceforge.net/p/llcon/discussion/software/thread/1856e44ffd/

**Comment by mxmilkiib** [comment]
Ah, I was meaning the messages used on https://github.com/corrados/jamulus/releases (via https://github.com/corrados/jamulus/releases.atom), though if there's another feed available with release info I could use that instead.

**Comment by corrados** [comment]
I just updated the Github releases with the release notes text. So your feed should hopefully work now. Can you please check?

**Comment by mxmilkiib** [comment]
Wonderful, thank you :)

**Comment by mxmilkiib** [comment]
Fyi, the page is https://libreav.org/news
