### ISSUE TITLE
Request free PVS-Studio license and integrate it into the project

### ISSUE THREAD

**Issue by grundic** [corrados/jamulus#593]
Hi,

The PVS-Studio is an advanced static code analyzer. It is proprietary and paid, but they propose a free license for open source projects: https://www.viva64.com/en/b/0600

It would be nice to ask for a license for jamulus and integrate using CircleCI (https://www.viva64.com/en/b/0676/) or other continues integration option.

This should potentially increase code health and catch possible bugs.

Thank you.

**Comment by maallyn** [comment]
Is this a library that is linked in with the rest of the code? Does it do analysis and then 'phone home' with data to a central server somewhere? I am playing devils advocate for users who may be paranoid of traffic going to strange places. Or is this only residing in the servers?

**Comment by grundic** [comment]
This is not a library and it does not deployed/installed to the users.

This is a binary tool used by developers to analyze source code to help in finding potential bugs, memory leaks, nil pointers and alike.
You can read more about what static code analyzer does here https://en.wikipedia.org/wiki/Static_program_analysis or browse PVS studio web-site from the links I provided before.

**Comment by maallyn** [comment]
Then I have no issue with this. Users will not notice or see anything. I'd say go for it.

**Comment by corrados** [comment]
Is this something similar like this: https://github.blog/2020-09-30-code-scanning-is-now-available

**Comment by corrados** [comment]
@grundic If it is a similar tool to what Github offers in https://github.blog/2020-09-30-code-scanning-is-now-available, I would prefer to use the Github tool instead.

**Comment by corrados** [comment]
No feedback so far. So, I'll close this issue. As stated above, instead of using some external tool like PVS-Studio I would use something which Github offers instead.
