### ISSUE TITLE
Facilitate ASIO(4All) sound setup on Windows

### ISSUE THREAD

**Issue by ann0see** [corrados/jamulus#598]
Setting up ASIO4All correctly can be quite challenging (see survey https://github.com/corrados/jamulus/issues/534#issuecomment-680225729). The setup should be made easier.

This GitHub issue should focus on how to make the audio setup process easier for new users.

### What has already been done or is in process:

* Wiki explains ASIO4All setup in a generic way 
* New website will link wiki more prominently to get more users through the wiki (#581)

### What has not been done yet:

* Guidance in Jamulus specifically for new users.  Suggestion: If ASIO4All is detected show a link to the windows audio setup page in the wiki.
* Some aid if there's no connection to a server yet and asio4all is found (maybe show helping text if the mixer board is empty)
* ?
Also see #534

**Comment by gilgongo** [comment]
It's hard to know what the main cause of setup problems is on Windows, but I suspect it's knowing which device to enable/disable in the ASIO4All control panel, since the names of these devices are often obscure. This is an example of trying to clarify what needs to be done: https://www.sweetwater.com/sweetcare/articles/installing-and-using-asio4all-for-windows/

(BTW in the install video it shows the selection of "offline settings" - I wonder what that is?)

The animated gif showing the input and output device selections being highlighted is interesting. We could maybe re-create that and add it to the wiki?

**Comment by ann0see** [comment]
Off line settings is a way to access the control panel without a ASIO host, I think. 
The link could be quite good. 

An other problem I heard about is the MS wavetable synth which could block A4A.

**Comment by ann0see** [comment]
I've added the windows page and added some more help and structure

**Comment by gilgongo** [comment]
The thing that's interesting about the gif is that it attempts to help with what (I think!) is the central problem: which input and which output from which device (assuming you have more than one) do you choose (and how do you choose them? You can select the "parent" or the "child")?

**Comment by ann0see** [comment]
What if we just link the site and declare it as "further help"?

**Comment by gilgongo** [comment]
The trouble is that section mentions a few potentially confusing things like talking about a DAW (do they need a DAW to use Jamulus? What is a DAW? Etc.), Offline (What if they didn't install that? You don't need it for Jamulus), and adjusting buffer size (which we're silent on - should we tell people to set to 128 at first?). Also, what about "always resample 44.1kHz to 48Hz"? I don't actually know what the advice is on those things and that link doesn't really help on those.

Perhaps we should just add the following to the setup steps and that will cover it? Assuming this is the correct advice:

6 . Set the "buffer size" slider to 128 (if you can)
7 . Set "always resample 44.1kHz to 48Hz" (if you can)

**Comment by ann0see** [comment]
I don’t think that any of these options are actually needed (only in special situations)?

Buffer sizes are (at least for me) set via jamulus.

**Comment by trombonepizza** [comment]
New here.  Not new to audio and computers.

ASIO has been a real pain when trying to get people up and running on telepresence apps like Jamulus.  I did make a video on using it with Soundjack.  It may only add to the confusion.  Here it is :  https://youtu.be/G49yCO11XGs

I might make another one on using it with Jamulus.  I think one of the biggest problems people run in to with Windows and ASIO4All is that whichever app grabs the microphone first will lock to it, and then other apps will not be able to access it.  This becomes a really slippery issue because many Windows setups have uncounted hidden apps grabbing the microphone (Cortana, etc).

**Comment by trombonepizza** [comment]
Here's a rather lengthy video on implementing ASIO4ALL with Jamulus.  I've tried many times to make videos that are concise and exciting, but always failed.  Generally, my videos are somewhat easy to follow, if you have a long attention span.  If anyone wants to try to make a concise version of what I am saying here, feel free to do so.

https://youtu.be/_GzOsitVgLI

**Comment by ann0see** [comment]
The video looks quite good. We could link it with a sentence like: "Can't work out ASIO4All? Look at this video form @trombonepizza which gives more detailed setup information on ASIO4All!"

**Comment by trombonepizza** [comment]
Cool with me.

**Comment by ann0see** [comment]
@gilgongo?

Nevertheless, it might solve the problem for people who find the wiki. I'd actually include some aid in the Jamulus app too.

**Comment by gilgongo** [comment]
No problem with linking to a video (I've yet to watch it though). When you say "include some aid in the Jamulus app too" we have links to the wiki already in the help menu. Do you mean elsewhere in the UI?

**Comment by ann0see** [comment]
Yes. I mean a link or whatever which shows up if ASIO4All is detected. I'd prefer to link it right in the main window (where the sliders are) and/or next to the sound setup in settings.

**Comment by gilgongo** [comment]
> I'd prefer to link it right in the main window (where the sliders are) and/or next to the sound setup in settings.

Yes, that's probably a good idea, but a link on the main window would need to be conditional in some way - I doubt we'd want it there after they'd configured ASIO?

**Comment by ann0see** [comment]
No. We probably don't want it there if ASIO was configured.

Ways to check this: 

* Was the ASIO-Setup window already opened? (Then the message should say: You've installed ASIO4All and haven't opened the ASIO-Setup yet. If you want your audio doesn't work yet, you have to setup ASIO4All. See the wiki for more information (link to wiki). The setup guide is always linked under the ASIO-Setup button in Jamulus settings and shown if you select ASIO4All/close this message)

* Person connected to server and no audio detected for e.g. 10 seconds after connecting and user has installed ASIO4All and not yet opened the settings page: Show message: "There's currently no audio input detected. Since you haven't setup ASIO4All yet. If you need help how to setup ASIO4All, see the setup guide in the wiki. The setup guide is always linked under the ASIO-Setup button in Jamulus settings and shown if you select ASIO4All/close this message"
*

**Comment by ann0see** [comment]
This sums up the problem quite well: https://sourceforge.net/p/llcon/discussion/hardware/thread/8bb168b369/

A way around this would be a seperate app which gets all the WDM KS inputs and outputs and guides the user through the audio setup (Check which apps access the soundcard and tell him to close them, play a tone on click on an output, show input levels to be able to check the microphone,...). This app should also support ASIO and help the user to set it up. I don't know much about development for windows unfortunately.

**Comment by corrados** [comment]
See my comment here: https://github.com/corrados/jamulus/issues/710#issuecomment-727152655

It seems we now have two Issue about the same thing. So I would like to continue the discussion in the new Issue https://github.com/corrados/jamulus/issues/710 and close this one.

**Comment by ann0see** [comment]
Yes.

**Comment by pgScorpio** [comment]
Another problem is that Jamulus is **unable to connect to any server** (Keeps saying "CONNECTING TO SERVER") when there are some undetected problems in the ASIO setup ! 

In example when using FlexASIO, setting the number of input channels to 2 and your device only provides 1 channel !

 (And no wasapiAutoConvert does NOT convert mono to stereo! )

**Comment by ann0see** [comment]
Yeah. That's a known issue. Maybe #129

**Comment by pgScorpio** [comment]
It would be **very** appreciated by a lot of (especially new) users if there was a tool where you just could select **one** audio device from a list (or maybe also one for input and another one for output) and than automatically configure that device(s) , ASIO4ALL if needed and Jamulus.

So if a single device is selected and it has an ASIO driver, configure its ASIO and configure Jamulus to use that device.
And if the device has no ASIO driver, or different devices are selected for input and output, Configure the device(s), and configure ASIO4ALL to use (only) those device(s) and configure Jamulus to use ASIO4ALL.

**Comment by pgScorpio** [comment]
@ann0see 
> Yeah. That's a known issue. Maybe #129

You're right ! So I posted a comment there too.

**Comment by ann0see** [comment]
Something seems to come up for ASIO4ALL: https://www.asio4all.org/ maybe the developer knows about Jamulus?
