### ISSUE TITLE
Physical geography vs ping rate in the server list UI

### ISSUE THREAD

**Issue by gilgongo** [corrados/jamulus#60]
For reasons unknown, I understand from #54 that clients may often fail to ping servers. When this happens, they don't show on the list. I myself have never seen more than about 10 servers listed. Yet if I set `--showallservers` I can see several in my country. And if I try connecting to them, turn out to have better or at least similar ping times to those given at the top of my default list.

If my experience is representative of other users, this would seem to be significantly underselling the experience of using Jamulus by hiding servers that may well be faster if users could see them.

If we cannot do anything about clients failing to ping servers, perhaps we should make it easier for users to select servers in their physical geography rather than relying solely on ping rate?

**Comment by corrados** [comment]
If you cannot ping the server, you will not be able to connect to it.

**Comment by pljones** [comment]
The following are questions pertaining to the client without `--showallservers`.

How does the client decide whether a ping has been responded to in order for it to show the server?

If the server isn't shown initially, will the client ever try again?

**Comment by pljones** [comment]
And just to comment on the issue title: in the UK, from London, I get far better ping times to quite a lot of Europe (Netherlands, Germany, some servers in Spain) than to Scotland and Northern England.  But France is generally dreadful.  Geography has very little to do with ping time -- it's entirely down to backbone routing, speeds and capacity.

**Comment by gilgongo** [comment]
> If you cannot ping the server, you will not be able to connect to it.

I don't understand what you mean in that case. I can connect to servers shown on my full list that aren't on my default one.

**Comment by gilgongo** [comment]
>  it's entirely down to backbone routing, speeds and capacity.

Ah OK. I thought it was mainly geographic.

**Comment by corrados** [comment]
> >     If you cannot ping the server, you will not be able to connect to it.
> I don't understand what you mean in that case. I can connect to servers shown on my full list that  > aren't on my default one (I was referring to this comment originally)

I just tried it out. When I open the list with --showallservers, some do not have a ping. But if you let the list open a long time, it may happen that they get a ping time after a while. If the servers do not get a ping time, even after waiting for a while, I cannot connect to them. This is my observation.

**Comment by pljones** [comment]
Let's be careful in the language.

Really, a client does not connect to a server.

"Connecting" to a listed server means the client reads the address given in the list and sends a connectionless request to that address.  "Success" at this point is achieved simply by sending the request - no response is required.

To get a list of the other participants on the server, the server has to receive that initial request (it might not) and send back a response with the list (which might not arrive).

So the client appearing to "connect" can be misleading - all it's done is say where it's sending data to and expecting data from.

**Comment by corrados** [comment]
Ok, by "connect" I mean that I get my mixer fader shown in the audio mixer board and that the buffer LED is red or green.

**Comment by pljones** [comment]
Yes, so @gilgongo - can you be clearer about what you're observing?

**Comment by gilgongo** [comment]
I mean I'm seeing an "unlisted" server and connecting to it like as below. 

I understand now though that when I click on some of the servers on the "unlisted" list, they do not connect in the sense that I do NOT see my fader in the window. That's clear now. 

BTW Volker says, "_if you let the list open a long time, it may happen that they get a ping time after a while_", although in my experience it seems that I can connect to perhaps a quarter of the servers in my "unlisted" list only a few seconds after I've opened the server list window. 

![image](https://user-images.githubusercontent.com/4561747/79069532-e7a5e800-7cc6-11ea-8e78-02f6eef1b084.png)

**Comment by pljones** [comment]
Oh, and regarding `--showallservers` - if you're not seeing about three screens full of servers, then your general network connectivity probably is the base cause of the problem.  From my site in London, I can ping Whanganui, New Zealand at 340ms successfully.
![image](https://user-images.githubusercontent.com/1549463/79069621-91857480-7cc7-11ea-9523-7c3d0cc89a56.png)

**Comment by gilgongo** [comment]
I'm not seeing anything like that!

**Comment by pljones** [comment]
I'd get in touch with your ISP and see if there's a problem.

**Comment by gilgongo** [comment]
What would I ask them? Are they blocking UDP packets of some kind?

**Comment by pljones** [comment]
A general "why is my internet connectivity so poor?"  You're not getting blocking - just very poor connectivity, by the look of it.

**Comment by gilgongo** [comment]
I'm on Virgin Media (fibre) which fast.com says I get 120Mb/s D 11Mb/s U. I've never noticed any performance issues before, but I guess I can keep digging. Maybe reboot my router or something.

**Comment by gilgongo** [comment]
I'll close this issue for now as there's not enough evidence to support my initial idea, since it may be I'm not representative.
