### ISSUE TITLE
Client issue with Pan on connect to server

### ISSUE THREAD

**Issue by pljones** [corrados/jamulus#601]
I've been hit by this and was told by someone on the server the fix, that person having been hit by the same thing.

Someone in the Jamulus WorldJam group sounds like they've also been hit by it:
https://www.facebook.com/groups/JamulusWorldJam/permalink/614740525767564/

What seems to happen is the mixer settings for your own channel get set to some... random-seeming... values when you connect to a server.  It's not clear when or why, as it doesn't happen for every connect.

**Comment by corrados** [comment]
Fortunately, this is already solved: https://github.com/corrados/jamulus/issues/537. Tomorrow there is a new Jamulus release. Unfortunately this is a server issue so we have to wait for the server operators to update their Jamulus server software until this issue is finally gone.
