### ISSUE TITLE
Make getting started page more straightforward

### ISSUE THREAD

**Issue by ann0see** [corrados/jamulus#602]
I'd suggest to move the "How jamulus works" description down (maybe not as far as I did in the link) and make some other changes: https://github.com/corrados/jamulus/wiki/Getting-started-easy

A new user should be able to start as fast as possible. 
An other option would be to move the "how jamulus works" to the starting page https://github.com/corrados/jamulus/wiki

**Comment by gilgongo** [comment]
Yes, the "How it works" diagram was an early thought, but maybe setup is simple enough without that "background knowledge" if we assume people think "OK, so I have this thing that lets me connect to these servers..."

**Comment by ann0see** [comment]
What could be done would be a very simple graph just showing the server <-> client principle

**Comment by gilgongo** [comment]
While I agree that a textual description might be nice, I think it's better to just move all that stuff into a separate "How does Jamulus work?" page in the interests of taking the complexity out of Getting Started. We don't know what level of understanding is actually required to use Jamulus successfully (there was some discussion about what "My local mix" meant, which is a concept that might require a client/server understanding but it's hard to say).

**Comment by ann0see** [comment]
Ok. I‘d say that understanding that
* Jamulus works with the server-client principle
* The server (which can be seen as a room) mixes all audio of every client and sends it to all clients
* There is a central server which sends server info to all clients

Are the most important points. 
Personally, I found jamulus because of the server-client principle so probably it‘s kind of important.

**Comment by gilgongo** [comment]
Is an easy way to test this. Walk out in the street and ask someone passing by if they know what the client-server principle is ;-)

**Comment by ann0see** [comment]
An other related issue: github wiki doesn’t seem to be indexed by google:

https://github.community/t/my-github-wiki-is-not-crawl-data-by-google/947

That’s really a problem.

**Comment by chrisrimple** [comment]
I encourage you to "steal" whatever content may be beneficial from my doc...

https://docs.google.com/document/d/1smcvsxdaaViPQvGMQHmah_6BQeqowhmGSFMHfnlY2FI

I'm happy to condense or rewrite it if needed for the Wiki, just let me know what's desired.

**Comment by ann0see** [comment]
This document looks really promising! Nice work! I‘m sure we could add some things.

**Comment by ann0see** [comment]
I've now moved some stuff around (mainly restructuring, clarification, simplification). Especially have a look at the getting started page (and installation, compilation, hardware setup)

**Comment by gilgongo** [comment]
I've edited Getting Started a bit more so that it presents as simple and (hopefully) gets people going in minimum time. I've added notes in the editing history but (amongst other things) I removed the para about mics as I wasn't sure what we were trying to say about that. Perhaps have stuff about mics and hardware input in https://github.com/corrados/jamulus/wiki/Hardware-Setup instead.

**Comment by ann0see** [comment]
No, I wouldn’t. If a new user sees the getting started page he should also know that he needs either a microphone or an interface (=way to bring sound of your instrument e.g. guitar into your pc). He should know that and not have to look at the hardware site.

**Comment by chrisrimple** [comment]
It's a little more work to maintain, but I recommend a Quick Start page ("for musicians and others with some technical knowledge") and a separate, longer Getting Started with more details (for those that need or want it).  In my doc, I've provided a significant amount of detail, but also tried to make it understandable for non-technical readers.

https://docs.google.com/document/d/1smcvsxdaaViPQvGMQHmah_6BQeqowhmGSFMHfnlY2FI/

**Comment by gilgongo** [comment]
@ann0see the audio interface bit is in there. I was just unclear what we were trying to say about microphones. As it was it was it seemed to be saying that you use the microphone input or something. So I thought we could re-think that part. Fine to have it on the same page if it's worded ok. @chrisrimple Yes, if we think that solves actual problems that people have. Examples are cases like acoustic instruments or something that need special treatment suppose?  Or if we think people are curious as to why we are suggesting certain things (beyond the basics)? I'm keen to make sure we don't over-explain things at the beginning. As I said on a previous ticket, the problem for newbies is (for example) not latency, it's maybe the fact they're running Zoom at the same time. That's the sort of approach I like to adopt.

**Comment by chrisrimple** [comment]
As my doc has evolved over time, I've had to add a section Jamulus For Choral Singers specifically because (1) they tend to be very non-technical and (2) their equipment needs can often be solved with less (or lesser) equipment.  I wonder if Getting Started would benefit from having a short section for each item, with a link to a longer explanation?  For example, "You need a wired internet connection - _read more on what that means, why it's needed, and how to do it_" with a link to much more detail.

**Comment by gilgongo** [comment]
I'm still a little nervous about having a section called "getting started" (the primary aim of which is to literally get people up and running as fast as possible) which also hints at problems and concepts beneath the surface in a sort of ominous "this is going to be difficult" way. Would it not be better to simply state the facts that people can act on, then if they have problems, direct them to appropriate places depending on the issues that they they experience? This is what the troubleshooting page was created for in fact.

IOW attempting to predict the problems that people will have is I think a slippery slope.

**Comment by chrisrimple** [comment]
Maybe "getting started" is the wrong name?  These days, a lot of hardware products come with a Quick Start guide and a full manual, with the Quick Start intended for people who can handle limited instructions/information.  But who's the primary audience landing on the Wiki?  In my doc, I've intentionally provided detailed explanations for each pertinent area, with the expectation that most readers will not have the needed knowledge, but that those who do can skip through them.

**Comment by ann0see** [comment]
I've swapped headphones and internet since (at least for me) this makes more sense. 
The microphone part should
* say that you need a way to input sound into your pc: 
either:
A microphone (+ interface). Explanation: using internal mics is ok, but it's recommended to use external ones. Either USB or an external interface + mic (better quality, latency, simple setup)
or:
An interface + instrument. Explanation: you need to be able to connect your instrument to your pc
* say that it must support 48kHz sample/word rate, which most devices do (this is important for the user since he doesn't want to buy a wrong device)

What about USB-Mics? Do we need to mention them?

**Comment by chrisrimple** [comment]
Yes, need to cover USB mics for choral singers.  Many are trying Jamulus now and they don't need an audio interface unless they want high quality, and it's a barrier to getting started for many.

I also think it's important to be explicit about the 48kHz requirement and HOW to solve that.  For example, on a Mac need to use Audio MIDI Setup to adjust, which is an application that most Mac users will have never seen.

**Comment by ann0see** [comment]
Ok. That's a good point. How is the latency/quality with USB mics? Especially on Windows? Are there ones with a native ASIO driver?

**Comment by chrisrimple** [comment]
I can't speak to ASIO drivers, since I'm on a Mac.  But certainly, I've used my wired earbuds on my Mac with built-in soundcard on Jamulus and there's no appreciable latency - I can't imagine that a USB mic would be much different.  And a LOT of choral singers that might want to use Jamulus are going to have nothing better than a USB headset or earbuds.

**Comment by ann0see** [comment]
Ok. So it probably has to be added.

**Comment by ann0see** [comment]
The linux page says 

...installation with git... and lets the user execute this command:
R=`curl -s https://api.github.com/repos/corrados/jamulus/releases/latest | grep -oP '"tag_name": "\K(.*)(?=")'` && wget https://github.com/corrados/jamulus/archive/$R.tar.gz && tar -xvf $R.tar.gz

As far as I see, this doesn't clone the repo. It's just a download. I've added a statement that says you can clone the repo via git or execute following command: R=`curl -s https://api.github.com/repos/corrados/jamulus/releases/latest | grep -oP '"tag_name": "\K(.*)(?=")'` && wget https://github.com/corrados/jamulus/archive/$R.tar.gz && tar -xvf $R.tar.gz to get and unpack the latest version of Jamulus.

**Comment by ann0see** [comment]
Let's close this since the getting started page is now much cleaner. Of course there might still be other places but the most important sites are ok.
