### ISSUE TITLE
RealTek USB Audio not working

### ISSUE THREAD

**Issue by brunnerjs** [corrados/jamulus#605]
My H390 set not working with Jamulus 3.5.11.  Didn't work with 3.5.10 either.
Jim Brunner

**Comment by ann0see** [comment]
Do you get an error message like sample rate is not correct?

**Comment by brunnerjs** [comment]
No error messages.  Red buffers light that nothing I do seems to change.  My built in computer mike & speakers function OK.

**Comment by ann0see** [comment]
I assume you are using ASIO4ALL? Are you sure that the driver was set up correctly? For me it seems like the problem lies in the ASIO driver

**Comment by brunnerjs** [comment]
Yes I’m using ASIO4ALL V2.  Downloaded it a second time when first encountered problems.

**Comment by ann0see** [comment]
Interesting. Can you try to reset ASIO4All or remove it again?

**Comment by WolfganP** [comment]
Does your audio card work via ASIO with some other app? (ie Audacity)

**Comment by brunnerjs** [comment]
Reinstalled.  No help.  Now getting feedback squeal when use computer audio.  That has happed sporadically before.

**Comment by ann0see** [comment]
Ok. Now you have to setup your headphones as output, not your speakers. This can be done in ASIO settings. See [ASIO4All Setup](https://github.com/corrados/jamulus/wiki/Installation-for-Windows#setting-up-asio4all) maybe it helps.

**Comment by brunnerjs** [comment]
Reinstalled Jamulus.  Still not working.

**Comment by brunnerjs** [comment]
Audacity works but I don’t know how to check if it’s via ASIO.

**Comment by ann0see** [comment]
I assume it doesn’t use ASIO:

See: https://manual.audacityteam.org/man/asio_audio_interface.html

Could you please take a screenshot of your ASIO4ALL settings?

**Comment by brunnerjs** [comment]
Here you go.

**Comment by ann0see** [comment]
I‘m sorry, but I can’t see the picture. Can you please upload it on GitHub.com (not mail)

**Comment by brunnerjs** [comment]
See if this works
![Jamulus screenshot](https://user-images.githubusercontent.com/71571379/93897771-7b410300-fcc0-11ea-92f2-5da580d474c2.png)

**Comment by ann0see** [comment]
Switch off mic in and speaker and uncheck always resample 44.1kHz <-> 48kHz

**Comment by brunnerjs** [comment]
unchecked always resample 44.1kHz <-> 48kHz.  Didn’t help.

 

Don’t know what you mean by Switch off mic in and speaker.  The computer mic and speaker were listed as idle and RealTek stuff as active.

**Comment by ann0see** [comment]
Your screenshot shows two devices. The disabled device has two enabled inputs (I assume it’s your internal audio card). You can try to disable these inputs too.

Your internal card works, I think. You could try if your internal microphone and your headphones work. 

Let’s wait for others to join this issue. Maybe they have an idea?

—-
ASIO4ALL is a pain to setup. If you’re able to use an external interface I‘d use that.

Other options could be Jamulus OS or a device which connects directly to your sound card via AUX.

**Comment by ann0see** [comment]
I'm not sure if it helps, but can you try https://www.youtube.com/watch?v=_GzOsitVgLI&feature=youtu.be
Maybe it helps?

**Comment by brunnerjs** [comment]
Issue has been resolved.  H390 now working with Jamulus.

**Comment by corrados** [comment]
Great, thanks for the feedback. I'll close this Issue now.
