### ISSUE TITLE
Make the "Enable recording" sticky in the GUI inifile

### ISSUE THREAD

**Issue by pljones** [corrados/jamulus#606]
From https://sourceforge.net/p/llcon/discussion/server/thread/698e6ee735/#495c

I thought I'd already got the GUI/inifile remembering the state of "Enable recording" but in tests just now, it seems not.

As with other settings, passing `--norecord` on the command line would override the inifile.

**Comment by pljones** [comment]
#608 pull request raised.

**Comment by corrados** [comment]
Can this one be closed now?

**Comment by pljones** [comment]
Ah yes!
