### ISSUE TITLE
Add Barbershop as a Genre

### ISSUE THREAD

**Issue by lesmower** [corrados/jamulus#613]
Barbershop singers are finally swarming to Jamulus. In the last several weeks it appears that we have several hundred singers and dozens of singers dedicated to Barbershop singers. Can you add Barbershop as a separate genre from Classical/Fold/Choir?

**Comment by WolfganP** [comment]
Is Classical/Folk/Choir central server saturated already? (as per https://github.com/corrados/jamulus/wiki/Central-Servers each genre sever is configured to hold/list 150 servers)

**Comment by pljones** [comment]
Perhaps rename "Choir"?

**Comment by corrados** [comment]
> Perhaps rename "Choir"? "Vocal ensembles"?

I am no native speaker. Would you recommend to rename it? I thought a Barbershop is also kind of a choir.

**Comment by lesmower** [comment]
They are a choir though exclusively A Capella. As we roll out current results to our choruses barbershop choruses are getting onboard quick which made me think if we could get a separate genre it would simplify things.

 

 

Les Mower

407-230-4040

Sunshine District Chapter Development Liaison 

Member at Large Orange Blossom Chorus

“Learn the rules like a pro so you can break them like an artist.” Anon

**Comment by corrados** [comment]
The problem is that for each new server list, we need to setup a separate Jamulus server instance which is managing the list. Also, you would need the newest Jamulus version to see the new list. So you will have a lot of users which will complain: "I cannot see the server list" since they use an old version of Jamulus. Therefore a new list might add more problems than it solves.

As pljones already noted, there is plenty of space in the Classical/Fold/Choir server list. The idea is to create new lists only if the existing ones are full and no more servers can register (as is with, e.g., the Default server list).

**Comment by pljones** [comment]
> 
> 
> > Perhaps rename "Choir"? "Vocal ensembles"?
> 
> I am no native speaker. Would you recommend to rename it? I thought a Barbershop is also kind of a choir.

Technically, I'd entirely agree.  However, "choir" can have overtones (e.g. church choirs or generally classical type music).  But personally I've no problem with "choir", I was just raising an alternative if that's what's putting people off using the server.

**Comment by corrados** [comment]
Ok, then I would like to keep the name.

@lesmower Are you fine with just adding your special barbershop servers "Classical/Folk/Choir"? The server list dialog has a Filter function so you could highlight and find all barbershop servers easily in that existing list.

**Comment by corrados** [comment]
No response after 9 days so I assume this Issue can be closed now.

**Comment by chrisrimple** [comment]
@corrados Although closed, I'll add some context.  In the USA, "choir" is usually the term for a religious singing group, singing primarily religious songs.  A "chorus" is usually the term for a non-religious singing group.  In the Barbershop singing community, groups of singers are a "chorus", which is also the term used by most groups in the larger A Cappella singing community.  So yes, a change from Classical/Folk/Choir to something else would help reduce any confusion.

If you're still open to a change, I think Classical/Folk/Choral is good.  The term "Choral" encompasses choir and chorus, a cappella and singing accompanied by instruments, so it's inclusive of all forms of group singing.

**Comment by corrados** [comment]
Sure, that is no problem. So I'll change it to **Classical/Folk/Choral** as you suggested.

**Comment by corrados** [comment]
-> done
