### ISSUE TITLE
UnSOLO All Users

### ISSUE THREAD

**Issue by chrisrimple** [corrados/jamulus#616]
Feature Request:
Need the ability to unSOLO all users in Jamulus settings, even when those users are not connected to current server.

Reason:
After spending time on public servers, I may have SOLOed some users while playing with them.  When I later participate in the Jamulus World Jam, or join a server on which there are many users, if ANY user on that server is SOLOed then I don't hear other users.  This becomes a particular problem when I'm performing on the JWJ and someone joins the performance server (because they're on the next song), they're SOLOed, and suddenly I can't hear anyone that I'm actively performing with.

Implementation Notes:
I recommend a menu item to Clear All Solo Settings.  Maybe also a Clear All Mute Settings.

**Comment by corrados** [comment]
Good idea. But I fear that if there is a menu entry "Clear All Solo Settings" the users can think that this only applies to the currently connected clients and not also to the settings which are stored in the ini file for musicians which are currently not connected.

Also, the question is if you can solve your problem already with the existing functionality. We have a File->Load/Save Mixer Channels Setup. You could start Jamulus from a fresh inifile (either delete the jamulusini-file in your AppData directory or start Jamulus with the --inifile command line argument) and immediatly save the Mixer Channels Setup. This setup you could use as a "fresh template". In that setup no client settings are stored.
When you start your Worldjam rehearsals and soundchecks, load that template beforehand and try not to use the Solo button. Then you should be save that no Solo state is stored. What do you think about this workaround?

**Comment by chrisrimple** [comment]
That is an interesting, albeit non-obvious, solution.  :)  It could certainly work, and I can document it for World Jam participants.  Where is the default storage location for INI settings on Mac?  I'm unable to find it, and I've done a LOT of searching.  I've used the command line argument to create an INI file in a location of my choosing, but where's the original/default?

**Comment by mawess** [comment]
why would anyone expect mute/solo settings to remain for non-connected clients?
To me that is very strange. Is this because of users are "auto connected" on server restarts?

the suggested solution maybe works but would be very much not intuitive...

I would think that most users are not wven aware that there is a inifile...

**Comment by corrados** [comment]
> Where is the default storage location for INI settings on Mac?

@gilgongo I think we should add the typical ini file locations on the different OSs in the Wiki, what do you think?

> That is an interesting, albeit non-obvious, solution.

Yes, it is :-). It is just a workaround to have a solution with the current Jamulus version.

I have an idea how to implement it. I'll create a new menu entry in the Edit menu "Clear All Stored Solo Settings" which is only available when not connected. Than it is clear what it does. Also with this specification the implementation effort is much less than if I would apply this setting during an active connection. I'll take care of it in the next days.

**Comment by corrados** [comment]
I just looked at the code and found out that this is an easy fix. I already finished the implementation (it is on Git master) -> closed.

**Comment by gilgongo** [comment]
>  I think we should add the typical ini file locations on the different OSs in the Wiki

That might be a good idea. Someone on the forums was asking about it (for MacOS) recently in fact.

**Comment by WolfganP** [comment]
> I would think that most users are not wven aware that there is a inifile...

One way to make the inifile more present in an advanced config workflow (I saw this approach in several other apps), is to have an advanced menu entry/button/link in the settings window, to trigger the inifile opening with the default text editor for the system.

**Comment by chrisrimple** [comment]
@corrados Thanks for the quick fix.  That said, two more thoughts:

- @mawess makes a good point.  Why is Jamulus storing Solo/Mute settings between sessions at all?  That doesn't seem like a useful feature and can (as I pointed out) cause issues.  Or, if Solo/Mute settings are stored, maybe they should only be stored with the existing File > Save Mixer Channels Setup command?

- I'm the one that's been asking around for the INI file location on Mac.  Can't find it, and I've asked a number of places and tried hard on my own.  I've used the command line argument to create and load an INI file, but I need to know where to find the default.  Do you know?

Thanks again!

**Comment by alanz1357** [comment]
@chrisrimple 

I can't be sure for every  Mac installation but on my system the configuration file is in under my user directory


/Users/<your user name>/.config/Jamulus

**Comment by corrados** [comment]
> Why is Jamulus storing Solo/Mute settings between sessions at all?

Because a lot of musicians use that. E.g. if you have a band and they want to rehearse on a public server, they usually set all musicians of the band to Solo. And it is convenient that the next time they rehearse, everything is setup as they left the server the last time they played.

**Comment by gilgongo** [comment]
If we are to document where the file is, we'll need to explain how its formatted too (it's XML, yes?). So not a particularly trivial job, and probably needs a separate section (maybe in Tips & Tricks I think).

**Comment by chrisrimple** [comment]
@gilgongo Yes, XML.  I've looked at it and most of the values are self-obvious, but it might even be good to have a key for it, similar to the list of Command Line arguments.
