### ISSUE TITLE
Commit 8fd59dd93f399b1657e68fcc2e37bbf5d2f23796 breaks linux build

### ISSUE THREAD

**Issue by andorardo** [corrados/jamulus#62]
Commit #8fd59dd seems to have introduced a change (undeclared QRegularExpressionMatchIterator) that cases a build error on Debian/Qt4:

```$ make
g++ -c -m64 -pipe -std=c++11 -O2 -D_REENTRANT -Wall -W -DAPP_VERSION=\"3.4.8git\" -DOPUS_BUILD -DUSE_ALLOCA -DCUSTOM_MODES -D_REENTRANT -DHAVE_LRINTF -DHAVE_STDINT_H -DQT_NO_DEBUG -DQT_XML_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtXml -I/usr/include/qt4 -Isrc -Ilibs/opus/include -Ilibs/opus/celt -Ilibs/opus/silk -Ilibs/opus/silk/float -I. -I. -o connectdlg.o src/connectdlg.cpp
src/connectdlg.cpp: In member function ‘void CConnectDlg::SetServerList(const CHostAddress&, const CVector<CServerInfo>&)’:
src/connectdlg.cpp:329:17: error: ‘QRegularExpressionMatchIterator’ was not declared in this scope
                 QRegularExpressionMatchIterator reMatchIt = QRegularExpression ( "[A-Z][^A-Z]*" ).globalMatch ( strCountryToString );
                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/connectdlg.cpp:331:25: error: ‘reMatchIt’ was not declared in this scope
                 while ( reMatchIt.hasNext() )
                         ^~~~~~~~~
Makefile:1544: recipe for target 'connectdlg.o' failed
make: *** [connectdlg.o] Error 1
```

**Comment by corrados** [comment]
Thanks for reporting. Can you please try out the commit af32867216aa38d79197c64319ce7e29c1066eb3?

**Comment by andorardo** [comment]
Commit #af32867 worked on Debian/Qt4, thanks for the fix.

A couple of follow-up questions, if I may:
1. What's the best way to always pull the latest 'gold' commit? Or is there a way to always pull the latest release, rather than HEAD?
2. Which is the better repo to rely on, the cvs repo on sf, or the git repo here?

Thanks!

**Comment by corrados** [comment]
1. The code on master may be broken or experimental. It depends on if you want to always have the latest features or if you prefer a more stable version.
2. The Sourceforge Git is usually outdated. Source development is done in the Github repo. The Sourceforge Git code will eventually be removed completely.

**Comment by andorardo** [comment]
1. If I want a relatively stable release in sync with the binary clients?
2. Thanks for clarifying.

**Comment by corrados** [comment]
1. Usually you can use the HEAD. In most of the cases it should run just fine.
