### ISSUE TITLE
Security issues with the new "open external links" function in the chat window

### ISSUE THREAD

**Issue by corrados** [corrados/jamulus#620]
In the pull request https://github.com/corrados/jamulus/pull/592, the openExternalLinks is set to true for the QTextBrowser. This opens a wide range of security concerns. E.g., you could send something like: `<a href="http://fraudulentsite.com">https://www.google.com/search?q=lyrics+sunshine+of+my+love</a>` (see https://github.com/corrados/jamulus/commit/18b1fcab57e178770bab19fe40bab5b94a6fb509#r42649147).

We already discussed some security concerns in https://github.com/corrados/jamulus/issues/360 and, e.g., https://github.com/corrados/jamulus/pull/380#issuecomment-647042975 and https://github.com/corrados/jamulus/issues/360#issuecomment-652938350.

**Comment by ann0see** [comment]
I would consider opening sites automatically without warning as dangerous.

What could be done: BB Code or Markdown support. This is much easier and less dangerous in my opinion.

**Comment by corrados** [comment]
Some of the security issues should be solved now. I do not use the openExternalLinks of the QTextBrowser anymore but have implemented my own code for opening the URL in an external browser. That way I can make sure that only https links are opened and nothing else (e.g. no ftp, file, etc.).

**Comment by corrados** [comment]
So for the upcoming release I will implement the following:
![grafik](https://user-images.githubusercontent.com/46655886/94599338-99929a00-0290-11eb-8ff0-52c7345d01d2.png)
So, when you click on a link, a message box opens which shows you the actual link and asks you if you really want to open the link.
I know this is not the optimal solution but it is better than nothing.

**Comment by ann0see** [comment]
Yeah. That’s much better.

**Comment by corrados** [comment]
Since we now have a dialog asking if the link should really be opened in an external browser and the actual link address is clearly shown, this issue can be closed now.
