### ISSUE TITLE
Software issues

### ISSUE THREAD

**Issue by bassguy66** [corrados/jamulus#621]
After installing the software and drivers I am unable to see any channel sliders or controls.

See image

![Screen shot 1](https://user-images.githubusercontent.com/71038711/94061308-1063fa80-fd9a-11ea-85b7-9c4c448e234b.jpg)

**Comment by ann0see** [comment]
Have you tried connecting to a server? The sliders should only show up if you're connected

**Comment by bassguy66** [comment]
I haven’t been able to connect after multiple attempts   Douglas Elia503-410-6468 Sent from Mail for Windows 10 From: ann0seeSent: Wednesday, September 23, 2020 12:43 PMTo: corrados/jamulusCc: bassguy66; AuthorSubject: Re: [corrados/jamulus] Software issues (#621) Have you tried connecting to a server? The sliders should only show up if you're connected—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by ann0see** [comment]
I'm sorry to say that, but your answer shows css and e-mail links,... (probably due to your e-mail client). Could you please try to use an other one or github on the web?

> I haven’t been able to connect after multiple attempts.

So your issue is probably a networking issue. Do you have a firewall? How do you connect to the internet?

By the way: How did you find the GitHub issues page? Google/Jamulus website? Which setup guide did you follow (if you did)?

**Comment by bassguy66** [comment]
Sorry, was using my email server.

I use a direct ethernet connector and have had no other connectivity problems . Will continue to attempt to investigate 
 other avenues. thank you for your assistance. Will advise if corrected.,

**Comment by bassguy66** [comment]
I have found that there is no input or output channel mapping options displayed. I have connected to a server after disabling one firewall

**Comment by ann0see** [comment]
> I have found that there is no input or output channel mapping options displayed

Do you mean in ASIO4All (look at ASIO-Settings) or in jamulus?

If ASIO4All doesn't show any inputs/outputs you might have an unsupported soundcard (I'd consider this as very rare).

**Comment by ann0see** [comment]
Any updates? Did you manage to solve your problem?

**Comment by bassguy66** [comment]
I have been able to get it working,  thank you,  there are still controls
that don't show up, however,  I'm able to use it now,  so I'll see how it
goes.

Thanks again for your help.

D. Elia

**Comment by ann0see** [comment]
That's great. Did you follow the guide in the wiki?
If your problem was solved, please close this issue.

**Comment by corrados** [comment]
Any updates?

**Comment by bassguy66** [comment]
Yes, I've been able to connect to a server and have a good signal.  My
associates in the studio have not yet installed the software,  so I have
yet to try it out with other parties

D. Elia

**Comment by corrados** [comment]
Ok, so your problem seems to be solved so I'll close this Issue now.
