### ISSUE TITLE
Client volume 100% when joining a server

### ISSUE THREAD

**Issue by chrisrimple** [corrados/jamulus#628]
May be related to https://github.com/corrados/jamulus/issues/622.

With 3.5.11 installed, connecting to various World Jam servers (including Studio SEATTLE), the mix has all participants at 100% even with New Client Level at 50%.  There's a momentary "blast" of full volume, then it adjusts.  But frankly, it's dangerous to the ears if expecting 50%.  Perhaps playback of the server stream should be delayed until (1) values are read from the client at applied at the server, and (2) the server stream with adjusted values is received at the client?

**Comment by corrados** [comment]
That problem is not a 3.5.11 specific problem, right? Or was it different with older versions?

**Comment by chrisrimple** [comment]
I don't remember it happening in the past.  But I also probably wasn't paying close attention.

**Comment by corrados** [comment]
We already have a fade-in of new clients entering the server. If I understand you correctly, you would like to have this for all clients which are connected to the server before you enter that server, right? Since it takes some time to update the New Client Level for you at the server, the signal does not come in at full level then.

**Comment by chrisrimple** [comment]
Let me give an example.  I have New Client Level = 50%.  When I enter a server, I see the faders...

Musician1 = 50%
Musician2 = 50%
Musician3 = 50%

But when I first join the server, I'm hearing 100% from all of them for a very short time (less than 1 sec), then they drop to 50%.  Problem is that the initial 100% "blast" is LOUD when wearing headphones.

**Comment by corrados** [comment]
Ok, I see. Should not be a big deal to support this in the server.

**Comment by corrados** [comment]
I just implemented this. Since this is a server feature, it will take time until you actually get this feature. I think for the Worldjam it will get faster since Simon regularily updates his servers with the newest release versions.
-> closed
