### ISSUE TITLE
Audio delay and Server recording Question

### ISSUE THREAD

**Issue by acul71** [corrados/jamulus#63]
Hello.
Thanks for Jamulus is a great software.
I want to ask: 
I'm using Jamulus with a local server and two client myself (A) with overall delay 20ms and a remote user (B) 60ms delay. With jitter on auto. 5.33 ms buffer delay with jack both linux software and os.
We're having issues because I hear B with delay and vice versa. We can play but sometimes we struggle cause A is waiting for B and vice versa and the time of the song drops.
The recording files are almost perfect no scratches in the sound or delay.
How is possible the we hear sound with delay and sometimes scratches but the recording section is in sync?
Thanks, Bye Luca
![Screenshot from 2020-04-13 00-22-49](https://user-images.githubusercontent.com/34693171/79081355-f0c1a400-7d1c-11ea-8150-63203020abb8.png)

**Comment by pljones** [comment]
It sounds like you're ears are hearing something different from what the server is hearing.

Make sure that the only way for sound to reach your ears is from the server.

**Comment by corrados** [comment]
Please post questions like this in the Discussion forum at Sourcforge.
The recording is done at the server where all streams are added up. I guess that is the reason.
