### ISSUE TITLE
Jamulus Connect List Disappears then re-appears possible cause and solution

### ISSUE THREAD

**Issue by interogativ** [corrados/jamulus#631]
I’ve spent a great deal of time trying to figure out why many users can never see the server list for ‘All Genres” from the connect Dialog, and why when we do it can disappear for minute or hours.  I believe it’s because the PROTMESSID_CLM_SERVER_LIST getting sent from Germany to the US is fragmented into too many UDP packets.  The routers along the way (at least 5 hops for me), are NOT obligated to pass along these fragmented packets.  The more Servers on  the list the greater the odds that we will not be able to get a whole PROTMESSID_CLM_SERVER_LIST intact.  Having been a communications programmer for the last (let just say many) years, here are some thoughts:

1. A Compressed SERVER LIST message.

From the code here’s the PROTMESSID_CLM_SERVER_LIST:

            4 /* IP address */ +
            2 /* port number */ +
            2 /* country */ +
            1 /* maximum number of connected clients */ +
            1 /* is permanent flag */ +
            2 /* name utf-8 string size */ + name size a MAX of 20
            2 /* empty string */ +
            2 /* city utf-8 string size */ + city size a MAX of 20

The PROTMESSID_CLM_SERVER_LIST message has a fixed length per server of
16 + up to 20 chars for the name and 20 for the city.  So for the All Genres server list which averages 110-150 servers, assuming an average name size of 12 and an average city size of 8, you get 36 * 110 = 3960 to 36 * 150 = 5400 bytes per UDP message thus ensuring message fragmentation.

What if we reduced the message to its essentials?  Since the client limits name and city size entries to 20 bytes, why not take advantage of that?  Since the permanent flag is only 1 bit and the max clients field allows up to 255, why not limit the max clients to 128 and use the high order bit as the permanent flag.  I propose a compressed server format that looks like this:

            4 /* IP address */ +
            2 /* port number */ +
            2 /* country */ +
            1 /* permanent plus max connected clients */
            1 /* name utf-8 string size */ + name size a MAX of 20
            1 /* city utf-8 string size */ + city size a MAX of 20

This reduces the fixed message size to 11 and will save (5*110) = 560 to (5*150) = 750 bytes per message.  

Or if you changed the max city name and name sizes to 16 and packed the lengths into 1 byte you’d save another byte.

On most systems this should eliminate 1 UDP fragment per message.  It’s easy and just requires two new messages:

#define PROTMESSID_CLM_REQ_COM_COMP_SERVER_LIST        1018 // request compressed server list
#define PROTMESSID_CLM_REQ_SERVER_LIST 1019                               // compressed server list

2.  Even More Compression:

I thought about compressing the Unicode text using the standard Unicode compression algorithm (https://www.unicode.org/reports/tr6/tr6-4.html) but that really won’t save that much for most small texts.  Other types of compression will use far less data and could potentially fit in 1 UDP message (1460 bytes), but would require a few more additional messages and more CPU time on the central server to process.  While I haven’t designed the actual scheme, the outline would be that the server list message would provide only indices into a server table, and the clients would have to request server information in the same manner as the PROTMESSID_CLM_PING_MS_WITHNUMCLIENTS message.  The downside is that the connect dialog would take at least a minute to load and the central server would be sending two orders of magnitude more messages.

3.  Have More Central Servers:

Many of the permanent servers on the ‘All Genres’ server list are ALWAYS there.  

1.	Have permanent servers query the main Central Server once per minute for a current server list and keep it.  

2.	Add them as “backup servers” to your Central server list in the client, or publish a list (on the website).  

3.	The client could use this server list if it could not get to the one in Germany for a minute.  This would reduce the load on the Central server because it wouldn’t have to respond to endless requests for connect messages that will not arrive intact.

If I were the programmer I’d go with solution #3 because that’s a pretty standard way of doing things in the communications world.  Companies have multiple redundant servers to deal with just  such problems as well as outages.  These are just my thoughts.

**Comment by corrados** [comment]
This is a topic which is under discussion for quite a while, see, e.g., https://github.com/corrados/jamulus/issues/255.

For the normal protocol messages (i.e. not the "connection less messages") I recently implemented a fix: https://github.com/corrados/jamulus/pull/582.

As softins already suggested, the same mechanism could also be used for the connection less messages: https://github.com/corrados/jamulus/pull/582#issuecomment-691139088

**Comment by interogativ** [comment]
Yes, thats’s a good solution that shouldn’t create problems for existing users, but i’d still use only 1 byte for the length field, or just use a C style string and terminate it with a null (0).

**Comment by corrados** [comment]
I just implemented this test on a separate branch: https://github.com/corrados/jamulus/tree/reduced_serverlist

And I just updated the Default Central server with that new version of the code for testing.

**Comment by corrados** [comment]
> but i’d still use only 1 byte for the length field

Thats what I have implemented.

**Comment by corrados** [comment]
Ok, it seems to work but there are still some outstanding issues I have to solve (e.g. it shows (full) for all servers and the reduced list is refreshed every two seconds). But the legacy Jamulus clients seem not to be influenced by the new message. It just works for me.

**Comment by interogativ** [comment]
Right, I didn’t remember that, I can’t see both the message I’m composing and yours on my ipad at the same time.sorry.

**Comment by interogativ** [comment]
You’ve done such a great job on this SW, now that it’s getting some heavy usage, it holds up nicely. Problems like this are really a sign that you’ve succeeded with the design.

**Comment by corrados** [comment]
Thanks :-)

I have just solved the outstanding issues. Here is how it looks like now if you do not receive the full list:
![grafik](https://user-images.githubusercontent.com/46655886/94457451-ddb06c80-01b4-11eb-993c-65db260f5100.png)

The branch is updated. Happy testing :-)

**Comment by softins** [comment]
I updated my wireshark dissector to support the new reduced servers message and compiled the client on my RPi. Here is what I saw when fetching the Default Server list:

![image](https://user-images.githubusercontent.com/3224952/94462751-e2c0ec00-01b3-11eb-93b7-0c343a0c4da4.png)

So the reduced list took 3 fragments when the full list took 7.

An extract of the reduced server message looks fine:

![image](https://user-images.githubusercontent.com/3224952/94462922-1b60c580-01b4-11eb-8ab7-5425fbb74189.png)

I'll push the update to the dissector soon.

**Comment by interogativ** [comment]
Tried it out after building from the Github,  In cases where the connect dialog was blank on 3.5.11, the compressed message worked. Not familiar with your release process, how do you determine when to release new versions?

**Comment by corrados** [comment]
That is great news that the situation has improved.

The last release is just 10 days old but since we have some nice features already and important bug fixes, it makes sense to schedule a new release soon.

Since you now see a server list, should we close this issue now?

**Comment by corrados** [comment]
Regarding the release, see here: https://github.com/corrados/jamulus/issues/77#issuecomment-700863814

**Comment by interogativ** [comment]
You can if you wish, but if it were I, I would take the top bit from the length and use it as a permanent flag since your’re limiting the server name to 20 and that would give you a name length of up to 128.

But I’m ok with the current configuration.

**Comment by corrados** [comment]
Ok, so let's keep it as it is now and I will create a new release version soon. Hopefully a lot of Jamulus users will then see an improvement (i.e. they see a server list where they previously got none) -> closed.

**Comment by interogativ** [comment]
Ok, sounds good
