### ISSUE TITLE
Update chat message design

### ISSUE THREAD

**Issue by ann0see** [corrados/jamulus#632]
The chat dialog (especially the chat message functionality) looks a bit outdated. I've updated the server to send colored messages (done via HTML Tables, which is quite outdated.): https://github.com/ann0see/jamulus/tree/newchat
Screenshot: 
![screenshotNewChatDesign](https://user-images.githubusercontent.com/20726856/94375168-ffa4e300-0111-11eb-9f2e-7ae1753b1d62.png)

Unfortunately it breaks the automatic link detection. The design could probably be improved but the allowed css is quite limited.
Any thoughts?

**Comment by gilgongo** [comment]
What would be the utility of this? Do you mean that users would be able use, say, a text formatting bar (with emojis etc.) or insert other types of content or something?

**Comment by ann0see** [comment]
Yes. 
At the moment it’s just a graphical change. 

Concerning formatting:
For formatting HTML can be used, but I see that as a potential security issue (especially links). I already suggested to move to something like BB-Code, Markdown etc and a local conversion to HTML.

**Comment by gilgongo** [comment]
There is currently no real convention of using markdown (much less or markup) in chat UIs. You can markup bold and italic (eg on Whatsapp) and links will pull in metadata, but I think but that's about it. I'm unclear why anyone would think to format text beyond that, other than the insertion of emojis. Perhaps there might be a specific music-related use case? Notation or something? But again, this seems to violate Volker's principle of just doing one thing well.

**Comment by ann0see** [comment]
Actually formatting already works (but my issue is about redesigning chat messages) not adding formatting. 

The other issue I was raising is related to #620

**Comment by ann0see** [comment]
I mean that the current chat design looks a bit outdated.

Chat messages nowadays look different e.g.: 
![31055048-2223-4B78-8067-E74979EBBA48](https://user-images.githubusercontent.com/20726856/94478182-3989ee00-01d3-11eb-8c43-056fabbb6dc3.jpeg)

The timestamp and name are usually located somewhere less prominent and the chat text is bigger.

The security issue is unrelated to this issue but can maybe be fixed with a chat redesign.

**Comment by gilgongo** [comment]
Oh ok so the visual design of the messages themselves.

**Comment by ann0see** [comment]
Yes. Basically that’s it.

**Comment by trombonepizza** [comment]
I actually prefer things that look old, like irc.  Less addictive, more cool.

**Comment by corrados** [comment]
> I actually prefer things that look old, like irc. Less addictive, more cool.

Yes, me too. But it should not block improvements of the chat functionality. I would not use a complete new design as indicated in the first post. But we could implement some slight improvements. E.g.:

> The timestamp and name are usually located somewhere less prominent and the chat text is bigger.

This timestamp could be simplyfied and the text may be adjusted to a smaller font, e.g.

**Comment by ann0see** [comment]
Considering the timestamp: yes. That would be great

**Comment by ann0see** [comment]
What about: Username (HH:MM): Message?

**Comment by chrisrimple** [comment]
I'd reverse that as [HH:MM] Username:, like...

[14:35] **Chris**: blah blah blah
[14:38] **Joe**: I agree

Now, is HH:MM in local time or UTC?

**Comment by ann0see** [comment]
I think HH:MM is in local server time. 

Of course we can swap time and user name again. 

The problem with your proposal (without newline) in my opinion is that the username and time can’t be made smaller then the text since that would look really strange. Of course it looks more "old school" but I think, the message, not the time or user which has sent the message is important therefore I included the line break.

**Comment by gilgongo** [comment]
> I think HH:MM is in local server time.

In general, what is the utility of message time stamps? Is it so that you can make a decision about whether to reply to a message? Eg if you saw it 1 hour after it came in, compared to if you saw it 1 second after, you might decide that the 1 hour one was "stale" and that the 1 second one was worth replying to? If so, a better approach may be to  have "relative" stamps (1 second ago, 2 minutes ago, etc until you get to maybe 1 hour and then show times (which may be in a different zone)

BTW ideally, any time stamps displayed would be in the time zone of the reader of the message. But the likelihood of a server being more than a couple of hours different to the players' zones may be fairly low, since most people would be playing on geographically close servers. Be that as it may, if your local time is 12:00 and somebody messages you with a time stamp saying 11:00 I wonder whether that would be confusing?

**Comment by ann0see** [comment]
> If so, a better approach may be to have "relative" stamps

Agree

> BTW ideally, any time stamps displayed would be in the time zone of the reader of the message.

Yes. 

Currently all the message creation is done Server side. We might better do all the displaying client side.

**Comment by sthenos** [comment]
I personally don't like this current trend in big balloon messages  in chat clients, it wastes too much real estate for my liking and forces me to scroll unneccessarily, but then I am old school.    So perhaps we have a check box in settings :  "Show traditional chat format".     For the WorldJam coordination we use Discord and I have it on compress view... this is what it looks like:

![image](https://user-images.githubusercontent.com/11177553/97415208-d4720700-18fc-11eb-8c3d-646dc2ca29dc.png)

So for traditional people and using @chrisrimple 's idea i think having the time to the left as reported by the server, followed by the name and then the message would suit me.

For millenials and younger (people without the checkbox checked) a format like this would suit them:

![image](https://user-images.githubusercontent.com/11177553/97415479-329eea00-18fd-11eb-927d-240d9cfd6a9d.png)

**Comment by gilgongo** [comment]
As an aside - any changes to the visual style of the chat should probably also be in line with your chosen skin for the main window At least that's the general expectation with stuff like this.

**Comment by corrados** [comment]
Shouldn't we close this issue and continue the discussion in the new issue: https://github.com/corrados/jamulus/issues/787?

**Comment by ann0see** [comment]
We can make a list of proposed design choices there.
