### ISSUE TITLE
Some cleanup

### ISSUE THREAD

**Issue by corrados** [corrados/jamulus#638]
I would like to clean up some things:

~~Who has ever switched off this setting? :
![grafik](https://user-images.githubusercontent.com/46655886/94475841-f8440f00-01cf-11eb-8885-780e0b32181c.png)
I assume everybody wants to have the level meters and since the network traffic is so low, it is not very meaningful to have it.
**-> Remove the Display Channel Levels switch**~~ _-> done_

The -m, --htmlstatus and -a, --servername are features which were implemented a long long time ago. I wanted to do something similar like Ninjam does. But we now have a much better solution for that with the [Jamulus Explorer](http://jamulus.softins.co.uk/). In that explorer you do not only see the occupation of one server but all servers in the list.
**-> Remove the -m, --htmlstatus and -a, --servername**

~~Every Central server should use the -g, --pingservers. It does not make sense to operate a Central server without it. So this should be always enabled.
**-> Remove the -g, --pingservers**~~ _-> done_

~~See discussion in https://github.com/corrados/jamulus/issues/646: --serverinfo should only contain the server info of the local server and no other servers.
**-> Remove support for further server infos in --serverinfo**~~ _-> done_

**Comment by pljones** [comment]
All apart from `--htmlstatus` I agree with -- I actually use that.  I've got a website associated with my server and it displays who's on my server.  There's no other easy way to get that from the server, currently.  Tony Montifield's code is a starting point but it would need a bit of effort (do-able).

(It can't query the central server, though, as it's got to work even if the server is private.)

**Comment by gilgongo** [comment]
If we do end up keeping `--htmlstatus`, does that also mean we keep `--servername`? If so I've noticed a couple of people getting confused between that and the `[name]` parameter for `--serverinfo`. Dunno if  `--htmlstatus` could just use `[name]` instead?

Note to self: if we do remove `--htmlstatus` we need to remove [these instructions](https://github.com/corrados/jamulus/wiki/Tips,-Tricks-&-More#making-a-server-status-page)

**Comment by pljones** [comment]
Yeah, I was thinking that --servername and the server name in the server info are redundant... but if you're not publishing your server details to a server list, the --serverinfo needn't be specified.

To a degree, this comes back to #69, Server Status -- I'm after a list of clients - I don't need the host name (in fact, I don't particularly like it being there...).  Really, it's just that I'd need to extend Tony's PHP work to make what I want easier to get - it shouldn't block this.

**Comment by corrados** [comment]
> Really, it's just that I'd need to extend Tony's PHP work to make what I want easier to get - it shouldn't block this.

That would be great. Tony did a very good job with his PHP scripts. I think it should be straightforward to use Tony's code to just query the connected clients from your Central Server via UDP.

**Comment by genesisproject2020** [comment]
I add another vote to keep --htmlstatus as I also use it for a local status page on private servers.

**Comment by corrados** [comment]
@genesisproject2020 But I assume you have PHP available on your web server, right? The idea is to have a simple PHP script which queries the information from the server via the normal UDP interface (as the clients also do). Would it be possible for you to run such a script on your server?

**Comment by pljones** [comment]
> query the connected clients from your Central Server via UDP

It's not a central server.  It's a normal server.  (It might not even be a public server -- I'd still want the status page available.)  So it'll take a little work.

**Comment by corrados** [comment]
You are right. But it should be possible to query the connected clients list from every server (i.e. it must not be a Central Server), since in CServer we have
```
    void OnCLReqConnClientsList ( CHostAddress InetAddr )
        { ConnLessProtocol.CreateCLConnClientsListMes ( InetAddr, CreateChannelList() ); }
```
But I must admit, I have not tried that out myself yet.

**Comment by corrados** [comment]
The advantage of using the PROTMESSID_CLM_CONN_CLIENTS_LIST is that you get much more information about the clients than the --htmlstatus provides you with.

**Comment by pljones** [comment]
Oh yes - I plan to use the protocol message, but it'll be directly to the server.  I don't want the PHP to access anything outside the local host.

**Comment by corrados** [comment]
That was what I initially meant. Yes, you should only talk to your own server on the same PC.

**Comment by pljones** [comment]
...and I just remembered I use the status from a bash script, too.  I use it to check that the server is idle.  I can get that from the server log easily enough, though.

**Comment by corrados** [comment]
Just added one item from "Mysterious central server information" (#646) on the list in my initial post.

**Comment by pe9ghz** [comment]
Not every server runs a full fledged PHP webserver, so I'd vote to keep the --htmlstatus file .

**Comment by corrados** [comment]
> I add another vote to keep --htmlstatus as I also use it for a local status page on private servers. [...]
> Not every server runs a full fledged PHP webserver, so I'd vote to keep the --htmlstatus file .

Ok, so what about removing just **-a, --servername** for now? I.e. there is still the info about connected clients written in the file but no longer the server:port as a title.

**Comment by corrados** [comment]
> I add another vote to keep --htmlstatus as I also use it for a local status page on private servers. [...]
> Not every server runs a full fledged PHP webserver, so I'd vote to keep the --htmlstatus file .

Ok, so what about removing just **-a, --servername** for now? I.e. there is still the info about connected clients written in the file but no longer the server:port as a title.

**Comment by corrados** [comment]
I just removed "**--servername**".

Let's keep "**--htmlstatus**" for now. But it would still be good to have an alternative to query the information with a PHP script.

I'll close this Issue now.

**Comment by gilgongo** [comment]
Is this issue related to the removal of --servername? 

https://sourceforge.net/p/llcon/discussion/server/thread/206a68e62b/#0176

**Comment by corrados** [comment]
No, if the --servername was given in the call the the Jamulus server, the Jamulus server would not start up but just exit with an error message.
