### ISSUE TITLE
Notification on new server release

### ISSUE THREAD

**Issue by chrisrimple** [corrados/jamulus#639]
I'm unclear: when there's a new client release, is there always a new server release?  If so, then this may not be needed, since server owners are likely to be paying attention to client releases.

When a new server version is available, since there isn't automatic updating, it would be nice if:

1. The server owner were notified.  Not sure how to accomplish this unless (a) central server reports the current version number, (b) local server compares, and (c) central server sends an email to owner (email address maybe stored in local server jamulus.service file).
2. Similar to the [Recording] message at the top of the client window, maybe show something like "Server version is out of date, please notify the owner".

**Comment by gilgongo** [comment]
> when there's a new client release, is there always a new server release?

Yes.

> The server owner were notified. 

This is handled in the GUI like this now: https://github.com/corrados/jamulus/issues/370#issuecomment-683412347

I can't remember what the decision was on headless servers was though.

**Comment by corrados** [comment]
> The server owner were notified.

As gilgongo already mentioned, the Jamulus server GUI will also show the "Software upgrade available" message on the main window, similar what you have on the Jamulus client. So all Jamulus server operators which use the GUI will immediately see it.

> Similar to the [Recording] message at the top of the client window, maybe show something like "Server version is out of date, please notify the owner".

Something else is already in preparation. Not long ago I introduced a server register protocol message which includes the server version of the server which wants to register at the Central server. Sometime in the future I plan to use that information to only allow server to register at the Central server which have a sufficient version number.
