### ISSUE TITLE
UAD Arrow Twin X not working with latest 3.5.11 update

### ISSUE THREAD

**Issue by dirttini** [corrados/jamulus#643]
All worked so well until I updated to 3.5.11 and also updated OSX 10.15.7 Catalina and then now cannot get Audio out of the client.  I am using the same settings that have worked for months.  Any ideas?

**Comment by dirttini** [comment]
Actually I should have tested this.  I just tried just the mics from my display and MBP 2016  and nothing is getting thru the audio on the client.  This now makes possible more sense.  My drummer had the same exact issue on his 2020 MBP running a Scarlett 2i2 and I am betting if he tries his laptop mic it also wont work.  Now I am thinking this is a MBP specific issue because our guitarist is using the Scarlett Solo on a 2019 Imac and he had no issue along with our bass player using a 4i4 on a windows laptop.

**Comment by pljones** [comment]
You've said you updated both Jamulus and the OS.

Have you tried installing the older version of Jamulus and checking it still works?

**Comment by dirttini** [comment]
I let osx delete the old file when updating.  Is there a way to download and older revision?

**Comment by dirttini** [comment]
Also my drummer did also do the test without his interface and just the mic onboard the MBP and same issue as I see.

**Comment by pljones** [comment]
All the versions are here:
https://sourceforge.net/projects/llcon/files/Jamulus/

**Comment by corrados** [comment]
@dirttini Have you tried out an older version of Jamulus yet?

**Comment by corrados** [comment]
Any updates?

**Comment by dirttini** [comment]
New Jamulus version .12 seems to have fixed the issue.

**Comment by corrados** [comment]
Great to hear :-) -> closed.

**Comment by dirttini** [comment]
You are very responsive and what you are doing for musicians right now is
so very helpful and very kool.

Best!
