### ISSUE TITLE
Mysterious central server information

### ISSUE THREAD

**Issue by gilgongo** [corrados/jamulus#646]
Just running through the wiki looking for problems and found this in the central server docs:

"If there are always certain hosts you want to list (whether they're actually online and registered or not), this can be done with the extended --serverinfo value, with the additional entries being the fixed values. See the command line options page for further information about this feature."

Can somebody explain what that means?

**Comment by pljones** [comment]
It means if you're running a central server and there are hosts that you want to list, whether they're online or not (i.e. whether they're registered or not), you supply them as shown.  There's no other function in having that additional information.  It's been in the help text with no explanation "forever" -- I thought I'd try adding something to the Wiki.

**Comment by gilgongo** [comment]
Oh OK. So `[server1 country as QLocale ID]; ... [server2 address]; ...` on `--serverinfo` I didn't see the "server2" there!

This is quite exotic though. Under what circumstances would you want to list servers (I assume that's what "host" refers to here) that were offline?

**Comment by pljones** [comment]
I think it's historic, mostly.  It still works, though.

Once upon a time, there were no central servers.  No protocol support for them, etc.

Then, as more people started running servers and more importantly, more people wanted to find them, the idea of a central server arose.  (Up until March this year, remember, there was only the one.)

Initially there weren't many other servers, so there was no concept of "registering your server with the central server", etc.  The central server knew which servers were there -- and this is _how_ it knew.

After a while, with more servers coming along, it became impossible to maintain a list manually like this, so server registration was added.

And then multiple "central" server support was added to the client.  None of these ("central") servers knows about the others.  The client just knows the names / ports of five built in ones and allows another to be specified as the "custom central server".

**Comment by gilgongo** [comment]
This feels like something that might belong to https://github.com/corrados/jamulus/issues/638

**Comment by pljones** [comment]
Only if it warrants removal.  Anyone, anywhere could be running their own server list server and be using it.  May not be likely but it's possible...

**Comment by corrados** [comment]
I have implemented that a long time ago. At the beginning of the Jamulus development I was very concerned with network load. If you specify servers on with that command line option, they do not need to register every 15 minutes. But actually, the registration load is so minor compared to all the other network load, I think every server should just register with the normal mechanism via UDP. So yes, we could also remove that functionality.

> Anyone, anywhere could be running their own server list server and be using it.

I guess the chance that anybody is using this is very low. Since that user has to operate his own Central server.

Should I add this to #638?

**Comment by pljones** [comment]
May as well -- there's nothing stopping anyone running a central server but then the servers can register with it as normal, so the feature isn't needed.

**Comment by gilgongo** [comment]
OK - so if I may, I'll remove that para from the wiki in the interests of brevity.
