### ISSUE TITLE
create a "crowd fund" to develop quicker

### ISSUE THREAD

**Issue by kezzy1966** [corrados/jamulus#647]
I think Jamulus is fantastic. Have you thought about funding all your efforts ? 

Jamkazam is a different model but they raised 100,000 USD by crowd funding (!)
I wonder if a large cash injection would assist you ?

Here is an extract from the email I received today:
"First, we’d like to say thank you very much for your support of our GoFundMe campaign here: https://www.gofundme.com/f/cy2fsq-keep-jamkazam-alive-amp-improving. With your support, we met our goal to raise $100K that we can invest into improving the JamKazam service for everyone."

**Comment by corrados** [comment]
> I wonder if a large cash injection would assist you

If you ask me personally, than no. I have a full time job already. Jamulus is just a hobby.

**Comment by gilgongo** [comment]
I think crowdfunding would introduce a very different (and possibly unpredictable) dynamic, not only for the management overhead that it implies, but also the expectations it might raise.

That said, would such an approach work for a specific (and time-limited) purpose within the Jamulus project? Re-designing (and re-engineering) the UI or website might be a candidate for a crowd-funded project, for example. While I can do some of that for free, I'm not a visual designer - and unlike developers, designers tend to be rather mercenary.

**Comment by chrisrimple** [comment]
I suspect that we have some user experience and visual design professionals among the Jamulus community - if we put out a call for volunteers, we'd probably get them.  The risk with taking money is twofold: expectations go up and it can create a perception that some/all contributors are treating it "like a business".  I don't feel that I should have a say, but my recommendation would be against raising funds.

**Comment by mayankasthana** [comment]
Could Patreon be an option? It doesn't have the same expectations as that of gofundme in my opinion.

**Comment by chrisrimple** [comment]
Patreon is based on "completed work".  A musician posts a song and gets paid for it, each time.  The only way Patreon could work for Jamulus is if we posted "completed features".  But the larger question is: who receives the money and for what purpose?  Right now, the open source community is doing a great job (in my opinion) of driving Jamulus forward under Volker's guidance.  How would the addition of money help?

**Comment by gilgongo** [comment]
Yes, _ongoing_ funding isn't needed. But if we identified as specific cost for a one-off operation then... maybe.

>  user experience and visual design professionals among the Jamulus community

I am one (not a visual designer though) and have been playing about with UI concepts for Jamulus for a while, only recently getting to a place where I felt I knew enough about its usage to suggest something. Unfortunately, it would involved a complete re-engineering of the front end. And getting a designer to do some work of proper quality on that would be very difficult without some compensation I think. But I'm willing to be proven wrong.

**Comment by corrados** [comment]
If you really want to hire and pay a developer which works 100 % on Jamulus development, I cannot manage that anymore. My time is limited and I already spend way too much time on the Jamulus project. So, if you hire a developer, than this calls for a Jamulus fork like the Sagora fork. In such a fork you can implement/change whatever you want.

**Comment by gilgongo** [comment]
@kezzy1966 Would it be OK to close this issue now? Crowdfunding a fork of Jamulus would be the best way to go.

**Comment by corrados** [comment]
I agree. Crowdfunding is not relevant to this "corrados/jamulus" project. So I'll close it now.
