### ISSUE TITLE
Best way to contribute (just) a new instrument icon?

### ISSUE THREAD

**Issue by dora71** [corrados/jamulus#649]
What is the best way to contribute to this project?
It's no coding, I just want to add a new icon for an instrument or perhaps doing some translation work.

Thanks for any comment.

Greetings from Germany. Rainer.

**Comment by dora71** [comment]
A friend of mine (Ariane) took a picture of her Mountain Dulcimer (that's the instrument and also the suitable name in Jamulus) and made it suitable for Jamulus.
Category: STRING_INSTRUMENT
She released it under the CC0 licence. And here it is:

![Favicon Jamulus_Mountain Dulcimer schräg_Hintergrund weiß_27 27](https://user-images.githubusercontent.com/720694/95356289-cb29e780-08c6-11eb-953a-b22d22c63856.png)

Hope this is alright for Jamulus. Can you use it like this? Feel free to ask if not.

**Comment by corrados** [comment]
Thanks for the picture. But for integrating it into Jamulus I need a transparent background. Do you have a version available with transparent background?

**Comment by dora71** [comment]
Here is now the icon with transparent background :-)

![FaviconJamulus_MountainDulcimerschräg_Hintergrundtransparent_2727](https://user-images.githubusercontent.com/720694/95491750-5922d280-099a-11eb-8870-2a9b5425f37c.png)

**Comment by corrados** [comment]
I just integrated you icon. Thanks. I'll close this Issue now.
