### ISSUE TITLE
My mixer background

### ISSUE THREAD

**Issue by keepers305** [corrados/jamulus#652]
You have done such a nice job on Jamulus that all I could find to make it just a little more polished (to may taste anyway) is this alternative solid mixer board background color.  Anyone compiling their own can choose edit with a color of their choice, replace the one in the src/res folder and compile 

![mixerboardbackground](https://user-images.githubusercontent.com/66562312/94872761-6defeb00-041b-11eb-8de0-fad9382d315e.png)
mixerboardbackground.png

**Comment by corrados** [comment]
I would not change the existing "fancy" style. I would introduce a new style as in https://github.com/corrados/jamulus/issues/73. We now have a new icon and design. It would be interesting to have a style which matches the color/design of the logo and the banner.

**Comment by ignotus666** [comment]
I'm a fan of dark themes—I find them easier on the eyes—and some time ago created my own background using a brushed metal image and also made a new .png for the fader background to match it better. It's nothing special (flat, no fake bolts, rounded corners or raised effect...) but I like it more than the stock fancy skin. I have a script to download and install Jamulus and just added a couple of lines that replace those 2 files before it gets compiled.
![custom_skin](https://user-images.githubusercontent.com/4263412/94988725-a6a0d900-056f-11eb-81e7-510cd6c03301.png)

**Comment by ignotus666** [comment]
Had a go at cleaning it up a bit (made the fader background largely transparent) and replaced the fader and on/off icons. Maybe not everyone's cup of tea but I rather like it myself. 
![custom_skin2](https://user-images.githubusercontent.com/4263412/94994808-6e62c000-059a-11eb-9ebf-27500b1e6225.png)

**Comment by corrados** [comment]
I would recommend to continue this discussion in the existing Issue #73 and close this one. Is this ok for you?

**Comment by keepers305** [comment]
If you are asking me - sure. Maybe I posted in the wrong place. I was offering this to the few that are compiling their clients and may want to do some simple customization. For me, it was my "Hello World" experiment.

**Comment by ignotus666** [comment]
Fine by me. I was also just showing what can be easily done if anyone compiling Jamulus themselves wants to spice up the interface. I wasn't aware of that thread; I see that the idea was to create a skin in line with the new logo, which my dark theme doesn't really fit in with :)

**Comment by corrados** [comment]
Ok, so I'll close this one now.
