### ISSUE TITLE
Menu item name mismatch

### ISSUE THREAD

**Issue by chrisrimple** [corrados/jamulus#656]
On MacOS, the Settings window is displayed by choosing Preferences from the Jamulus menu.  It should be Settings in the menu or Preferences in the window title.  My guess is that Edit > Settings from Windows has been carried over to the Mac version, but the naming hasn't been made OS-dependent.

**Comment by corrados** [comment]
The Mac OS does these things automatically. It seems to detect entries like "About" or "Settings" in the menu entries and if it detected one, it moves it to a different place and also sometimes renames it. The application cannot change that, this seems to be a Mac OS "feature". You can try it out: If you change the language, you can see that Mac OS will no longer detect these menu entries and they appear at the places defined by Jamulus.

**Comment by chrisrimple** [comment]
Bummer.  But knowing that, perhaps renaming the window title to Settings & Preferences would make more sense for Mac users?

**Comment by corrados** [comment]
Well, isn't settings and preferences almost the same? I would not have an issue if the menu says Preferences but the dialog window says Settings.
