### ISSUE TITLE
Have a constant URL for the latest release tarball

### ISSUE THREAD

**Issue by softins** [corrados/jamulus#663]
It would be very useful when creating instructions for newcomers compiling Jamulus if there could be a constant URL that could be used to fetch the latest release, whatever that might be. Something like:
```
wget https://github.com/corrados/jamulus/archive/latest.tar.gz
```
This would avoid everyone just doing `git clone`, which results in a LOT of servers in the list running `r3_5_Ngit` instead of a proper release version.

**Comment by gilgongo** [comment]
The instructions here do that, albeit is a bit messily:

https://github.com/corrados/jamulus/wiki/Installation-for-Linux#get-jamulus-sources

**Comment by softins** [comment]
At the moment, all the worldjam people just do `git clone` and end up with the latest git WIP. I would try and encourage them at least afterwards to do:
```
git checkout $(git tag -l 'r*' | sort -t_ -k1,1 -k2,2n -k3,3n | tail -1)
```
But really, people who just want to fetch and compile shouldn't need to worry about git.

**Comment by gilgongo** [comment]
> people who just want to fetch and compile shouldn't need to worry about git.

So is https://github.com/corrados/jamulus/releases/latest no good?

**Comment by softins** [comment]
Well, they're ok for people looking manually (although the SF one is harder to navigate being cluttered with adverts), and the github one certainly can be scraped to extract the URL, so long as they don't change the page format. It just seemed worthwhile to have a way to wget the latest tarball without having to know the version number. It arose from a conversation earlier, and is not a big deal, but could be an easy win.

**Comment by gilgongo** [comment]
> easy way to wget the latest tarball

That would be nice. But other than the currently favoured way of using a git one-liner script to parse out the latest [as given here](https://github.com/corrados/jamulus/wiki/Installation-for-Linux#get-jamulus-sources) (we're just talking about Linux users, right?) I'm not sure how we'd do it unless there's some hidden magic with gitub?  How do other projects do it?

**Comment by softins** [comment]
> How do other projects do it?

It's easy if they are just maintaining their own download space. For github's auto-generated tarballs, I wonder if it would be enough just to make an additional release tagged "latest" at the same time as the version-numbered release? I haven't played with releases myself, but I could do so on a test project.

**Comment by softins** [comment]
OK, I've done some experimentation on a test repo, and all that is needed is this:
1. Do the release in the normal way.
2. Before making any further changes to the repo, do this:
```
git push origin :refs/tags/latest
git tag -f latest
git push --tags
```
This will add the tag `latest` to the release commit, which will also cause github to make available `.../archive/latest.tar.gz` and `.../archive/latest.zip`. There appears no need to make another actual release with the tag `latest`.

**Comment by gilgongo** [comment]
Great! (I guess GH will remove the "latest" tag from the previous commit) So what's the URL it creates then?

**Comment by softins** [comment]
Yes, that's correct. It's the `git push origin :refs/tags/latest` that deletes the old "latest" tag from the remote. Otherwise the `git push --tags` fails with a "tag already exists on remote".

**Comment by corrados** [comment]
Ok, I have just done it for the last 3.5.12 release. Can you please check that it works for you?

**Comment by pljones** [comment]
> git push origin :refs/tags/latest

Isn't modern idiom "git push --delete origin latest"?

**Comment by gilgongo** [comment]
Excellent anyway - I'll update the Linux docs. One less dependency - no git required!

**Comment by corrados** [comment]
Ok, then I think we can close this Issue. But one problem remains: I have to remember to move the label the next time I create a new Jamulus release. Anyway, if I forget it, it is no problem to move that tag some days after the release. If you find out that the tag was not moved, just tell me about it and I'll fix it :-).

**Comment by softins** [comment]
Cool, many thanks!

**Comment by pljones** [comment]
> 
> 
> Ok, then I think we can close this Issue. But one problem remains: I have to remember to move the label the next time I create a new Jamulus release. Anyway, if I forget it, it is no problem to move that tag some days after the release. If you find out that the tag was not moved, just tell me about it and I'll fix it :-).

You need an automated release process ;).

**Comment by WolfganP** [comment]
> 
> 
> > Ok, then I think we can close this Issue. But one problem remains: I have to remember to move the label the next time I create a new Jamulus release. Anyway, if I forget it, it is no problem to move that tag some days after the release. If you find out that the tag was not moved, just tell me about it and I'll fix it :-).
> 
> You need an automated release process ;).

I was going to suggest the same. There are several Github Actions to automate releases, maybe one of them would fit & simplify the current process.

**Comment by ann0see** [comment]
> Automated release process

#795
