### ISSUE TITLE
Can't start server

### ISSUE THREAD

**Issue by chrisrimple** [corrados/jamulus#665]
I was attempting to upgrade to the latest server version.  I followed the instructions that I have here, which have worked in the past...

https://docs.google.com/document/d/1smcvsxdaaViPQvGMQHmah_6BQeqowhmGSFMHfnlY2FI/edit#heading=h.ttnch1lxf6f

They are:

```
cd /tmp/
git clone https://github.com/corrados/jamulus.git
cd jamulus
qmake "CONFIG+=nosound headless" Jamulus.pro
make clean
make
make install
mv Jamulus /usr/local/bin/
systemctl start jamulus
systemctl status jamulus
```

But I got an error message.  Figuring that I'd done something wrong, I tried again, and got the same error.  Then I restarted the server and tried, but same error.  So I destroyed the server, created a new one, reinstalled from scratch using these instructions (which are the same I had used originally):

https://andrewferguson.net/2020/07/08/jamulus-and-temporally-hyper-near-servers/

My jamulus.service file contents are a little different, specifically the ExecStart line...

`ExecStart=/usr/local/bin/Jamulus --server --nogui --servername $(uname -n) --centralserver jamulusallgenres.fischvolk.de:22224 --serverinfo "School of Rock WS;Seattle, WA;225" -g --welcomemessage "<h1>School of Rock West Seattle Jamulus Server</h1><p>This server is primarily for <b>School of Rock West Seattle</b> students, but is also open for public use. It is often busy with band rehearsals on Wednesdays, Fridays, and Sundays 6-9pm PST (UTC-8). <b>Recordings are enabled on this server and are automatically deleted after 24 hours</b>. It is hosted at Vultr.com in Seattle, WA, USA by Chris Rimple. Please contact chrisrimple@yahoo.com with questions.</p><p>For general information about Jamulus and Jamulus resources, see the Remote Band Rehearsals document:</p><p><a href="https://docs.google.com/document/d/1smcvsxdaaViPQvGMQHmah_6BQeqowhmGSFMHfnlY2FI/">https://docs.google.com/document/d/1smcvsxdaaViPQvGMQHmah_6BQeqowhmGSFMHfnlY2FI/</a></p>" --numchannels 20 --fastupdate --recording /var/jamulus/recording/`

Finally, I started the service and checked it:

```
systemctl start jamulus
systemctl status jamulus
```

And I'm getting the same error:

```
● jamulus.service - Jamulus-Server
   Loaded: loaded (/etc/systemd/system/jamulus.service; disabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Tue 2020-10-06 17:59:28 UTC; 7s ago
  Process: 16765 ExecStart=/usr/local/bin/Jamulus --server --nogui --servername $(uname -n) --centralserver jamulusallgenres.fischvolk.de:22224 --serverinfo School of Rock WS;S
 Main PID: 16765 (code=exited, status=1/FAILURE)
```

So I'm guessing there's something in the my ExecStart line, that worked with prior server versions, that is now failing.   Was one or more command line parameters changed/removed?

**Comment by trombonepizza** [comment]
why do you have "mv Jamulus" after "make install"?

**Comment by chrisrimple** [comment]
@corrados Thank you, sir!  When new server versions are published, is there a list of added/deprecated command line parameters posted somewhere?

@trombonepizza No idea.  :)  I'm not a Linux expert, so I was just following Andrew Ferguson's original instructions from:

https://andrewferguson.net/2020/07/08/jamulus-and-temporally-hyper-near-servers/

**Comment by corrados** [comment]
I write all changes in the file ChangeLog, see https://github.com/corrados/jamulus/blob/master/ChangeLog#L14

**Comment by chrisrimple** [comment]
@corrados Excellent, I'll look there in the future.  I've updated my jamulus.service file (ExecStart), and it's working now.  Thanks!  And I'll close this issue.
