### ISSUE TITLE
Use user Profile name for server recording filename

### ISSUE THREAD

**Issue by chrisrimple** [corrados/jamulus#667]
I've got recording enabled on my server at all times.  After a band rehearsal, I'll download the recording folder for that session.  The folder name is a timestamp, I get that.  But the individual WAV files are also named with timestamps, when it would be much easier if they were named using the Profile names of the Jamulus users - for example, if my Profile name is "Chris", my recording filename might be "Chris [timestamp].WAV" or similar.  Oddly, occasionally a WAV file will be created based on a user's Profile name, but usually not, and I don't see a way to control that.

**Comment by pljones** [comment]
So each time some random user "Chris" connects, it overwrites the same file?

**Comment by chrisrimple** [comment]
Chris1.wav, Chris2.wav, etc.?

But I see your point.  Weird thing is, sometimes the filenames ARE the Jamulus names, but only for 1-2 files (in a recording that included a dozen).  How is that happening?

Anyway, sounds like I'm not getting this one, so it can close.  But I'm going to log a new issue limiting the use of the Jamulus name Chris to only me.  :)

**Comment by trombonepizza** [comment]
if you issue a server kill SIGUSR2 to start a recording when your server is already populated with musicians, their individual tracks will have their names on the recordings.  Perhaps this is related to why it sometimes happens inadvertently.

**Comment by chrisrimple** [comment]
@trombonepizza Thanks!  Didn't know that, and it's a handy feature that I'll use for every band rehearsal.  :)

**Comment by pljones** [comment]
> Weird thing is, sometimes the filenames ARE the Jamulus names, but only for 1-2 files (in a recording that included a dozen). How is that happening?

It depends on the order of things arriving at the server and how long things take to get to the recorder.
