### ISSUE TITLE
ping times went up with new version?

### ISSUE THREAD

**Issue by Andre-de-Vos** [corrados/jamulus#668]
I updated to version 3.5.12 the other day. It looks like my ping times doubled/tripled and the amount of servers with acceptable ping times are now so much less. Is this coincidence or must be of other causes or could the cause be in the new version?

**Comment by 38github** [comment]
I noticed that too but changed genre, changed back and the ping was correct. Do you get the same result?

**Comment by Andre-de-Vos** [comment]
Unfortunately changing genre had no effect. Sorting on ping time is also noticably slower. Thinking about going back a version.

**Comment by Andre-de-Vos** [comment]
Went back to 3.5.1 and ping times were OK again. To be sure installed 3.5.12 again and ping times went down. 
I have screenprints of the differences if someone is interested. I attached a file with screenprints of both versions.
[Ping times down with 3.5.12.docx](https://github.com/corrados/jamulus/files/5358656/Ping.times.down.with.3.5.12.docx)

**Comment by corrados** [comment]
You seem to look at different server lists.

**Comment by Andre-de-Vos** [comment]
I did use what's coming out of the box. Does the two versions use different server lists out of the box? And would I override that by filling the "Central Server Address" in settings?
I saw one server at both lists ( e.g. Andre's Public Sound with pingtimes 101 ms / 20 ms respectively), but looking better they are on different locations (Newark US and London UK respectively). 
Could it be 3.5.12 using the US Central server and 3.5.1 European Central server?  If so what should I configure in 3.5.12 to get the European?

**Comment by Andre-de-Vos** [comment]
I just saw that for a Jamulus server with the -e option you can specify a central server, but this is no option with a Jamulus client. Looks like I cannot change this for the client?

**Comment by corrados** [comment]
There is a List selection right above the table:
![grafik](https://user-images.githubusercontent.com/46655886/95659310-75e91280-0b20-11eb-822b-48f034434e83.png)

**Comment by corrados** [comment]
Any updates? Can you close this issue?

**Comment by Andre-de-Vos** [comment]
Yes thank you very much. That was it. The "Default" list points to the "right" server list.
