### ISSUE TITLE
Jamulus User Survey?

### ISSUE THREAD

**Issue by gilgongo** [corrados/jamulus#67]
If we knew more about how people were using Jamulus, would we do things differently?

Knowing more about how Jamulus is being used might might help uncover mis-understandings, structure the documentation better, as well as possibly evolve the functionality of the software. 

I've created [a draft survey here with some initial questions](https://forms.gle/hSSjsxjWj2Pnp5kr7). I'm thinking mostly from the point of view of improving the documentation, but anything we can ask that we think we can act on, the better.

_**Please don't submit real answers yet!**_ This is still under construction!

**Comment by vocobox** [comment]
I would also invite user to share video or audio of their sessions to prove Jamulus works :)

**Comment by gilgongo** [comment]
OK I think this is ready to go out now.

@corrados Can you put a combined Announcement and Sticky thread up on the SF forums, and the Facebook group (and anywhere else that might be visible)  with something like this for the wording?

---

_Tell Us About Jamulus!_

We'd love to know more about how you use Jamulus, what you think of it so far, and what issues you mostly commonly have with it.

If you have a couple of minutes, please [fill out our anonymous survey](https://forms.gle/hSSjsxjWj2Pnp5kr7)!

---

**Comment by corrados** [comment]
I put it on the Discussion forum. Can you please post it in Facebook?

**Comment by gilgongo** [comment]
Sure - are you able to make it a combined Announcement and Sticky so that it won't get buried in the forums?

**Comment by corrados** [comment]
Thanks for reminding. I forgot to set it to Sticky.

**Comment by gilgongo** [comment]
Live now so will wait until it gets maybe 100 or so replies before doing a summary (we have over 60 right now).
