### ISSUE TITLE
Extend PHP code to deliver JSON server status

### ISSUE THREAD

**Issue by pljones** [corrados/jamulus#670]
In a similar manner to Tony Mountifield's server list PHP Jamulus UDP Protocol support, it would be useful for web site developers 
to be able to query a local server for information.

An initial set would be:
- server name (as shown on any server list, if registered, else empty - the caller then presumably knows what to do some other way)
- if registered with a server list, the server list server details
- the server version
- the maximum number of connections
- the current connection details

Connection details would be minimal and represent what could be seen when connected as a Jamulus client.

(It'll be a while before I get to this if someone else wants to grab it.  My PHP is rusty, too...)

**Comment by dzpex** [comment]
I'm able to help you but i do not understand how work the jamulus protocol for capture some information.
I wrote a python program that are able to start or stop a jamulus server in a specified port and return the status of the server at a php client.
I wrote this for managing a remote cloud private jamulus server and start or stop it with a PHP - Boostrap GUI.

I'm happy to collaborate...if is possible.

**Comment by pljones** [comment]
The best starting points:
- Tony's Jamulus Explorer PHP
- protocol.h / protocol.cpp in the Jamulus source

**Comment by pljones** [comment]
Just commenting, partly as I'm starting to think about this again and I want to organise my thoughts...

#638 was aiming to remove `--htmlstatus` but it has been kept as JavaScript and UDP don't mix.

This ticket was raised mainly to provide similar display in a browser, based on a backend query (e.g. in PHP or python), using the same mechanism the client does when querying for servers on the connection page - but limited to a single server.

There are a number of benefits of this, the main one being that the existing flat file "goes stale" if the server crashes: it will continue to indicate there are connections, as nothing is writing to it.  So an active probe will provide a more reliable monitoring facility.

As noted on the initial post, additional information above the existing html status file would be useful.

**Comment by pljones** [comment]
And... Tony's PHP already returns pretty much everything possibly needed:
https://explorer.jamulus.io/servers.php?server=62.113.206.102
```
[
  {
    "index": 0,
    "name": "62.113.206.102",
    "numip": 1047645798,
    "ip": "62.113.206.102",
    "port": 22124,
    "ping": 12,
    "os": "Linux",
    "version": "3.6.1git",
    "versionsort": "003006001git",
    "nclients": 9,
    "clients": [
      { "chanid": 0, "country": "Italy", "instrument": "Vocal", "skill": "-", "name": "Alberinda", "city": "milano" },
      { "chanid": 1, "country": "Germany", "instrument": "Vocal Tenor", "skill": "-", "name": "Karli", "city": "" },
      { "chanid": 2, "country": "Canada", "instrument": "-", "skill": "-", "name": "No Name", "city": "" },
      { "chanid": 3, "country": "Spain", "instrument": "Bass Guitar", "skill": "Intermediate", "name": "oscar", "city": "" },
      { "chanid": 4, "country": "Germany", "instrument": "Keyboard", "skill": "Intermediate", "name": "Schmidty", "city": "Düren" },
      { "chanid": 5, "country": "Germany", "instrument": "Vocal Tenor", "skill": "-", "name": "Rainer", "city": "Heilbronn" },
      { "chanid": 7, "country": "Germany", "instrument": "Drum Set", "skill": "Expert", "name": "Schlumpf", "city": "" },
      { "chanid": 9, "country": "Netherlands", "instrument": "Keyboard", "skill": "Expert", "name": "Bill", "city": "Deventer" },
      { "chanid": 15, "country": "Germany", "instrument": "-", "skill": "-", "name": "Valerie", "city": "" }
    ]
  }
]
```
The only odd thing being `name` seems to be whatever value was passed as `server`, rather than the server name...  I've raised https://github.com/softins/jamulus-php/issues/2 for that.

**Comment by corrados** [comment]
> Extend PHP code

I must admit that I do not really understand this. Which Jamulus PHP code you are referring to? Or do you referring to a PHP code in another repo?

**Comment by pljones** [comment]
> I must admit that I do not really understand this. Which Jamulus PHP code you are referring to? Or do you referring to a PHP code in another repo?

I think it's  likely going to end up in https://github.com/softins/jamulus-php rather than here, so I'll close.
