### ISSUE TITLE
Regarding increasing opus quality setting

### ISSUE THREAD

**Issue by trombonepizza** [corrados/jamulus#674]
I'm thinking of making a custom compile that will have a higher quality audio basis.  

As I currently understand it, this is relatively simple.  All that is really needed is to increase the numerical values in the following table:

#define OPUS_NUM_BYTES_MONO_LOW_QUALITY                     12
#define OPUS_NUM_BYTES_MONO_NORMAL_QUALITY                  22
#define OPUS_NUM_BYTES_MONO_HIGH_QUALITY                    36
#define OPUS_NUM_BYTES_MONO_LOW_QUALITY_DBLE_FRAMESIZE      25
#define OPUS_NUM_BYTES_MONO_NORMAL_QUALITY_DBLE_FRAMESIZE   45
#define OPUS_NUM_BYTES_MONO_HIGH_QUALITY_DBLE_FRAMESIZE     71

#define OPUS_NUM_BYTES_STEREO_LOW_QUALITY                   24
#define OPUS_NUM_BYTES_STEREO_NORMAL_QUALITY                35
#define OPUS_NUM_BYTES_STEREO_HIGH_QUALITY                  73
#define OPUS_NUM_BYTES_STEREO_LOW_QUALITY_DBLE_FRAMESIZE    47
#define OPUS_NUM_BYTES_STEREO_NORMAL_QUALITY_DBLE_FRAMESIZE 71
#define OPUS_NUM_BYTES_STEREO_HIGH_QUALITY_DBLE_FRAMESIZE   142

My questions are:

1.  Does anyone know how much quality increase is to be expected per byte (roughly)?  (I realize this is subjective, but I'd like to have some idea of how much to try out.

2.  I assume "double framesize" means small network and sample buffers?

TIA

**Comment by corrados** [comment]
> Does anyone know how much quality increase is to be expected per byte (roughly)?

There were some quality tests made a while ago. See, e.g.: https://sourceforge.net/p/llcon/discussion/533517/thread/bdb3fe2195/#4b18/952a/32fb/cd47/404e/053a

> I assume "double framesize" means small network and sample buffers?

DBLE_FRAMESIZE meanse that "Smalle Network Buffers" are **not** used.

**Comment by corrados** [comment]
Since your questions are answered, should we close this Issue?

**Comment by trombonepizza** [comment]
Yes thanks
