### ISSUE TITLE
Windows ASIO4ALL driver support interacts with Zoom audio input

### ISSUE THREAD

**Issue by wattdave** [corrados/jamulus#676]
Zoom and Jamulus can only run on the same Windows computer at the same time if they are using completely independent audio input devices. If both are configured to use the same microphone, then the microphone input never gets delivered to either Zoom or Jamulus, and a Windows user is left listening to the Jamulus server, but unable to send. Is this an as-designed of the ASIO4ALL driver? Is there any hope of having this work?

**Comment by trombonepizza** [comment]
Yes, ASIO4ALL can only work with one application at a time, and if something else tries to grab the audio, then problems happen.

**Comment by gilgongo** [comment]
Also, it's probably best not to use Zoom on the same machine as Jamlus in any case to avoid CPU spikes and possibly other interference that may affect the integrity of the session.

**Comment by wattdave** [comment]
For what it's worth, it's reasonably stable on Macs. Windows is flakier.

**Comment by trombonepizza** [comment]
<begin opinion>
if at all possible, avoid all use of Windows like the plague whenever professional or low-latency audio is the goal
<end opinion/>

**Comment by gilgongo** [comment]
>  avoid all use of Windows  

Unfortunately, yes. This is one reason why I usually suggest Jamulus OS to people having intractable problems on Windows. Just wish it was easier to set  that up with persistent settings.

**Comment by trombonepizza** [comment]
You can make your own custom .iso with Jamulus (or whatever) installed, add those persistent settings and flash it to a USB stick using Cubic.

**Comment by gilgongo** [comment]
@trombonepizza Indeed, but whether a casual Windows user will be willing or able to do that is another matter :-)

**Comment by gilgongo** [comment]
@wattdave Are you OK with the explanation here? I'm afraid there's probably not much that can be done about the behaviour of ASIO4All.

**Comment by corrados** [comment]
Any update? Should we close this one then?

**Comment by corrados** [comment]
No feedback... So, I'll close this now. If there is some outstanding issue left, just re-open this issue or create a new one.
