### ISSUE TITLE
Minimise window option disappeared

### ISSUE THREAD

**Issue by ignotus666** [corrados/jamulus#683]
Using the latest git version, the 'minimise' icon has disappeared from the client and server windows. Nor is it available (greyed-out) when right-clicking.

**Comment by corrados** [comment]
What operating system are you using?

**Comment by ignotus666** [comment]
Linux

**Comment by storeilly** [comment]
It's missing on the beta 3.6.0 windows build also

**Comment by corrados** [comment]
Should be fixed now. Thanks for reporting.

Please check if it works for you now. If not, please re-open this Issue.

**Comment by ignotus666** [comment]
Yup, fixed!
