### ISSUE TITLE
Server Status

### ISSUE THREAD

**Issue by pljones** [corrados/jamulus#69]
I just realised this is a bit of a problem.

If I display the server status that's written to the html file, it shows the name I've asked it to show, plus to server internal port.  Ideally, the value would be stored without the port number (internal and external are likely to differ) - all that's wanted is the server status.

Very low priority (I've fixed it in my javascript processing).

**Comment by ginjo** [comment]
As an alternative to an html status page, a json or xml status page containing user and server details would be useful, especially on headless servers. This would also offload the responsibility of data presentation from Jamulus. Something like:

jamulus_status.json
```json
  {
    "some_server_info": "...",
    "some_server_config": "...",
    "client_count": 2,
    "clients": [
      {"name":"bill", "ip":"x.x.x.x", "port":22333, "jitter_buffer_size":12},
      {"name":"amy", "ip":"x.x.x.x", "port":22333, "jitter_buffer_size":9}
    ]
  }
```

**Comment by pljones** [comment]
It needs a `"last_updated_at": "YYYY-MM-DDThh:mm:ss.nnnnnnZ"` field.

Then add two settings / options to the server: `--status-timeout <seconds>` and `--status-json <filename>`.

Presume it should create the file as a text file if not found.  It's not a log file, so it should also overwrite the file on each update.

**Comment by corrados** [comment]
> Ideally, the value would be stored without the port number (internal and external are likely to differ) - all that's wanted is the server status.

The server name is no longer written in the HTML file, see https://github.com/corrados/jamulus/issues/638.

> As an alternative to an html status page, a json or xml status page containing user and server details would be useful, especially on headless servers.

As written in https://github.com/corrados/jamulus/issues/638, the HTML status should completely removed from the Jamulus software. It would be better to have a PHP script which queries the information via UDP. Then you can format your output exactly like you want.

So I'll close this Issue now.

**Comment by pljones** [comment]
Raised #670 to get some PHP written.
