### ISSUE TITLE
IP_LOOKUP_TIMEOUT = 500ms shouldn't it be 5000ms (5 s) see global.h

### ISSUE THREAD

**Issue by DavidSavinkoff** [corrados/jamulus#690]
I noticed extra DNS packets on my network with Jamulus. Maybe Jamulus was timing out too quickly, then resending the requests to a slow DNS server. I changed IP_LOOKUP_TIMEOUT from 500 ms to 5000 ms (msft uses 5 second timeout here, linux nslookup uses 10 seconds).
See line 118 in src/global.h and change from 500 ms to 5000 ms.

**Comment by corrados** [comment]
@pljones You have written that code. Can you please give a short comment why you have chosen 500 ms? Is it so short because you have some blocking functionality?

**Comment by DavidSavinkoff** [comment]
Note that IP_LOOKUP_TIMEOUT is used only once in Jamulus:
find . -type f -print0 | xargs -0 grep -Iw IP_LOOKUP_TIMEOUT
./src/util.cpp:    if ( socket.waitForConnected ( IP_LOOKUP_TIMEOUT ) )
./src/global.h:#define IP_LOOKUP_TIMEOUT                500       // ms

**Comment by pljones** [comment]
Nope, half a second is plenty on application start up.  If 8.8.8.8 routing fails, you want it to fail fast.

**Comment by DavidSavinkoff** [comment]
I noticed in ./src/util.cpp line 1002
    QTcpSocket socket;
    socket.connectToHost ( WELL_KNOWN_HOST, WELL_KNOWN_PORT );
Shouldn't it be
    QUdpSocket socket;
because DNS is udp
note 8.8.8.8:53

**Comment by pljones** [comment]
Nope, on some platforms UDP won't correctly set the source IP address.  We're not doing a DNS lookup, we're just getting this host's external IP address.

**Comment by DavidSavinkoff** [comment]
My topic:
 IP_LOOKUP_TIMEOUT = 500ms shouldn't it be 5000ms (5 s) see global.h #690
Will be resolved with topic #633 because it is just another angle on this topic.

#633 could reference #690 if #690 is deemed informative.
Thank you for your patience, I'm not opposed to closing my topic.

**Comment by corrados** [comment]
OK, let's close this one then. I'll write a short notice in the other Issue.
