### ISSUE TITLE
Improve Group Selection UI : one click to group / ungroup

### ISSUE THREAD

**Issue by houbsta** [corrados/jamulus#695]
Currently live mixing with groups is near impossible for broadcast purposes. It requires two clicks to add each fader to a group. Should you need to ungroup a fader because that individual signal suddenly increases or decreases, you need two clicks to ungroup, then set the fader, then another two clicks to add back.

I propose that - at least in the fancy skin - the 4 groups be immediately assignable with a row of 4 narrow buttons that instantly group or ungroup.

For the compact skin there isn't the space, but the compact skin isn't practical for live broadcast mixing anyway, unless you really have a lot of clients and no choice.

**Comment by kwindrem** [comment]
I mixed live sound for almost 20 years and most digital consoles offer some form of channel grouping. On the Yamaha CL5 for example, to isolate a channel from the group temporarily, you held the SELect button for the channel and moved the fader. You could do something similar in Jamulus with a shift-click-drag.

Live mixing consoles offer "VCA" faders that function much like a channel group. However, each individual channel fader is still adjustable. The VCA fader is just another gain adjustment in the signal path. 

Adding VCA faders to Jamulus would take additional space. But with a sufficient number of VCAs you might get away with hiding channel faders assigned to a VCA fader. If individual channel adjustment was needed, opening the channel faders assigned to a VCA in another panel of faders would allow quick adjustments.

Generally, I like the idea of each musician having their own mix. However I can see cases where a musician isn't in a position to create their own mix especially with lots of channels. In this case, allowing an engineer to take over any musician's mix and make changes could be helpful. The engineer would need to hear that mix of course.

Another concept that might have value is to establish a baseline musician mix that could be imported by each musician. This would include groups and fader levels. I haven't played around with it but the Save and Load Mixer Setup is probably most of what's needed here, combined with the ability of an engineer's Jamulus client to "solo" a specific musician's mix and make tweaks.

One other thing that might help is a "master level" for each channel in the mix. This master live would affect levels at all Jamulus clients. This comes up for example when a musician switches instruments and their contribution to the mix is suddenly too loud or too quiet.

**Comment by corrados** [comment]
I have just implemented shortcuts in the group menu. You now can click on the GRP button and quickly press the 1, 2, 3 or 4 key on your keyboard to select the group. Or you click on the GRP button and press the n key on your keyboard to un-group.

I wanted to make a short clip to show you how fast this can be but unfortunately I cannot create an animated GIF right now to post it here.

**Comment by houbsta** [comment]
Sounds great @corrados I will test this as soon as I can. I am a victim of French AZERTY keyboards which means numbers also need SHIFT to be pressed, but as long as this works on the number pad it will be fine.

**Comment by WolfganP** [comment]
> I mixed live sound for almost 20 years and most digital consoles offer some form of channel grouping. On the Yamaha CL5 for example, to isolate a channel from the group temporarily, you held the SELect button for the channel and moved the fader. You could do something similar in Jamulus with a shift-click-drag.

The using of the SHIFT key on a grouped channel to override the group fader movement is a good way to solve the spikes or temp situation from individual channels. Nice suggestion!

**Comment by houbsta** [comment]
I have successfully built a Mac version of the latest 3.6.0git, and the Normalise #622  is working perfectly - also tested on Linux.

However for grouping: I can click GRP and quickly hit 1 then enter to group, but I would prefer if after hitting 1 it just assigns grp1 without having to press enter. Not a big issue, I can learn 1-ENTER 2-ENTER etc if need be.

However I do not have a shortcut to unassign, AFAICT. So I still have to do click GRP-1-UpArrow-ENTER to achieve this, which is again "learnable" but starting to be suboptimal. Perhaps 0 (zero) be used as a shortcut to no group?

**Comment by houbsta** [comment]
> I have successfully built a Mac version of the latest 3.6.0git, and the Normalise #622 is working perfectly - also tested on Linux.
> 
> However for grouping: I can click GRP and quickly hit 1 then enter to group, but I would prefer if after hitting 1 it just assigns grp1 without having to press enter. Not a big issue, I can learn 1-ENTER 2-ENTER etc if need be.
> 
> However I do not have a shortcut to unassign, AFAICT. So I still have to do click GRP-1-UpArrow-ENTER to achieve this, which is again "learnable" but starting to be suboptimal. Perhaps 0 (zero) be used as a shortcut to no group?

My bad - it seems "N" works as a shortcut to No Grouping.

**Comment by corrados** [comment]
> I can click GRP and quickly hit 1 then enter to group, but I would prefer if after hitting 1 it just assigns grp1 without having to press enter.

That is interesting. On my Linux I do not have to press the enter key. I just click on the GRP button and then press just the key "1" and then the fader is already assigned to the group. So, it seems that the Mac is behaving differently (which is not good...).

**Comment by corrados** [comment]
> My bad - it seems "N" works as a shortcut to No Grouping.

Yes, it is. I hope this shortcut is ok for you? I have to use a character as a shortcut which is in the name "No Grouping".

**Comment by houbsta** [comment]
> That is interesting. On my Linux I do not have to press the enter key. I just click on the GRP button and then press just the key "1" and then the fader is already assigned to the group. So, it seems that the Mac is behaving differently (which is not good...).

Yes I checked my build contains the correct code (most recent commit ea6868cdb0094a8540fa739ff3edc472e52eb938) and can confirm on my Mac it requires ENTER to be pressed

> > also tested on Linux.
> 
> Have you tried the grouping on Linux, too?

Yes, and on Linux it works as you say - one keypress and no need for ENTER afterwards.

**Comment by corrados** [comment]
> Yes, and on Linux it works as you say - one keypress and no need for ENTER afterwards.

I just found out a useful feature on Linux: You can press and hold the 1 key and then just click on each fader GRP button you want to assign to that group. That works for me and let's you very quickly assign groups to faders. BTW, the same works for press and hold the n key to ungroup.

**Comment by corrados** [comment]
> On the Yamaha CL5 for example, to isolate a channel from the group temporarily, you held the SELect button for the channel and moved the fader. You could do something similar in Jamulus with a shift-click-drag.

That's a good idea, thanks. Very easy to implement. I've just implemented it with the following Git commit: https://github.com/corrados/jamulus/commit/a410922ad1cd58a5e2e54f318cca4abf689fcd3a

**Comment by corrados** [comment]
@gilgongo The "press 1 key and click on GRP" and the "shift-click-drag" features should be documented as soon as the next release is out.

**Comment by sthenos** [comment]
Fantastic feature adding the SHIFT hold to move specific faders in a group.  This is one of the main reasons why I haven't been fully utilising the group feature.    Thanks!

**Comment by corrados** [comment]
@houbsta, are you happy with the implementations I did so far so that we can close this Issue now?

**Comment by houbsta** [comment]
Yes very happy, I will be giving it a proper test during this evening's WorldJam, but I have tested and it's all working very nicely (on Linux in particular).

**Comment by corrados** [comment]
> I will be giving it a proper test during this evening's WorldJam

Would be interesting to hear your feedback here.

I'll close it now.

**Comment by houbsta** [comment]
I mixed last night's WorldJam with the latest version of Jamulus from Git, including SHIFT-click features on pan and grouped faders. 

Compared to a previous WorldJam it was night and day. 

- Grouping can now be used live to keep a handle on backing vocals, horns or groups of guitars. Quick to group, easy to ungroup, and during song SHIFT can adjust individual faders. Perfect. 
- Panning is a lot safer and when people talk back after their song you can easily centre them again
- CTRL-L to set levels to new client setting was used before most songs with big lineup changes and particularly when jumping studios (we had servers in New Jersey, London, Virginia, Amsterdam...) for different bands
- Not forgetting that very few clients now exhibited burbling (usually backstage there's an "oh no it's a shame great playing but burbling" every 2 or 3 songs) even though we used our infamous OVH server which had exhibited very bad burbling for Virgin Media clients, who played on this show

We also made some changes to our broadcast FX chain post Jamulus and audio quality was the best we have ever had, just one or two client-side issues with mic preamps but no Jamulus problems. 

Thank you very much, the audio engineer can really control things so much better now.

**Comment by corrados** [comment]
Thanks for your feedback. I really like these types of software improvement. They were done with just a minimal change in the code.
