### ISSUE TITLE
Excellent Undocumented Server Features

### ISSUE THREAD

**Issue by DavidSavinkoff** [corrados/jamulus#696]
I discovered features that should be documented in the source code, and in user documentation. Please keep these features.

I noticed that you can run a Public server long enough for your band to connect, then you can go Private by simply unchecking the 'Make my server Public' box in the server GUI. Excellent!

I also noticed that you can go Public in one of the Genres, pick up a musician on the server, then move to another Genre, pick up another musician, ... and so on, then go Private by the method above if you wish. All without dropping the connections to your musician clients. Excellent!

Note that these methods Don't cybersquat on the Central Server name list. Excellent!

**Comment by corrados** [comment]
@gilgongo You should make this a "documented feature" :-).

**Comment by gilgongo** [comment]
Interesting!

**Comment by corrados** [comment]
@gilgongo As soon as you have finished the testing and documentation, please close this Issue then.

**Comment by ann0see** [comment]
I think if this works, you should open an issue on jamulussoftware/jamulussoftware.github.io

**Comment by DavidSavinkoff** [comment]
The documentation has been updated on The Jamulus homepage and wiki
https://github.com/jamulussoftware/jamulussoftware.github.io
If this is sufficient, could this be closed?

**Comment by ann0see** [comment]
@DavidSavinkoff actually I wasn't aware of this change. I hope the translations will consider this. But I think we can close it if that's the case

**Comment by gilgongo** [comment]
@ann0see It was on the [list of changes](https://github.com/orgs/jamulussoftware/teams/translators/discussions/1) using the "old" system when I messaged the translators a couple of weeks ago.

**Comment by ann0see** [comment]
Ah ok. I suggest you focus on the changes from now on. I will focus on the tecal stuff. 

This issue can be closed then.

**Comment by Humpri** [comment]
I wonder if there is a possibility to do the same trick (public --> privat) on a headless server?

**Comment by gilgongo** [comment]
Yes, essentially just stop the server in one mode, then start it immediately after in another. Perhaps having two separate start scripts a bit like that described for controlling recordings [here](https://jamulus.io/wiki/Server-Linux#footnotes).

**Comment by Humpri** [comment]
Thanks gilgongo. But when I stop the server the connected clients will be kicked out, isn't it? 
For the record controling you simply start scripts sending signals, you don't stop the server.

**Comment by gilgongo** [comment]
> when I stop the server the connected clients will be kicked out, isn't it?

No, the nature of the UDP client/server connection means that they will stay connected during the restart. 

> For the record controling you simply start scripts sending signals, you don't stop the server.

Sorry, I wasn't clear. I didn't mean you'd use those exact scripts, but suitably modified versions to achieve what you wanted.

**Comment by Humpri** [comment]
O yes, it definitely works! The connection stays. I didn't expect that. 
Many thanks!
