### ISSUE TITLE
Add Multiple custom central servers.

### ISSUE THREAD

**Issue by storeilly** [corrados/jamulus#698]
Would it be a big task to allow more than one custom central server? 
I have two private centrals and I know of others that I use occasionally.

**Comment by sthenos** [comment]
Yea I was thinking about this to Stephen, I'm changing custom central servers for a few different reasons.  One of the things I used to like about the old custom server text box is that it remembered all values typed in there and dropped down to allow you to pick a previous one.  This was a very useful feature for that reason.   Perhaps this would be a combo box instead that allows you to pick from previously used custom servers?

**Comment by gilgongo** [comment]
> combo box instead that allows you to pick from previously used custom servers?

Yes, the server name/address field in the connection setup used to work like that (does it still?)

**Comment by sthenos** [comment]
@gilgongo No, I don't think it still does.   When it went through that major change with the addition of the various central server list dropdowns, I believe this feature went away.

**Comment by gilgongo** [comment]
I can't remember why that change was made on the server list input field now.

**Comment by corrados** [comment]
> old custom server text box is that it remembered all values typed in there and dropped down to allow you to pick a previous one

I also cannot remember such a feature.

Anyway, making the central server address edit field a combo box isn't a big deal. I'll take a look at it.

The plan is that the combo box remembers old entries and when you select and old entry, the server list is immediatly updated. This will make the combo box very useful if you have multiple custom server addresses stored in the combo box list.

**Comment by corrados** [comment]
Multiple central server addresses are supported now:
![grafik](https://user-images.githubusercontent.com/46655886/97779280-51abaf00-1b7d-11eb-9593-f4bb4f5b3d4f.png)

**Comment by storeilly** [comment]
Thank you.

**Comment by JW144754** [comment]
Love it! thanks!

**Comment by jp8** [comment]
It's great Volker - would you consider moving the setting to the connection dialog, instead of the settings dialog ?  Personally, any time I need to change to a different central server, I am already on the connection dialog.

**Comment by jp8** [comment]
perhaps integrated somehow with the 'fixed' list of central servers...
