### ISSUE TITLE
Give server commands from client

### ISSUE THREAD

**Issue by chrisrimple** [corrados/jamulus#704]
Allow client user to execute server commands, such as Start/Stop Recording, etc.

- Server’s Jamulus.service file would contain a password
- Client user would provide the password
- Valid password would provide access to non-destructive server features

Since the Jamulus client already has a user interface for Enable Recording and similar when in Server mode:

- Add a new client menu item for “cloud server control mode” or similar
- Add an edit field for Server Password
- When connecting to a server, if Password is valid, display Server controls

It’s basically like launching Jamulus in Server mode, except it’s Remote Server mode.

**Comment by pljones** [comment]
It's much safer to set yourself up with some desktop shortcuts that run the appropriate server commands securely.  It's pretty easy to do.

**Comment by chrisrimple** [comment]
@pljones I'm on a Mac.  I use Cyberduck for sftp to download recordings, but looking for an easier way to restart Jamulus recording on the server than the current process of run Terminal, ssh to server, execute command "systemctl kill -s SIGUSR1 jamulus", exit server, exit Terminal.  At your suggestion, I looked at Cyberduck SSH capabilities, and configuring it to envoke Terminal seems the only option.  It appears that there's a Mac PuTTY version, but I haven't looked at it yet.  Would love to have a shortcut that achieves what I want, but I suspect that may also require some AppleScript.  Thoughts?

**Comment by kwindrem** [comment]
If you can achieve what you want via SSH, then you can build a shell script or Apple Script to send the command with a single button press. Ditto for downloading the recorded audio.

I would suggest adding a command to start and stop recording while the server is running. I haven't played with the recorder so I'm not sure what facilities are already in place or how recording is currently controlled.

**Comment by chrisrimple** [comment]
Thanks, @kwindrem.  I'm looking at shell scripts now - it likely can serve my needs.  However, I'm not closing this because some Jamulus cloud server owners may not be as adept, and operating server functions from the client would be very handy.  :)

**Comment by pljones** [comment]
The Jamulus git tree does allow for other to contribute scripts - do please feel free to share anything useful.

**Comment by corrados** [comment]
> However, I'm not closing this because some Jamulus cloud server owners may not be as adept, and operating server functions from the client would be very handy.

I actually would like to close this. I don't like remote control of server functionality from the client, see also https://github.com/corrados/jamulus/issues/629#issuecomment-700236000. As pljones mentioned here, SSH access is much safer than using any Jamulus protocol communication.

**Comment by chrisrimple** [comment]
Ok, closing.  :)
