### ISSUE TITLE
Double click pan-pot should reset the pan to 0 L/R

### ISSUE THREAD

**Issue by sthenos** [corrados/jamulus#707]
Currently it's hard to use the pan-pot on faders to get the centre back to 0db left and right.   In most DAWS pan can be dead-centred by double-clicking the fader or pan pot.  Can this feature be added pls?

**Comment by corrados** [comment]
I've implemented it this way: If you press shift+click on the Pan control, it will jump in the center:
![m14JIYbWys](https://user-images.githubusercontent.com/46655886/97747797-cda9e680-1aec-11eb-9b0a-b8f599c2520f.gif)
Commit: https://github.com/corrados/jamulus/commit/f5170ad6c6d9ef5f92e1a21b42bbb1e4f6539472

**Comment by sthenos** [comment]
Brilliant, thank you @corrados, this plus thus the shift-drag on group faders is going will make all the different to the sound engineer role!
