### ISSUE TITLE
Digital noise after runnung current functional update of Windows 10

### ISSUE THREAD

**Issue by klingstar** [corrados/jamulus#709]
Dear all, 
after runnung the current Windows 10 functional Update, I get heavy digital noise from my Jamulus client in the direction server -> client. Appears repeatedly, holds on for about a minute each time. 
Jamulus 3.6.0, Hardware Lenovo ThinkPad T520, LAN 1 GBit, Internet 100/10 Fibre. Maybe, but not sure, depending on internet workload.
Any correlation thinkable?
Thanks and best regards,
Gerd

**Comment by corrados** [comment]
I suspect that this could be an audio driver issue. Maybe the Windows update has unloaded the previous audio driver.

**Comment by klingstar** [comment]
Many thanks, corrados!
I forgot to mention: it is a Steinberg UR22mkII. I will test and keep you informed.

**Comment by corrados** [comment]
Any updates?

**Comment by klingstar** [comment]
Yesterday, my second computer (Tower, Proc. i5 / 3.2 Ghz) was updated to Win10 Version 2004, too. After this, I ran 2 hours of Jamulus session without any distortion, using the same USB interface and audio equipment as in the distorted Laptop (Proc. i5, 2.4 GHz) sessions. 
So I think, this may be a device specific problem. I proceed with unburding the Laptop (Autostart etc.).
Many thanks so far!

**Comment by corrados** [comment]
Ok, thanks for the feedback. So, I'll close this Issue now.
