### ISSUE TITLE
Increase LED luminance in UI?

### ISSUE THREAD

**Issue by gilgongo** [corrados/jamulus#71]
With the addition of the UV meters, the issue of contrast in the UI has become more important. Suggest increasing the luminescence of the colours as below. However, in this mockup the lights are 2D, whereas in the UI they are 3D. This means I can only approximate a good luminance for them.

Here the Red is #FF3300, Green is #66FF33 and Yellow is #FFFF00 while the default is #F2F2F2

![image](https://user-images.githubusercontent.com/4561747/79324569-b700c100-7f07-11ea-85db-0468770d6969.png)

**Comment by corrados** [comment]
I'll take care of it.

**Comment by corrados** [comment]
I started with the green LED (see the "Delay" LED on the following screen shot):
![grafik](https://user-images.githubusercontent.com/46655886/79359925-79ba2480-7f43-11ea-83e1-1c3b419efae5.png)
How do you like it?

**Comment by trebmuh** [comment]
I need to see the whole picture to be able to see if I'm seeing everything correctly. Most of the time, the color _differences_ is the key.

**Comment by corrados** [comment]
What do you mean by "whole picture"? Do you mean you must see it live in the software when its running?
Here is another screen shot, now the green and red round LEDs are modified:
![grafik](https://user-images.githubusercontent.com/46655886/79367445-35805180-7f4e-11ea-9747-6377d3405ac7.png)

**Comment by gilgongo** [comment]
@trebmuh I'm not colour blind, but I think I'm right in saying that we'd never be able to get good contrast between red, green and yellow for everyone on the Delay and Buffers indicator, so that's why I raised #57 The VU meters are a slightly different matter though, since the difference between those colours is only nice to have - the main utility is to see them moving.

**Comment by trebmuh** [comment]
> What do you mean by "whole picture"? Do you mean you must see it live in the software when its running?

Usually yes. Or at least a picture with all the _final_ colors.

On the picture above, I've got difficulties to see the differences on the Input L&R horizontal segments which are colored and the other in gray. With a quick look at it, it seems that the 3 last of each columns are colored on green, but if I look closer, the first column could have only 2 greens horizontal segments, and the R colum probably 3 but maybe 4. Note that if I'm looking too long at it, everything gets mixed and I'm loosing ground.

**Comment by trebmuh** [comment]
@gilgongo of course it is possible to get a good contrast. That's why greenlight on the street are the colors they are. If not, colorblind would be car-less :wink:
Your #57 proposition is a good addition by the way and is a good step for blind people with a screen reader to be able to use jamulus.

**Comment by corrados** [comment]
We may solve https://github.com/corrados/jamulus/issues/57 by adding a new skin to Jamulus. That new skin should be designed to look very nice but also fulfill all criteria so that color-blind people can distinguish all indicators. See https://github.com/corrados/jamulus/issues/73

BTW: My screen shot was just work-in-progress. Not the finished version. I did not change the fader LEDs yet in that screen shot.

**Comment by trebmuh** [comment]
Yes, I saw that #73 . Yes @corrados I did understand that your previous screeenshot wasn't finished yet, but because you asked "_How do you like it?_", I've answered you the best I can. No rush that being said, just ping me when you're done with the color, and I'll test it and will give you a _colordblind_ feedback on it if you want one.

**Comment by corrados** [comment]
Here is another example, now the level meter LEDs are also in new color:
![grafik](https://user-images.githubusercontent.com/46655886/79372167-e3dbc500-7f55-11ea-9eec-4fc609c1cff2.png)

**Comment by trebmuh** [comment]
It's is very nice for me. The red and green colors are _flashy_ enough for my eyes and I can see the difference. TS, I'm no very sure but here might be a "yellow light on the Input left column ? If so, it isn't very visible for me. But depending of the meaning of this yellow color, it might not be very important.

**Comment by corrados** [comment]
Yes, it is. Yellow is critical. It is almost not possible to get it clearer.
I have applied my changes to the Git repo and will use these for the next release. I would close this Issue now and if you tested the new version and still have issues with it, just re-open this Issue again.

**Comment by gilgongo** [comment]
BTW using this simulator, you can see what I mean about the Delay and Buffers indicators if you have deuteranopia for example (which I take it @trebmuh doesn't have?). But this is a minor point as we have the other ticket.

**Comment by trebmuh** [comment]
From an online test I just did, I've got a deuteranomaly which is red-green color blindness.

**Comment by gilgongo** [comment]
> I've got a deuteranomaly which is red-green color blindness.

Yes, which is different from deuteranopia. This is why I said I think it's not possible to achieve good contrast for everyone because one person might need the contrast between red and yellow, but others might want it between the green and red, for example. We can only optimise for the most common types, of which I think your's is.

**Comment by trebmuh** [comment]
So I'm lucky about coloring maybe :angel:

**Comment by trebmuh** [comment]
@corrados note that having a clever enough color defaulting system covering most of the case is fine, and [having a user defined color scheme option](https://github.com/falkTX/Carla/issues/1011#issuecomment-614076969) will allow to cover pretty much all scenario.
