### ISSUE TITLE
Soundcards on macos only get scanned as available at startup

### ISSUE THREAD

**Issue by brandflake11** [corrados/jamulus#711]
Hello all,

I worked with a student today who was having issues with Jamulus on macos. It seems that external headphones do not show up as an option under settings>device when the student launches Jamulus before plugging in external headphones. The external headphones show when plugged in before launching Jamulus. 

I wanted to report this to make sure it is not a bug with Jamulus or a constrain with macos or coreaudio.

Thank you very much,
Brandon

**Comment by chrisrimple** [comment]
I have seen the same behavior.  I'm pretty sure that Jamulus only scans for devices at launch, so devices connected after starting Jamulus will not be seen by Jamulus, although they will be seen by the operating system.

**Comment by brandflake11** [comment]
If this is fixable, I think it would improve Jamulus to allow for it to recognize when new devices are plugged in and out.

**Comment by corrados** [comment]
This is a duplicate: https://github.com/corrados/jamulus/issues/181

**Comment by corrados** [comment]
Since this is a duplicate, I'll close this one now. Please continue your discussion about this problem in the original Issue.
