### ISSUE TITLE
Is the project hosted on SourceForge?

### ISSUE THREAD

**Issue by yurivict** [corrados/jamulus#714]
The README says so, but SourceForge doesn't have the version 3.6.0.

Arch Linux takes the tarball from the GitHub account: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=jamulus

**Comment by corrados** [comment]
The binaries and the discussion forums are hosted at Sourceforge.

**Comment by trebmuh** [comment]
@corrados the last 3.6.0 version is named [Jamulus-version.tar.gz](https://sourceforge.net/projects/llcon/files/Jamulus/3.6.0/) while it was named 3.5.12 [before](https://sourceforge.net/projects/llcon/files/Jamulus/3.5.12/). Is that expected?

**Comment by yurivict** [comment]
FreeBSD new version discovery system failed to find ```3.6.0``` on SourceForge because the latest tarball is named ```Jamulus-version.tar.gz```.

As a result, the FreeBSD port wasn't updated when the new version was released.

Is the code now hosted on GitHub?

**Comment by corrados** [comment]
I just corrected the name on Sourceforge. Now that tar.gz file has 3.6.0 in its name.

-> closed
