### ISSUE TITLE
Using Jackd on windows with Jamulus

### ISSUE THREAD

**Issue by dzpex** [corrados/jamulus#718]
Hi, i have installed the jackd tool on windows but on the settings of Jamulus i can't see Jackd audio driver option for selection.

Is possible to have this feature implemented ?

Thanks!

**Comment by corrados** [comment]
You need to re-compile Jamulus with the jackonwindows qmake config switch enabled (https://github.com/corrados/jamulus/blob/master/Jamulus.pro#L77).

**Comment by pljones** [comment]
Or use a JACK<->ASIO driver with the standard build.

**Comment by corrados** [comment]
So since your request is already implemented (native Jack support is implemented but must be enabled when you compile the software) or you could use the Jack for windows software (which supplies the Jamulus software with an ASIO interface), I'll close this Issue now.
