### ISSUE TITLE
VS 2019 build Qt5Guid.dll, Qt5Widgetsd.dll,.. not found 

### ISSUE THREAD

**Issue by A5005** [corrados/jamulus#72]
Hi there,

I'm actually a pure .NET developer, but this project is so cool that I am dealing with the open source / cross platform for the first time in my life. My last unmanaged line of code was more than 10 years ago. So sorry if my requests should be trivial.

I was already able to compile the project in Visual Studio 2019.
When setting up Qt I selected the latest version Qt 5.14.2 (I wasn't sure here, since Qt 5.9.9 to Qt 5.14.2 could be selected)

When I start the project from Visual Studio 2019, I get the error message:
Qt5Guid.dll, Qt5Widgetsd.dll, Qt5Networkd.dll, Qt5Xmld.dll not found.

I probably forgot to install something at Qt (no experience with it so far), but unfortunately, I don't know what.

![Qt](https://user-images.githubusercontent.com/44929101/79337061-20db9380-7f25-11ea-9766-03f3f573ca20.png)

**Comment by corrados** [comment]
Unfortunately, I cannot help you with that. But since this is a general Qt problem, you should post it in some Qt help forum instead.
