### ISSUE TITLE
Support multiple rows for the mixer panel

### ISSUE THREAD

**Issue by corrados** [corrados/jamulus#720]
I just read about such a feature request on a Facebook group. For large choral groups that feature might be interesting. I did some quick hack test implementation which then would look like this:
![grafik](https://user-images.githubusercontent.com/46655886/98993493-d65bdd00-252e-11eb-8855-cecc154502c6.png)

The problem is that if you make the main window small, you only see the lowest row:
![grafik](https://user-images.githubusercontent.com/46655886/98993586-f25f7e80-252e-11eb-9425-1ad75dd274e6.png)

You can even shrink the window so that it looks like only one row would be present which is not good:
![grafik](https://user-images.githubusercontent.com/46655886/98993531-e4116280-252e-11eb-8c96-d71cbd0ee9cc.png)

The coding part is not too complicated. Basically using a QGridLayout instead of a QHBoxLayout and some other small modifications make it possible. But the question is how to configure this? Should Jamulus automatically use multiple rows if the number of faders exceeds a certain number? Or should the user configure this?

BTW: I am not planning to support this anytime soon. I just wanted to raise a feature request here to start a discussion about this feature.

**Comment by corrados** [comment]
If anybody wants to play with my quick hack code, you can checkout my test branch https://github.com/corrados/jamulus/tree/feature_mult_rows_mix_panel (note that you have to enable some sorting to make it look like the screen shot above).

**Comment by ann0see** [comment]
This idea looks great (Actually I also thought about that a while ago). I think if you add multiple rows, the layout must be altered a little bit (don't show the mixer board in a scroll-able box but expand the whole window.

**Comment by gene96817** [comment]
I am glad this is getting some thought. 
Consider grouping all the sliders by instrument/voice parts. Then the sliders can be nested. At the top level, the mixer would be sliders by section. It probably needs some experimentation to know if each musician in a section is accessed by expanding or if they are all at the same level (row) with a section slider. The other complication is who has control over the section balance and how is the section balance managed. All good problems now that we can have large ensembles (>50 musicians).

**Comment by pljones** [comment]
I'd actually been thinking about switching the orientation but retaining the "compact" style:
```
+---------------------------+
| X flag icon Name          | ("X" is "this channel has you muted")
| M[x] S[x] [===========[]] | ("M[x]" is the mute checkbox; "S[x]" is the solo checkbox)
| G[x] P(@) [-------------] | ("G[x]" is the group checkbox; "P(@)" is a very small pan control)
+---------------------------+
```
Each of these would be a fixed height and width, laid out across a flow panel, wrapping onto multiple rows as needed.  That way you could get a _lot_ of players on screen without scrolling and all nicely aligned.

**Comment by chrisrimple** [comment]
@pljones Love the thinking.  While audio engineers may be accustomed to vertical slider controls, there's no reason that they couldn't be horizontal to maximize the layout.  

Having a fixed width and height for each musician's controls would allow for 3-4 horizontally on each row.  Something that might be easier to implement but still effective would be fixed height (using your control layout) but unlimited width - essentially, rotating the existing controls 90 degrees clockwise.  That would result in vertical scrolling, rather than horizontal, to view more musicians/controls,  which is both easier to accomplish and more familiar to average computer users.

**Comment by corrados** [comment]
I want to keep it simple (as usual ;-) ). If you want to have a different fader orientation, then this is for a new Github Issue. In this Issue I want to focus specifically on the multiple rows support while using the single fader setup as is (i.e. vertical fader and everything is vertically stacked).

**Comment by mawess** [comment]
On our band we require each sectiont to start their names with a specific number. 
0 - singers, 1 - komp, 2 - saxes, 3 -trumpets etc
It would be nice if you can group sliders after the names and that each group could is placed under each other.

**Comment by corrados** [comment]
BTW, if you are a member of the official Jamulus Facebook group, you should check out the following Jamulus screen shot: https://www.facebook.com/photo.php?fbid=10220998002917998&set=p.10220998002917998&type=3. I find that very impressive.

**Comment by corrados** [comment]
I found time to implement it. Now we have a new menu entry for selecting that the mixer panel shall have one or two rows -> closed.

**Comment by mawess** [comment]
what decides what goes to second row? or is it more than two rows if they didnt fit in first two?

**Comment by corrados** [comment]
It is a very simple rule. The faders are equally distributed in the two rows.
