### ISSUE TITLE
Update link to new homepage and wiki on Sourceforge and github

### ISSUE THREAD

**Issue by ann0see** [corrados/jamulus#721]
This repo still links the old website and https://sourceforge.net/projects/llcon/support still links the github wiki. They should be updated.

**Comment by corrados** [comment]
@gilgongo Can you please take care of this?

**Comment by gilgongo** [comment]
I've updated the SF support link to go to Getting Started - unless we think the home page is better?

**Comment by ann0see** [comment]
I think the getting started page is good. Can you also edit the text saying Jamulus [...] recommends going to? I think it should say that you can visit the wiki page or go to the forums if you need help.

**Comment by gilgongo** [comment]
We don't get any control over what that text says unfortunately.

**Comment by ann0see** [comment]
That's a pitty. So probably we have to leave that as it is. 

The link on the GitHub repo still has to be changed (and maybe on the Facebook group

**Comment by ann0see** [comment]
Also the link on https://sourceforge.net/projects/llcon/ under Follow Jamulus - Internet Jam Session Software
 should be updated.

**Comment by ann0see** [comment]
SourceForge looks alright now. GitHub (this repo) and Facebook still have to be updated.

**Comment by gilgongo** [comment]
@corrados has that power :-)

**Comment by corrados** [comment]
Done.

**Comment by corrados** [comment]
So, I guess this Issue can then be closed now?

**Comment by ann0see** [comment]
If the Facebook page is updated yes.

**Comment by corrados** [comment]
Yes, Facebook is updated. So I'll close this Issue now.

**Comment by ann0see** [comment]
Ok. Great
