### ISSUE TITLE
Allow fader controls to flow horizontally and vertically

### ISSUE THREAD

**Issue by sebukoleth** [corrados/jamulus#724]
Today when performers join a session the controls flow sideways. Then we need to use side the scrollbars. Can we add an option to reflow the faders vertically and horizontally simultaneously? This would make better use of screen real estate. A mockup is attached.
![Jamulus-hor-ver-mockup](https://user-images.githubusercontent.com/1766488/99192718-361dd800-2729-11eb-978c-3c133da4e350.png)

**Comment by ann0see** [comment]
I think @corrados just implemented this feature.

**Comment by sebukoleth** [comment]
Hmmm, I was using the 3.6 client and did not see it reflowing that way. Is there any setting that needs to be tweaked?

**Comment by sebukoleth** [comment]
Ahhh, feature_mult_rows_mix_panel branch.

**Comment by corrados** [comment]
It's not in 3.6.0. It will go into 3.6.1. Here is the Issue: https://github.com/corrados/jamulus/issues/720.

**Comment by sebukoleth** [comment]
Dup of #720.
