### ISSUE TITLE
Switched to MacOS Big Sur: server no longer records!

### ISSUE THREAD

**Issue by dadaparadox** [corrados/jamulus#728]
I upgraded to Big Sur MacOS over the weekend and ever since, though Jamulus for the most part is working great, my server suddenly no longer records sessions - would any of you have any idea why that should be the case and how to fix? Many thanks in advance!

**Comment by corrados** [comment]
Maybe an issue with directory rights? Is it possible for the Jamulus server software to write that output directory you have created for storing the recordings?

**Comment by corrados** [comment]
BTW: Is this you? https://www.facebook.com/groups/619274602254947/permalink/796587574523648

**Comment by dadaparadox** [comment]
Hi - yes, and I’ve found a solution - so this query can be deleted.

Thanks,
Ian

**Comment by dadaparadox** [comment]
Thanks - did you read the thread on FB? In the end I just changed the name of the output directory - simplified it to ‘recordings’ and it worked again.

**Comment by dadaparadox** [comment]
Thanks!
