### ISSUE TITLE
[feature request] Improve status "page"

### ISSUE THREAD

**Issue by gegeweb** [corrados/jamulus#730]
As shown here https://jamulus.io/wiki/Tips-Tricks-More (making a server status page) I added the -m option to generate the status page.
In the end it only displays the name of the connected users.

Would it be possible to display more information?
* server up or down
* uptime
* bandwith
* name, instruments and location for the connected users. (not just the name)

As you can see below, what is displayed is really basic! 
<img width="815" alt="Capture d’écran 2020-11-17 à 15 17 52" src="https://user-images.githubusercontent.com/9108457/99401135-1d0f5580-28e8-11eb-89f0-a7aa59f4302b.png">

**Comment by corrados** [comment]
The server status page feature was already scheduled to be removed, see: https://github.com/corrados/jamulus/issues/638. So maybe sometime in the future it will no longer be awailable.

**Comment by chrisrimple** [comment]
Perhaps Tony Mountifield's [Jamulus Server Explorer](http://jamulus.softins.co.uk) provides some of the desired information?

**Comment by gegeweb** [comment]
> Perhaps Tony Mountifield's [Jamulus Server Explorer](http://jamulus.softins.co.uk) provides some of the desired information?

Yes, I've installed the php script.
But it returns the result in JSON format.
And obviously not the uptime (not of the system but of the service).
There is still more information that can be used.

**Comment by gegeweb** [comment]
> Perhaps Tony Mountifield's [Jamulus Server Explorer](http://jamulus.softins.co.uk) provides some of the desired information?

Yes, with little adaptation of this php script works fine to display the musiciens online on the server.
I'll publish the code soon on a Framagit repository.
That's the first version, I have some improvments on the TODO list before. First dislpaying if the server is up or down.
On the client side (html) I use AJAX request to the php script for displaying json content.

<img width="736" alt="Capture d’écran 2020-11-23 à 06 23 02" src="https://user-images.githubusercontent.com/9108457/99931446-d640b600-2d54-11eb-981d-1338fb5c69d5.png">

**Comment by gegeweb** [comment]
@corrados since I've a solution to do what I need. This issue can be closed. 
Especially if this feature is going to be removed.

It should be specified in the doc... ;)

**Comment by corrados** [comment]
Ok, thanks -> closed.
