### ISSUE TITLE
Enable The Manager To Force Un-Mute and Un-Solo

### ISSUE THREAD

**Issue by maallyn** [corrados/jamulus#732]
Let me try to explain this, but I was doing SoundCheck as well as shadowing the Sound Engineer during a recent World Jam. I had some frustration trying to do Sound Check because the performer had me muted (I knew this because the little orange/red light above their fader on the main panel of my Jamulus client was on. I had to beg someone else who happened to be in the same Sound Check room to tell that person to please un-mute me so I could talk to them through the sound check.

In addition, I believe there was a case where the Manager was unable to tell a performer to please  jump from the Waiting Room to the Backstage and then from Back Stage to the Studio due to the same problem.

This got me thinking. As many of us are away, the ssh facility on many Linux server use a public/private key combination to let you log in without having to know a password.

What would happen if somehow there was a public and private key arrangement where the Jamulus server (Sound Check, Waiting Room, Back Stage, Etc) had a list of public keys stored. Then each of the Managers (Stage Manager, Deputy Stage Manger; perhaps lead sound check person) each would have their public key on the servers. They would have their respective private key on their Jamulus client. If the keys do match, there would be a special button on the Jamulus client that would say something like 'Force Un-Mute / Force Un-Solo' that would force all performers to un-mute everyone else and un-solo. This could also go further, especially in a studio where the sound engineer does not hear sound from a performer who forgot to un-click their Mute Myself button. The sound engineer could have the right to force that buttun to unset and allow the performer's sound onto the sound engineer's client for mixing for the live stream.

On the other hand, by using the public/private key Asymetric Cryptography, we can still avoid abuse by someone who is not supposed to be able to mute/unmute other people.

Please, I hope I made sense. Sometimes I have trouble communicating.

**Comment by chrisrimple** [comment]
I wonder if #731 plus the request to move the Chat to be a sidebar on the Mixer window would mostly solve this?  If a performer has the sound check technician muted, the SCT can type to that performer in the chat to tell them to Clear All Mutes & Solos.  Since the Chat isn't "hidden" in a separate window, the performer is likely to see it.

**Comment by kwindrem** [comment]
You wouldn't want to clear all solos in another client to make the SM, etc. heard. 
The channel level must also be taken into consideration (it could be too low to be heard.)

A "paging" attribute could be assigned to the sound guy or SM clients which would instruct the mixer to ignore the client level, mute and solos so that the channel can always be heard. You could even have a TALKBACK button on the privileged client(s) that would temporarily override that channel in the mixer for all clients.

Consider that some clients should have functionality that other clients do not. The ability to be heard by all clients regardless of the client's current settings is one of these special functionality. I've posted elsewhere that the sound engineer may need to take over another client's mix to help them establish a mix they may not be able to do themselves. Part of that is also hearing the mix you are establishing for the other client.

**Comment by maallyn** [comment]
> You wouldn't want to clear all solos in another client to make the SM, etc. heard.
> The channel level must also be taken into consideration (it could be too low to be heard.)
> 
> A "paging" attribute could be assigned to the sound guy or SM clients which would instruct the mixer to ignore the client level, mute and solos so that the channel can always be heard. You could even have a TALKBACK button on the privileged client(s) that would temporarily override that channel in the mixer for all clients.
> 
> Consider that some clients should have functionality that other clients do not. The ability to be heard by all clients regardless of the client's current settings is one of these special functionality. I've posted elsewhere that the sound engineer may need to take over another client's mix to help them establish a mix they may not be able to do themselves. Part of that is also hearing the mix you are establishing for the other client.


This would work. I see nothing wrong, and it's better than my original suggestion. However, I still think that it should be 'controlled' in such a way that it cannot be abused by anyone else except for the SM, SoundCheck, and Sound Engineer. Which points to the possible use of ssh type keys (private key on the SM's client; public key in the server). Each volunteer who does sound check/stage manager/sound engineer would be asked to provide public keys; those would be stored in the server. There could be some pushback on basis of key management; but I want it to be 'put on the table' for discussion.

**Comment by corrados** [comment]
> I had some frustration trying to do Sound Check because the performer had me muted 

Well, being muted in the Jamulus software is one thing. But you could also be muted by the fact that the Jamulus user had turned down the audio on his audio hardware. You can never make sure for 100 % that the other one can hear you.
Jamulus needs a learning curve. There are so many parameters to be aware of to get a good Jamulus experience. It starts with not using WIFI, using a native ASIO driver, do not watch YouTube in parallel, use good audio gear, know how to operate the Jamulus software, etc. Not hearing you is just one little peace.

**Comment by corrados** [comment]
> What would happen if somehow there was a public and private key arrangement where the Jamulus server

If we really want to implement something like this, this would be a really really big task. You not only have to implement all that key handling and GUI changes in the client/server, you also would have to support protocol messages in the server and client to change the mute button in the client GUI. And, of course, this would not work for old Jamulus clients so you would never be sure if your unmute was actually performed or not.

I do not think the benefit of this proposed functionality is it worth to spend so much time for the implementation.

**Comment by maallyn** [comment]
Hearing you, Victor, I have to agree. I will go ahead and close this issue. Thank you.
