### ISSUE TITLE
Compiling Jamulus 3.6.1 is failing on Debian 9 Linode

### ISSUE THREAD

**Issue by corrados** [corrados/jamulus#736]
From the Sourceforge Disucssion forums: https://sourceforge.net/p/llcon/discussion/software/thread/487c151a57/?limit=25#6508

**Tom Wagner:**

_Make of the new release is failing on my Debian 9 Linode. It succeeds as usual on a Debian 8 server, instance, and on another Debian 9 client machine.

Working from git clone, my re-compile as follows is failing.

qmake "CONFIG+=NOSOUND" Jamulus.pro
make clean
make

throws this error:

--begin example--
src/serverlist.cpp: In member function ‘void CServerListManager::CentralServerRegisterServer(const CHostAddress&, const CHostAddress&, const CServerCoreInfo&, QString)’:
src/serverlist.cpp:315:18: error: ‘QVersionNumber’ has not been declared
QVersionNumber::compare ( QVersionNumber::fromString ( strMinServerVersion ), QVersionNumber::fromString ( strVersion ) ) > 0 )
^~~~~~~~~~~~~~
src/serverlist.cpp:315:44: error: ‘QVersionNumber’ has not been declared
QVersionNumber::compare ( QVersionNumber::fromString ( strMinServerVersion ), QVersionNumber::fromString ( strVersion ) ) > 0 )
^~~~~~~~~~~~~~
src/serverlist.cpp:315:96: error: ‘QVersionNumber’ has not been declared
mber::compare ( QVersionNumber::fromString ( strMinServerVersion ), QVersionNumber::fromString ( strVersion ) ) > 0 )
^~~~~~~~~~~~~~
Makefile:2251: recipe for target 'serverlist.o' failed
make: *** [serverlist.o] Error 1
--end example-----------

I re-installed the dependencies with apt and re-tried: no joy._

**Comment by pljones** [comment]
Previous instances, failing on `server.cpp`, have been where the cloud instance RAM size is too small.

This could be solved by creating `.deb` and `.rpm` files, as well as the Windows and MacOS installs - and maybe even providing APT and YUM repositories for easy update.

**Comment by corrados** [comment]
I assume that the problem is related to this: https://github.com/corrados/jamulus/pull/686

**Comment by pljones** [comment]
Ah, right, yes.  That would be why the full upgrade fixes it as it bumps the Qt version.

**Comment by motrengaw** [comment]
Vielen dank, Herr Fischer, et al!  Back to a clean compile, as usual.  Make is now happy on Jesse through Stretch for my systems.

**Comment by corrados** [comment]
Thanks for the feedback. So, I'll close this Issue now.
