### ISSUE TITLE
Jamulus Server still appears to have the same icon, on Mac

### ISSUE THREAD

**Issue by corrados** [corrados/jamulus#737]
From the Facebook groups: https://www.facebook.com/groups/JamulusWorldJam/permalink/659193974655552/?comment_id=659200781321538

**James Wu**
_Jamulus Server still appears to have the same icon, on Mac._

NOTE: On Windows it seems to work fine:
![grafik](https://user-images.githubusercontent.com/46655886/99898341-fc0c8300-2ca0-11eb-93c4-788e79d26b7a.png)

**Comment by marktheharp** [comment]
HI - just to post here too. This is what I imagined when I originally posted the idea of a different symbol - adding a red dot to it. I think that would work for colourblind people as well. 
![jamulus](https://user-images.githubusercontent.com/22644606/99973698-f34aa880-2d97-11eb-89cc-1cbefe0665bb.png)
Both my windows machines still show this with 3.6.1 
![jam 361](https://user-images.githubusercontent.com/22644606/99973779-0a899600-2d98-11eb-94e9-95eeca9f2d3e.jpg)

**Comment by corrados** [comment]
The idea is to fix the bug that the new icon is not actually used for the Windows shortcut and also for the Mac version. The intention is not to change the icon design. I really like the new icon design and since the shape is modified, the new icon is also distinguishable from the normal icon for color blind people.

**Comment by marktheharp** [comment]
Got it - thanks!

**Comment by corrados** [comment]
I just fixed the server icon on MacOS. It seems to work fine:
![grafik](https://user-images.githubusercontent.com/46655886/100473132-f1f1e680-30dd-11eb-93cc-8a64f175e85f.png)

**Comment by corrados** [comment]
I just created a beta version for MacOS which should fix the issue with the icon. Can you please test this beta and report back here: https://github.com/corrados/jamulus/issues/727#issuecomment-738970575
