### ISSUE TITLE
New dependency qtconcurrent not needed?

### ISSUE THREAD

**Issue by ann0see** [corrados/jamulus#741]
I ran build-debian-package.sh and dpkg-shlibdeps says that there is an unneeded dependency ("package could avoid a useless dependency").

See:

```
dpkg-shlibdeps: Warnung: Das Paket könnte eine nutzlose Abhängigkeit vermeiden, falls debian/jamulus-headless/usr/bin/jamulus-headless nicht gegen libQt5Concurrent.so.5 gelinkt wäre (es verwendet keines der Symbole der Bibliothek).
dpkg-shlibdeps: Warnung: Das Paket könnte eine nutzlose Abhängigkeit vermeiden, falls debian/jamulus/usr/bin/jamulus nicht gegen libGL.so.1 gelinkt wäre (es verwendet keines der Symbole der Bibliothek).
dpkg-shlibdeps: Warnung: Das Paket könnte eine nutzlose Abhängigkeit vermeiden, falls debian/jamulus/usr/bin/jamulus nicht gegen libQt5Concurrent.so.5 gelinkt wäre (es verwendet keines der Symbole der Bibliothek).
```

which translates to something like if jamulus-headless or jamulus wouldn't be linked to libQt5Concurrent.so.5 and jamulus wouldn't be linked to libGL.so.1 and libQt5Concurrent.so.5 we could avoid a debian (headless) dependency. Furthermore it says that the binary doesn't use any symbols of the library. I'm not quite sure what that exactly means. 

server.cpp uses QTConcurrent here: https://github.com/corrados/jamulus/blob/d8a5c6fdc7ec9bceaf6fb8569dce1a2962c64597/src/server.cpp#L833, so I don't understand this warning.

**Comment by corrados** [comment]
I am not sure what to do with this Issue. Who should take care of?

**Comment by ann0see** [comment]
Somebody who knows more about debian packaging and maybe the person who included qtconcurrent in the code?

**Comment by wvengen** [comment]
Just doing a wild guess here, but one thing could be happening is that qtconcurrent is necessary to compile, but not to run. If, for example, the functions used are macros or inlined functions, there is no link-dependency.

**Comment by corrados** [comment]
Should we keep this issue open? Does anybody intend to fix this? I am not since this is just a warning and if we have a minor dependency issue, I don't think we really have a problem here.

**Comment by ann0see** [comment]
Not sure if anybody knows more about this. In my opinion since it’s not solved, I would let it stay open.

**Comment by corrados** [comment]
Ok, so let's fix it. How to do it? ;-)

**Comment by ann0see** [comment]
I have no idea unfortunately. Is there anyone who knows Debian better than me?

**Comment by wvengen** [comment]
One solution would be to not link to the library, as the resulting binary doesn't use any symbols from it. But the linker flags are likely to come from pkg-config or so (didn't check the source), so it would be a little awkward to strip something from it.
Btw: similar issue here, but I didn't get to the gist of it yet: https://github.com/TokTok/c-toxcore/issues/359

**Comment by hoffie** [comment]
Hmm, I don't see this warning when running `./distributions/build-debian-package.sh` in a `debian:sid` container against current master (7af863373823fd7ab371b0f5f80d02bb884d8582).
As far as I can see, this is not because `dpkg-shlibdeps` would be any different, but rather because neither the jamulus nor the jamulus-headless binaries are linked against libQt5Concurrent.so.5 anymore.

I am wondering what causes this difference to @ann0see's build. I will try building in an Ubuntu container and/or with an older (~November) version of Jamulus to see if this causes any relevant changes. I'm not seeing anything relevant in a quick scan of `git log Jamulus.pro`.

```
root@8945354ef2ec:/foo/jamulus# dpkg-shlibdeps debian/tmp/usr/bin/jamulus*
dpkg-shlibdeps: warning: binaries to analyze should already be installed in their package's directory
dpkg-shlibdeps: warning: binaries to analyze should already be installed in their package's directory

root@8945354ef2ec:/foo/jamulus# ldd debian/tmp/usr/bin/jamulus-headless | grep -i qt
        libQt5Network.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Network.so.5 (0x00007ffa2a6a2000)
        libQt5Xml.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Xml.so.5 (0x00007ffa2a65e000)
        libQt5Core.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Core.so.5 (0x00007ffa2a115000)

root@8945354ef2ec:/foo/jamulus# ldd debian/tmp/usr/bin/jamulus | grep -i qt
        libQt5Widgets.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5 (0x00007fe6b9c70000)
        libQt5Gui.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5 (0x00007fe6b95ae000)
        libQt5Network.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Network.so.5 (0x00007fe6b9426000)
        libQt5Xml.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Xml.so.5 (0x00007fe6b93e2000)
        libQt5Core.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Core.so.5 (0x00007fe6b8e97000)
```

**Comment by ann0see** [comment]
I'm using Buster. This might be a difference?

**Comment by hoffie** [comment]
>  I'm using Buster. This might be a difference?

Yep, just confirmed it, the build is different on buster:
```root@1dea34257cc6:/foo/jamulus# lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 10 (buster)
Release:        10
Codename:       buster
root@1dea34257cc6:/foo/jamulus# ldd debian/tmp/usr/bin/jamulus | grep -i qt
        libQt5Widgets.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5 (0x00007f1473d49000)
        libQt5Gui.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5 (0x00007f14737be000)
        libQt5Network.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Network.so.5 (0x00007f147361d000)
        libQt5Xml.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Xml.so.5 (0x00007f14735de000)
        libQt5Concurrent.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Concurrent.so.5 (0x00007f14735d5000)
        libQt5Core.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Core.so.5 (0x00007f14730d8000)
root@1dea34257cc6:/foo/jamulus# ldd debian/tmp/usr/bin/jamulus-headless | grep -i qt
        libQt5Network.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Network.so.5 (0x00007f8d27eea000)
        libQt5Xml.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Xml.so.5 (0x00007f8d27eab000)
        libQt5Concurrent.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Concurrent.so.5 (0x00007f8d27ea2000)
        libQt5Core.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Core.so.5 (0x00007f8d279a7000)
```

I'm currently comparing the final compile/link commands to spot any differences between the proper builds (no linking to libQt5Concurrent) and those with the apparently unused dependency.

At least we now know that this issue only affects certain distributions/releases (Debian buster) and it does not seem to depend on the exact Jamulus version/commit.

**Comment by hoffie** [comment]
- The final g++ command invocation which produces the output file is identical in both cases.
- buster's g++ produces a binary which links against libQt5Concurrent.so.5. When dropping `-lQt5Concurrent` from the command, the binary does not link to it (as expected).
- Ubuntu 16.04's g++ and debian sid's g++ produce a binary which does not link against libQt5Concurrent.so.5. This is true eeven when specifying `-lQt5Concurrent`. I somehow suspect that g++ or some subprocess (ld, collect2) decides that this can safely be dropped.
- When further tracing what g++ does, one can see that non-buster passes `--as-needed` while buster doesn't. Adding `-Wl,--as-needed` after `-Wl,-O1` on buster makes buster behave the same as the other releases.
- I don't know where/why buster's g++ decides not to pass `--as-needed` by default. Maybe this is explained by different g++ versions.
- I still don't understand why the linking against is optional although functions from this module are referenced as visible in the source and even with a grep on the final binary. The overall explanation would probably "it's a build-time-only dependency" as @wvengen suggested.
- One can force qmake -> make -> g++ to pass `--as-needed` to the linker as the below output/patch shows.

I guess it's up to @corrados and/or @ann0see to decide if the patch is worth it to be included. It improves things for buster (and maybe other distributions) and should not affect other environments which already use `--as-needed`, but I definitely lack experience to judge whether it might break something nevertheless.

```root@1dea34257cc6:/foo/jamulus# lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 10 (buster)
Release:        10
Codename:       buster
root@1dea34257cc6:/foo/jamulus# git diff Jamulus.pro 
diff --git a/Jamulus.pro b/Jamulus.pro
index 2bd65c00..a8ce563e 100755
--- a/Jamulus.pro
+++ b/Jamulus.pro
@@ -309,6 +309,8 @@ win32 {
     # we want to compile with C++11
     CONFIG += c++11
 
+    QMAKE_LFLAGS += -Wl,--as-needed
+
     HEADERS += linux/sound.h
     SOURCES += linux/sound.cpp
 
root@1dea34257cc6:/foo/jamulus# grep -5 as-needed Makefile 
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = Jamulus3.6.2git
DISTDIR = /foo/jamulus/.tmp/Jamulus3.6.2git
LINK          = g++
LFLAGS        = -Wl,--as-needed -Wl,-O1
LIBS          = $(SUBLIBS) -lQt5Network -lQt5Xml -lQt5Concurrent -lQt5Core -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip
root@1dea34257cc6:/foo/jamulus# make
[...]
root@1dea34257cc6:/foo/jamulus# ldd Jamulus | grep -i qt
        libQt5Network.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Network.so.5 (0x00007ff4d2a27000)
        libQt5Xml.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Xml.so.5 (0x00007ff4d29e8000)
        libQt5Core.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Core.so.5 (0x00007ff4d24ed000)
```

Let me know what you think. I can submit a PR if wanted.

**Comment by corrados** [comment]
Sure you can do it, thanks. @ann0see you should then try it out and give feedback here if it works for you.

@hoffie You should write a short comment right above the new line you inserted why this is needed and refer to this Issue number.

**Comment by ann0see** [comment]
Ok. For me it builds and the warning is gone. The server also seems not to crash in multi threading mode. So I hope this is now fixed.
