### ISSUE TITLE
Compilation error on QVersionNumber...

### ISSUE THREAD

**Issue by vanasten** [corrados/jamulus#744]
At an Ubuntu-20.04 system, I got this compilation error while compiling Jamulus-3.6.1;
(qmake "CONFIG+=nosound headless" Jamulus.pro; make clean; make)
(former compilations worked; all dependencies are satisfied)

src/serverlist.cpp: In member function ‘void CServerListManager::CentralServerRegisterServer(const CHostAddress&, const CHostAddress&, const CServerCoreInfo&, QString)’:
src/serverlist.cpp:315:18: error: ‘QVersionNumber’ has not been declared
  315 |                  QVersionNumber::compare ( QVersionNumber::fromString ( strMinServerVersion ), QVersionNumber::fromString ( strVersion ) ) > 0 )
      |                  ^~~~~~~~~~~~~~
src/serverlist.cpp:315:44: error: ‘QVersionNumber’ has not been declared
  315 |                  QVersionNumber::compare ( QVersionNumber::fromString ( strMinServerVersion ), QVersionNumber::fromString ( strVersion ) ) > 0 )
      |                                            ^~~~~~~~~~~~~~
src/serverlist.cpp:315:96: error: ‘QVersionNumber’ has not been declared
  315 |                  QVersionNumber::compare ( QVersionNumber::fromString ( strMinServerVersion ), QVersionNumber::fromString ( strVersion ) ) > 0 )
      |                                                                                                ^~~~~~~~~~~~~~
make: *** [Makefile:10990: serverlist.o] Error 1

**Comment by pljones** [comment]
See #686 and #736 - please use the latest git source or update your Qt to 5.13 or later.

**Comment by corrados** [comment]
Referring to https://github.com/corrados/jamulus/issues/736#issuecomment-733713966, I'll close this one.
