### ISSUE TITLE
Mute button for own audio

### ISSUE THREAD

**Issue by sthenos** [corrados/jamulus#75]
Consider having a mute button to mute your own audio that is being sent up to the server.   There is a mute button on your own channel strip but that is just to mute your sound that you are hearing. Your audio is still being sent up to the server for other people to hear it.

**Comment by continuata** [comment]
Thanks for posting that FR, didn’t realise this was an open source project

**Comment by corrados** [comment]
This was already raised on Sourceforge: https://sourceforge.net/p/llcon/feature-requests/61

**Comment by trebmuh** [comment]
It'd be great. Could this button just _deconnect_ jamulus jack inputs maybe ?

**Comment by corrados** [comment]
From Sourceforge:

> how about the mute button not sending the local audio to the server at all, and mixing it locally with the server stream? This way you could initiate every new connection as muted until they opt to unmute. lots of people connect to a room and have a listen before they want to go live, so it would take load off the server for people who are not actively contributing. 

That is a good idea. That is fairly simply to implement. I'll look at it today.
But I will still send data to the server so that the fader is still there for all connected clients.

**Comment by continuata** [comment]
Maybe you need a flag for an active connection that you don’t want to actively stream data, so you can skip it in whichever loop does the mixing, saving yourself the overhead. I’ve been in rooms where 6 or 7 people join as listeners without playing. Taking the load off the server for non-participants will make a big difference. Also if you have a huge jam session and only certain players are live at any one time, you can greatly improve the performance of the jam steam.

**Comment by corrados** [comment]
That is not the way Jamulus is designed for. It is designed for active musicians and not for a lot of listeners. If you want a lot of people listening to the jam, you should setup one client which takes the stram from the Jamulus server and streams it to another server which is primariliy setup for streaming audio to a large number of clients.

**Comment by corrados** [comment]
I did some implementation already:
![grafik](https://user-images.githubusercontent.com/46655886/79475888-940a0600-8008-11ea-8a73-10b5c8de9d1e.png)
The My Profile button is replaced by a Mute button. If you press this button, your signal is no longer streamed to the server but you hear all the data coming back from the server (from other clients) and your local signal is mixed to that received stream directly.

**Comment by corrados** [comment]
Ok, the implmentation is now in the Git repo on the master branch. I close this Issue now.

**Comment by sthenos** [comment]
Sweet, i'll clone the master and compile and test it.

**Comment by continuata** [comment]
awesome work!! Will check it out tomorrow.

**Comment by corrados** [comment]
I have just applied a bug fix to the Mute Stream functionality: a76491c3e6328d0661a26974b4c57b6bc64271ca

**Comment by Hk1020** [comment]
I'd suggest to relabel it to _Mute Myself_ as with Stream I was confused what stream is being muted.

**Comment by corrados** [comment]
@gilgongo What is your opinion on that?

**Comment by sthenos** [comment]
Or even simpler, just "Mute me"

**Comment by gilgongo** [comment]
@corrados Yes, I was wondering how people might interpret "Mute Stream" :-) 

It does feel like "Mute myself" or "Mute me" would be clearer. From a native speaker POV, "Mute myself" feels slightly less ambiguous, since "Mute me" might be mis-interpreted as a signal to others (like "Kill me!" or "Forget me!")

**Comment by corrados** [comment]
The shorter the better. @sthenos, you are also a native speaker. Do you wote for Mute Myself or Mute Me.

**Comment by gilgongo** [comment]
"Mute" on its own might in fact be OK perhaps as it's next to Settings, since that's about you and not other people. Hard to say though. I wondered if the word "Stream" might be unfamiliar (it's ot a word we use in the docs). So might people think there was something else that could be muted that wasn't a stream?

**Comment by Hk1020** [comment]
Just a note why I was confused. There are just too many streams so I didn't know what was going to happen, people won't here me, I wouldn't here them (to avoid feedback) or whatever. Just _Mute_ I think is not enough. There already are a lot of _Mute_ buttons of which I still don't know exactly what they do. As you can tell I am completely new to this.

**Comment by corrados** [comment]
So would have "Mute Me" helped you when you first started Jamulus?

**Comment by sthenos** [comment]
I vote for mute me.  It's Simon Tomlinson here..

**Comment by Hk1020** [comment]
Yes, _Mute Me_ is certainly better than _Stream_. But I think there is enough room to make it as explicit as possible so I'd prefer _Mute Myself_ but I am not a native speaker. Up to you.

**Comment by corrados** [comment]
Votes summary:
"Mute Me": corrados, sthenos
"Mute Myself": hk1020, gilgongo

Hmm, I guess we need a fifth opinion to get to a decision :-). @pljones can you help us here?

**Comment by gilgongo** [comment]
I'm actually unsure what most people would think. But logically, "Mute myself" is clearer than "Mute me" because grammatically, "Mute me" has two meanings (both of which could be right but only one actually is), while "Mute myself" only has one meaning.

**Comment by corrados** [comment]
Ok, then we go with "Mute Myself".
Here it is:
![grafik](https://user-images.githubusercontent.com/46655886/79795324-0a35a200-8354-11ea-89d5-83ffff234696.png)

**Comment by pljones** [comment]
I'd actually have said "Mute input" - that's explicit and matches the input fader.

**Comment by gilgongo** [comment]
Ah, "Mute Input" is a good idea - not sure how it would roll with non-native speakers though.

**Comment by drummer1154** [comment]
I am native German with some decades of speaking English - from my PoV "Mute Input" would be perfect because it would directly refer to the Input level meter above.  I think it would be even more intuitive if the switch would be completely removed above the horizontal bar above "Settings" so as to belong to the Input level meter. "Settings" and "Chat" are not related to "Mute Input" at all.

**Comment by corrados** [comment]
Mute Input is not what I have implemented. If my input was muted, I would not hear my instrument at all. But this is not the case when you press the button.
Let's keep "Mute Myself". It is good enough.

**Comment by Hk1020** [comment]
Then what have you implemented? _Mute Input_ actually is how I understood it. If I don’t want to hear myself I pull down the fader of my user/instrument. See, I am utterly confused.

**Comment by corrados** [comment]
Ok, let's be technical again. What I have implemented was: "Mute my stream which is sent to the server". That is obviously too long for the button :-).

**Comment by sthenos** [comment]
I assumed this button just mutes the audio being sent to the serrver, it would still be desirable to be able to hear your own local sound so you can play along and learn songs without disturbing others.  Mute stream I suppose does suggest this more than Mute myself.  But even better would be "Mute myself to others".  But that's a bit long.   "Mute me" implies to me that it would be mute the sound from me so I cannot hear it, which is not what the intention is.   I would vote for "Mute myself" to avoid over "Mute me"

**Comment by pljones** [comment]
So it's now got audio mixing in the client when the client is bypassing the server?  Did you mean to do that..? ;)

"Bypass" might be better than "mute", as they're not muted (locally).  Close call - most other players say "Can you mute your input?" when someone's got audio problems they need to fix up.

**Comment by corrados** [comment]
> So it's now got audio mixing in the client when the client is bypassing the server? Did you mean to do that..? ;)

I am not sure that I understood you correctly. But what I exactly do is to take the sound card input signal, do not send this signal to the server (actually zeros are transmitted, i.e. silence), then I take the signal coming back from the server (containing the signal from other clients) mix that with my own local signal and output that mix to the sound card.

> Also, does that mean you could always be in "bypass" mode when not connected to a server?

No, you need to be connected.

**Comment by trebmuh** [comment]
what about a button "Don't send me" ?

**Comment by sthenos** [comment]
I'm not sure about that sentence, seems a little long.   How about changing
the label as well and reversing the "on" function so that the light is on
(and by default it is) which is allow all clients to hear my sound  the
label says "Live Stream" or just "Live"  like in a tv studio broadcast room
and when you click it label says "Local monitor" or just "Not live"?

Simon

**Comment by corrados** [comment]
Wow, things are getting more and more complicated... :-)
Hey, at the end it is just a simple button with a simple functionality. Nothing to worry too much about it. I think the end user may not know what it does exactly regardless of the text we put on the button. They will simply try it out and see what happens I guess :-).

**Comment by sthenos** [comment]
Happy either way!

One thing I've noticed with it however, is that the volume levels of your local monitor go to 10 when you mute.  So if you have your volume at say 5 (out of 10) and you mute, your volume jumps to 10.   Think the volume should remain unaffected.

**Comment by continuata** [comment]
I’ll throw a curve-ball
How about “practise mode”?

**Comment by Hk1020** [comment]
Well, this starts to turn into a bike shed discussion so I decided I wouldn't comment on the label anymore. But...

> 
> > So it's now got audio mixing in the client when the client is bypassing the server? Did you mean to do that..? ;)
> 
> I am not sure that I understood you correctly. But what I exactly do is to take the sound card input signal, do not send this signal to the server (actually zeros are transmitted, i.e. silence), then I take the signal coming back from the server (containing the signal from other clients) mix that with my own local signal and output that mix to the sound card.

I think this explanation helps me with my confusion. I have a microphone connected and nothing else (we want to sing together eventually). I need to know when I am blasting all my living room conversation into the world. _Mute Stream_ seems to cut off everything and nobody can hear me. Fine. 

But I still hear everything from the mic through my speaker/headphone. How to turn this off? Because if l disconnect from the server the mic sound is gone and the speaker is quiet. Is this how it is supposed to work? I don't know what is required for actual instruments plugged in, I don't have any.

On the other hand if I am connected with a server and click _MUTE_ on my fader or pull it down the speaker is also quiet but the world still hears me. This is really confusing.

**Comment by corrados** [comment]
I fear there is no easy solution to that. We need both, the "Mute Myself" (or whatever name it will be ;-) ) and the Mute button on your fader.
The more features are implemented in Jamulus, the more complexity is added, too...

**Comment by trebmuh** [comment]
> But I still hear everything from the mic through my speaker/headphone. How to turn this off? 

You can mute this at your audio-system level. If you use jack, just disconnect the cable.

**Comment by Hk1020** [comment]
I am not questioning the functionality. But the interface must transfer it to the user. The faders are kind of easy to understand, they only affect the local sound. Once you get the hang of it it's ok. But they could affect other people's sound via acoustic feedback.

**Comment by Hk1020** [comment]
> 
> 
> > But I still hear everything from the mic through my speaker/headphone. How to turn this off?
> 
> You can mute this at your audio-system level. If you use jack, just disconnect the cable.

Makes sense now but why is it quiet when I am disconnected?

And how to unplug a built-in mic? Only via system/sound settings I guess.

**Comment by trebmuh** [comment]
> Makes sense now but why is it quiet when I am disconnected?

What is "_it_" in your question ?


> And how to unplug a built-in mic? Only via system/sound settings I guess.

With jack, this is the same whether it's a built-in mic, or a XLR-mix on a external USB soundcard (as an example).

**Comment by Hk1020** [comment]
> 
> 
> > Makes sense now but why is it quiet when I am disconnected?
> 
> What is "_it_" in your question ?

My speakers. Consider these settings with only me connected to server: 

1. Mute Stream OFF, Fader MUTE on, server connected  => speaker quiet
2. Mute Stream ON, Fader MUTE on, server connected => speaker echoes mic input
3. Mute Stream ON, Fader MUTE on, server disconnected => speaker quiet

> 
> > And how to unplug a built-in mic? Only via system/sound settings I guess.
> 
> With jack, this is the same whether it's a built-in mic, or a XLR-mix on a external USB soundcard (as an example).

What exactly is jack? I am on Windows if it matters.

**Comment by trebmuh** [comment]
[JACK](https://jackaudio.org/).
I have close to no experience with windows (last time I installed one was probably ~15 years ago), so am probably not the right person to help you here.

**Comment by drummer1154** [comment]
> > > Makes sense now but why is it quiet when I am disconnected?
> > What is "_it_" in your question ?
> My speakers. Consider these settings with only me connected to server:
>     1. Mute Stream OFF, Fader MUTE on, server connected  => speaker quiet
>     2. Mute Stream ON, Fader MUTE on, server connected => speaker echoes mic input
>     3. Mute Stream ON, Fader MUTE on, server disconnected => speaker quiet

"why is it quiet when I am disconnected?" I think the answer to this question is simple: You _always_ hear the audio which is sent from the server, regardless whether or not other audio sources are mixed together with your signal in the server. This is necessary to account for the network delay ("latency"). So if you are disconnected from the server, you will hear - silence.

From my PoV "Mute Stream" is ambiguous - it does not contain the information "upstream" (audio from the client to the  server) or "downstream" (audio from the server to the client). Maybe "Mute Upstream" would be a solution.

And also from my PoV the upstream audio shall be automatically muted when a client connects to a server.
