### ISSUE TITLE
Jitter Buffer Auto settings low ?

### ISSUE THREAD

**Issue by frankyfranks** [corrados/jamulus#757]
When setting the jitter buffer to auto I regularly get buffer alerts, (light flashes red). This often coincides with a small blip on the audio quality. To overcome this I connect to a server using the auto jitter buffer, let it settle for 20-30 seconds then manually increment the jitter buffers to +2 or 3 on both the client and server. This normally stops the jitter light from flashing red and I rarely get audio blips/glitches.
I know there is a trade off in increased latency but as long as the server has good overall delay then manually increasing the jitter buffer gives me good audio quality.
For me it's no issue to change the jitter buffer settings. However with a choir of non-technical users changing any setting in Jamulus can be challenging, the users want plug and play as much as possible.
Is it possible to have 2 or 3 options on the auto jitter buffer? For example;-
1. auto jitter buffer - minimal delay
2. auto jitter buffer - normal
3. auto jitter buffer - extended buffer

Many thanks to all for this great software !!

**Comment by corrados** [comment]
This seems to be a duplicate. We already have covered this topic here: https://github.com/corrados/jamulus/issues/417, do you agree?

**Comment by DavidSavinkoff** [comment]
I think this is very similar to #417 .  I think a simple solution to this is to optionally enforce a minimum buffer size to the auto jitter buffer at the client side. eg. buffer cannot go below a set minimum. (maybe a maximum also)

**Comment by frankyfranks** [comment]
> This seems to be a duplicate. We already have covered this topic here: #417, do you agree?

corrados thanks for the prompt response. Yes it does seem the same issue, sorry I missed that topic in my search.
I'm using the latest client and server version 3.6.1 so the issue (at least in my setup) still prevails.

**Comment by corrados** [comment]
Ok, so let's close this one and continue the discussion in the existing Issue #417.
