### ISSUE TITLE
Don't encode audio and use P2P for lower latency

### ISSUE THREAD

**Issue by Zipdox** [corrados/jamulus#758]
Would it be possible to not encode the audio and send it raw to reduce the latency even more on high bandwidth networks? And what about using a peer-to-peer system instead of a client-server system, wouldn't that reduce latency further, as well as eliminate the bandwidth requirement for the server? This system would only use the server for peer lookup.

**Comment by pljones** [comment]
You mean, not be Jamulus?

**Comment by gene96817** [comment]
@Zipdox    Give JamKazam for a peer-to-peer experience. It has serious scaling challenges. We can discuss offline.

**Comment by corrados** [comment]
> Would it be possible to not encode the audio and send it raw to reduce the latency even more on high bandwidth networks?

The coding delay of the OPUS codec is so low that you can ignore this additional delay compared to the delay introduced by the ping time and the jitter buffers.

> what about using a peer-to-peer system instead of a client-server system

As mentioned above, the client-server concept is a fundamental design decision for Jamulus. If you want to try out a peer-to-peer solution, you could use JamKazam, Jack-Trip or Soundjack.

**Comment by Zipdox** [comment]
> @Zipdox Try JamKazam for a peer-to-peer experience. It has serious scaling challenges. We can discuss offline.

It's proprietary and doesn't run on Linux.

**Comment by Zipdox** [comment]
> As mentioned above, the client-server concept is a fundamental design decision for Jamulus. If you want to try out a peer-to-peer solution, you could use JamKazam, Jack-Trip or Soundjack.

JamKazam is not an option and I'm unable to actually Find a Soundjack download. What would really be great is a system that uses peer-to-peer connections for transferring audio and a central server only for peer discovery and for serving metadata.

**Comment by corrados** [comment]
Interesting that there is no Soundjack download. I guess you have to register to get the software. A long time ago one could simply download the software. That seems to have changed recently.

No plans for Jamulus to support peer-to-peer connections. But there is a new Open Source project from HPS, the [HPSJam software](https://github.com/hselasky/hpsjam). You might want to ask HPS if he will support peer-to-peer in his software. He is very actively developing the software right now.

**Comment by Zipdox** [comment]
Interesting. I'll look into it.

**Comment by corrados** [comment]
You could also have a look at this project: https://github.com/essej/sonobus

**Comment by Zipdox** [comment]
> You could also have a look at this project: https://github.com/essej/sonobus

Oh my god SonoBus is exactly what I was looking for! It even has FX, metronomes and stuff. Thanks!

**Comment by corrados** [comment]
Ok, so I think we can close this Issue now, because:

- Don't encode audio

This is already covered by https://github.com/corrados/jamulus/issues/516

and for

- use P2P for lower latency

you can use SonoBus.
