### ISSUE TITLE
Nice to have: Hungarian translation

### ISSUE THREAD

**Issue by dyeopensource** [corrados/jamulus#760]
Hi, it would be nice to have a Hungarian translation of the UI and also for the setup instructions. I already started to create it here: https://github.com/dyeopensource/jamulus

**Comment by corrados** [comment]
Great, thanks. We have a common Issue for the translations which is: https://github.com/corrados/jamulus/issues/77. So let's continue the discussion on that Issue and I will close this one.

**Comment by dyeopensource** [comment]
OK, thx.
