### ISSUE TITLE
[Feature] More Vocal options for Choir down the intstrument profile in My profile

### ISSUE THREAD

**Issue by ann0see** [corrados/jamulus#772]
Originally written by @Sollenberg72 

*Moved from website repo: https://github.com/jamulussoftware/jamuluswebsite/issues/150*

**Describe the solution you'd like**
In a choir you have more different vocal options than in traditional barbershops (Soprano, Alto, Tenor and Bass). We have two options for Alto and Soprano = Alto 1 and Alto 2 and Soprano 1 and Soprano 2. This helps us to create groups in Jamulus and use the panorama button so that we can create the same feeling as in the room You stand in reality.

**Describe alternatives you've considered**
We want more choices under the menu for instruments for us who use Jamulus for our choir rehearsals. Today there is singing in the form of Soprano, Alto, Tenor and Bass. We need to divide Alto and Soprano respectively into Sopranos 1 and 2 and Alto 1 and 2, as there are divided parts in a choir.

**Additional context**
Vocal (soprano)
Vocal (soprano 1)
Vocal (soprano 2)
Vocal (alto)
Vocal (alto 1)
Vocal (alto 2)

I think soprano and alto without division need to remain for those who do not divide soprano and alto parts into 1 and 2 respectively

**Comment by ann0see** [comment]
Originally written by @gene96817 

For complete support of a classical chorus, this should be extended for Tenor1, Tenor2, Bass1, and Bass2.

**Comment by pljones** [comment]
The general guidance for choirs is for each participant to prefix their name with their voice range, so S1-name, A2-name, etc.  That then allows the mixer to be sorted by name, making it easy to use the grouping feature.

**Comment by ann0see** [comment]
Why should we maintain a never ending list of instruments, musicians,...?
It is already too long in my opinion (and finding the right one becomes increasingly difficult).
Couldn't we just allow the user to input custom text (for his instrument) and add an option for him to load a bulk list of instruments & pictures?

Then we could remove a lot of not widely used instruments but allow the user to load them from a list (published e.g. online) if he wants more instruments. If a user has set an instrument your client doesn't know, it should show the name and propose to load/set an icon you either download from the web or set from your hard disk.

**Comment by corrados** [comment]
> Couldn't we just allow the user to input custom text

This instruments are transmitted in the protocol with an index. So it is not possible to use a free text.

I agree with pljones. If you want to distinguish the vocal groups further, you should do it using the name. If you are on Facebook, I can recommend the following group: https://www.facebook.com/groups/jamuluschoralcommunity. There is a lot of information given how to deal with a lot of users connected to a Jamulus server.

**Comment by gene96817** [comment]
In general, I agree with ann0see. To manage the list size, some generic types are needed to catch the less common variations (example: wind, brass, percussion). In the case of voice types, going from X (eg. Alto) to X1 and X2 is not comprehensive because some compositions might have a third or more part. This problem mostly occurs with large ensembles.

**Comment by pljones** [comment]
> In the case of voice types, going from X (eg. Alto) to X1 and X2 is not comprehensive because some compositions might have a third or more part. 

The idea is expandable.  You just take the number at the end and add one to it to get the new number.

**Comment by gene96817** [comment]
Of course the numeration is expandable. I thought ann0see was concerned that the list is getting too long. There is wisdom to avoid making the list longer and longer.

**Comment by ann0see** [comment]
> ann0see was concerned that the list is getting too long

Yes, I am

**Comment by pljones** [comment]
> Of course the enumeration is expandable. I thought ann0see was concerned that the list is getting too long. There is wisdom to avoid making the list longer and longer.

The suggestion is not to change code.

The suggestion is to use the existing features of the software.

**Comment by gene96817** [comment]
@pljones   I am not following you. Do you mean users should prepend their names with a voice-part prefix? I don't think this is what you mean. Do you mean users can add their own voice-part to the list? This is how I think you mean no change to the code is needed. Is this case is this interoperable between user communities. For interoperability, the code's internal enumeration needs to be universally unique. I suspect I am now far from your intent.

**Comment by pljones** [comment]
> I don't think this is what you mean.

Why don't you think so?  It's _explicitly_ what I said.

> Do you mean users can add their own voice-part to the list?

No.  Why do you think I might have meant that?  There's no such facility.  I wouldn't suggest using a facility that doesn't exist when explaining that no change is needed.

> For interoperability, the code's internal enumeration needs to be universally unique. I suspect I am now far from your intent.

"Interoperability"?  I don't follow.  Seeing what part a singer is singing isn't about interoperability.  It's about labelling.  The user's name is a label.  The client can sort by name.  So you can group all your sopranos, altos, tenors, horn and key players together really, really easily.

**Comment by gene96817** [comment]
@pljones Thanks for the reply. We aren't communicating. There are things you are saying that doesn't make sense to me. That is because I don't completely know what are "existing features" you specifically mean. It doesn't matter.

**Comment by corrados** [comment]
> Why should we maintain a never ending list of instruments, musicians,...?

What do you mean by "musicians"? We are talking about the instrument type, right?

> It is already too long in my opinion (and finding the right one becomes increasingly difficult).

The instruments have already assigned a type internally. So it would be relatively easy to introduce a sub-group to the instrument list in the GUI which makes it much easier to select the correct instrument.

**Comment by gene96817** [comment]
Introducing a sub-group sounds like a great idea. There is not much impact if it is just an ephemeral label for the session. (eg. Violin-1, Violin-2, Vocal Alto-1, Vocal-Alto 2, etc.).

**Comment by corrados** [comment]
BTW, the text background of the instruments in the combo box are already color coded by the type of instrument:
![grafik](https://user-images.githubusercontent.com/46655886/103822348-3d4dcc00-5070-11eb-823c-3c9ab23b36f8.png)
So, e.g., if you search for a string instrument, you can only look at the light blue entries.

**Comment by corrados** [comment]
As pljones already mentioned in his post (https://github.com/corrados/jamulus/issues/772#issuecomment-740213960), the preferred way of doing this is to add a prefix to the user name. So I would like to close this Issue now. Any objections?

**Comment by ann0see** [comment]
Ok. To unclutter the issues list, I think we can close this as wontfix
