### ISSUE TITLE
Delete the wiki content and point to jamulus.io

### ISSUE THREAD

**Issue by trebmuh** [corrados/jamulus#776]
If I'm not wrong (please correct me if so), the wiki manual here is now superseded by the jamulus.io content.
We should then delete the wiki content here and put a:
> This wiki moved to https://jamulus.io/

(_originates from https://github.com/jamulussoftware/jamuluswebsite/issues/167_)

**Comment by ann0see** [comment]
Do you mean https://github.com/corrados/jamulus/blob/master/src/res/homepage/manual.md?

I would not remove https://github.com/corrados/jamulus/wiki since it will break a lot of links on other websites.

**Comment by trebmuh** [comment]
Here is the general idea:

It seems to me that the wiki pages from here were used a starting point for jamulus.io . If jamulus.io is the future of Jamulus documentation, then it would be counterproductive to keep the wiki pages here because Jamulus.io is updated and improved. Therefore the wiki pages here will gradually become outdated. We should therefore consider deleting them so that users do not use the pages here, but the jamulus.io page which are the most up-to-date documentation.

If deleting completely the pages here is a problem for a reason or another, then probably a link to jamulus.io (or even automatic redirection if possible) is a good solution.

**Comment by ann0see** [comment]
> then probably a link to jamulus.io

That's what @gilgongo already did? Not for the software manual, but for the rest.

I don't know if it's possible to make a real redirect to jamulus.io

**Comment by gilgongo** [comment]
> That's what @gilgongo already did? 

Correct (unless I missed something?). 

However, we do need to deal with https://github.com/corrados/jamulus/blob/master/src/res/homepage/manual.md so I'll raise a ticket on that.

**Comment by gilgongo** [comment]
Done. Closing this as duplicate. 

https://github.com/corrados/jamulus/issues/779

**Comment by trebmuh** [comment]
> > That's what @gilgongo already did?
> 
> Correct (unless I missed something?).

Nope: https://github.com/corrados/jamulus/wiki

**Comment by trebmuh** [comment]
My mistake, I didn't realise that @gilgongo had already done the job here.
Thanks for that.
