### ISSUE TITLE
Retire manual.md

### ISSUE THREAD

**Issue by gilgongo** [corrados/jamulus#779]
The content of the [manual in the repo](https://github.com/corrados/jamulus/blob/master/src/res/homepage/manual.md) is now out of date. The updated one now [lives on jamulus.io](https://jamulus.io/wiki/Software-Manual). There were various reasons for this, but mainly it gives us the ability to translate it, more control on layout, and there might be some SEO benefit if anyone links to it.

I propose we:

1. Replace the link in Jamulus's help menu to point to the new one (the same goes for Getting Started I think but I'll check).

2. Replace the current content with a message saying it's moved.

If that's OK I'll open a PR.

**Comment by ann0see** [comment]
It would be great if the URLs in Jamulus would be translatable. See

https://github.com/corrados/jamulus/pull/780#discussion_r541658370

**Comment by gilgongo** [comment]
Merged so closing thanks all.

**Comment by trebmuh** [comment]
@gilgongo: am I right in understanding that the link to the manual is not translatable in the current state? If so, could you please make it so?

**Comment by gilgongo** [comment]
By "translatable" in this context (that is, the now retired [manual.md file here](https://github.com/corrados/jamulus/blob/master/src/res/homepage/manual.md)) what do you mean exactly?

**Comment by ann0see** [comment]
No. 

If Jamulus is set to English, the link to the software manual and website should be to the English site.
If Jamulus is set to Spanish, the link to the software manual and website should be to the Spanish site.
If Jamulus is set to German, link to German.
If Jamulus is set to Portuguese, (since we don't have a Portuguese translation yet) link to the English site.

**Comment by trebmuh** [comment]
I mean that the:  `#define SOFTWARE_MANUAL_URL              "https://jamulus.io/wiki/Software-Manual" ` line would present the "https://jamulus.io/wiki/Software-Manual" link into the .po file.

That way, as an example, the French GUI translator will be able to "translate" it to "https://jamulus.io/fr/wiki/Software-Manual" in the fr.po file, and then, users with a French locale will have a direct link to "https://jamulus.io/fr/wiki/Software-Manual".

**Comment by gilgongo** [comment]
Oh OK. I was confused as this ticket is simply about the EN and ES files in the software repo (it's a very minor thing, since less than 5% of Jamulus users would ever see the English one there, let alone the Spanish). 

If you mean the Jamulus application itself, I don't know how to to that I'm afraid. But I'm sure somebody else does :-)

**Comment by trebmuh** [comment]
> If you mean the Jamulus application itself

Yes, I mean in the GUI translation itself.
@corrados can you please have a look to this?
