### ISSUE TITLE
Increase "stability" of Connection Setup server list

### ISSUE THREAD

**Issue by corrados** [corrados/jamulus#78]
This issue has been migrated from Sourceforge. Created: 2020-04-06

One of the most irritating parts of using Jamulus is trying to click on the server you want to join, now the number of servers has increased so much.

The current behaviour appears to be as follows:
1. Sort the list by ping time, smoothing this over some period (as it stabilises with time)
2. Each time the number of musicians on a server changes, pop open the display

Between the two, with people joining and leaving servers that have very similar ping times - about 20 in or around London - it means you can very easily start a click with the pointer over one server and end up joining a different one.

So...
1. The smoothing algorithm could be improved - don't change the "sort ping" more often than once every 10 seconds or something
2. Also, if I've chosen not to display the musicians on a server, it means I don't want to display the musicians on that server, so don't pop open the list of musicians on that server again (at least for 30 seconds maybe 2 minutes).

That should help keep usage a bit smoother without losing the information that's displayed.
Discussion

    Volker Fischer - 2020-04-06

As a quick workaround you could start Jamulus with --showallservers. This list is sorted by the registration time and does not change at all.
      

    Volker Fischer - 2020-04-06

> Also, if I've chosen not to display the musicians on a server, it means I don't want to display the musicians on that server, so don't pop open the list of musicians on that server again (at least for 30 seconds maybe 2 minutes).

 Agreed, that was a bad behavior. I fixed that:
https://github.com/corrados/jamulus/commit/70c499a82a76f62377ed80e95d99841562fac3c4
Can you please test this new version if you are happier with the behavior?

**Comment by pljones** [comment]
That does make it much better.  The only thing is that the "show all musicians" could do with being stored for the user.

**Comment by corrados** [comment]
Yes, I think that would be beneficial. I agree with you. I'll write it on my list.

**Comment by pljones** [comment]
Ooh!  Bug!

Start up the new version with the Connection Setup showing.  "Show all musicians" is on (as I say).  Switch it off before the list is displayed.  The checkbox is off - but the list displays all musicians!

**Comment by corrados** [comment]
Ok, I'll write that on my list, too :-).

**Comment by corrados** [comment]
Other than the storing of "Show Musicians" setting and the bug, you are now happy with the implementation? If yes, I would close this Issue then.

**Comment by pljones** [comment]
Yes - I wasn't seeing the ping time sorting problem as much when the musicians lists were closed.

(It would jump six or ten lines or more sometimes and you'd not find the server, because the list had opened then the ping times changed, etc.  And because there have been so many servers near me in London, it's been particularly bad.  Keeping the musicians lists closed means it's only the ping time reordering and that tends to only move by one or two lines and settles down.)

**Comment by corrados** [comment]
Ok, thanks for the feedback -> closed.
