### ISSUE TITLE
Intentional line wrap in jamulus.service file?

### ISSUE THREAD

**Issue by chrisrimple** [corrados/jamulus#783]
**My jamulus.service file has this line...**

`ExecStart=/usr/local/bin/Jamulus --server --nogui --centralserver jamulusallgenres.fischvolk.de:22224 --serverinfo "School of Rock WS;Seattle, WA;225" --welcomemessage "<h1>School of Rock West Seattle Jamulus Server</h1><p>This server is primarily for <b>School of Rock West Seattle</b> students, but is also open for public use. It is often busy with band rehearsals on Wednesdays, Fridays, and Sundays 6-9pm PST (UTC-8). <b>Recordings are enabled on this server and are automatically deleted after 24 hours</b>. It is hosted at Vultr.com in Seattle, WA, USA by Chris Rimple. Please contact chrisrimple@yahoo.com with questions.</p><p>For general information about Jamulus and Jamulus resources, see the Remote Band Rehearsals document:</p><p><a href="https://docs.google.com/document/d/1smcvsxdaaViPQvGMQHmah_6BQeqowhmGSFMHfnlY2FI/">https://docs.google.com/document/d/1smcvsxdaaViPQvGMQHmah_6BQeqowhmGSFMHfnlY2FI/</a></p>" --numchannels 20 --fastupdate --recording /var/jamulus/recording/`

**Is there a way to add intentional line wraps that won't break it, so it's formatted like...**

ExecStart=/usr/local/bin/Jamulus 

--server 

--nogui 

--centralserver jamulusallgenres.fischvolk.de:22224 

--serverinfo "School of Rock WS;Seattle, WA;225" 

--welcomemessage "School of Rock West Seattle Jamulus Server..." 

--numchannels 20 

--fastupdate 

--recording /var/jamulus/recording/

**In that way, adding or removing a single command line parameter is easier.**

**Comment by kwindrem** [comment]
end each line with a back slash e.g,:

ExecStart=/usr/local/bin/Jamulus\
--server\
-nogui\
--centralserver  jamulusallgenres.fischvolk.de:22224\

The last physical line must not end in backslash

I made my .service file call a shell script which makes it easier to maintain since you don't need to do a

sudo systemctl daemon-reload

after a change

**Comment by chrisrimple** [comment]
Excellent, thanks.  Closing this issue.
