### ISSUE TITLE
UI/UX Contributions

### ISSUE THREAD

**Issue by mulyaj** [corrados/jamulus#787]
Hi there, 

Have there been any plans/ideas on implementing design contributions? I'd be interested in approaching solutions from a UX (user research/testing) perspective.

**Comment by ann0see** [comment]
I assume this is related to https://github.com/corrados/jamulus/issues/596#issuecomment-746043121?

I'd be happy if we had a look at the website jamulus.io and do a few (design) improvements. The repo is https://github.com/jamulussoftware/jamuluswebsite/

Sure, the software Jamulus can and in my opinion should also be tested

**Comment by mulyaj** [comment]
Yes this is related to @erioldoesdesign's comment.

@ann0see I'll take a look at the website repo. 

Is there currently a platform for more informal discussion on proposed changes and development?

**Comment by ann0see** [comment]
> I'll take a look at the website repo.

Great!

> Is there currently a platform for more informal discussion on proposed changes and development?

Yes, there are the [discussion forums on SourceForge](https://sourceforge.net/p/llcon/discussion/)

and a Facebook group. Nevertheless, I think that GitHub is the place where changes are discussed.

**Comment by gilgongo** [comment]
@mulyaj @Erioldoesdesign 

I think this depends on what you mean by UI/UX exactly. 

There are certainly a number of "cosmetic" improvements that could be made to Jamulus and its related applications such as the website and satellite projects (https://explorer.jamulus.io, https://lounge.jamulus.io) (see also https://github.com/corrados/jamulus/issues/73)

At a deeper level, there is as you imply probably a need to review the UI itself against the expectations of new and exiting users with a view to making improvements. That is obviously a much bigger undertaking, and in my opinion would probably require a fork of Jamulus to do properly, since the nature of the changes that might come out of such research would probably be too large to cope with in the current architecture. But I'm really just guessing at that. 

If there are some number of people interested, perhaps it would be best to form a "working group"  of some kind to discuss how we might proceed, audit the skills available and generally sort out what think we might be able to contribute? 

Put is this way: working on open source UI is not a trivial undertaking :-)

**Comment by ann0see** [comment]
As far as I understand, UX != "fancy gui". It's more about ease of use, etc. So it would involve e.g.

1. How can we make the onboarding easier (Get rid of SmartScreen, Gatekeeper, ASIO4All (or at least make it easier for the user to setup), make Jamulus a "one click" application, allow users to just click on a link to join a server,...)
2. How can we be more visible on the web (SEO).
3. etc.

**Comment by gilgongo** [comment]
@ann0see Yes, I think if we were to conduct research of some kind, then I would expect on-boarding to be a major factor, but we might also uncover other issues along the way. Such research would involve some planning though.

I'm not sure how SEO comes into this exactly, but we can discuss.

So in general, how best to start this all off? Would it be good to get together on a call first to discuss things in general? Let's see what the others say.

**Comment by ann0see** [comment]
> Would it be good to get together on a call first to discuss things in general?

Not sure if a call is the right thing (who would participate? Would we use a Jamulus Server everybody can join?)

**Comment by mulyaj** [comment]
> @mulyaj @Erioldoesdesign @geheimerEichkater
> 
> I think this depends on what you mean by UI/UX exactly.
> 
> There are certainly a number of "cosmetic" improvements that could be made to Jamulus and its related applications such as the website and satellite projects (https://explorer.jamulus.io, https://lounge.jamulus.io) (see also #73)
> 
> At a deeper level, there is as you imply probably a need to review the UI itself against the expectations of new and exiting users with a view to making improvements. That is obviously a much bigger undertaking, and in my opinion would probably require a fork of Jamulus to do properly, since the nature of the changes that might come out of such research would probably be too large to cope with in the current architecture. But I'm really just guessing at that.
> 
> If there is some number of people interested, perhaps it would be best to form a "working group" of some kind to discuss how we might proceed, audit the skills available and generally sort out what think we might be able to contribute?
> 
> Put is this way: working on open source UI is not a trivial undertaking :-)
> 
> PS: Over the last 9 months from my own "observation" of issues on the forums and elsewhere, I've formed some hypotheses around user behaviour and created some prototype sketches of what a (possibly more usable) Jamulus UI might look like. I've not yet shown them here though because I'm still evaluating them against issues I see come up. The audience for Jamulus is still rather small and it's hard to know what the core demographic really is.

Yes, that is generally what I mean. I'd be good to get in a group to discuss this.

**Comment by gilgongo** [comment]
OK so we could get together on a Jamulus server and talk a bit about it. I'm in London and am pretty flexible time-wise. Let's see what other say, although we are coming up to holiday time too.

@ann0see Those tagged on this ticket are probably the best to attend at first, since this would just be an "orientation" meeting. We could do more formal stuff with more people later perhaps.

**Comment by Erioldoesdesign** [comment]
Hi hi folks! wow! in all my time as a designer in OSS I've never seen such an enthusiastic discussion thread! so cool!

Just so y'all know i'm helping @mulyaj with this OSS design contribution effort so I'm here to support them as a Designer that's been doing OSS-y stuff for a while so I'll be helping out from that perspective. I'll join calls and read threads and support them as much as possible. It's tough being a designer in OSS first time 😄

**Comment by gilgongo** [comment]
Thanks @Erioldoesdesign! And good to know you've got some OSS experience. This is the first time I've contributed to OSS and you're right, it's pretty tough compared to commercial practice!

@geheimerEichkater is the effective brand director for the project though so we need to keep him in the loop. Let's wait to see if he responds.

**Comment by geheimerEichkater** [comment]
Hello to this round. Very honored to be considered the brand director ^^
I´ll help out as much as possible. I've privately had my fair share of questions and thoughts and couple mockups mainly about the actual UI of the app itself (and the underlying wireframe, happy to see @gilgongo also went for it), not so much about the over all UX yet, but I'm curious to see how we take it to the next step. Are we tackling UI and UX at the same time?

**Comment by gilgongo** [comment]
Hi @geheimerEichkater !

> Are we tackling UI and UX at the same time?

I think because this is the first time some of us connected with the project from a design perspective have "met" as it were, we can look at both at first as part of an initial "orientation" discussion. I'm probably most interested at this stage to get a feel for our collective interests, resources, availability etc. (particularly if we might be thinking of doing research). We can then think about how we might go about a more coherent design "strategy" based on that perhaps?

**Comment by corrados** [comment]
Is this Issue then related to this existing one: https://github.com/corrados/jamulus/issues/73?

**Comment by gilgongo** [comment]
It may well be :-)

**Comment by ann0see** [comment]
I will have some time in the next week(s). We could get into a call/meeting after Christmas?

I’m trying to onboard a choir next year, so I can help out with research

**Comment by mulyaj** [comment]
That sounds like a good idea. What date would be good for you?

**Comment by ann0see** [comment]
Depends on all the others. I'm quite flexible at the moment.

**Comment by gilgongo** [comment]
I'm going to be a bit tied up from the 28th for a week or so unfortunately, but I can have a go at suggesting some agenda points that can agree on in the meantime. Are will all in European time zones? If, so then how about Weds 30th in the evening?

**Comment by ann0see** [comment]
> I'm going to be a bit tied up from the 28th for a week or so unfortunately

Ok, yes, the 6th should work. (Although I'd also have time from now on).

>  Are will all in European time zones?

I live in CET.

> Maybe we should just keep it pretty broad for now? [...]

A few things could also be discussed or at least mentioned here (probably smaller points).

The talk should then go into more detail.

So we will focus on:

1. User experience issues
2. Graphical design aspects

?

**Comment by mulyaj** [comment]
I'm from Canada in EST.

 I think we should look at our overall strategy.

- Which users are we designing for (Designing for beginners vs experts will have differing outcomes)
- Scope of the project 
- Possible timeline(s)?

With the strategy in mind, defining the specific UI issues and graphics problems would be a lot easier.

**Comment by gilgongo** [comment]
EST makes it a bit trickier, but with those time zones it looks like an EST time of between maybe 12:00 to 2:00pm would be best as that would be early [evening in the other zones](https://www.timeanddate.com/worldclock/meetingtime.html?day=6&month=1&year=2021&p1=136&p2=250&p3=48&iv=0).

**Comment by mulyaj** [comment]
Early afternoon (your evening) works for me.

**Comment by Erioldoesdesign** [comment]
Hey folks! as someone helping out with this totally keen to come to the meeting on the 6th. I can only do these times though:
<img width="338" alt="Screenshot 2020-12-28 at 15 42 31" src="https://user-images.githubusercontent.com/11681324/103226149-5c878380-4923-11eb-9bf7-38d0ff3e9854.png">
<img width="333" alt="Screenshot 2020-12-28 at 15 42 36" src="https://user-images.githubusercontent.com/11681324/103226150-5db8b080-4923-11eb-8b8e-075bc60c74aa.png">

I'll mostly be providing back up to @mulyaj if needed

**Comment by gilgongo** [comment]
So shall we try for 12:00 Toronto time (so 17:00 in UK and 18:00 Brussels?) on Wed 6th Jan?

**Comment by Erioldoesdesign** [comment]
Sounds great! my email is erioldoesdesign@gmail.com for calendar invites. I have a whereby room that i use for calls but also happy using jitsi or zoom etc.

**Comment by ann0see** [comment]
Jitsi would be simplest (if we need video)

**Comment by corrados** [comment]
I am curious: What will be the outcome of this procedure? Is it a new skin (see https://github.com/corrados/jamulus/issues/73) or a complete redesign of the GUI? Are you aiming a Jamulus fork or is it more related to this one: https://github.com/corrados/jamulus/issues/472?

**Comment by mulyaj** [comment]
Currently from our discussion in this thread, we are probably looking to make changes to the GUI; as @gilgongo discussed above a fork will probably be needed.

**Comment by ann0see** [comment]
I would only see a fork as the last resort. In my opinion we should focus on improving Jamulus. That's just my opinion.

**Comment by gilgongo** [comment]
@corrados I think this is really just an initial discussion about experience design issues (both visual and non-visual) to see what we might be able to do. I don't think there's going to be necessarily a specific outcome other than just getting "aligned" on what we think the priorities are and maybe agreeing on some preliminary stuff. Various things (skin design, site design, overall UI, user research, forks, target audiences...) have been mentioned, so there might be a number of things we could do.

**Comment by ann0see** [comment]
Feel free to update following list: 

# Design changes
[] Update chat message design #632 
[] New Skin for Jamulus #73

**Comment by Erioldoesdesign** [comment]
Seconding/+1-ing @gilgongo If we can approach the meeting on the 6th as an initial discussion around what we think needs improvement and design investigation from both a visual and non-visual perspective that way scope and skills match can be better understood and there's a good chance of capturing other design issues for other OSS designers of the future.

😄 most designers have a 'specialism' (or they're a generalist like me!) but capturing and understanding what the OSS needs on a broader scale could help towards sustainability of both tool and community.

Stopping before I get to long-winded and rambling.

**Comment by ann0see** [comment]
Ok. So how will the meeting look like tomorrow?
Which software will we use? I'd suggest Jitsi Meet

Content:
My proposal:

1. Short introduction: (I suggest especially @mulyaj and @Erioldoesdesign to explain what/how they can contribute)
2. Presentation of current design issues
2.1 Discussion of design issues of the Jamulus Software (We should document them somewhere)
2.2 Discussion of design issues of jamulus.io
3. Discussion of solutions

Any comments?

**Comment by mulyaj** [comment]
The first proposal sounds great!  

To add, we could also discuss ideas on how to best incorporate design into the current workflow.

**Comment by Erioldoesdesign** [comment]
looks great to me @ann0see let us know what jitsi link we'll be using tomorrow :)

**Comment by ann0see** [comment]
Not sure if we can use https://jitsi.debian.social/JamulusUIDiscussions20210106

**Comment by Erioldoesdesign** [comment]
**Notes from the Jitsi call on 6th of Jan 2021**

**Short introduction:** 
(I suggest especially @mulyaj and @Erioldoesdesign to explain what/how they can contribute)

- Quick rounds of intros :)

- What do this group want to work on.
- Github issue template for design issues.
- Create a board of design ideas and issues.

**Presentation of current design issues (do we already have a list of this?)**
- Some design issue already but mostly in heads.
- Best ratio between design satisfaction & dev possibility is 'the skin' a 'brittle template'. Visual design of it would be improved. #73 
- Windows on-ramping: setting up audio interfaces etc.
- Can an epic be created around #73 that has research and testing and visual design.

**2.1 Discussion of design issues of the Jamulus Software (We should document them somewhere)**
- We didn't get to here yet :)

**2.2 Discussion of design issues of jamulus.io**
- We didn't get to here yet :)

Discussion of solutions
- We didn't get to here yet :)

Other notes:
- Jordan has direct access to usertesters from the music uni course!
- What are the structures of governance, what is worked on, why and how?
- Google form survey from Jonathan.
- Large design changes and forks. Re. new skins
- Looks like a mixing desk so some people expect that! 

**Theres a few actions (I think I captured them all?)*

- Create a board of issues that designs have noticed could be improved
- Create a place for user insights to go to be accessed - maybe a wiki?
- Consider an epic for issue #73 but check in with devs and the wider OSS team to see what they think.

**Comment by mulyaj** [comment]
Hi everyone, I've come up with a [Trello board](https://trello.com/invite/b/2fgE3IW4/1892c949ca876db72841afc3d34a6c0f/jamulus-ux-ui that we could possibly use for organizing our design goals. 

To explain the board, as a team we can define current issues (and future/potential issues) into an overall project. Within the project, user research should then be conducted to support the design decisions that are made. In reference to #73 as @Erioldoesdesign mentioned, we could get into a call again to discuss how we could implement this issue into an epic.

Let me know your thoughts!

**Comment by geheimerEichkater** [comment]
Thanks for organizing the board, I've joined. Curious where the next call will lead us, how to tackle progress. Is there any tendency as to when the next call could take place?

**Comment by mulyaj** [comment]
I'm available at the same time this week - we will probably have to check with the others.

**Comment by Erioldoesdesign** [comment]
I don't think I'm free next week at the same time but I think you folks got this 💪 I'll be around to support if y'all need it!

**Comment by geheimerEichkater** [comment]
Are we on tonight in app half an hour?

**Comment by ann0see** [comment]
If I find time (not too likely) I might be able to join.

**Comment by ann0see** [comment]
Ok. I would have time now. Not sure about others.

**Comment by mulyaj** [comment]
My bad, I didn't think we were going meet today. 

Can we meet tomorrow or the day after at 17:00 GMT?

**Comment by ann0see** [comment]
I wasn't online either. Tomorrow should work.

**Comment by mulyaj** [comment]
Hey everyone, @ann0see and I are currently in call right now. 

https://jitsi.debian.social/JamulusUIDiscussions20210106

**Comment by ann0see** [comment]
Notes from the Jitsi call on 14th of Jan 2021

* Added a few open design issues to the Trello board 
* We're now thinking of doing further research; @mulyaj already has a google document with his findings
* We're thinking of implementing Slack or GitHub discussions for easy communication. Designers were invited to the jamulussoftware organisation
* @mulyaj proposed to structure the process in 3 (sub) projects (starting with smaller contributions like the installer graphics [Who does this? @geheimerEichkater ?])
* Short introduction to git and GitHub

There are probably some other open points I can't remember.

**Comment by dcorson-ticino-com** [comment]
I see I should be looking more deeply into this board more often.  I have been thinking about how to improve the UI for a while and missed out that you are working on that here.  I have been helping several groups getting on board and heard several comments repeatedly such as it is not visible when one should expect not to hear any sound.  Having two level meters for oneself also threw several people.  

When pljones recently encouraged me to start programming I decided to make a "better" UI as an exercise before trying to be useful.  The results are at repo dcorson-ticino-com/jamulusUI-01 (assuming my use of git has worked out correctly).
My design guidelines were: -visually separate local from remote (local in horizontal band at top) -give visual clues what is happening -make connect prominent -keep the Jamulus DNA mixing table unchanged.

All this does not, however, help at all for the nr1 problem that almost every new user has had, that is setting the input level correctly.  They always set the volume way too soft, or way too loud and then complain that Jamulus has bad sound quality when the sound clips and causes distortion.  I think we need to find a way to help people with this, maybe a wizard?  One thing is for sure, people don't read what has been written as a guide and if they do, they don't believe it.
Don

**Comment by ann0see** [comment]
Great! I'll add you to the jamulussoftware/designers team so that we can maybe add you to one of our next calls and talk about your proposals.

**Comment by corrados** [comment]
Please consider the following new Issue: https://github.com/corrados/jamulus/issues/899 in your discussions.

**Comment by ann0see** [comment]
Since we now have a GitHub discussion in the organisation, can we close this issue now?

**Comment by corrados** [comment]
I have no objections.

**Comment by ann0see** [comment]
Closed now since we have another communication channel.
