### ISSUE TITLE
problem with alesis io2 and Jamulus in Mojave and Catalina

### ISSUE THREAD

**Issue by Yostap** [corrados/jamulus#788]
Hy,

I've a weird bug which appeared on Mojave on my Mac mini and which is still there on Catalina using Jamulus 3.6.2 and alesis io2.

It seems that Alesis is class compliant and i don't need specific drivers.

The VU meter leds goes yellow or red on my alesis io2 indicating that there are inputs but the input VU meter on Jamulus does not activate. I can hear every one else on the Jamulus server but nobody hear me.

My sound card works nicely with Logic and skype but when i run Jamulus i have no inputs ...

I'm perhaps missing something but there seems to be a bug somewhere ...

Any help is welcome !

**Comment by chrisrimple** [comment]
On the Jamulus Settings screen, when you click the Device dropdown, do you see "in:iOS2" listed?  It sounds like the answer is "no".  If no, then Jamulus isn't seeing it as a device (but apparently Logic is).

Run the app Finder > Applications > Utilities > Audio MIDI Setup.  From the Window menu, choose Show Audio Devices.  Do you see the iO2 listed on the left?  If not, then the Mac isn't seeing it as an audio device.  If it is listed, click it and check the settings on the right.  Does anything look wrong?  Ensure that Format = 48KHz.

Can you post a screenshot of the Jamulus Settings window with the Device dropdown expanded, and of the Audio MIDI Setup window?

**Comment by Yostap** [comment]
Thank you for your help, chrisrimple, it seems I have  no problem in the  Jamulus setting screen, io2 is listed
And I see nothing wrong with the audio midi setup, io2 is also listed, and the format is 48khz
I show you

![Capture d’écran 2020-12-19 à 18 56 42](https://user-images.githubusercontent.com/76255874/102696099-231c8d00-422c-11eb-95b3-9d46df5a72e3.png)

![Capture d’écran 2020-12-19 à 18 55 40](https://user-images.githubusercontent.com/76255874/102696111-329bd600-422c-11eb-93ae-896c72ba2e85.png)

**Comment by chrisrimple** [comment]
@Yostap In your screenshot of Audio MIDI Setup, I see that Flux Principal = 0%.  Any way to get that to 100% for Entree and Sortie?  Perhaps it's tied to your Apple > System Preferences > Sound settings?

Also, after selecting "in:io2/out:io2" in Jamulus, what channels do you have selected for Input and Output?

**Comment by drummer1154** [comment]
@chrisrimple 

>  Flux Principal = 0%. Any way to get that to 100%

No way, this only means that you cannot influence levels of the audio interface from the Mac. Same with my Lexicon Omega, not explained anywhere and quite annoying.

> what channels do you have selected for Input and Output?

To which setting does this refer to?

This Issue is IMHO annother argument for my https://github.com/jamulussoftware/jamuluswebsite/issues/174

**Comment by chrisrimple** [comment]
@drummer1154 After you've selected a Device from the dropdown, if the device offers more than 2 channels, you should see Input and Output channels like this...

<img width="633" alt="image" src="https://user-images.githubusercontent.com/47258736/102698901-a8387f80-41f5-11eb-88b8-b7799de1f44e.png">

I'm wondering if @Yostap has the wrong channel selected for Input?  For example, instrument plugged into 3 but Input = 1.

**Comment by newlaurent62** [comment]
The alesis io2 has only two channels so I'm afraid there is no channel selection.

**Comment by Yostap** [comment]
exact, newlaurent62
exact, drummer1154
So, it seems I can't make the mistake you think about, with only 2 channels on io2
I really don't understand my problem, seems like a bug, I don't know...

**Comment by drummer1154** [comment]
@chrisrimple I am normally working with PCs and am forced to use an iMac for band rehearsals (explained elsewhere). I am writing this on a PC, the iMac (and my vDrum environment) is powered off and everything I write here is from memory, may be wrong and needs to be verified with the iMac on.
My Lexicon Omega has 4 input channels and 2 output channels. It shows up as 3 different devices in the iMac "Audio MIDI Setup":
1x Mac (4 ins, 2 outs) and 2x Win (each 2 ins, 2 outs)
and shows up in a vast combination of devices in Jamulus Setup:
[to be filled later]
But as said by @newlaurent62, if the chosen device has only 2 channels for input and 2 for output, you will not see any input/output channel mapping - also quite annoying (the setting could be displayed r/o).

@Yostap Do you test this while connected to a Jamulus server?

**Comment by Yostap** [comment]
@drummer1154 yes, the problem happens when I'm connected to a jamulus server, I can hear the others but they can't hear me, my VU-meter don't move at all

**Comment by chrisrimple** [comment]
@Yostap Has Jamulus ever worked on your Mac Mini?  You mention Mojave and Catalina - was it working on an older MacOS version?  Since you're not seeing any input LEDs in Jamulus, it's clear that sound from your io2 isn't reaching Jamulus, even when you have the io2 as the selected Device.  You do get sound from your io2 to Logic Pro?

**Comment by Yostap** [comment]
@chrisrimple, no,  jamulus has never worked on my mac mini. Because of the problem on jamulus whith mojave, I updated to catalina, but the problem stayed exactely the same.
And Logic works well with io2

**Comment by drummer1154** [comment]
Only one other thing which has cost me hours: What about sample rate? Jamulus needs all devices at 48 kHz...

**Comment by chrisrimple** [comment]
@Yostap Ok, here's a test for you...

- Install BlackHole (it's free)
- Run Logic and in Audio preferences, set IN = io2 and OUT = BlackHole
- Run Jamulus and set Device = in:BlackHole/out:io2
- Connect to a Jamulus server and play your instrument

If things are working correctly, your audio path should be...

Instrument > io2 > Logic > BlackHole > Jamulus

I'm wondering if there's something about selecting Device = in:io2 in Jamulus that's causing the problem.

Also, another test...

- Plug earbuds with microphone into Mac Mini
- Run Jamulus and set Device = in:System/out:System
- Connect to a Jamulus server and talk

If things are working properly, you should hear your voice back from the Jamulus server.

**Comment by newlaurent62** [comment]
@Yostap Can you also try with another sound card and tell us if you observe the same behavior?

**Comment by Yostap** [comment]
@newlaurent62, I tried with an Apollo twin, same problem
@chrisrimple, I'll try today what you say, I suppose I can use soundflower instead of blackhole ?

**Comment by Yostap** [comment]
@chrisrimple, with micro plugged into mac mini and phones on mac output, nothing with jamulus "in:System/out:System".
And nothing with soundflower as you proposed with  blackhole...

**Comment by newlaurent62** [comment]
Is there a System Mac sound mixer that could explain the VU-meter input in Jamulus does not activate ? (I'm not a Mac user ...)

**Comment by chrisrimple** [comment]
@Yostap It seems that Jamulus isn't getting sound from any device, not just your io2.  Perhaps you need to uninstall (Trash) and reinstall Jamulus?

**Comment by Yostap** [comment]
@chrisrimple, already done, no résult... pfff

**Comment by Yostap** [comment]
@newlaurent62, I don't know any System Mac mixer...

**Comment by chrisrimple** [comment]
@Yostap I'm also on Mac, so maybe you can screenshare and we can try to solve your issue.  Email me at chrisrimple@yahoo.com and let's find a time.

**Comment by alanz1357** [comment]
Have you granted Jamulus permission to access your microphone?

Settings -> Security & Privacy ->   pick Microphone on the left list and  Check Jamulus in the right list

**Comment by kwindrem** [comment]
Just a thought:

There is a system security system that restricts use of resources like the "microphone". On first launch of an app, the system asks if you want to grant access to the microphone. What isn't obvious is this access applies to ALL audio input devices, not just the internal microphone. It may be that you accidentally denied Jamulus access to audio input devices. I did thinking "microphone" was just the internal microphone.

You can reset the access permissions in System Preferences / Security / Privacy, then select Microphone and insure Jamulus is checked.

**Comment by Yostap** [comment]
@alantz1357 and kwindrem
YESSSS !!!!
Problem solved
Thanks a lot to  you all for your help !
