### ISSUE TITLE
Store Jack connections

### ISSUE THREAD

**Issue by corrados** [corrados/jamulus#80]
_This issue has been migrated from Sourceforge.  Created: 2015-03-13
Creator: Volker Fischer_

Right now we always make auto connections to the default inputs and outputs of the system. It would be better if the user changes the connections to store the new connections and if they are available at Jamulus startup then reconnect them. If not, then use the system default as is done right now.

**Comment by corrados** [comment]
This Issue is a very old one. It was created by myself a long time ago.

My opinion regarding Jack auto connecting has changed since then. I prefer to do the connections outside of Jamulus. We support the essential mode that the system input/outputs are connected automatically which is very convenient for most use cases. And we also support a command line argument to set the Jack connections manually.

I prefer to do the connections in a script which calls Jamulus myself. Storing connections has the big disadvantage that if the other application is not running before Jamulus is started, the auto connection is not possible. If you are using a script, you can much better control what is actually connected and not.

Therefore I will close this Issue now.

**Comment by WolfganP** [comment]
As I'm having issues launching jamulus as client in a headless raspberry (no X11, other GUI system nor dbus installed, loopback sound interface to allow lab testing of multi-threading), this issue caught my attention.
No matter how I configure jackd and launch, jamulus doesn't detect it and triggers the launch of a new jack server (obviously oblivious to the params I passed on my own jack server running already)

Looking at the examples at https://github.com/corrados/jamulus/wiki/Tips,-Tricks-&-More#jamulus-client-linux-start-script and https://github.com/corrados/jamulus/blob/master/distributions/raspijamulus.sh none of them seems to use any cmd line switch to avoid the auto jack config (I expected to see -j or --nojackconnect on the scripts but none is used).

Any tip?

**Comment by corrados** [comment]
That is interesting. I thought only one Jack server can exist on a system. Why do you want to start your own Jack server before starting Jamulus? Why not use that auto-started new server?

**Comment by WolfganP** [comment]
For my setup, it's a matter of selecting the right card interface with preconfig parameters in my headless system:

```
$ sudo JACK_NO_AUDIO_RESERVATION=1 jackd --no-realtime --timeout 2000 -d alsa --device hw:1,1 --softmode --rate 48000 --period 256 --nperiods 2 &
[1] 1842
jackdmp 1.9.12
Copyright 2001-2005 Paul Davis and others.
Copyright 2004-2016 Grame.
Copyright 2016-2017 Filipe Coelho.
jackdmp comes with ABSOLUTELY NO WARRANTY
This is free software, and you are welcome to redistribute it
under certain conditions; see the file COPYING for details
JACK server starting in non-realtime mode
self-connect-mode is "Don't restrict self connect requests"
creating alsa driver ... hw:1,1|hw:1,1|256|2|48000|0|0|nomon|swmeter|soft-mode|32bit
configuring for 48000Hz, period = 256 frames (5.3 ms), buffer = 2 periods
ALSA: final selected sample format for capture: 32bit float little-endian
ALSA: use 2 periods for capture
ALSA: final selected sample format for playback: 32bit float little-endian
ALSA: use 2 periods for playback
```

Then jamulus seems to trigger another jack server with another interface:

```
$ jamulus --nogui --connect 192.168.1.155 \
        --port 22122 --fastupdate --clientname Raspi1 --nojackconnect \
    --inifile /mnt/usb_12/wTools/jamulus/jamclient.ini --log /tmp/jamulus.log &
- no GUI mode chosen
- connect on startup to address: 192.168.1.155
- selected port number: 22122
- using 64 samples frame size mode
- client name: Jamulus Raspi1
- disable auto Jack connections
- initialization file name: /mnt/usb_12/wTools/jamulus/jamclient.ini
- logging file name: /tmp/jamulus.log
jackdmp 1.9.12
Copyright 2001-2005 Paul Davis and others.
Copyright 2004-2016 Grame.
Copyright 2016-2017 Filipe Coelho.
jackdmp comes with ABSOLUTELY NO WARRANTY
This is free software, and you are welcome to redistribute it
under certain conditions; see the file COPYING for details
JACK server starting in realtime mode with priority 10
self-connect-mode is "Don't restrict self connect requests"
Cannot lock down 82287136 byte memory area (Cannot allocate memory)
control open "hw:0" (No such file or directory)
control open "hw:0" (No such file or directory)
creating alsa driver ... hw:0|hw:0|1024|2|48000|0|0|nomon|swmeter|-|32bit
control open "hw:0" (No such file or directory)
ALSA lib pcm_hw.c:1822:(_snd_pcm_hw_open) Invalid value for card
ALSA lib pcm_hw.c:1822:(_snd_pcm_hw_open) Invalid value for card
ALSA: Cannot open PCM device alsa_pcm for playback. Falling back to capture-only mode
JackTemporaryException : now quits...
control open "hw:0" (No such file or directory)
control open "hw:0" (No such file or directory)
Cannot initialize driver
JackServer::Open failed with -1
```

Unless I'm missing something plain obvious I was thinking about the lines not starting jack on my own, but instead playing with `~/.jackdrc` to properly configure the auto launched server.

**Comment by corrados** [comment]
Maybe the "JACK_NO_AUDIO_RESERVATION" causes this behaviour?

**Comment by WolfganP** [comment]
[HALF] Solved. 
I put my jackd starting line in `~/jackdrc` (`/etc/jackdrc` is a systemwide alternative) and that ensured that jamulus triggers launch of jackd with the desired parameters. I also got rid of `--nojackconnect` in jamulus cmd line as I saw no effect to it.

`export JACK_NO_AUDIO_RESERVATION=1` is needed in my headless system as I'm not running dbus (usually installed with X11) so no IPC available for jack.

Now to solve another problem :-) (this particular client failing to connect to the server even if other windows clients connect ok, and no jamulus.log generated)

```
$ jamulus --nogui --connect devsrvr.lan \
        --port 22122 --clientname Raspi1 \
    --inifile /mnt/usb_12/wTools/jamulus/jamclient.ini --log /tmp/jamulus.log 

- no GUI mode chosen
- connect on startup to address: devsrvr.lan
- selected port number: 22122
- client name: Jamulus Raspi1
- initialization file name: /mnt/usb_12/wTools/jamulus/jamclient.ini
- logging file name: /tmp/jamulus.log
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jackdmp 1.9.12
...
```

**Comment by corrados** [comment]
Is the port number 22122 already take by another Jamulus process?

**Comment by WolfganP** [comment]
> Is the port number 22122 already take by another Jamulus process?

Nope, free and available for use in the client machine, used by jamulus in the server one.
