### ISSUE TITLE
Maybe add a second licence choice for the server

### ISSUE THREAD

**Issue by corrados** [corrados/jamulus#81]
_This issue has been migrated from Sourceforge.  Created: 2015-02-05
Creator: Volker Fischer_

Right now only the CC licence is available. Maybe it makes sense to offer a second choice.
Discussion

    Volker Fischer - 2015-03-13

        Priority: 5 --> 2
      

    Volker Fischer - 2017-10-08

        status: open --> closed
      

    Volker Fischer - 2017-10-08

Nobody is using the CC licence feature anyway, so no need to add another one which is then also not used by anyone...
      

    Peter L Jones - 2019-07-06

I am :)

I'd have rather not had to have the NC version but that's not a major issue for me.

Now the recording feature is there, it does become more important, as the recorded media are subject to copyright of the individual contributors.

(There are probably also GDPR issues... Hm.)

**Comment by vocobox** [comment]
Maybe it should simply be stated that copyrighted content should not be broadcasted on public Jamulus servers and that any user take the responsability of sending content that is compatible with the licence ?

Another option is have public servers without recording capabilities that would not imply to agree to a licence as music passing through it is transient? It is a question. I don't know if transient content is subject to copyright.

**Comment by corrados** [comment]
I am no legal expert. Long time ago I included the CC license agreement since Ninjam also did it. If you use that license, I think as a server operator you are on the save side, even if it comes to recording the sessions.

**Comment by vocobox** [comment]
Maybe each public OR private server owner should be free to choose **which license is relevant for audio content**. In that case, license chose by each server "runner" should appear in the server list. (Sorry for the headache that mmight appear valueless with respect to feature queries). 

By the way, I am curious about your choice on **software licence**. You chose GPL, which is known to be contaminent and not open to commercial use. Was this an englighted or random choice? 

I personnaly chose [New BSD license](https://en.wikipedia.org/wiki/BSD_licenses#Commercial_license_compatibility) for my own [open source framework Jzy3d](https://github.com/jzy3d/jzy3d-api) as it permissive. I think business usage of a free software is good for everyone - but I would understand this would not apply for free applications allowing to create art.

**Comment by trebmuh** [comment]
> which is known to be contaminent and not open to commercial use

What ? This is plain wrong. GPL has nothing to do with commercial or not. Of course people are able to use a GPL software for making money. The only thing is, if they're taking the GPL licensed software and they sell it, they have to tell where it originates from and provide the source code for free. Same thing, if they modify the code and redistribute the software, they have to distribute the resulting code under the same license.

**Comment by vocobox** [comment]
> This is plain wrong. GPL has nothing to do with commercial or not.

My understanding of the GPL licensing is that if you modify a software to integrate it in your own software, then you have to make the modified code AND your own software both open source. Did I misunderstand? Assume I am Facebook and I want to integrate Jamulus in WhatsApp. Am I forced to publish the modified Jamulus AND WhatsApp source code?

**Comment by trebmuh** [comment]
If you modify the code and redistribute the code, you have to make the code in GPL too. as long as you make the code GPL, you can still sell the binary as an example. This is how Ardour does as an example.

> Assume I am Facebook and I want to integrate Jamulus in WhatsApp. Am I forced to publish the modified Jamulus AND WhatsApp source code?

IANAL, so you need to check that with reading the code and/or a lawyer and/or asking how people does it in the GPL's world.

**Comment by wolftune** [comment]
> My understanding of the GPL licensing is that if you modify a software to integrate it in your own software, then you have to make the modified code AND your own software both open source.

Somewhat clarified by other reply, but to be more clear: The keep-the-license clause *only* applies if you *convey* (distribute to others) the software. Any modifications of GPL that stay private do *not* need to be released to anyone.

In short: you are barred from giving the software to anyone *else* under *different* terms. But you can either *not* share the modified software *or* you can share it while keeping the GPL license.

With the AGPL specifically, this clause counts even if you only let others *access* the running software over a network. But even with AGPL, it does not apply if you don't let others use the software.

**Comment by wolftune** [comment]
I really want this feature. I want my server to offer [CC-BY-SA](https://creativecommons.org/licenses/by-sa/4.0/) (without the NC), as that is the license I use for my own music. Anyone who connects to *my* server I want them to agree to that license.

**Comment by mirabilos** [comment]
Aaron Wolf dixit:

>I really want this feature. I want my server to offer
>[CC-BY-SA](https://creativecommons.org/licenses/by-sa/4.0/) (without
>the NC), as that is the license I use for my own music. Anyone who
>connects to *my* server I want them to agree to that license.

I think I understand how the predefined licence works now.
It sets a byte in the message to the enum value, and the
client displays the licence dialogue.

Adding new enum values, however, makes old clients not
show anything. I think we’d need to break old clients :(

Besides that, I’d be happy to provide a patch to add quite
a number of common-ish licences for this kind of thing, both
free and nonfree, so we could use a dropdown instead of the
checkbox in the server dialogue.

**Comment by corrados** [comment]
> quite a number of common-ish licences for this kind of thing

What do you mean by "quite a number". What number would that be?

**Comment by mirabilos** [comment]
corrados dixit:

>> quite a number of common-ish licences for this kind of thing
>
>What do you mean by "quite a number". What number would that be?

I’d have to see… at least most of the Creative Commons ones and
some from the Copyfree licence list (because CC is often rather
restrictive) plus an entry saying that a specific deal with the
server operator is needed (e.g. for private things like rehear‐
sals of proprietary music).

Maybe a dozen, thus?

**Comment by corrados** [comment]
Ok, a dozen is a lot... Maybe we can shrink that down to 5-7 new licences? The current licence, BTW, is located here in the code: https://github.com/corrados/jamulus/blob/master/src/util.cpp#L482

**Comment by trebmuh** [comment]
What about proving a few common ones and allowing the server admin to add others?

**Comment by corrados** [comment]
I would like to keep the current mechanism for now. Let's just add some important ones. That should do it for most of the practical usecases.

**Comment by gilgongo** [comment]
> Let's just add some important ones. That should do it for most of the practical usecases.

@corrados From the advice I was given, it would be best to also allow a free text message along with a list of formal licence choices, since we do not want to be drawn into the area of which licence server operators should choose (if they want to put up a licence at all). 

Also, is this related or a dupe of #100 ?

**Comment by mirabilos** [comment]
Jonathan dixit:

>@corrados From the advice I was given, it would be best to also allow a
>@free text message along with a list of formal licence choices, since
>@we do not want to be drawn into the area of which licence server
>@operators should choose (if they want to put up a licence at all).

That's what I suggested as final solution in #100, but it appears
to be tricky due to the on-wire format.

On the other hand, when we need to break old clients in the case
of new licences anyway… perhaps that’s a chance to add it.

>Also, is this related or a dupe of #100 ?

Related-ish…

**Comment by corrados** [comment]
As we now refer in the licence accept dialog to the server Welcome message, the server operator now can use whatever licence he wants (see https://github.com/corrados/jamulus/issues/587#issuecomment-699513191). Therefore this Issue can be closed now.
