### ISSUE TITLE
Channel Layout Minor Tweaks

### ISSUE THREAD

**Issue by jdrage** [corrados/jamulus#811]
Couple of minor layout bugs I noticed:

1. When unmuting and muting, the appearance of the info icon causes the layout to jitter a little -- the fader bounces up and down a few pixels. (Repros on all skins.)
2. On the Fancy skin, the fader handle isn't centered over the slot.

**Comment by jdrage** [comment]
I have fixes for these, will create a PR shortly.

**Comment by corrados** [comment]
Pull Request is merged.

**Comment by corrados** [comment]
I actually don't like the new implementation. This is the spacings we had before:
![grafik](https://user-images.githubusercontent.com/46655886/104815238-a2918200-5813-11eb-808f-dcc887134182.png)
And this is with the new code:
![grafik](https://user-images.githubusercontent.com/46655886/104815249-b50bbb80-5813-11eb-928c-0d72c947f036.png)
This is definitely too much wasted space. I'll undo the change for now.

**Comment by corrados** [comment]
I just saw that the compact skin was also affected by the change:
![grafik](https://user-images.githubusercontent.com/46655886/104854262-fb414780-5905-11eb-977d-240e6778477c.png)
So, it is better to disable it and find a better solution...

**Comment by gene96817** [comment]
Would it help to rotate the text 90 degrees counterclockwise?

**Comment by corrados** [comment]
There is no issue with the compact skin. This is how it is supposed to look like: https://github.com/corrados/jamulus/issues/339#issuecomment-661153946.

The issue was just with the patch provided by jdrage in his Pull Request https://github.com/corrados/jamulus/pull/812. But as I said, I reverted that patch.

**Comment by corrados** [comment]
With my latest commit, at least on Windows the layout does not jump on Mute now:
![xwGQgOT8nx](https://user-images.githubusercontent.com/46655886/105066593-3fa42300-5a7f-11eb-8b9f-512607983bd8.gif)
