### ISSUE TITLE
AppImage build (since Flatpak seem to not handle JACK)

### ISSUE THREAD

**Issue by 38github** [corrados/jamulus#816]
Since Flatpak does not seem to handle JACK (well) (Ardour flatpak only has ALSA and Pulseaudio options) would someone like to try to build Jamulus as an AppImage? I have tried an AppImage of Qjackctl 0.9 that seem to work perfectly so AppImage does not seem to have issues with JACK.

**Comment by 38github** [comment]
@probonopd Do you have any recommendations or can give any help about how to more easily make this happen? Thanks in advance for any help you can give the developers!

**Comment by 38github** [comment]
There does not seem to be a lot of interest in an AppImage and as a Flatpak is on its way I personally am not that interested in keeping this request open.

**Comment by ann0see** [comment]
Just pasting the barebones command here which should create an appimage after you ran make in the root:

```
/path/to/linuxdeploy-x86_64.AppImage -e Jamulus --appdir AppDirOut -d linux/jamulus.desktop --icon-file src/res/io.jamulus.jamulus.svg --output appimage
```

**Comment by 38github** [comment]
Thank you!
