### ISSUE TITLE
Levels reset for group when grouped user re-enters server

### ISSUE THREAD

**Issue by LauraMardones** [corrados/jamulus#817]
Case: I have 40 singers, and group them with 10 peeps in each group. Then I set the levels - group 1 is slightly louder than the rest, group 4 slightly lower. Individuals in each group get some minor adjustments (e.g. to compensate for low or high gain).

BUT: One person has issues, and leaves group 3. After 30 sec, the person re-enters. For whatever reason, the person repeats this regularly throughout an hour.

The effect is that every time the person re-enters the server, the levels of that person's group (group 3) are all re-set, presumably to whatever levels I have set in "New Client Level", including the one's I've made individual changes to.

QUESTION: Is this a bug or simply expected behavior?

Is this the same issue as in #611?

**Comment by corrados** [comment]
Die you See this issue in Version 3.6.2?

**Comment by LauraMardones** [comment]
Thanks Volker, I had some assistance by Magnus Enorsson, and it may have
been in 3.6.1.
Let me double-check this next Tuesday, when we have our next rehearsal.
<3
/Laura
-----
*Typed by thumbs and badly spell checked. *
*Skickat från en mobil enhet; ber om ursäkt för kortfattade formuleringar,
förkortningar och dåliga autokorrigeringar.*


Den fre 8 jan. 2021 kl 08:43 skrev Volker Fischer <notifications@github.com

**Comment by corrados** [comment]
Any updates on this?

**Comment by corrados** [comment]
@LauraMardones I assume that you did not see the bug in 3.6.2 in your last rehearsal, so, I'll close this Issue now. If you have seen the bug in 3.6.2, please re-open this Issue again.
