### ISSUE TITLE
fix depreciated warnings

### ISSUE THREAD

**Issue by nefarius2001** [corrados/jamulus#827]
Hi,

when compiling i receive a few hundred unimportant warnings like:
-  warning: 'endl' is deprecated: Use Qt::endl [-Wdeprecated-declarations]
-  warning: 'null' is deprecated: use QString() [-Wdeprecated-declarations]

Is it appreciated if I create a pull request solving the easy ones? Or are there reasons to keep some of them?
( I assume most programmers work without depreciated-warnings?)

**Comment by ann0see** [comment]
I think it’s a macOS only issue?

**Comment by hoffie** [comment]
> I think it’s a macOS only issue?

Nah, Linux as well, just verified it on Fedora 33. I suspect it might depend on the Qt version.
5.15.2 is what I tested with.

**Comment by hoffie** [comment]
I suspect these are the relevant lines:
https://github.com/qt/qtbase/blob/5.15.2/src/corelib/serialization/qtextstream.h#L293
https://github.com/qt/qtbase/blob/5.15.2/src/corelib/text/qstring.h#L953

If I understand the deprecation macros correctly, at least the `endl` deprecations have come fairly recently. I assume that everyone with the most recent Qt release will see the warnings, independent of the platform. There are probably not many people building themselves on Windows (and Mac?), but more on Linux.

I think the deprecations can be fixed if it can be verified that all versions of Qt, which Jamulus aims to support, contain the replacements.

`QString` seems to be a core component which I understand has been around for at least ten years:
https://github.com/qt/qtbase/blame/5.15.2/src/corelib/text/qstring.h#L258

Same for `Qt::endl`:
https://github.com/qt/qtbase/blame/5.15.2/src/corelib/serialization/qtextstream.cpp#L3114

In the end, I think it's up to @corrados to decide. To me as a Qt-layman it looks like it would be safe to replace if everyone building Jamulus uses a Qt no older than 10 years. ;)

**Comment by corrados** [comment]
On my Mac I am using Qt 5.9.4.

**Comment by pljones** [comment]
On the CodeAL Analysis, the MacOS build is using 5.15.2.  I spotted that mass of warnings on the MacOS build.

The Windows build currently isn't pulling the ASIOSDK, so it doesn't get as far as running the compiler -- once I have that running, I expect to get the same warnings there, as it's also 5.15.2.

The linux build is currently 5.9.5, because ubuntu-latest is 18.04 -- that will soon change to 20.04, which has a later Qt, and will probably also then have the warning.

**Comment by corrados** [comment]
I need some more time working with older Qt versions. Can we, in the meantime, work with something like this: QT_NO_DEPRECATED_WARNINGS

**Comment by ann0see** [comment]
If we add the changes, do you think it would break old versions of Qt?

**Comment by corrados** [comment]
Yes, I've already tried that a while ago, see, e.g., https://github.com/softins/jamulus/commit/48e29be2b1f1e703ae7238e62d59197d25993933#commitcomment-43762698

**Comment by DavidSavinkoff** [comment]
I use qt-5.6.1 on my old computer. Compile time warnings are only an ephemeral blight as compared to breaking a build. Please don't break my build by modifying Jamulus to hide an unimportant QT warning.

**Comment by nefarius2001** [comment]
I like QT_NO_DEPRECATED_WARNINGS.
Disabling the warnings for the projects is also is fine, and better than breaking somenones build.
