### ISSUE TITLE
Jamulus server multiple systemd service files repo vs. documentation

### ISSUE THREAD

**Issue by ann0see** [corrados/jamulus#831]
On https://jamulus.io/wiki/Server-Linux
the systemd file configuring a server is different to https://github.com/corrados/jamulus/blob/master/distributions/jamulus-server.service

As far as I see, the one on jamulus.io gives the server realtime priority while the one in this repo doesn't. Shouldn't we merge the one on jamulus.io into the repo (of course with some smaller edits)?

**Comment by pljones** [comment]
Different host configurations may need different service files.  A "safe" default could perhaps be provided with guidance on suggested improvements and pointers to the supporting documentation on how to manage a service.

**Comment by ann0see** [comment]
> Different host configurations may need different service files.

Yes. The question is: should we really configure a public server with these files?
