### ISSUE TITLE
Server name for headless private server

### ISSUE THREAD

**Issue by DominikSchaller** [corrados/jamulus#837]
Hi, is it possible to add a server name to a headless private server? The serverinfo parameter doesn't seem to have the desired effect. I'd like for the clients to have the server name as the title of their application instead of the IP + port. Maybe just use the serverinfo parameter for this, if you don't want to introduce an additional parameter for it.

**Comment by corrados** [comment]
What are the command line arguments you are using when you start your headless Jamulus server?

**Comment by DominikSchaller** [comment]
ExecStart=/usr/local/bin/Jamulus --server --nogui --port 22129 --fastupdate --multithreading --numchannels 20 --welcomemessage /etc/systemd/system/jamulus-welcome-message

**Comment by DominikSchaller** [comment]
But I also tried adding this parameter to no effect: --serverinfo "A Cappella Company;Munich;82"

**Comment by corrados** [comment]
Now I see what your problem is. The --serverinfo is only used for the Server List which is managed by the Central Server. If you just have a private server, there is no protocol information which transferrs the server name to the client.

As an alternative, you could register your server to the "private server list" which I created recently: jamulusprivate.fischvolk.de

**Comment by DominikSchaller** [comment]
Is the private server list truly private? Then this would be a good solution.
Alternatively, I could also add --centralserver localhost, correct? Or does this have any negative effect on the performance?

**Comment by corrados** [comment]
> Is the private server list truly private?

Well, anybody who knows the URL can access the list. But it is not hard-coded inside the official Jamulus software. So it is kind of "semi-private".

> Alternatively, I could also add --centralserver localhost, correct? Or does this have any negative effect on the performance?

Yes, you can do it. I don't think it has any negative effect on the performance.

**Comment by DominikSchaller** [comment]
Ok, thanks. This is for a female chorus and I want to avoid unwanted visitors.

The second option works, but only if the central server address is set. Which kind of defeats the purpose.

Well, I think you can close the issue, it is not THAT important and if it's more than a few lines of code, it is not worth the effort.

By the way, Volker: Thank you so much for your software, it is a lifesafer in these times. After almost a year of Zoom rehearsals, yesterday I had a big smile in my face while singing live with my friends for the first time in a long while. Vielen Dank aus München!

**Comment by corrados** [comment]
You're welcome :-) -> closed.
