### ISSUE TITLE
More information in Jamulus client about failed connections

### ISSUE THREAD

**Issue by corrados** [corrados/jamulus#84]
_This issue has been migrated from Sourceforge.  Created: 2020-03-30
Creator: Dan Koloski_

My experience is that MAC OS Jamulus clients don't deliver any obvious message when they are unable to connect to a server (I have not tried a Windows client).

Symptom: There is no visible error, just no chat welcome message appears and there is no visual representation of user's track (or any other tracks) in the mixer, but the server name still appears at the top of the mixer in the UI and the Connect button is still toggled as if connected. For me, this seems to happen when attempting to connect to any server that doesn't yet have a ping time established, as well as every time I've tried to connect to a private server directly via IP.

Suggestion: It would be ideal to
1) give a more obvious message that the connection was unsuccessful
2) to reset the Connect button
3) remove the server name from the UI above the mixer, and
4) tell the users what they can do about it. For example: "Connection to [servername] failed. Unable to establish a UDP connection, which is required for streaming audio. For tips on how to resolve this issue, visit [URL or support article]."

**Comment by corrados** [comment]
1. and 3. are already solved in the newest version, see:
![grafik](https://user-images.githubusercontent.com/46655886/79494604-94fc6100-8023-11ea-95fb-e1498e80d995.png)

**Comment by gilgongo** [comment]
I don't think I've seen people on the forums having problems with failed connections in this context (although before we had the "connecting" message there was some confusion about whether they had connected and it was simply an empty room). 

So perhaps 3 and 4 aren't needed? If they had UDP issues they wouldn't be able to see any servers to connect to, for example.

**Comment by corrados** [comment]
I agree with you. So let's close this one and if there are still outstanding issues, a new Issue should be created.

**Comment by niebert** [comment]
Recommendation: On MacOSX the is/out "device" in the settings are empty. If they set it to your default in/out device the slider in the mixer appears again.

**Comment by chrisrimple** [comment]
This issue has already Closed, so it's possible no one is monitoring additional comments.  And niebert's point isn't addressing the original issue.  On Mac, the current Jamulus version for MacOS defaults to Device = in:System/out:System, which is the correct behavior on launch, unless the user has previously selected other options that are still available at launch.  But note that MacOS defaults to 44.1KHz for System (Built-In Speaker, Built-In Microphone), so all new installs on MacOS are defaulting to a Device = value that will then give an error on first connection attempt if other adjustments are not made by the user.  I'll log a new issue for a better error message in Jamulus.
