### ISSUE TITLE
New Windos installer shows incorrect error message

### ISSUE THREAD

**Issue by corrados** [corrados/jamulus#865]
I think we have a problem with the nsProcess.dll. When I start the new Windows installer in the current version of the Git repo, I get:
![grafik](https://user-images.githubusercontent.com/46655886/104949983-25efd680-59c0-11eb-8db3-c545d1c6e2f2.png)
I had this before and that was caused by nsProcess.dll not correctly installed or missing or something similar (I do not remember...).

**Comment by ann0see** [comment]
That's strange. The autobuild versions work fine: https://github.com/ann0see/jamulus/releases/tag/releasetag%2FAndroidBuild

I will try to download and compile the current code from master.

**Comment by ann0see** [comment]
For me with a clean build it works correctly.

**Comment by corrados** [comment]
That is weird. I deleted everything and built the installer again and now it works. I have no idea what went wrong the first time. Anyway -> closed.
