### ISSUE TITLE
Less stereotypical icons for choir vocal parts

### ISSUE THREAD

**Issue by eeconn** [corrados/jamulus#876]
I sing a lot of early music, in which the soprano and alto parts and the tenor and bass parts are not always sung by women and men respectively, particularly the alto and tenor parts.  The current rather stereotypically gendered icons for these parts are kind of disconcerting and potentially confusing in groups that may be using male altos or female tenors, and it's not particularly welcoming to trans singers of any vocal register. It may be better to use a more generic, non-specifically gendered singer icon.

**Comment by gene96817** [comment]
In mixed barbershop, men and women can also sing any part.

**Comment by corrados** [comment]
@Alberstein8 should comment on that. The pictures are from him: https://github.com/corrados/jamulus/issues/131#issuecomment-629772105

**Comment by 38github** [comment]
A guitar doesn't need to have a head stock or a classical body shape so please change the stereotypical icon, please. Also for the drums, why is the bass drum in its icon? Not everyone uses a bass drum or maybe they use two and would like to see an icon representing that.

I am biting my toungue...

**Comment by Alberstein8** [comment]
Hello,
First of all, thank you for letting me share my opinion.
As creator of the icons, back in May, as far as I know there were very few choirs using Jamulus for their rehearsals, if any. I decided to picture the most common situation of choir voices: female for sopranos and altos, male for tenors and basses, eventhough I do know women who sing as tenor and men as alto. I sing in two choirs who use Jamulus, with people of different orientations/cultures/countries and they never complained about this. 
Now, this project has become a huge community and things have changed a lot. I must say, I feel shamesly "proud" whenever I see choirs using this program with my icons, apart of some minor changes Volker let me introduce in the code. Actually, new voices have been introduced by others, baritone or main voice, using my pictures. I must say I'd feel a bit sad if my images dissapeared. 
Anyway, I see two options, in case you think icons should change:
1. Use the current Tenor/bass icon, removing all but the lips and teeth, see attachment. I think it could be less cisgender. But even so, someone might think it is not enough yet... 
2. Use clefs for different voices
I've attached examples for you to review
![sopranos](https://user-images.githubusercontent.com/9966701/105559047-704ebb80-5d10-11eb-83f8-0318657bf819.png)
![tenors](https://user-images.githubusercontent.com/9966701/105559072-80ff3180-5d10-11eb-979a-c9cd6767bc30.png)
![bariton](https://user-images.githubusercontent.com/9966701/105559079-86f51280-5d10-11eb-83c0-56c7ca07a75d.png)
<img width="18" alt="instrvocalbass2" src="https://user-images.githubusercontent.com/9966701/105559094-91171100-5d10-11eb-9bda-cfc6bbcba5d0.png">

In the end, I think, Volker, it is up to you to decide what to do regarding this. It's your creation, rest of us are mere helpers and obviously, I'll accept any decission you make.
Kind regards.

**Comment by gene96817** [comment]
@Alberstein8 Thank you for your work. I offer a couple points to consider.
-- FYI, the barbershop style is written in four part harmony, and by tradition, the four parts are called tenor, lead, baritone, and bass, regardless of the score in SSAA, SATB or TTBB.
-- many a-cappella/barbershop singers learn by ear (i.e. poor music readers) and the intent of your clefs might not be understood.

**Comment by corrados** [comment]
FYI: https://www.facebook.com/groups/jamuluschoralcommunity/permalink/1839969346150297/

**Comment by Alberstein8** [comment]
Actually, I did that poll.

**Comment by Alberstein8** [comment]
Some people suggests being able to upload your own icon, maybe too much effort for this?

**Comment by corrados** [comment]
You could use an icon in your Jamulus name. More and more people are making use of that. Under Windows you can use [Windows key]+"." to open the icons dialog.

**Comment by corrados** [comment]
The "official" instrument icons are compiled into the Jamulus software. There is no support for uploading your own pictures.

**Comment by DavidSavinkoff** [comment]
I think that the Vocal pictures can be changed to have plausible deniability of race or gender by:
- changing the purple lipstick to a flesh tone on one picture.
- removing facial hair from the other picture.

btw there is 'electric guitar' and 'acoustic guitar' but no 'guitar' for guitarists.

**Comment by 38github** [comment]
Everyone, is this actually something important to put a lot of work into? This is just social justice warriors trying to make an alternative world and replacing nature with factory.

**Comment by DominikSchaller** [comment]
There's always one *sigh* ... Yes, this is important. No, nature is not binary.

**Comment by 38github** [comment]
XX, XY and?

**Comment by DominikSchaller** [comment]
There is a couple more: https://en.wikipedia.org/wiki/XY_sex-determination_system#Humans
But it is also not just biological: https://en.wikipedia.org/wiki/Non-binary_gender
Anyway, I suggest you educate yourself. I also don't understand why you are commenting on this. You don't need to implement the changes. This is Github. Somebody can step up to the task. Wouldn't it be a good thing if Jamulus were inclusive to everybody?

**Comment by 38github** [comment]
> There is a couple more:[...]

Anbormalities.

> But it is also not just biological:

Factory

You, yes, you people (or do you have any other pronounce that you wish that I would have used to address you/them/they/zing etc) often (almost always) say that those of us who do not buy into these made up fairy tales made to make people walk on egg shells and stand in line need to educate ourselves. Are you refering to re-education?

Being a transvestite, transexualal, agrophobic, depressive etc are mental issues and should be taken seriously. I hope those of us who have these issues get the help they/we need BUT do not try to enforce upon others that your prognosis is the normal and the normal is uneducated and ill-informed and need to re-educate. I have read these types of repeated words and it didn't come from people and groups that accepted everyone and were known for being forgiving. 

Congratulations, you attacked an online jamming application and probably made people involved feeling like they do not include or like them/they/zing etc. What is next? Attack all the newspapers for not including Braille on every odd row or maybe that will be uninclusive to you since it wasn't on the even rows? Ban NKOTB's from history books because they were not asian, black, scandinavian zing, indian and eskimo?

**Comment by DominikSchaller** [comment]
Oh boy, you sure showed your true colors now. This is disgusting. I guess it is up to Volker if he wants people like you in this project. Hint to @corrados : https://github.blog/2016-04-04-organizations-can-now-block-abusive-users/

**Comment by 38github** [comment]
Again, the typical stuff. Asking others to ban people you don't like because you don't like the opinions/facts. That is the true disgusting way of dealing with things and lately you have been very successful. Probably this time too.

**Comment by 38github** [comment]
By the way, who said I'm a boy? You assumed my gender?

**Comment by corrados** [comment]
Guys, please keep the discussion technical here on Github. We all have one common goal: To make Jamulus as good as possible.

We have a designer team working on updating the web pages and GUI. I'll create a new Github Issue for creating a complete new set of consistent instrument icons.

**Comment by corrados** [comment]
I have created a new Issue which replaces this one. So, I will close this one now.
