### ISSUE TITLE
Support http links in the chat dialog

### ISSUE THREAD

**Issue by AndyMcProducer** [corrados/jamulus#879]
Links http: not clickable, only https: becomes clickable.
Is there a reason for it or a bug?

**Comment by hoffie** [comment]
I was asking myself the same. Some resources are still available via HTTP only. In such cases, one has to copy and paste the URL which is a bit inconvenient. One might argue about security reasons, on the other hand, the Jamulus protocol is not encrypted/authenticated either. :)

I can submit a PR if wanted.

**Comment by passing** [comment]
according to the code that's on purpose
```
   // only allow https URLs to be opened in an external browser
    if ( Url.scheme() == QLatin1String ( "https" ) )
```
https://github.com/corrados/jamulus/blob/master/src/chatdlg.cpp#L133-L134

**Comment by hoffie** [comment]
> according to the code that's on purpose

Yeah, the question is what the intention was. Was the intention to limit this to "safe" handlers (in other words: forbid `file://`, `javascript:` or something) or was it really to stop usage of `http://`.

The [commit message](https://github.com/corrados/jamulus/commit/5a991289d9871ad6aa2013833452e26243659869) provides some more details, but is still not totally clear to me if `http://` was disabled deliberately.

I guess we should wait for input from @corrados.

**Comment by corrados** [comment]
See, s.g., here: https://github.com/corrados/jamulus/issues/314#issuecomment-644191787

**Comment by hoffie** [comment]
> See, s.g., here: [#314 (comment)](https://github.com/corrados/jamulus/issues/314#issuecomment-644191787)

Thanks, I understand those comments that the intention was to disallow problematic handlers such as `file://` and that you would therefore accept a change to whitelist `http://`? I have opened #886 for that.

**Comment by AndyMcProducer** [comment]
IF it's being updated could blhblah.com .co.uk.net.org be added? So if someone puts in thissite.com it becomes clickable.

**Comment by corrados** [comment]
Changed the title since it is no bug but it was a decision to not support http.
