### ISSUE TITLE
Create Icon for Jamulus Server in Mac installation

### ISSUE THREAD

**Issue by corrados** [corrados/jamulus#89]
If you run the Windows installer, a link to the client and also to the server is created in the Windows start menu. On Mac, there is no such thing. If you install Jamulus, you simply get an icon for the client. If you want to start the server, you have to use the command line. This has to be improved. Maybe you can work on Mac with symlinks or something similar. This has to be investigated.

**Comment by doloopuntil** [comment]
I am having a go at addressing this. I'll let you know how it goes.

**Comment by doloopuntil** [comment]
I've looked at this and explored three options:

1. Add a thin Bash wrapper inside the Jamulus.app bundle to run the application with the`-s` switch. This doesn't make it any easier than it is today as the Bash wrapper cannot be located easily, for example by Spotlight.

1. Build a custom version of Jamulus into a separate bundle (for example, something like JamulusServer.app) and place that bundle inside the main Jamulus bundle. This is better as the bundle can be installer separately, but doesn't solve the problem that the server bundle cannot be located by Spotlight.

1. Build a custom version of Jamulus, which starts up in server mode by default and ship it as a separate bundle. I think this is the best option. Although it introduces a little redundancy (there are effectively two separate bundles to install), it gives users the ability to choose whether they want to install both client and server version or just one of them. It also keeps the two applications completely separate so it's easy to add a link to both to the dock.

I also reworked the way the overall installer image is built by introducing `dmgbuild`. This allowed me to build an installer image that pops up the license agreement and ask the user to accept it. It also provides the classic Mac "application installation" experience, like the screenshot below:
![jamulusinstaller](https://user-images.githubusercontent.com/5366115/79685177-8c2bab00-822e-11ea-816b-11f81e73c848.png)

If you think this is going in the right direction, an initial commit is at https://github.com/doloopuntil/jamulus/commit/8411debb391d154d696fc95526bc2cecded49e23

Question for you: how do you usually build the different versions of the application installers? I've heavily changed the default Mac deployment script in `mac/deploy_mac.sh` but I don't know if that breaks your deployment process.

**Comment by corrados** [comment]
Looks good :-). I agree, option 3 seems to be the best solution. I have to try it out on my old MacMini if your scripts work.

**Comment by corrados** [comment]
I get:

mac/deploy.sh: line 50: dmgbuild: command not found

Is the dmgbuild something I have to install first?

**Comment by doloopuntil** [comment]
Yes, you can either do a `python -m pip install dmgbuild`. The other option is that I add a bit of logic to find it inside the Qt Creator bundle, but that requires having Qt Creator installed.

**Comment by gilgongo** [comment]
Can't you just do this in with .app text file with Appify? 

https://mathiasbynens.be/notes/shell-script-mac-apps

**Comment by corrados** [comment]
I have Qt Creator installed.

**Comment by doloopuntil** [comment]
OK, then what I can do is add a bit of fallback logic. 
1. If possible, find `dmgbuild` inside the Qt Creator bundle. This may still require to know the path where Qt Creator is installed (e.g. via an environment variable). Unless you have it installed in `/Applications`? This is not the case for my Qt installation, which is in my home directory.
2. If `dmgbuild` cannot be found, ask the user to install it via `pip`.

**Comment by corrados** [comment]
Maybe option 2. is better. I have to admit that I did not try to run "python -m pip install dmgbuild" yet. Maybe it would just work. But having implemented option 2 would make things easier.

**Comment by doloopuntil** [comment]
OK, I'll add a couple of lines to the script. In the meanwhile if you'd like to give it a try, tun the following before the deployment script.
```
python -m ensurepip --user --default-pip
python -m pip install --user dmgbuild
```

**Comment by corrados** [comment]
This is what I get if I type in these two lines:

Volkers-Mini:jamulus corrados$ python -m ensurepip --user --default-pip
Ignoring indexes: https://pypi.python.org/simple
Requirement already satisfied (use --upgrade to upgrade): setuptools in /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python
Collecting pip
Installing collected packages: pip
Successfully installed pip
Volkers-Mini:jamulus corrados$ python -m pip install --user dmgbuild
Collecting dmgbuild
  Could not find a version that satisfies the requirement dmgbuild (from versions: )
  No matching distribution found for dmgbuild

**Comment by doloopuntil** [comment]
Oh that's odd. Can you try `python -m pip install -vvv --user dmgbuild` and copy the output, so maybe we get some more hints on why it fails. I've tried on my Mac with Python2.7 and it worked as expected.

**Comment by corrados** [comment]
Here it is:

Volkers-Mini:jamulus corrados$ python -m pip install -vvv --user dmgbuild
Starting new HTTPS connection (1): pypi.python.org
There was an error checking the latest version of pip
Traceback (most recent call last):
  File "/Users/corrados/Library/Python/2.7/lib/python/site-packages/pip/utils/outdated.py", line 126, in pip_version_check
    headers={"Accept": "application/json"},
  File "/Users/corrados/Library/Python/2.7/lib/python/site-packages/pip/_vendor/requests/sessions.py", line 476, in get
    return self.request('GET', url, **kwargs)
  File "/Users/corrados/Library/Python/2.7/lib/python/site-packages/pip/download.py", line 367, in request
    return super(PipSession, self).request(method, url, *args, **kwargs)
  File "/Users/corrados/Library/Python/2.7/lib/python/site-packages/pip/_vendor/requests/sessions.py", line 464, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/corrados/Library/Python/2.7/lib/python/site-packages/pip/_vendor/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/Users/corrados/Library/Python/2.7/lib/python/site-packages/pip/_vendor/cachecontrol/adapter.py", line 46, in send
    resp = super(CacheControlAdapter, self).send(request, **kw)
  File "/Users/corrados/Library/Python/2.7/lib/python/site-packages/pip/_vendor/requests/adapters.py", line 431, in send
    raise SSLError(e, request=request)
SSLError: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:590)
Collecting dmgbuild
  Getting page https://pypi.python.org/simple/dmgbuild/
  Starting new HTTPS connection (1): pypi.python.org
  Could not fetch URL https://pypi.python.org/simple/dmgbuild/: connection error: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:590) - skipping
  1 location(s) to search for versions of dmgbuild:
  * https://pypi.python.org/simple/dmgbuild/
  Getting page https://pypi.python.org/simple/dmgbuild/
  Starting new HTTPS connection (2): pypi.python.org
  Could not fetch URL https://pypi.python.org/simple/dmgbuild/: connection error: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:590) - skipping
  Could not find a version that satisfies the requirement dmgbuild (from versions: )
  Cleaning up...
  No matching distribution found for dmgbuild
  Exception information:
  Traceback (most recent call last):
    File "/Users/corrados/Library/Python/2.7/lib/python/site-packages/pip/basecommand.py", line 246, in main
      status = self.run(options, args)
    File "/Users/corrados/Library/Python/2.7/lib/python/site-packages/pip/commands/install.py", line 342, in run
      requirement_set.prepare_files(finder)
    File "/Users/corrados/Library/Python/2.7/lib/python/site-packages/pip/req/req_set.py", line 345, in prepare_files
      functools.partial(self._prepare_file, finder))
    File "/Users/corrados/Library/Python/2.7/lib/python/site-packages/pip/req/req_set.py", line 290, in _walk_req_to_install
      more_reqs = handler(req_to_install)
    File "/Users/corrados/Library/Python/2.7/lib/python/site-packages/pip/req/req_set.py", line 467, in _prepare_file
      req_to_install.populate_link(finder, self.upgrade)
    File "/Users/corrados/Library/Python/2.7/lib/python/site-packages/pip/req/req_install.py", line 251, in populate_link
      self.link = finder.find_requirement(self, upgrade)
    File "/Users/corrados/Library/Python/2.7/lib/python/site-packages/pip/index.py", line 502, in find_requirement
      'No matching distribution found for %s' % req
  DistributionNotFound: No matching distribution found for dmgbuild

**Comment by doloopuntil** [comment]
I see. It's because you're on a (very) old MacOS version and pip can no longer connect to the package repository due to the TLSv1 deprecation, see [here](https://stackoverflow.com/questions/49768770/not-able-to-install-python-packages-ssl-tlsv1-alert-protocol-version). You'll have to issue:

```
curl https://bootstrap.pypa.io/get-pip.py > get-pip.py
python get-pip.py --user
python -m pip install --user dmgbuild
```

Then you can run `dmgbuild` as follows: `"$(python -c 'import site; print(site.USER_BASE)')/bin/dmgbuild"`

I've made a branch with most of this setup automatically taken case of: https://github.com/doloopuntil/jamulus/commit/10f65f1ee24692f5a28bc5af1bb7e6f36e2795b8  (except for the pip upgrade, that's a little too risky to automate).

**Comment by corrados** [comment]
Thanks it seems to have worked:

Volkers-Mini:TMP corrados$ python get-pip.py --user
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Collecting pip
  Downloading pip-20.0.2-py2.py3-none-any.whl (1.4 MB)
     |████████████████████████████████| 1.4 MB 1.4 MB/s 
Collecting wheel
  Downloading wheel-0.34.2-py2.py3-none-any.whl (26 kB)
Installing collected packages: pip, wheel
  Attempting uninstall: pip
    Found existing installation: pip 6.1.1
    Uninstalling pip-6.1.1:
      Successfully uninstalled pip-6.1.1
  WARNING: The scripts pip, pip2 and pip2.7 are installed in '/Users/corrados/Library/Python/2.7/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script wheel is installed in '/Users/corrados/Library/Python/2.7/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed pip-20.0.2 wheel-0.34.2
Volkers-Mini:TMP corrados$ python -m pip install --user dmgbuild
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Collecting dmgbuild
  Downloading dmgbuild-1.3.3.tar.gz (35 kB)
Collecting ds_store>=1.1.0
  Downloading ds_store-1.1.2.tar.gz (13 kB)
Collecting mac_alias>=2.0.1
  Downloading mac_alias-2.0.7.tar.gz (17 kB)
Collecting biplist>=0.6
  Downloading biplist-1.0.3.tar.gz (21 kB)
Building wheels for collected packages: dmgbuild, ds-store, mac-alias, biplist
  Building wheel for dmgbuild (setup.py) ... done
  Created wheel for dmgbuild: filename=dmgbuild-1.3.3-py2-none-any.whl size=35378 sha256=f42061f2822e6bcd4d312fcd0830114b7c8e7aedfb0a0ebf2e3d2d2a12d5d452
  Stored in directory: /Users/corrados/Library/Caches/pip/wheels/f5/9f/99/89dba2211b70a2f2fd5e6e0a3feb50dd190ceb98eedbb593d0
  Building wheel for ds-store (setup.py) ... done
  Created wheel for ds-store: filename=ds_store-1.1.2-py2-none-any.whl size=13884 sha256=99065107285537f9ea1224ff9344278463a10a3216ebef5ab65878199d836bf4
  Stored in directory: /Users/corrados/Library/Caches/pip/wheels/58/53/b0/e42a7d87c4972c0281b065410d2e1ad248f14d53f185b33e9f
  Building wheel for mac-alias (setup.py) ... done
  Created wheel for mac-alias: filename=mac_alias-2.0.7-py2-none-any.whl size=18949 sha256=e4160939f95c95f04423928640add24a94f829e302df859f31fd5de2a068dcc6
  Stored in directory: /Users/corrados/Library/Caches/pip/wheels/4a/44/35/f214870f0469bbcf0c781836945300fa3ddb80b67a14667766
  Building wheel for biplist (setup.py) ... done
  Created wheel for biplist: filename=biplist-1.0.3-py2-none-any.whl size=11092 sha256=fce11d0b52b27732e04ec0ed3222b07a3d6d33c7b8479cff83e1a0ca7715ee37
  Stored in directory: /Users/corrados/Library/Caches/pip/wheels/69/5d/5c/159afd117b8de239775411c5a9f20369f46a174f81b45de2ad
Successfully built dmgbuild ds-store mac-alias biplist
Installing collected packages: biplist, mac-alias, ds-store, dmgbuild
Successfully installed biplist-1.0.3 dmgbuild-1.3.3 ds-store-1.1.2 mac-alias-2.0.7

**Comment by corrados** [comment]
That is strange... I still get:

mac/deploy.sh: line 50: dmgbuild: command not found

when I call deploy.sh.

**Comment by doloopuntil** [comment]
Yes, sorry, my instructions were a bit confusing. `dmgbuild ` is installed as a Python user package, so it won't be directly available on the command line (it would have been if installed as a system package, but that would have required sudo, which I preferred not to use). In my branch https://github.com/doloopuntil/jamulus/tree/improved_mac_deployment I changed `deploy.sh` so it finds `dmgbuild` even in it's not on the system path, see https://github.com/doloopuntil/jamulus/blob/improved_mac_deployment/mac/deploy.sh#L37

**Comment by corrados** [comment]
Great work! Now it ran successfully. The installer looks very professional now.
I did not do a full test but one thing I noticed right away: There is a ">" in front of Jamulus in the menu:
![grafik](https://user-images.githubusercontent.com/46655886/79695022-91134d80-8274-11ea-9153-604357023d23.png)
Have you seen this on your Mac?

**Comment by corrados** [comment]
I have a define "#define APP_NAME                         "Jamulus"" in global.h. Could this have anything to do with the issue? Because I saw that you also define an APP_NAME: https://github.com/doloopuntil/jamulus/blob/improved_mac_deployment/mac/deploy.sh#L4

**Comment by doloopuntil** [comment]
Yeah, I just noticed it on my Jamulus too. I'll see what causes it. Probably a typo somewhere :)

**Comment by doloopuntil** [comment]
It was indeed a typo. I fixed it on the branch, see https://github.com/doloopuntil/jamulus/commit/a24d14cb91cac8227c0f478ae5103b7e1b7d13a2. If you're happy with the result I'll open a pull request.

**Comment by corrados** [comment]
Yes, please.
One thing: I know it is kind of redundant, but I would like to have the old name back: deploy_mac.sh. Then it is consistent with deploy_windows and deploy_linux in the other directories.

**Comment by doloopuntil** [comment]
No problem, I've done that in https://github.com/corrados/jamulus/pull/113

**Comment by corrados** [comment]
It's already merged, thanks.
