### ISSUE TITLE
Link to docs from application Help menu?

### ISSUE THREAD

**Issue by gilgongo** [corrados/jamulus#90]
Documentation about using Jamulus is spread across Facebook, Github, the SF forums, YouTube and possibly other places. I suspect this causes some users to assume that the only information available is at the first place they find it (eg Facebook or SF) and don't go elsewhere. I don't think there's much we can do about that though.

However, there is a convention in many apps of having a link to documentation in the app itself. Suggest perhaps adding a link to the relevant wiki pages for the [client](https://github.com/corrados/jamulus/wiki/Software-Manual) (and perhaps also to manual.md?) and the [server](https://github.com/corrados/jamulus/wiki/Running-a-Server) on the window bar,  and replacing the "?" with the word "Help".

BTW (perhaps a separate ticket?) the"What's this?" mouseover help function could do with larger hit areas in the UI (suggest perhaps double the current radius on center) - it's quite hard to invoke the help panels.

**Comment by corrados** [comment]
Can you be more specific with the links? Right now have have "Whats This", "Download Link" and "About" in the "?" menu. Do you want to add more entries there?

Changing the "?" in "Help" is trivial. But right now the only help in that menu is the "'Whats This".

**Comment by gilgongo** [comment]
> Can you be more specific with the links? 

@corrados What I had in mind was for the "Help" menu (changed from "?") to contain:

**For the client**:

"Getting Started" - linking to the [wiki client introduction](https://github.com/corrados/jamulus/wiki/Software-Manual)
"Software Manual" - linking to [manual.md](https://github.com/corrados/jamulus/blob/master/src/res/homepage/manual.md)
\----
"What's This - Shift +F1?" 
\----
"About ..." (which would contain a link to "[Download latest version](https://sourceforge.net/projects/llcon/files/)") \*

**For the server**:

"Getting Started" - linking to the [wiki server introduction](https://github.com/corrados/jamulus/wiki/Running-a-Server)
\----
"What's This - Shift +F1?" 
\----
"About ..." (which would contain a link to "[Download latest version](https://sourceforge.net/projects/llcon/files/)") \*

\* _The current "Download link" is a bit unconventional, and possibly confusing since you can't see the help menu without having downloaded the software, so it might imply some other downloads are needed?_

**Comment by corrados** [comment]
Maybe we should remove the "Download latest version" completely?

**Comment by corrados** [comment]
It's implemented now -> closed.
