### ISSUE TITLE
Question: Does one person with bad ping/latency ruin it for everybody?

### ISSUE THREAD

**Issue by DominikSchaller** [corrados/jamulus#900]
The question came up on Facebook and at our own rehearsal, and I was not able to answer it.

Does the server do some kind of synchronization based on the ping/latency of all clients? Like is the worst latency the common denominator? Or does the server just collect all inputs in fixed cycles and sends the mix back (independent of the clients)?

And if it has an influence, I have a special case follow-up question: If we have a guy with a bad connection and he is muted, does that have influence on the overall latency?

**Comment by hoffie** [comment]
> Does the server do some kind of synchronization based on the ping/latency of all clients?

No, I don't think so.

> Or does the server just collect all inputs in fixed cycles and sends the mix back (independent of the clients)?

Yes, that's my understanding. The server runs a (tight) loop which collects audio data for each client/channel:
https://github.com/corrados/jamulus/blob/master/src/server.cpp#L423
https://github.com/corrados/jamulus/blob/master/src/server.cpp#L782

So, a slow/bad connection should not break a Jamulus server. It might ruin the experience musically for other users due to cracks, clicks or delays unless everyone mutes the problematic client.

If you have evidence that a slow client does indeed cause technical troubles for everyone, I'm pretty sure it would be interesting to track down such cases (I think someone mentioned something like this in the past, but I cannot find the place).

**Comment by pljones** [comment]
One player not listening only to the mix can be playing out of time and that will cause everyone else to start trying to allow for them and you'll get a "cascading" effect.

**Comment by gene96817** [comment]
@hoffie  I believe our sessions at HI-Studio1 is experiencing this behavior when a person with  >150ms joined. The aberration affected all users. Having everyone mute this person did not resolve the problem. Normal behavior was established after the visitor disconnected. I believe this has been observed in two different weeks.

What information do you want to collect?

**Comment by pljones** [comment]
WorldJam weekly concerts have have people playing together with over 100ms between some players and the server -- I'm not sure if it's as much as 150ms ping.  The overall delay might be that high, I'm not sure.

Did the new joiner state their ping _and_ overall latency figures?

**Comment by gene96817** [comment]
Curious. I will confirm. Assuming the delays are symmetric, my delay to a server in that local is >100ms. I will confirm the details for the next occurances.

**Comment by pljones** [comment]
Please quote both "Ping Time" and "Overall Delay" figures from the Jamulus Settings panel - without both, any figure isn't particularly useful.

What do you mean by "symmetric"?

For "Ping Time", your client sends a packet to the server with "now" on it, the server returns a packet with that original timestamp on it and your client determines how long it took.  "Overall Delay" takes into account the displayed buffer sizes.

**Comment by gene96817** [comment]
If we assume transit times are relatively symmetric, then I can get an estimate of ping and overall delay from what I see for a server near the user.

**Comment by pljones** [comment]
> 
> 
> If we assume transit times are relatively symmetric, then I can get an estimate of ping and overall delay from what I see for a server near the user.

What do you mean by "symmetric"?

**Comment by hoffie** [comment]
> What information do you want to collect?

Besides what @pljones already said, the following details may be worth collecting: Jamulus server/client versions, number of users, server options (`--multithreading`, `--fastupdate`), client options (buffer sizes, small network buffers, etc.).
The simple fact that such an issue is reproducible (is it?) in your environment may be also interesting. Any detail helps for some developer to reproduce and debug it. To simulate high ping times, `tc` can be [used under Linux](https://bencane.com/2012/07/16/tc-adding-simulated-network-latency-to-your-linux-server/), for example.

**Comment by gene96817** [comment]
This is going to be tricky interrupting a rehearsal to collect all these details from 10-20 participants. Some of the participants are nervous about technology. 

My plan will be to first see if this condition will appear with under 10 participants. Then collect ping times, overall delay, and client versions when it happens.
