### ISSUE TITLE
Build project with Qt6.0.0

### ISSUE THREAD

**Issue by remy4096** [corrados/jamulus#905]
I wrote a few modifications to make Project code compatible with Qt6.0.0 SDK
Build on windows 32 bits environment Desktop_Qt_6_0_0_MSVC2019_x86_amd64 = success
Launch application = success
Build windows installer = in progress
others target = in progress
Remark: the master Qt project Jamuls.pro doesn't works with QtCreator

**Comment by pljones** [comment]
Does the github auto build process work with Qt 6.0.0?

**Comment by remy4096** [comment]
Qt6 is a cross platform IDE, see https://www.qt.io/product/qt6
Qt 6.0.0 is the last release of Qt library, previous one was Qt 5.15, probably this one used to build actual binary of Jamulus V 3.6.2
BUT my work demonstrate it is possible to build Jamulus software with the new version, it's works really on Windows, I'v to try others compilation for mac and unix. Mac version I also use is in previous version= 3.5.5

It contains lot of tools, like Qt Creator which is a large cross IDE to automatize the build of your software for different targets. It'as also capable to manage git.
You can alse automatize yourself the build process through git bash environment, I tried it, but it's a peace of cake, mostly problems are in the 'PATH" parameters, see below what I'v done. I reproduced Qt Creator build process.
[ResponsetoPlJones.txt](https://github.com/corrados/jamulus/files/5892066/ResponsetoPlJones.txt)

Bye, Have a nice day, 
Remy
