### ISSUE TITLE
64 bit Jamulus crashes with Jack Audio on Windows

### ISSUE THREAD

**Issue by corrados** [corrados/jamulus#93]
Other 64 bit DAWs work fine with Jack Audio on Windows whereas Jamulus crashes.

**Comment by corrados** [comment]
See this post: https://sourceforge.net/p/llcon/discussion/software/thread/d0a345f8e9/#678a

**Comment by corrados** [comment]
I checked if the Jamulus binary selects the correct 64 bit Jack Audio ASIO driver and that is the case. I also checked that the regsvr32 COM registration of the 64 bit Jack ASIO driver was successful. Both is the case and still Jamulus crashes when it tries to load the JackAudio driver.

**Comment by elliotclee** [comment]
I attached WinDbg.exe to Jamulus and tried selecting JackRouter. After looking at the stack trace and googling, I found that it's not a Jamulus problem, but there is a Jamulus workaround. 

See https://github.com/jackaudio/jack2/issues/332 - there is a linker flag you can add that will make the problem go away until the Jack people fix their bug.

**Comment by elliotclee** [comment]
I did a 64-bit mingw build in Qt Creator, and it worked fine. So it's something to do with MSVC and that /DYNAMICBASE:NO flag.

**Comment by corrados** [comment]
Wow, it works. I just tested it successfully.
Thank you very much!
The fix will be in the next official Jamulus version. I'll close this issue now.
