### ISSUE TITLE
Jamulus 3.5.1 Mac - missing "MyProfile" button

### ISSUE THREAD

**Issue by MaxMariano** [corrados/jamulus#94]
Hi, I have just downloaded the 3.5.1 release and I see that the "My Profile" (third top-down) button of the GUI is now showing "Mute Streams" (new feature),  but I am not able to access and change My Profile any more (had to revert to 3.5.0).

PS. just checked that the same applies to the 3.5.2 I just compiled on my RPi3 (I use it as a Jamulus server-only so I didn't see that)

Thanks. Max
![Screenshot 2020-04-18 16 02 15](https://user-images.githubusercontent.com/63913784/79639794-1d971080-818e-11ea-8649-4fe6240cc7a3.png)

**Comment by corrados** [comment]
It is in Menu->View.

**Comment by MaxMariano** [comment]
OK, probably got confused as the release notes talked about a button “added” (not changed). Thanks!
